// The Careers kit (July 16, 2026, owner ask: "a career subtab, where we
// also give out resume templates, interview guides + a few articles").
// One hub for the job side of student money: the Career Explorer door,
// free resume/cover-letter .docx downloads (lib/templates kind "doc",
// generated by scripts/build-resume-templates.mjs), the Getting-hired
// guides, and the Opportunity Finder. Student-native page — the layout
// provides StudentHeader; everything links in-frame.

import Link from "next/link";
import type { Metadata } from "next";
import { Download, Telescope, Briefcase } from "lucide-react";
import Footer from "@/components/Footer";
import ScrollDrift from "@/components/ScrollDrift";
import TopicMark from "@/components/TopicMark";
import HeadlineRise from "@/components/HeadlineRise";
import { templates } from "@/lib/templates";

export const metadata: Metadata = {
  title: "Careers Kit | Empower — Economic Mobility Project",
  description:
    "Everything for landing the first job: free resume and cover letter templates (no signup), interview guides written for people with no experience yet, and 100 careers with real pay data.",
};

const GUIDES = [
  {
    slug: "resume-with-no-experience",
    title: "A Resume With No Work Experience (Everyone Starts Here)",
    dek: "What you already have — classes, projects, helping people — counts, if you write it down right.",
  },
  {
    slug: "ace-your-first-interview",
    title: "Your First Interview, Without the Panic",
    dek: "Interviews are a learnable format. Three stories, two questions, one email.",
  },
  {
    slug: "first-job-offer-money",
    title: "Reading Your First Job Offer (Before You Say Yes)",
    dek: "The wage is one line. Hours, taxes, and benefits decide what it actually pays.",
  },
  {
    slug: "work-study-explained",
    title: "Work-Study, Explained",
    dek: "The campus job that comes with your aid letter — and how to actually get one.",
  },
];

export default function CareersPage() {
  const docs = templates.filter((t) => t.kind === "doc");
  return (
    <div className="min-h-screen bg-paper text-ink">
      {/* Hero — C voice on forest, sitewide letter-reveal accent */}
      <section className="relative overflow-hidden bg-forest text-cream">
        <ScrollDrift range={46} driftX={20} rotate={-4}>
          <TopicMark
            id="budgeting"
            color="#fbf8f1"
            className="pointer-events-none absolute -right-16 -top-12 h-[24rem] w-[24rem] opacity-[0.13]"
          />
        </ScrollDrift>
        <div className="relative mx-auto max-w-6xl px-6 py-14 lg:py-20">
          <span className="text-xs font-bold uppercase tracking-[0.25em] text-amber">
            For Students · Careers
          </span>
          <h1 className="mt-4 max-w-4xl font-display text-[2.6rem] font-medium leading-[1.07] sm:leading-[0.98] tracking-tight sm:text-6xl">
            No experience isn&apos;t a wall.{" "}
            <span className="italic text-amber">
              <HeadlineRise chars>It&apos;s a starting line.</HeadlineRise>
            </span>
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-cream/75">
            The whole first-job kit in one place: resume templates you can
            download and fill in, interview guides written for people whose
            experience is school and real life, and {""}
            100 careers with verified pay data. No signup, no email — just
            take what you need.
          </p>
        </div>
      </section>

      {/* Resume kit — the downloads */}
      <section className="border-b-2 border-ink bg-paper">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <span className="text-xs font-semibold uppercase tracking-[0.2em] text-terracotta">
            The resume kit
          </span>
          <h2 className="mt-2 font-display text-2xl font-bold text-ink sm:text-3xl">
            Three files, zero forms. Download, fill in, send.
          </h2>
          <p className="mt-2 max-w-2xl text-base leading-7 text-stone">
            Word documents that open anywhere (Google Docs included). Every
            placeholder explains what belongs in it, so the template teaches
            while you type.
          </p>
          <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-3">
            {docs.map((t) => (
              <div
                key={t.file}
                className="card-ink flex h-full flex-col rounded-2xl bg-cream p-5"
              >
                <h3 className="font-display text-lg font-bold leading-snug text-ink">
                  {t.title}
                </h3>
                <p className="mt-1.5 text-sm leading-6 text-stone">{t.blurb}</p>
                <ul className="mt-3 flex-1 space-y-1.5">
                  {t.includes.map((line) => (
                    <li
                      key={line}
                      className="text-[13px] leading-5 text-stone before:mr-1.5 before:text-amber before:content-['✓']"
                    >
                      {line}
                    </li>
                  ))}
                </ul>
                <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-sand pt-3">
                  <a
                    href={t.file}
                    download
                    className="btn-ink inline-flex items-center gap-1.5 rounded-md bg-amber px-3.5 py-2 text-sm font-bold text-ink"
                  >
                    <Download className="h-4 w-4" strokeWidth={2.5} />
                    Download .docx
                  </a>
                  {t.tool && (
                    <Link
                      href={
                        t.tool.href.startsWith("/learn/")
                          ? `/students${t.tool.href}`
                          : t.tool.href
                      }
                      className="text-[13px] font-semibold text-forest underline decoration-amber decoration-2 underline-offset-4 hover:text-ink"
                    >
                      {t.tool.label}
                    </Link>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Getting hired — the guides */}
      <section className="bg-paper-deep">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <span className="text-xs font-semibold uppercase tracking-[0.2em] text-terracotta">
            Getting hired
          </span>
          <h2 className="mt-2 font-display text-2xl font-bold text-ink sm:text-3xl">
            The guides: resume to interview to offer.
          </h2>
          <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
            {GUIDES.map((g) => (
              <Link
                key={g.slug}
                href={`/students/learn/college/${g.slug}`}
                className="card-ink group flex h-full flex-col rounded-xl bg-cream p-5 transition-transform duration-200 hover:-translate-y-1"
              >
                <h3 className="font-display text-base font-bold leading-snug text-ink group-hover:underline group-hover:decoration-amber group-hover:decoration-2 group-hover:underline-offset-4">
                  {g.title}
                </h3>
                <p className="mt-1 text-sm leading-6 text-stone">{g.dek}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Explore + apply — the two big doors */}
      <section className="border-t-2 border-ink bg-paper">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <Link
              href="/students/career-explorer"
              className="card-ink-lg group flex h-full flex-col rounded-2xl bg-forest p-6 text-cream transition-transform duration-200 hover:-translate-y-1"
            >
              <Telescope className="h-6 w-6 text-amber" strokeWidth={2.25} />
              <h3 className="mt-3 font-display text-xl font-bold leading-snug group-hover:underline group-hover:decoration-amber group-hover:decoration-2 group-hover:underline-offset-4">
                Career Explorer
              </h3>
              <p className="mt-1.5 text-sm leading-6 text-cream/75">
                100 careers with verified federal data: median pay, growth,
                what training each really needs — and the paths that pay you
                while you learn.
              </p>
            </Link>
            <Link
              href="/students/opportunities"
              className="card-ink-lg group flex h-full flex-col rounded-2xl bg-cream p-6 transition-transform duration-200 hover:-translate-y-1"
            >
              <Briefcase className="h-6 w-6 text-terracotta" strokeWidth={2.25} />
              <h3 className="mt-3 font-display text-xl font-bold leading-snug text-ink group-hover:underline group-hover:decoration-amber group-hover:decoration-2 group-hover:underline-offset-4">
                Internships &amp; Opportunities
              </h3>
              <p className="mt-1.5 text-sm leading-6 text-stone">
                68 verified internships, fellowships, and programs — many paid
                — ready for the resume you just built.
              </p>
            </Link>
          </div>
        </div>
      </section>

      <Footer frame="student" />
    </div>
  );
}
