// Distinct careers added after the original line-by-line BLS occupation audit.
// These are intentionally concentrated in gaps students actually search for:
// academic sciences, engineering-technician paths, career-ladder management,
// creative work with hourly-only wage data, and a handful of specialized
// healthcare, energy, and transportation jobs. We still consolidate subject-
// by-subject professor codes and omit residual "all other" categories.

import type { Career } from "./careers";
import type { CareerDetail } from "./careerDetails";

export const careerAdditions: Career[] = [
  {
    id: "anthropologist-archaeologist",
    title: "Anthropologist / Archaeologist",
    field: "engineering",
    medianPay: 70770,
    medianHourlyPay: 34.02,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree; field-school experience matters",
    growth: 3.7,
    note: "Studies people, cultures, and material remains through fieldwork, research, and careful documentation.",
  },
  {
    id: "meteorologist",
    title: "Meteorologist / Atmospheric Scientist",
    field: "engineering",
    medianPay: 99070,
    medianHourlyPay: 47.63,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in meteorology or atmospheric science",
    growth: 0.7,
    note: "Forecasting is only one route; climate, aviation, research, and emergency planning also hire atmospheric scientists.",
  },
  {
    id: "materials-scientist",
    title: "Materials Scientist",
    field: "engineering",
    medianPay: 117790,
    medianHourlyPay: 56.63,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in materials science, chemistry, or a related field",
    growth: 4.9,
    note: "Develops and tests metals, polymers, ceramics, batteries, and other materials used in real products.",
  },
  {
    id: "hydrologist",
    title: "Hydrologist",
    field: "engineering",
    medianPay: 96600,
    medianHourlyPay: 46.44,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in hydrology, geology, or environmental science",
    growth: -0.1,
    note: "Tracks how water moves through rivers, soil, and groundwater for drought, flood, and supply decisions.",
  },
  {
    id: "political-scientist",
    title: "Political Scientist",
    field: "public",
    medianPay: 142080,
    medianHourlyPay: 68.31,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree is typical for research roles",
    growth: -3.1,
    note: "Researches political systems, public opinion, elections, and policy for government, universities, and organizations.",
  },
  {
    id: "sociologist",
    title: "Sociologist",
    field: "education",
    medianPay: 106030,
    medianHourlyPay: 50.98,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree in sociology or applied social research",
    growth: 3.6,
    note: "Studies groups, institutions, and social change using surveys, interviews, and data analysis.",
  },
  {
    id: "historian",
    title: "Historian",
    field: "education",
    medianPay: 76750,
    medianHourlyPay: 36.9,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree is typical outside entry-level research support",
    growth: 2.2,
    note: "Researches and interprets the past for museums, archives, government agencies, and public history projects.",
  },
  {
    id: "astronomer",
    title: "Astronomer",
    field: "engineering",
    medianPay: 128820,
    medianHourlyPay: 61.94,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "PhD for independent research; physics degrees lead to support roles",
    growth: 2.2,
    note: "Uses telescopes, satellites, and large datasets to study planets, stars, galaxies, and the universe.",
  },
  {
    id: "mathematician",
    title: "Mathematician",
    field: "engineering",
    medianPay: 126710,
    medianHourlyPay: 60.92,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree is typical; some federal roles accept a bachelor's",
    growth: -0.7,
    note: "Builds mathematical models and methods for science, technology, government, and business problems.",
  },
  {
    id: "animal-scientist",
    title: "Animal Scientist",
    field: "engineering",
    medianPay: 68940,
    medianHourlyPay: 33.14,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in animal science or agriculture",
    growth: 5.8,
    note: "Studies animal nutrition, genetics, health, and production, usually outside the clinical work veterinarians do.",
  },
  {
    id: "agricultural-engineer",
    title: "Agricultural Engineer",
    field: "engineering",
    medianPay: 98590,
    medianHourlyPay: 47.4,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in agricultural or biological engineering",
    growth: 5.9,
    note: "Designs equipment and systems for food production, water use, storage, and farm automation.",
  },
  {
    id: "marine-engineer",
    title: "Marine Engineer / Naval Architect",
    field: "engineering",
    medianPay: 112230,
    medianHourlyPay: 53.96,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in marine engineering or naval architecture",
    growth: 5.8,
    note: "Designs ships, submarines, and offshore systems; this is the design path, not the onboard ship-engineer role.",
  },
  {
    id: "io-psychologist",
    title: "Industrial-Organizational Psychologist",
    field: "business",
    medianPay: 193950,
    medianHourlyPay: 93.24,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree in industrial-organizational psychology",
    growth: 6.3,
    note: "Applies psychology to hiring, training, leadership, and workplace design, often with substantial data analysis.",
  },
  {
    id: "electrical-engineering-tech",
    title: "Electrical Engineering Technician",
    field: "engineering",
    medianPay: 78190,
    medianHourlyPay: 37.59,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in electronics or electrical engineering technology",
    growth: 0.6,
    note: "Builds, tests, and repairs electrical and electronic systems alongside engineers.",
  },
  {
    id: "industrial-engineering-tech",
    title: "Industrial Engineering Technician",
    field: "engineering",
    medianPay: 66120,
    medianHourlyPay: 31.79,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in industrial engineering technology",
    growth: 1.7,
    note: "Measures workflows, layouts, quality, and costs to help factories and service operations run better.",
  },
  {
    id: "mechanical-engineering-tech",
    title: "Mechanical Engineering Technician",
    field: "engineering",
    medianPay: 74510,
    medianHourlyPay: 35.82,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in mechanical engineering technology",
    growth: 0,
    note: "Builds prototypes, runs tests, and troubleshoots mechanical products and equipment with engineers.",
  },
  {
    id: "mechatronics-tech",
    title: "Mechatronics Technician",
    field: "engineering",
    medianPay: 73900,
    medianHourlyPay: 35.53,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in mechatronics or electro-mechanical technology",
    growth: 1.1,
    note: "Maintains the combined mechanical, electrical, and computer-controlled systems used in automation and robotics.",
  },
  {
    id: "surveying-mapping-tech",
    title: "Surveying & Mapping Technician",
    field: "engineering",
    medianPay: 54240,
    medianHourlyPay: 26.08,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "High school plus paid field training; certificates can help",
    growth: 4.5,
    note: "Collects field measurements and turns them into maps and survey records, often as the entry rung toward surveying.",
  },
  {
    id: "chemical-technician",
    title: "Chemical Technician",
    field: "engineering",
    medianPay: 60390,
    medianHourlyPay: 29.03,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in chemistry or chemical technology",
    growth: 3.7,
    note: "Runs laboratory and production tests for chemicals, fuels, medicines, food, and manufactured materials.",
  },
  {
    id: "environmental-science-tech",
    title: "Environmental Science Technician",
    field: "engineering",
    medianPay: 55090,
    medianHourlyPay: 26.49,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in environmental science or a related field",
    growth: 4,
    note: "Collects air, soil, and water samples and checks workplaces and communities for pollution and health hazards.",
  },
  {
    id: "agricultural-tech",
    title: "Agricultural Technician",
    field: "engineering",
    medianPay: 49630,
    medianHourlyPay: 23.86,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in agricultural science or technology",
    growth: 4.3,
    note: "Supports crop, soil, animal, and food research through field sampling, equipment, and laboratory tests.",
  },
  {
    id: "aerospace-engineering-tech",
    title: "Aerospace Engineering Technician",
    field: "engineering",
    medianPay: 82890,
    medianHourlyPay: 39.85,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in aerospace engineering technology",
    growth: 8.1,
    note: "Installs instruments, runs tests, and maintains equipment used to develop aircraft, spacecraft, and missiles.",
  },
  {
    id: "occupational-safety-tech",
    title: "Occupational Health & Safety Technician",
    field: "engineering",
    medianPay: 61560,
    medianHourlyPay: 29.59,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "High school plus paid on-the-job safety training",
    growth: 8.5,
    note: "Collects samples, tests equipment, and documents hazards under the direction of safety specialists.",
  },
  {
    id: "compensation-benefits-specialist",
    title: "Compensation & Benefits Specialist",
    field: "business",
    medianPay: 78210,
    medianHourlyPay: 37.6,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in human resources, business, or analytics",
    growth: 5.3,
    note: "Analyzes pay structures, health plans, retirement benefits, and job levels for employers.",
  },
  {
    id: "labor-relations-specialist",
    title: "Labor Relations Specialist",
    field: "business",
    medianPay: 95420,
    medianHourlyPay: 45.87,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus experience with labor or human resources",
    growth: -0.1,
    note: "Works on union contracts, grievances, workplace policy, and negotiations for employers or labor organizations.",
  },
  {
    id: "financial-examiner",
    title: "Financial Examiner",
    field: "business",
    medianPay: 94160,
    medianHourlyPay: 45.27,
    education: "bachelor",
    earnWhileTraining: true,
    trainingNote: "Bachelor's degree followed by paid long-term examiner training",
    growth: 18.5,
    note: "Reviews banks and other financial institutions for legal compliance, risk, and consumer protection.",
  },
  {
    id: "financial-risk-specialist",
    title: "Financial Risk Specialist",
    field: "business",
    medianPay: 117330,
    medianHourlyPay: 56.41,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree in finance, economics, math, or a related field",
    growth: 6.5,
    note: "Measures the chance of financial loss and builds controls for investments, lending, markets, and operations.",
  },
  {
    id: "natural-sciences-manager",
    title: "Natural Sciences Manager",
    field: "business",
    medianPay: 167220,
    medianHourlyPay: 80.39,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Science degree plus several years of laboratory or research experience",
    growth: 3.7,
    note: "Leads scientists, laboratories, budgets, and research programs after time working in a scientific field.",
  },
  {
    id: "purchasing-manager",
    title: "Purchasing Manager",
    field: "business",
    medianPay: 148080,
    medianHourlyPay: 71.19,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus several years as a buyer or purchasing agent",
    growth: 3.1,
    note: "Sets sourcing strategy and leads the people who negotiate for materials, equipment, and services.",
  },
  {
    id: "pr-manager",
    title: "Public Relations Manager",
    field: "business",
    medianPay: 146910,
    medianHourlyPay: 70.63,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus several years in communications or public relations",
    growth: 5,
    note: "Directs an organization's public messaging, media response, reputation, and communications team.",
  },
  {
    id: "fundraising-manager",
    title: "Fundraising Manager",
    field: "business",
    medianPay: 125470,
    medianHourlyPay: 60.32,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus several years in fundraising or nonprofit work",
    growth: 4.2,
    note: "Leads donor strategy, campaigns, events, and fundraising teams for nonprofits and institutions.",
  },
  {
    id: "training-development-manager",
    title: "Training & Development Manager",
    field: "business",
    medianPay: 133000,
    medianHourlyPay: 63.94,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus experience in training, HR, or management",
    growth: 5.8,
    note: "Plans how an organization teaches skills, develops leaders, and measures whether employee training works.",
  },
  {
    id: "mediator",
    title: "Arbitrator / Mediator",
    field: "education",
    medianPay: 75530,
    medianHourlyPay: 36.31,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus specialized training and relevant experience",
    growth: 4.3,
    note: "Helps people and organizations resolve disputes outside court through structured negotiation or a binding decision.",
  },
  {
    id: "college-professor",
    title: "College Professor",
    field: "education",
    medianPay: 82250,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "Master's or doctorate, depending on subject and institution",
    growth: 5.9,
    note: "We use one useful umbrella here instead of padding the explorer with a separate federal code for every subject taught.",
  },
  {
    id: "cte-teacher",
    title: "Career & Technical Education Teacher",
    field: "education",
    medianPay: 66270,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree, occupational experience, and a state teaching license",
    growth: -1.8,
    note: "Teaches hands-on career subjects such as health occupations, auto technology, construction, agriculture, or business in secondary schools.",
  },
  {
    id: "trade-school-instructor",
    title: "Trade School Instructor",
    field: "education",
    medianPay: 63820,
    medianHourlyPay: 30.68,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Industry experience plus the degree or credential required by the school",
    growth: 0.7,
    note: "Teaches an occupation at a community college or technical school after building real experience in that trade or field.",
  },
  {
    id: "childcare-director",
    title: "Preschool / Childcare Center Director",
    field: "education",
    medianPay: 59300,
    medianHourlyPay: 28.51,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus early-childhood experience; state rules vary",
    growth: -2.5,
    note: "Runs the staff, budget, enrollment, safety, and learning program of a preschool or childcare center.",
  },
  {
    id: "library-technician",
    title: "Library Technician",
    field: "education",
    medianPay: 44580,
    medianHourlyPay: 21.43,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Postsecondary certificate is typical; some roles train high school graduates",
    growth: -6.8,
    note: "Helps patrons, manages materials and records, and supports programs under a librarian's direction.",
  },
  {
    id: "archivist",
    title: "Archivist",
    field: "education",
    medianPay: 64550,
    medianHourlyPay: 31.03,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree in library science, history, archives, or a related field",
    growth: 3.8,
    note: "Preserves and organizes historical records, photographs, digital files, and collections so people can find and use them.",
  },
  {
    id: "pt-aide",
    title: "Physical Therapist Aide",
    field: "health",
    medianPay: 35240,
    medianHourlyPay: 16.94,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "High school plus short paid on-the-job training",
    growth: 2.8,
    note: "Sets up treatment spaces and helps patients move safely; it is distinct from the licensed two-year physical therapist assistant role.",
  },
  {
    id: "health-information-tech",
    title: "Health Information Technologist / Medical Registrar",
    field: "health",
    medianPay: 68020,
    medianHourlyPay: 32.7,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in health information management or a related field",
    growth: 14.7,
    note: "Builds and analyzes clinical data systems and registries, connecting healthcare, records, quality, and analytics.",
  },
  {
    id: "medical-dosimetrist",
    title: "Medical Dosimetrist",
    field: "health",
    medianPay: 147470,
    medianHourlyPay: 70.9,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree plus an accredited dosimetry program and certification",
    growth: 3.5,
    note: "Calculates and maps radiation doses for cancer treatment with radiation oncologists and medical physicists.",
  },
  {
    id: "pathologist",
    title: "Pathologist",
    field: "health",
    medianPay: 312400,
    medianHourlyPay: 150.19,
    education: "doctoral",
    earnWhileTraining: true,
    trainingNote: "Medical school followed by paid pathology residency",
    growth: 4.2,
    note: "Diagnoses disease by examining tissue, blood, and laboratory results, often working behind the scenes in hospitals and labs.",
  },
  {
    id: "actor",
    title: "Actor",
    field: "service",
    medianPay: null,
    medianHourlyPay: 29.05,
    education: "some-college",
    earnWhileTraining: false,
    trainingNote: "Classes and performance experience; no single required credential",
    growth: 0.3,
    note: "BLS reports acting pay by the hour because projects and workweeks are irregular, so we do not invent an annual salary.",
  },
  {
    id: "musician-singer",
    title: "Musician / Singer",
    field: "service",
    medianPay: null,
    medianHourlyPay: 47.8,
    education: "none",
    earnWhileTraining: false,
    trainingNote: "Years of practice and auditions; formal study is common but not required",
    growth: 1.1,
    note: "BLS reports an hourly median because performances and recording work are intermittent, not a standard annual salary.",
  },
  {
    id: "dancer",
    title: "Dancer",
    field: "service",
    medianPay: null,
    medianHourlyPay: 24.8,
    education: "none",
    earnWhileTraining: false,
    trainingNote: "Long-term dance training and auditions; no required degree",
    growth: 4.5,
    note: "Dance work is seasonal and project-based, so the federal wage survey publishes hourly pay rather than an annual median.",
  },
  {
    id: "choreographer",
    title: "Choreographer",
    field: "service",
    medianPay: 55310,
    medianHourlyPay: 26.59,
    education: "hs",
    earnWhileTraining: false,
    trainingNote: "Long-term dance experience; no single required degree",
    growth: 6.1,
    note: "Creates and rehearses movement for stage, screen, concerts, and other performances, usually after years as a dancer.",
  },
  {
    id: "broadcast-technician",
    title: "Broadcast Technician",
    field: "service",
    medianPay: 59570,
    medianHourlyPay: 28.64,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree in broadcast technology or a related field",
    growth: -2.8,
    note: "Operates the equipment that records, switches, transmits, and monitors television, radio, streaming, and live productions.",
  },
  {
    id: "cnc-programmer",
    title: "CNC Tool Programmer",
    field: "trades",
    medianPay: 68120,
    medianHourlyPay: 32.75,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Certificate plus paid shop training or apprenticeship",
    growth: 12.8,
    note: "Writes and tests the instructions that tell computer-controlled machines how to cut precise parts.",
  },
  {
    id: "substation-tech",
    title: "Substation / Relay Technician",
    field: "trades",
    medianPay: 103020,
    medianHourlyPay: 49.53,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Technical program followed by paid utility training",
    growth: 5.5,
    note: "Tests and repairs the control, relay, and switching equipment that protects the electric grid.",
  },
  {
    id: "power-dispatcher",
    title: "Power Distributor / Dispatcher",
    field: "trades",
    medianPay: 106730,
    medianHourlyPay: 51.31,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "High school plus extensive paid utility training",
    growth: -3.2,
    note: "Balances electricity supply and demand from a control room and coordinates the grid during outages and emergencies.",
  },
  {
    id: "nuclear-technician",
    title: "Nuclear Technician",
    field: "engineering",
    medianPay: 110240,
    medianHourlyPay: 53,
    education: "associate",
    earnWhileTraining: true,
    trainingNote: "Associate degree followed by paid employer training",
    growth: -7.7,
    note: "Monitors radiation and equipment and supports engineers and operators in nuclear power, research, or waste work.",
  },
  {
    id: "nuclear-reactor-operator",
    title: "Nuclear Reactor Operator",
    field: "trades",
    medianPay: 122890,
    medianHourlyPay: 59.08,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "High school plus years of paid plant training and federal licensing",
    growth: -15.3,
    note: "Controls a nuclear reactor and responds to plant conditions; openings are few and the training and licensing bar is high.",
  },
  {
    id: "ship-engineer",
    title: "Ship Engineer",
    field: "service",
    medianPay: 109530,
    medianHourlyPay: 52.66,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Maritime program or sea-time route plus a Coast Guard credential",
    growth: 1.6,
    note: "Operates and repairs a vessel's engines, generators, pumps, and mechanical systems while at sea.",
  },
  {
    id: "rail-car-repairer",
    title: "Rail Car Repairer",
    field: "trades",
    medianPay: 67530,
    medianHourlyPay: 32.46,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "High school plus long-term paid railroad training",
    growth: 2.8,
    note: "Inspects and repairs freight cars, passenger coaches, brakes, couplers, and undercarriages in rail yards and shops.",
  },
  {
    id: "commercial-fisher",
    title: "Fishing / Hunting Worker",
    field: "service",
    medianPay: null,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "Paid on-the-job training; Coast Guard credentials for some vessel duties",
    growth: -4.6,
    note: "The work is seasonal and often self-employed, so BLS does not publish a wage estimate; the explorer leaves pay blank instead of inventing one.",
  },
];

export const CAREER_ADDITION_DETAILS: Record<string, CareerDetail> = {
  "anthropologist-archaeologist": {
    soc: "19-3091",
    payLow: 49050,
    payHigh: 108060,
    hourlyPayLow: 23.58,
    hourlyMedian: 34.02,
    hourlyPayHigh: 51.95,
    numJobs: 8990,
    annualOpenings: 800,
    selfEmployedPercent: 3.6,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/anthropologists-and-archeologists.htm",
    whatTheyDo: "Study human cultures and societies or recover and interpret material evidence from the past.",
    workSetting: "Offices, museums, laboratories, and field sites; travel and seasonal fieldwork are common.",
    hours: "Usually full-time; field projects can mean long or irregular days.",
    skills: ["Research", "Field methods", "Writing", "Cultural awareness"],
    related: ["historian", "archivist", "sociologist"],
  },
  meteorologist: {
    soc: "19-2021",
    payLow: 53060,
    payHigh: 161890,
    hourlyPayLow: 25.51,
    hourlyMedian: 47.63,
    hourlyPayHigh: 77.83,
    numJobs: 10000,
    annualOpenings: 700,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/atmospheric-scientists-including-meteorologists.htm",
    whatTheyDo: "Measure and model the atmosphere to forecast weather and study climate and atmospheric processes.",
    workSetting: "Weather offices, research labs, broadcast studios, and field stations.",
    hours: "Full-time; forecasting centers may use nights, weekends, and rotating shifts.",
    skills: ["Weather modeling", "Data analysis", "Physics", "Communication"],
    related: ["environmental-scientist", "physicist", "data-scientist"],
  },
  "materials-scientist": {
    soc: "19-2032",
    payLow: 66820,
    payHigh: 197290,
    hourlyPayLow: 32.13,
    hourlyMedian: 56.63,
    hourlyPayHigh: 94.85,
    numJobs: 8470,
    annualOpenings: 600,
    selfEmployedPercent: 1.1,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/chemists-and-materials-scientists.htm",
    whatTheyDo: "Research the structure and properties of materials and develop new ones for specific products and conditions.",
    workSetting: "Laboratories, manufacturing plants, and offices.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Laboratory testing", "Chemistry", "Data analysis", "Problem solving"],
    related: ["chemist", "materials-engineer", "chemical-engineer"],
  },
  hydrologist: {
    soc: "19-2043",
    payLow: 64020,
    payHigh: 153130,
    hourlyPayLow: 30.78,
    hourlyMedian: 46.44,
    hourlyPayHigh: 73.62,
    numJobs: 5850,
    annualOpenings: 500,
    selfEmployedPercent: 3.1,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/hydrologists.htm",
    whatTheyDo: "Measure and model surface water and groundwater to understand supply, quality, floods, and drought.",
    workSetting: "Offices, laboratories, rivers, wells, and other outdoor field sites.",
    hours: "Full-time; travel and longer field days may occur.",
    skills: ["Field sampling", "GIS", "Data modeling", "Technical writing"],
    related: ["environmental-scientist", "geoscientist", "civil-engineer"],
  },
  "political-scientist": {
    soc: "19-3094",
    payLow: 83350,
    payHigh: 195190,
    hourlyPayLow: 40.07,
    hourlyMedian: 68.31,
    hourlyPayHigh: 93.84,
    numJobs: 5540,
    annualOpenings: 500,
    selfEmployedPercent: 1.1,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/political-scientists.htm",
    whatTheyDo: "Research political ideas, institutions, public opinion, elections, policy, and government behavior.",
    workSetting: "Government agencies, universities, research organizations, and offices.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Policy research", "Statistics", "Writing", "Critical thinking"],
    related: ["economist", "sociologist", "urban-planner"],
  },
  sociologist: {
    soc: "19-3041",
    payLow: 65160,
    payHigh: 172550,
    hourlyPayLow: 31.33,
    hourlyMedian: 50.98,
    hourlyPayHigh: 82.96,
    numJobs: 2260,
    annualOpenings: 300,
    selfEmployedPercent: 3,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/sociologists.htm",
    whatTheyDo: "Design research and analyze how groups, organizations, communities, and social institutions behave and change.",
    workSetting: "Research organizations, government, universities, and offices.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Social research", "Statistics", "Interviewing", "Writing"],
    related: ["political-scientist", "anthropologist-archaeologist", "market-research-analyst"],
  },
  historian: {
    soc: "19-3093",
    payLow: 42730,
    payHigh: 131810,
    hourlyPayLow: 20.55,
    hourlyMedian: 36.9,
    hourlyPayHigh: 63.37,
    numJobs: 3450,
    annualOpenings: 300,
    selfEmployedPercent: 2,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/historians.htm",
    whatTheyDo: "Research primary sources and explain historical events and change for public, academic, or institutional audiences.",
    workSetting: "Museums, archives, government agencies, universities, and offices.",
    hours: "Usually full-time; travel to archives or historic sites may occur.",
    skills: ["Archival research", "Writing", "Source evaluation", "Public speaking"],
    related: ["archivist", "curator", "anthropologist-archaeologist"],
  },
  astronomer: {
    soc: "19-2011",
    payLow: 78010,
    payHigh: 195190,
    hourlyPayLow: 37.5,
    hourlyMedian: 61.94,
    hourlyPayHigh: 93.84,
    numJobs: 2120,
    annualOpenings: 100,
    selfEmployedPercent: 5.4,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/physicists-and-astronomers.htm",
    whatTheyDo: "Observe and model objects and events beyond Earth using telescopes, satellites, physics, and large datasets.",
    workSetting: "Universities, observatories, federal laboratories, and offices.",
    hours: "Full-time; observations, deadlines, and travel can create irregular hours.",
    skills: ["Physics", "Programming", "Data analysis", "Research"],
    related: ["physicist", "aerospace-engineer", "data-scientist"],
  },
  mathematician: {
    soc: "15-2021",
    payLow: 69240,
    payHigh: 195190,
    hourlyPayLow: 33.29,
    hourlyMedian: 60.92,
    hourlyPayHigh: 93.84,
    numJobs: 2030,
    annualOpenings: 100,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/math/mathematicians-and-statisticians.htm",
    whatTheyDo: "Develop mathematical methods and models and apply them to problems in science, engineering, government, and business.",
    workSetting: "Offices, universities, government agencies, and research organizations.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Advanced mathematics", "Modeling", "Programming", "Logical reasoning"],
    related: ["statistician", "operations-research-analyst", "data-scientist"],
  },
  "animal-scientist": {
    soc: "19-1011",
    payLow: 44350,
    payHigh: 166000,
    hourlyPayLow: 21.32,
    hourlyMedian: 33.14,
    hourlyPayHigh: 79.81,
    numJobs: 3100,
    annualOpenings: 200,
    selfEmployedPercent: 2.3,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/agricultural-and-food-scientists.htm",
    whatTheyDo: "Research animal nutrition, genetics, growth, reproduction, and welfare in agriculture and food systems.",
    workSetting: "Farms, laboratories, universities, and offices.",
    hours: "Usually full-time; animal and field work may require irregular hours.",
    skills: ["Animal biology", "Research", "Data analysis", "Fieldwork"],
    related: ["veterinarian", "food-scientist", "agronomist"],
  },
  "agricultural-engineer": {
    soc: "17-2021",
    payLow: 68060,
    payHigh: 166460,
    hourlyPayLow: 32.72,
    hourlyMedian: 47.4,
    hourlyPayHigh: 80.03,
    numJobs: 1480,
    annualOpenings: 100,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/agricultural-engineers.htm",
    whatTheyDo: "Design machinery, structures, sensors, and water or energy systems for agriculture and food production.",
    workSetting: "Offices, laboratories, farms, and manufacturing facilities.",
    hours: "Usually full-time; travel to project sites may occur.",
    skills: ["Engineering design", "CAD", "Systems thinking", "Problem solving"],
    license: "A professional engineer license is optional early on and required for some public-facing work.",
    related: ["mechanical-engineer", "environmental-engineer", "agronomist"],
  },
  "marine-engineer": {
    soc: "17-2121",
    payLow: 83010,
    payHigh: 173330,
    hourlyPayLow: 39.91,
    hourlyMedian: 53.96,
    hourlyPayHigh: 83.33,
    numJobs: 8250,
    annualOpenings: 600,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/marine-engineers-and-naval-architects.htm",
    whatTheyDo: "Design and evaluate ships, vessel machinery, propulsion, and offshore structures.",
    workSetting: "Engineering offices, shipyards, testing facilities, and docks.",
    hours: "Usually full-time; deadlines and sea trials may extend hours.",
    skills: ["Naval design", "Fluid mechanics", "CAD", "Systems engineering"],
    license: "A professional engineer license may be required for some senior roles.",
    related: ["ship-engineer", "mechanical-engineer", "ship-captain"],
  },
  "io-psychologist": {
    soc: "19-3032",
    payLow: 79010,
    payHigh: 247220,
    hourlyPayLow: 37.99,
    hourlyMedian: 93.24,
    hourlyPayHigh: 118.86,
    numJobs: 790,
    annualOpenings: 400,
    selfEmployedPercent: 80.5,
    workExperience: "None",
    onJobTraining: "Internship/residency",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/psychologists.htm",
    whatTheyDo: "Study and improve how people are selected, trained, organized, motivated, and supported at work.",
    workSetting: "Consulting firms, corporate offices, government, and research settings.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Psychometrics", "Statistics", "Research design", "Consulting"],
    license: "Licensing rules vary; independent psychological practice may require a state license.",
    related: ["hr-specialist", "management-analyst", "training-development-specialist"],
  },
  "electrical-engineering-tech": {
    soc: "17-3023",
    payLow: 49510,
    payHigh: 115700,
    hourlyPayLow: 23.8,
    hourlyMedian: 37.59,
    hourlyPayHigh: 55.62,
    numJobs: 95130,
    annualOpenings: 8400,
    selfEmployedPercent: 0.1,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/electrical-and-electronics-engineering-technicians.htm",
    whatTheyDo: "Build, test, calibrate, and repair electrical and electronic equipment and prototypes.",
    workSetting: "Laboratories, factories, utilities, and engineering offices.",
    hours: "Usually full-time; manufacturing roles may use shifts.",
    skills: ["Circuit testing", "Electronics", "Schematics", "Troubleshooting"],
    related: ["electrical-engineer", "electronics-engineer", "mechatronics-tech"],
  },
  "industrial-engineering-tech": {
    soc: "17-3026",
    payLow: 47300,
    payHigh: 99150,
    hourlyPayLow: 22.74,
    hourlyMedian: 31.79,
    hourlyPayHigh: 47.67,
    numJobs: 75570,
    annualOpenings: 6300,
    selfEmployedPercent: 1.5,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/industrial-engineering-technicians.htm",
    whatTheyDo: "Collect and analyze production data and help design efficient workflows, layouts, standards, and quality controls.",
    workSetting: "Factories, warehouses, hospitals, and offices.",
    hours: "Usually full-time; plant roles may use shifts.",
    skills: ["Process mapping", "Data analysis", "Quality tools", "Measurement"],
    related: ["industrial-engineer", "quality-inspector", "production-supervisor"],
  },
  "mechanical-engineering-tech": {
    soc: "17-3027",
    payLow: 48400,
    payHigh: 106050,
    hourlyPayLow: 23.27,
    hourlyMedian: 35.82,
    hourlyPayHigh: 50.99,
    numJobs: 36190,
    annualOpenings: 3200,
    selfEmployedPercent: 1.5,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/mechanical-engineering-technicians.htm",
    whatTheyDo: "Create drawings, build prototypes, run tests, and troubleshoot mechanical products and systems.",
    workSetting: "Engineering offices, laboratories, and manufacturing plants.",
    hours: "Usually full-time with regular schedules.",
    skills: ["CAD", "Mechanical testing", "Measurement", "Troubleshooting"],
    related: ["mechanical-engineer", "mechatronics-tech", "machinist"],
  },
  "mechatronics-tech": {
    soc: "17-3024",
    payLow: 47840,
    payHigh: 109890,
    hourlyPayLow: 23,
    hourlyMedian: 35.53,
    hourlyPayHigh: 52.83,
    numJobs: 15520,
    annualOpenings: 1300,
    selfEmployedPercent: 1.5,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/electro-mechanical-technicians.htm",
    whatTheyDo: "Install and maintain automated systems that combine mechanics, electronics, sensors, and computer controls.",
    workSetting: "Factories, engineering labs, and equipment service sites.",
    hours: "Usually full-time; shift and on-call work may occur.",
    skills: ["Automation", "Electronics", "Mechanical systems", "Troubleshooting"],
    related: ["industrial-mechanic", "electrical-engineering-tech", "industrial-engineer"],
  },
  "surveying-mapping-tech": {
    soc: "17-3031",
    payLow: 37520,
    payHigh: 81630,
    hourlyPayLow: 18.04,
    hourlyMedian: 26.08,
    hourlyPayHigh: 39.24,
    numJobs: 58010,
    annualOpenings: 7600,
    selfEmployedPercent: 3.6,
    workExperience: "None",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/surveying-and-mapping-technicians.htm",
    whatTheyDo: "Use field instruments, GPS, drones, and software to collect measurements and prepare maps and survey documents.",
    workSetting: "Outdoor field sites and offices; travel to changing locations is common.",
    hours: "Full-time; field days depend on weather and project schedules.",
    skills: ["GPS instruments", "GIS", "Measurement", "Attention to detail"],
    related: ["surveyor", "cartographer", "civil-engineering-tech"],
  },
  "chemical-technician": {
    soc: "19-4031",
    payLow: 41740,
    payHigh: 92040,
    hourlyPayLow: 20.07,
    hourlyMedian: 29.03,
    hourlyPayHigh: 44.25,
    numJobs: 57540,
    annualOpenings: 6700,
    selfEmployedPercent: 0.7,
    workExperience: "None",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/chemical-technicians.htm",
    whatTheyDo: "Prepare experiments, operate laboratory equipment, and test chemicals and products under scientists or engineers.",
    workSetting: "Laboratories, manufacturing plants, and quality-control facilities.",
    hours: "Usually full-time; production labs may use shifts.",
    skills: ["Lab techniques", "Chemical safety", "Data recording", "Quality control"],
    related: ["chemist", "materials-scientist", "clinical-lab-tech"],
  },
  "environmental-science-tech": {
    soc: "19-4042",
    payLow: 38170,
    payHigh: 94160,
    hourlyPayLow: 18.35,
    hourlyMedian: 26.49,
    hourlyPayHigh: 45.27,
    numJobs: 34670,
    annualOpenings: 5600,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/environmental-science-and-protection-technicians.htm",
    whatTheyDo: "Collect samples, inspect sites, and run tests to monitor pollution and environmental health risks.",
    workSetting: "Laboratories, offices, factories, and outdoor field sites.",
    hours: "Usually full-time; field response may require irregular hours.",
    skills: ["Sampling", "Laboratory testing", "Regulations", "Technical records"],
    related: ["environmental-scientist", "occupational-safety-tech", "hydrologist"],
  },
  "agricultural-tech": {
    soc: "19-4012",
    payLow: 35980,
    payHigh: 76480,
    hourlyPayLow: 17.3,
    hourlyMedian: 23.86,
    hourlyPayHigh: 36.77,
    numJobs: 15130,
    annualOpenings: 2900,
    selfEmployedPercent: 5.2,
    workExperience: "None",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/agricultural-and-food-science-technicians.htm",
    whatTheyDo: "Set up and support tests involving crops, soil, animals, food, and agricultural equipment.",
    workSetting: "Farms, fields, laboratories, processing plants, and offices.",
    hours: "Usually full-time; field seasons may bring longer days.",
    skills: ["Field sampling", "Lab testing", "Data recording", "Equipment use"],
    related: ["agronomist", "animal-scientist", "food-scientist"],
  },
  "aerospace-engineering-tech": {
    soc: "17-3021",
    payLow: 59050,
    payHigh: 125160,
    hourlyPayLow: 28.39,
    hourlyMedian: 39.85,
    hourlyPayHigh: 60.18,
    numJobs: 11280,
    annualOpenings: 900,
    selfEmployedPercent: 1.4,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/architecture-and-engineering/aerospace-engineering-and-operations-technicians.htm",
    whatTheyDo: "Install test equipment, collect data, and maintain systems used in aircraft and spacecraft development.",
    workSetting: "Laboratories, manufacturing plants, hangars, and test facilities.",
    hours: "Usually full-time; test programs may require shifts.",
    skills: ["Test equipment", "Electronics", "Measurement", "Technical documentation"],
    related: ["aerospace-engineer", "avionics-tech", "aircraft-mechanic"],
  },
  "occupational-safety-tech": {
    soc: "19-5012",
    payLow: 46280,
    payHigh: 100160,
    hourlyPayLow: 22.25,
    hourlyMedian: 29.59,
    hourlyPayHigh: 48.15,
    numJobs: 30590,
    annualOpenings: 3400,
    workExperience: "None",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/healthcare/occupational-health-and-safety-specialists-and-technicians.htm",
    whatTheyDo: "Inspect equipment and worksites, collect samples, and help document and correct workplace hazards.",
    workSetting: "Factories, construction sites, offices, and other workplaces.",
    hours: "Usually full-time; travel and emergency response may occur.",
    skills: ["Inspection", "Sampling", "Safety rules", "Recordkeeping"],
    related: ["occupational-safety-specialist", "building-inspector", "environmental-science-tech"],
  },
  "compensation-benefits-specialist": {
    soc: "13-1141",
    payLow: 49480,
    payHigh: 128920,
    hourlyPayLow: 23.79,
    hourlyMedian: 37.6,
    hourlyPayHigh: 61.98,
    numJobs: 112380,
    annualOpenings: 8500,
    workExperience: "Less than 5 years",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/business-and-financial/compensation-benefits-and-job-analysis-specialists.htm",
    whatTheyDo: "Research market pay, evaluate jobs, and help design salary, health, retirement, and leave programs.",
    workSetting: "Corporate, government, consulting, and nonprofit offices.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Data analysis", "Job evaluation", "Benefits rules", "Communication"],
    related: ["hr-specialist", "hr-manager", "financial-analyst"],
  },
  "labor-relations-specialist": {
    soc: "13-1075",
    payLow: 50490,
    payHigh: 156180,
    hourlyPayLow: 24.27,
    hourlyMedian: 45.87,
    hourlyPayHigh: 75.09,
    numJobs: 64810,
    annualOpenings: 5100,
    selfEmployedPercent: 0.5,
    workExperience: "Less than 5 years",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/business-and-financial/labor-relations-specialists.htm",
    whatTheyDo: "Interpret labor contracts, investigate grievances, and support negotiations between employers and workers.",
    workSetting: "Employer offices, unions, government, and worksites.",
    hours: "Usually full-time; negotiations may extend beyond regular hours.",
    skills: ["Negotiation", "Labor law", "Conflict resolution", "Writing"],
    related: ["hr-specialist", "mediator", "lawyer"],
  },
  "financial-examiner": {
    soc: "13-2061",
    payLow: 56230,
    payHigh: 174200,
    hourlyPayLow: 27.04,
    hourlyMedian: 45.27,
    hourlyPayHigh: 83.75,
    numJobs: 67830,
    annualOpenings: 5700,
    selfEmployedPercent: 0.4,
    workExperience: "None",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/business-and-financial/financial-examiners.htm",
    whatTheyDo: "Review financial institutions' records and practices to assess risk and enforce laws that protect the financial system and consumers.",
    workSetting: "Government offices, banks, and financial institutions; travel is common.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Financial analysis", "Regulation", "Auditing", "Technical writing"],
    related: ["accountant", "compliance-officer", "financial-risk-specialist"],
  },
  "financial-risk-specialist": {
    soc: "13-2054",
    payLow: 64820,
    payHigh: 196110,
    hourlyPayLow: 31.17,
    hourlyMedian: 56.41,
    hourlyPayHigh: 94.29,
    numJobs: 63850,
    annualOpenings: 4800,
    selfEmployedPercent: 4,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm",
    whatTheyDo: "Analyze market, credit, and operational risks and recommend limits or controls to reduce potential losses.",
    workSetting: "Banks, investment firms, insurers, consulting firms, and offices.",
    hours: "Usually full-time; market-driven roles may run longer.",
    skills: ["Risk modeling", "Statistics", "Finance", "Communication"],
    related: ["financial-analyst", "actuary", "financial-examiner"],
  },
  "natural-sciences-manager": {
    soc: "11-9121",
    payLow: 79710,
    payHigh: 316850,
    hourlyPayLow: 38.32,
    hourlyMedian: 80.39,
    hourlyPayHigh: 152.33,
    numJobs: 108690,
    annualOpenings: 8500,
    workExperience: "5 years or more",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/management/natural-sciences-managers.htm",
    whatTheyDo: "Plan research, manage laboratories and budgets, and lead scientists and technical staff.",
    workSetting: "Research laboratories, manufacturing, government, and offices.",
    hours: "Usually full-time; deadlines may extend hours.",
    skills: ["Scientific leadership", "Project management", "Budgeting", "Communication"],
    related: ["medical-scientist", "chemist", "engineering-manager"],
  },
  "purchasing-manager": {
    soc: "11-3061",
    payLow: 92490,
    payHigh: 223280,
    hourlyPayLow: 44.47,
    hourlyMedian: 71.19,
    hourlyPayHigh: 107.35,
    numJobs: 84320,
    annualOpenings: 6400,
    selfEmployedPercent: 0.8,
    workExperience: "5 years or more",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/business-and-financial/purchasing-managers-buyers-and-purchasing-agents.htm",
    whatTheyDo: "Set purchasing policies, negotiate major contracts, and lead buyers who source goods and services.",
    workSetting: "Corporate, government, healthcare, and manufacturing offices.",
    hours: "Usually full-time; travel and supplier deadlines may extend hours.",
    skills: ["Negotiation", "Supplier strategy", "Cost analysis", "Leadership"],
    related: ["purchasing-agent", "logistician", "operations-manager"],
  },
  "pr-manager": {
    soc: "11-2032",
    payLow: 82410,
    payHigh: 284990,
    hourlyPayLow: 39.62,
    hourlyMedian: 70.63,
    hourlyPayHigh: 137.01,
    numJobs: 74850,
    annualOpenings: 6600,
    selfEmployedPercent: 0.3,
    workExperience: "5 years or more",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/management/public-relations-managers.htm",
    whatTheyDo: "Plan public communications, supervise media relations, and manage reputation and crisis response.",
    workSetting: "Companies, agencies, nonprofits, government, and offices.",
    hours: "Usually full-time; news events can create irregular hours.",
    skills: ["Media strategy", "Writing", "Crisis communication", "Leadership"],
    related: ["pr-specialist", "marketing-manager", "editor"],
  },
  "fundraising-manager": {
    soc: "11-2033",
    payLow: 75130,
    payHigh: 222350,
    hourlyPayLow: 36.12,
    hourlyMedian: 60.32,
    hourlyPayHigh: 106.9,
    numJobs: 38810,
    annualOpenings: 3600,
    selfEmployedPercent: 0.2,
    workExperience: "5 years or more",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/management/public-relations-managers.htm",
    whatTheyDo: "Set fundraising strategy, lead campaigns and staff, and build relationships with donors and institutions.",
    workSetting: "Nonprofits, colleges, hospitals, arts organizations, and offices.",
    hours: "Usually full-time; events may require evenings and weekends.",
    skills: ["Donor strategy", "Campaign planning", "Writing", "Leadership"],
    related: ["fundraiser", "community-service-manager", "event-planner"],
  },
  "training-development-manager": {
    soc: "11-3131",
    payLow: 79550,
    payHigh: 233600,
    hourlyPayLow: 38.24,
    hourlyMedian: 63.94,
    hourlyPayHigh: 112.31,
    numJobs: 48050,
    annualOpenings: 3800,
    workExperience: "5 years or more",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/management/training-and-development-managers.htm",
    whatTheyDo: "Set employee-learning strategy, lead trainers, choose programs, and evaluate whether training improves performance.",
    workSetting: "Corporate, government, healthcare, and education offices.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Learning strategy", "Leadership", "Program evaluation", "Communication"],
    related: ["training-development-specialist", "hr-manager", "instructional-coordinator"],
  },
  mediator: {
    soc: "23-1022",
    payLow: 47220,
    payHigh: 155440,
    hourlyPayLow: 22.7,
    hourlyMedian: 36.31,
    hourlyPayHigh: 74.73,
    numJobs: 9210,
    annualOpenings: 300,
    selfEmployedPercent: 9.1,
    workExperience: "Less than 5 years",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/legal/arbitrators-mediators-and-conciliators.htm",
    whatTheyDo: "Guide parties through disputes or hear evidence and issue decisions outside the traditional court process.",
    workSetting: "Law offices, government, courts, conference rooms, and remote sessions.",
    hours: "Full-time, part-time, or contract; schedules follow cases.",
    skills: ["Conflict resolution", "Listening", "Negotiation", "Legal reasoning"],
    license: "Requirements vary by state and practice area; courts often maintain approved rosters.",
    related: ["lawyer", "judge", "labor-relations-specialist"],
  },
  "college-professor": {
    soc: "25-1000",
    payLow: 48230,
    payHigh: 177070,
    numJobs: 1370560,
    annualOpenings: 136400,
    selfEmployedPercent: 0.3,
    oohUrl: "https://www.bls.gov/ooh/education-training-and-library/postsecondary-teachers.htm",
    whatTheyDo: "Teach college courses, advise students, assess learning, and often conduct research or professional work in a subject area.",
    workSetting: "Community colleges, four-year colleges, universities, and online programs.",
    hours: "Schedules mix classes, preparation, office hours, grading, and research; part-time work is common.",
    skills: ["Subject expertise", "Teaching", "Research", "Mentoring"],
    related: ["nursing-instructor", "trade-school-instructor", "instructional-coordinator"],
  },
  "cte-teacher": {
    soc: "25-2032",
    payLow: 50040,
    payHigh: 101340,
    numJobs: 111420,
    annualOpenings: 6200,
    workExperience: "Less than 5 years",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/education-training-and-library/career-and-technical-education-teachers.htm",
    whatTheyDo: "Teach career and technical subjects in middle or high school through classroom lessons, labs, and hands-on projects.",
    workSetting: "Public and private secondary schools, labs, shops, and classrooms.",
    hours: "School-day schedule plus planning, grading, and activities.",
    license: "Public-school teachers need a state license; occupational experience may count toward an alternative pathway.",
    skills: ["Teaching", "Industry knowledge", "Safety", "Lesson planning"],
    related: ["trade-school-instructor", "teacher-hs", "instructional-coordinator"],
  },
  "trade-school-instructor": {
    soc: "25-1194",
    payLow: 41960,
    payHigh: 108620,
    hourlyPayLow: 20.17,
    hourlyMedian: 30.68,
    hourlyPayHigh: 52.22,
    numJobs: 114110,
    annualOpenings: 8800,
    selfEmployedPercent: 0.4,
    workExperience: "Less than 5 years",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/education-training-and-library/career-and-technical-education-teachers.htm",
    whatTheyDo: "Teach an occupation or technical field through demonstrations, labs, projects, and job-ready practice.",
    workSetting: "Community colleges, trade schools, technical institutes, and training centers.",
    hours: "Full-time or part-time; evening classes are common.",
    skills: ["Industry expertise", "Teaching", "Demonstration", "Safety"],
    related: ["cte-teacher", "college-professor", "training-development-specialist"],
  },
  "childcare-director": {
    soc: "11-9031",
    payLow: 38580,
    payHigh: 98240,
    hourlyPayLow: 18.55,
    hourlyMedian: 28.51,
    hourlyPayHigh: 47.23,
    numJobs: 73660,
    annualOpenings: 5500,
    selfEmployedPercent: 4.9,
    workExperience: "Less than 5 years",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/management/preschool-and-childcare-center-directors.htm",
    whatTheyDo: "Manage a preschool or childcare center's staff, curriculum, enrollment, finances, safety, and licensing compliance.",
    workSetting: "Preschools, childcare centers, and school-based programs.",
    hours: "Usually full-time; centers may open early and close late.",
    license: "States set education, experience, background-check, and center-director licensing rules.",
    skills: ["Early childhood education", "Staff management", "Budgeting", "Family communication"],
    related: ["preschool-teacher", "childcare-worker", "school-administrator"],
  },
  "library-technician": {
    soc: "25-4031",
    payLow: 29300,
    payHigh: 63080,
    hourlyPayLow: 14.09,
    hourlyMedian: 21.43,
    hourlyPayHigh: 30.33,
    numJobs: 68690,
    annualOpenings: 13000,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/education-training-and-library/library-technicians-and-assistants.htm",
    whatTheyDo: "Help patrons, process and organize materials, maintain records, and support programs under a librarian's direction.",
    workSetting: "Public, school, academic, and special libraries.",
    hours: "Full-time or part-time; evenings and weekends may be required.",
    skills: ["Customer service", "Catalog systems", "Organization", "Digital tools"],
    related: ["librarian", "archivist", "admin-assistant"],
  },
  archivist: {
    soc: "25-4011",
    payLow: 39970,
    payHigh: 110550,
    hourlyPayLow: 19.22,
    hourlyMedian: 31.03,
    hourlyPayHigh: 53.15,
    numJobs: 7970,
    annualOpenings: 1100,
    selfEmployedPercent: 10.4,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/education-training-and-library/curators-museum-technicians-and-conservators.htm",
    whatTheyDo: "Appraise, preserve, describe, and provide access to records and collections with long-term historical value.",
    workSetting: "Archives, museums, government agencies, libraries, and universities.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Records management", "Research", "Digital preservation", "Organization"],
    related: ["curator", "librarian", "historian"],
  },
  "pt-aide": {
    soc: "31-2022",
    payLow: 25360,
    payHigh: 47780,
    hourlyPayLow: 12.19,
    hourlyMedian: 16.94,
    hourlyPayHigh: 22.97,
    numJobs: 48150,
    annualOpenings: 6600,
    selfEmployedPercent: 0.7,
    workExperience: "None",
    onJobTraining: "Short-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/healthcare/physical-therapist-assistants-and-aides.htm",
    whatTheyDo: "Prepare treatment areas, clean and arrange equipment, help patients move, and handle clerical tasks for physical therapists.",
    workSetting: "Therapy clinics, hospitals, and nursing facilities; active and on your feet.",
    hours: "Full-time or part-time; some evenings and weekends.",
    skills: ["Physical stamina", "Customer service", "Safety", "Organization"],
    related: ["pta", "physical-therapist", "nursing-assistant"],
  },
  "health-information-tech": {
    soc: "29-9021",
    payLow: 39830,
    payHigh: 117420,
    hourlyPayLow: 19.15,
    hourlyMedian: 32.7,
    hourlyPayHigh: 56.45,
    numJobs: 38100,
    annualOpenings: 3200,
    selfEmployedPercent: 7.8,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/healthcare/health-information-technologists-and-medical-registrars.htm",
    whatTheyDo: "Design, manage, and analyze computerized health information and registries used for care, quality, and research.",
    workSetting: "Hospitals, clinics, insurance organizations, and offices; mostly computer-based.",
    hours: "Usually full-time with regular schedules.",
    skills: ["Health data", "Database systems", "Privacy rules", "Analysis"],
    related: ["medical-records-specialist", "database-admin", "health-services-manager"],
  },
  "medical-dosimetrist": {
    soc: "29-2036",
    payLow: 111670,
    payHigh: 185450,
    hourlyPayLow: 53.69,
    hourlyMedian: 70.9,
    hourlyPayHigh: 89.16,
    numJobs: 3410,
    annualOpenings: 200,
    selfEmployedPercent: 13.8,
    workExperience: "None",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/healthcare/medical-dosimetrists.htm",
    whatTheyDo: "Use imaging and treatment-planning software to calculate radiation dose and shape a safe cancer-treatment plan.",
    workSetting: "Hospitals and cancer treatment centers; computer-based work with a clinical team.",
    hours: "Usually full-time with regular schedules.",
    license: "Certification is widely expected; some states regulate the work.",
    skills: ["Radiation physics", "Treatment planning", "Anatomy", "Precision"],
    related: ["radiation-therapist", "radiologic-tech", "medical-scientist"],
  },
  pathologist: {
    soc: "29-1222",
    payLow: 92540,
    payHigh: 449970,
    hourlyPayLow: 44.49,
    hourlyMedian: 150.19,
    hourlyPayHigh: 216.33,
    numJobs: 11110,
    annualOpenings: 400,
    selfEmployedPercent: 4.5,
    workExperience: "None",
    onJobTraining: "Internship/residency",
    oohUrl: "https://www.bls.gov/ooh/healthcare/physicians-and-surgeons.htm",
    whatTheyDo: "Diagnose disease by examining tissue, cells, blood, and laboratory findings and advise other physicians on results.",
    workSetting: "Hospitals, medical laboratories, universities, and offices.",
    hours: "Usually full-time; hospital roles may include call.",
    license: "Requires a medical license after medical school, residency, and board certification.",
    skills: ["Diagnosis", "Microscopy", "Laboratory medicine", "Attention to detail"],
    related: ["clinical-lab-tech", "medical-scientist", "physician"],
  },
  actor: {
    soc: "27-2011",
    hourlyPayLow: 16.5,
    hourlyMedian: 29.05,
    hourlyPayHigh: 143.68,
    numJobs: 55000,
    annualOpenings: 6300,
    selfEmployedPercent: 27.9,
    workExperience: "None",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/entertainment-and-sports/actors.htm",
    whatTheyDo: "Interpret roles for stage, film, television, voice, commercials, and other live or recorded productions.",
    workSetting: "Theaters, studios, sets, rehearsal rooms, and changing locations.",
    hours: "Irregular and project-based; auditions and gaps between jobs are common.",
    skills: ["Performance", "Voice", "Memorization", "Collaboration"],
    related: ["producer-director", "camera-operator", "dancer"],
  },
  "musician-singer": {
    soc: "27-2042",
    hourlyPayLow: 20.35,
    hourlyMedian: 47.8,
    hourlyPayHigh: 132.56,
    numJobs: 36180,
    annualOpenings: 19400,
    selfEmployedPercent: 46.8,
    workExperience: "None",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/entertainment-and-sports/musicians-and-singers.htm",
    whatTheyDo: "Perform music live or in recordings as an instrumentalist, vocalist, ensemble member, or session artist.",
    workSetting: "Venues, studios, theaters, houses of worship, and touring locations.",
    hours: "Irregular and project-based; nights, weekends, travel, and unpaid practice are common.",
    skills: ["Musicianship", "Performance", "Practice discipline", "Collaboration"],
    related: ["music-director", "sound-engineer", "actor"],
  },
  dancer: {
    soc: "27-2031",
    hourlyPayLow: 14.88,
    hourlyMedian: 24.8,
    hourlyPayHigh: 52.3,
    numJobs: 8130,
    annualOpenings: 1800,
    selfEmployedPercent: 25.4,
    workExperience: "None",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/entertainment-and-sports/dancers-and-choreographers.htm",
    whatTheyDo: "Perform choreographed movement in stage, screen, touring, entertainment, or commercial productions.",
    workSetting: "Studios, theaters, sets, and touring venues.",
    hours: "Irregular and physically demanding; rehearsals, performances, and travel vary by project.",
    skills: ["Dance technique", "Physical stamina", "Musicality", "Collaboration"],
    related: ["choreographer", "actor", "fitness-trainer"],
  },
  choreographer: {
    soc: "27-2032",
    payLow: 34090,
    payHigh: 138630,
    hourlyPayLow: 16.39,
    hourlyMedian: 26.59,
    hourlyPayHigh: 66.65,
    numJobs: 2860,
    annualOpenings: 700,
    selfEmployedPercent: 24.3,
    workExperience: "5 years or more",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/entertainment-and-sports/dancers-and-choreographers.htm",
    whatTheyDo: "Create movement, teach it to performers, and shape how dance supports a production or performance.",
    workSetting: "Studios, theaters, sets, schools, and touring productions.",
    hours: "Project-based and irregular; rehearsals may run evenings and weekends.",
    skills: ["Choreography", "Teaching", "Musicality", "Leadership"],
    related: ["dancer", "producer-director", "music-director"],
  },
  "broadcast-technician": {
    soc: "27-4012",
    payLow: 31390,
    payHigh: 123670,
    hourlyPayLow: 15.09,
    hourlyMedian: 28.64,
    hourlyPayHigh: 59.46,
    numJobs: 21110,
    annualOpenings: 1800,
    selfEmployedPercent: 12.6,
    workExperience: "None",
    onJobTraining: "Short-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/media-and-communication/broadcast-and-sound-engineering-technicians.htm",
    whatTheyDo: "Operate and maintain equipment that captures, switches, monitors, and transmits audio and video for broadcasts and streams.",
    workSetting: "Studios, control rooms, production trucks, venues, and field locations.",
    hours: "Full-time or project-based; live events often mean nights and weekends.",
    skills: ["Signal routing", "Broadcast equipment", "Troubleshooting", "Timing"],
    related: ["av-technician", "camera-operator", "sound-engineer"],
  },
  "cnc-programmer": {
    soc: "51-9162",
    payLow: 47530,
    payHigh: 100320,
    hourlyPayLow: 22.85,
    hourlyMedian: 32.75,
    hourlyPayHigh: 48.23,
    numJobs: 28500,
    annualOpenings: 3100,
    workExperience: "None",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/production/metal-and-plastic-machine-workers.htm",
    whatTheyDo: "Translate part designs into CNC instructions, choose cutting steps, and test programs for accuracy and efficiency.",
    workSetting: "Machine shops and manufacturing plants.",
    hours: "Usually full-time; shift work may occur.",
    skills: ["CNC programming", "CAD/CAM", "Machining", "Precision"],
    related: ["machinist", "cnc-operator", "tool-die-maker"],
  },
  "substation-tech": {
    soc: "49-2095",
    payLow: 65730,
    payHigh: 129920,
    hourlyPayLow: 31.6,
    hourlyMedian: 49.53,
    hourlyPayHigh: 62.46,
    numJobs: 20720,
    annualOpenings: 2000,
    workExperience: "Less than 5 years",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/installation-maintenance-and-repair/electrical-and-electronics-installers-and-repairers.htm",
    whatTheyDo: "Install, test, calibrate, and repair relays, breakers, controls, and other electrical equipment in substations and powerhouses.",
    workSetting: "Utility substations, power plants, shops, and outdoor sites.",
    hours: "Full-time; on-call, overtime, and emergency work are common.",
    skills: ["Electrical testing", "Relay systems", "Troubleshooting", "Safety"],
    related: ["lineworker", "electrician", "power-dispatcher"],
  },
  "power-dispatcher": {
    soc: "51-8012",
    payLow: 72440,
    payHigh: 154270,
    hourlyPayLow: 34.83,
    hourlyMedian: 51.31,
    hourlyPayHigh: 74.17,
    numJobs: 8520,
    annualOpenings: 800,
    workExperience: "None",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/production/power-plant-operators-distributors-and-dispatchers.htm",
    whatTheyDo: "Control the flow of electricity across the grid and coordinate generators, substations, and field crews.",
    workSetting: "Secure utility control rooms with continuous monitoring.",
    hours: "Rotating shifts, including nights, weekends, and holidays.",
    license: "Operators complete extensive employer training and may need North American Electric Reliability Corporation certification.",
    skills: ["Grid operations", "Fast decisions", "Communication", "Concentration"],
    related: ["power-plant-operator", "substation-tech", "lineworker"],
  },
  "nuclear-technician": {
    soc: "19-4051",
    payLow: 73150,
    payHigh: 133600,
    hourlyPayLow: 35.17,
    hourlyMedian: 53,
    hourlyPayHigh: 64.23,
    numJobs: 6470,
    annualOpenings: 700,
    workExperience: "None",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/life-physical-and-social-science/nuclear-technicians.htm",
    whatTheyDo: "Monitor radiation, collect samples, maintain instruments, and support nuclear engineers, scientists, and plant operators.",
    workSetting: "Nuclear plants, laboratories, waste facilities, and field sites.",
    hours: "Usually full-time; plants may use rotating shifts.",
    skills: ["Radiation monitoring", "Instrumentation", "Safety procedures", "Data recording"],
    related: ["nuclear-engineer", "nuclear-reactor-operator", "occupational-safety-tech"],
  },
  "nuclear-reactor-operator": {
    soc: "51-8011",
    payLow: 98640,
    payHigh: 149310,
    hourlyPayLow: 47.42,
    hourlyMedian: 59.08,
    hourlyPayHigh: 71.78,
    numJobs: 5150,
    annualOpenings: 400,
    workExperience: "None",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/production/power-plant-operators-distributors-and-dispatchers.htm",
    whatTheyDo: "Operate reactor controls, monitor systems, perform tests, and respond to changes under strict federal procedures.",
    workSetting: "Nuclear power plant control rooms.",
    hours: "Rotating 24-hour shifts, including nights, weekends, and holidays.",
    license: "Requires extensive plant training and a U.S. Nuclear Regulatory Commission operator license.",
    skills: ["Reactor systems", "Procedure discipline", "Concentration", "Emergency response"],
    related: ["power-plant-operator", "nuclear-technician", "stationary-engineer"],
  },
  "ship-engineer": {
    soc: "53-5031",
    payLow: 57870,
    payHigh: 165490,
    hourlyPayLow: 27.82,
    hourlyMedian: 52.66,
    hourlyPayHigh: 79.56,
    numJobs: 8400,
    annualOpenings: 1100,
    workExperience: "Less than 5 years",
    onJobTraining: "None",
    oohUrl: "https://www.bls.gov/ooh/transportation-and-material-moving/water-transportation-occupations.htm",
    whatTheyDo: "Operate, maintain, and repair a ship's engines, generators, pumps, electrical systems, and other machinery.",
    workSetting: "Engine rooms and machinery spaces aboard cargo, passenger, research, or government vessels.",
    hours: "Extended time at sea and rotating watches; long periods away from home.",
    license: "Most roles require a Merchant Mariner Credential and Coast Guard engineering endorsement.",
    skills: ["Marine engines", "Mechanical repair", "Electrical systems", "Emergency response"],
    related: ["marine-engineer", "ship-captain", "diesel-tech"],
  },
  "rail-car-repairer": {
    soc: "49-3043",
    payLow: 46800,
    payHigh: 95100,
    hourlyPayLow: 22.5,
    hourlyMedian: 32.46,
    hourlyPayHigh: 45.72,
    numJobs: 21350,
    annualOpenings: 1500,
    selfEmployedPercent: 3.3,
    workExperience: "None",
    onJobTraining: "Long-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/installation-maintenance-and-repair/heavy-vehicle-and-mobile-equipment-service-technicians.htm",
    whatTheyDo: "Inspect and repair rail-car bodies, brakes, wheels, couplers, doors, and undercarriage systems.",
    workSetting: "Rail yards, maintenance shops, and outdoor tracks.",
    hours: "Full-time; nights, weekends, and outdoor work are common.",
    skills: ["Mechanical repair", "Welding", "Inspection", "Safety"],
    related: ["locomotive-engineer", "diesel-tech", "railroad-conductor"],
  },
  "commercial-fisher": {
    soc: "45-3031",
    numJobs: 21900,
    annualOpenings: 2800,
    selfEmployedPercent: 57.1,
    workExperience: "None",
    onJobTraining: "Moderate-term on-the-job training",
    oohUrl: "https://www.bls.gov/ooh/farming-fishing-and-forestry/fishers-and-related-fishing-workers.htm",
    whatTheyDo: "Catch fish and shellfish or track and harvest wild game, operating specialized gear and following environmental and safety rules.",
    workSetting: "Fishing vessels, waterfronts, forests, and other outdoor settings in changing and sometimes dangerous weather.",
    hours: "Seasonal and irregular; fishing trips may last days or weeks and shifts can be very long.",
    skills: ["Equipment handling", "Outdoor navigation", "Physical stamina", "Safety"],
    related: ["sailor", "ship-captain", "ship-engineer"],
  },
};
