// Career Explorer data (July 16, 2026 — the last parked preview ships; owner
// ask continues the Compare Colleges pattern). 100 careers from PUBLIC BLS
// data: median annual pay (May 2023 Occupational Employment & Wage
// Statistics), 2023–33 employment-projection growth, and the typical entry
// education from the Occupational Outlook Handbook. Honesty rules:
//   - Figures are vintage-tagged (CAREER_DATA_VINTAGE) — re-check each year
//     when BLS refreshes OES (spring) and projections (fall).
//   - earnWhileTraining is strict: TRUE only when a genuinely PAID pathway
//     exists (registered apprenticeship, paid academy, employer-funded
//     training) — not merely "no degree required."
//   - No rankings; sort by published facts only (house rule).

export type CareerField =
  | "trades"
  | "health"
  | "tech"
  | "business"
  | "education"
  | "public"
  | "engineering"
  | "service";

export const FIELD_LABELS: Record<CareerField, string> = {
  trades: "Skilled trades",
  health: "Healthcare",
  tech: "Tech",
  business: "Business & finance",
  education: "Education, law & social work",
  public: "Public service",
  engineering: "Engineering & science",
  service: "Everyday & transport",
};

export type EducationLevel =
  | "hs"
  | "certificate"
  | "associate"
  | "bachelor"
  | "master"
  | "doctoral";

export const EDUCATION_LABELS: Record<EducationLevel, string> = {
  hs: "High school / no degree",
  certificate: "Certificate program",
  associate: "Associate degree",
  bachelor: "Bachelor's degree",
  master: "Master's degree",
  doctoral: "Doctoral / professional degree",
};

export interface Career {
  id: string;
  title: string;
  field: CareerField;
  /** Median annual pay, dollars (BLS OES, May 2023). */
  medianPay: number;
  /** Typical entry-level education (BLS OOH). */
  education: EducationLevel;
  /** True only when a PAID training pathway exists. */
  earnWhileTraining: boolean;
  trainingNote: string;
  /** Projected employment change 2023–33, percent (BLS). */
  growth: number;
  note: string;
}

/** Shown publicly; re-verify when BLS refreshes. */
export const CAREER_DATA_VINTAGE =
  "May 2023 BLS pay data · 2023–33 BLS employment projections";

/** Growth band in plain words (BLS-style framing, ~4% = all-job average). */
export function growthLabel(g: number): string {
  if (g >= 9) return "Much faster than average";
  if (g >= 5) return "Faster than average";
  if (g >= 2) return "About average";
  if (g >= -1) return "Little change";
  return "Declining";
}

export const careers: Career[] = [
  {
    id: "electrician",
    title: "Electrician",
    field: "trades",
    medianPay: 61590,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4–5 year paid apprenticeship",
    growth: 11,
    note: "Union apprentices earn from day one — journeyman pay beats many bachelor's careers.",
  },
  {
    id: "plumber",
    title: "Plumber / Pipefitter",
    field: "trades",
    medianPay: 61550,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4–5 year paid apprenticeship",
    growth: 6,
    note: "Licensed trades can't be outsourced or automated — steady work everywhere.",
  },
  {
    id: "hvac-tech",
    title: "HVAC Technician",
    field: "trades",
    medianPay: 57300,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship or a short cert program",
    growth: 9,
    note: "Every building has climate control — heat waves keep demand climbing.",
  },
  {
    id: "carpenter",
    title: "Carpenter",
    field: "trades",
    medianPay: 56350,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "3–4 year paid apprenticeship",
    growth: 4,
    note: "The broadest trade — framing to finish work, and a path to contractor.",
  },
  {
    id: "welder",
    title: "Welder",
    field: "trades",
    medianPay: 48940,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert programs or paid on-the-job training",
    growth: 2,
    note: "Specialty welds — pipeline, underwater — multiply the base pay.",
  },
  {
    id: "machinist",
    title: "Machinist / CNC Operator",
    field: "trades",
    medianPay: 50840,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Apprenticeships and paid on-the-job training",
    growth: 0,
    note: "CNC skills modernized the shop floor — precision still pays.",
  },
  {
    id: "ironworker",
    title: "Ironworker",
    field: "trades",
    medianPay: 60930,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "3–4 year paid apprenticeship",
    growth: 4,
    note: "High steel, real pay, no degree — and union benefits.",
  },
  {
    id: "sheet-metal",
    title: "Sheet Metal Worker",
    field: "trades",
    medianPay: 58760,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4–5 year paid apprenticeship",
    growth: 2,
    note: "Fabrication plus install — HVAC ductwork keeps it steady.",
  },
  {
    id: "equipment-operator",
    title: "Construction Equipment Operator",
    field: "trades",
    medianPay: 55270,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship or on-the-job",
    growth: 4,
    note: "Cranes and excavators — certifications stack the pay up.",
  },
  {
    id: "elevator-tech",
    title: "Elevator Installer & Repairer",
    field: "trades",
    medianPay: 102420,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4-year paid apprenticeship",
    growth: 6,
    note: "The best-paid trade in America — six figures, no degree, union apprenticeship.",
  },
  {
    id: "lineworker",
    title: "Power Line Installer",
    field: "trades",
    medianPay: 85420,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship",
    growth: 8,
    note: "Storm work pays overtime on top of six-figure potential.",
  },
  {
    id: "auto-tech",
    title: "Auto Service Technician",
    field: "trades",
    medianPay: 47770,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert programs plus dealer on-the-job training",
    growth: 3,
    note: "EVs are rewriting the job — early movers on electric certs win.",
  },
  {
    id: "diesel-tech",
    title: "Diesel Mechanic",
    field: "trades",
    medianPay: 58970,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert programs plus paid on-the-job training",
    growth: 3,
    note: "Everything that moves freight needs one.",
  },
  {
    id: "aircraft-mechanic",
    title: "Aircraft Mechanic",
    field: "trades",
    medianPay: 75020,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "FAA-approved program (~18–24 months)",
    growth: 5,
    note: "Airlines are short thousands of mechanics — hiring bonuses are common.",
  },
  {
    id: "wind-turbine-tech",
    title: "Wind Turbine Technician",
    field: "trades",
    medianPay: 61770,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert program plus paid on-the-job training",
    growth: 60,
    note: "The fastest-growing job in America.",
  },
  {
    id: "solar-installer",
    title: "Solar Panel Installer",
    field: "trades",
    medianPay: 48800,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid on-the-job training",
    growth: 48,
    note: "Second-fastest-growing job — learn on the roof.",
  },
  {
    id: "rn",
    title: "Registered Nurse",
    field: "health",
    medianPay: 86070,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "BSN — or the cheaper ADN route to the same license",
    growth: 6,
    note: "The associate-degree route earns the same RN license for a fraction of the cost.",
  },
  {
    id: "lpn",
    title: "Licensed Practical Nurse",
    field: "health",
    medianPay: 59730,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "~1-year practical nursing program",
    growth: 3,
    note: "The fastest route into nursing — many bridge to RN later, employer-paid.",
  },
  {
    id: "nurse-practitioner",
    title: "Nurse Practitioner",
    field: "health",
    medianPay: 126260,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "RN first, then an MSN",
    growth: 46,
    note: "Among the fastest-growing jobs anywhere — near-physician scope in many states.",
  },
  {
    id: "physician-assistant",
    title: "Physician Assistant",
    field: "health",
    medianPay: 130020,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "~27-month PA program after prerequisites",
    growth: 28,
    note: "Physician-level work on a master's timeline.",
  },
  {
    id: "pharmacist",
    title: "Pharmacist",
    field: "health",
    medianPay: 136030,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "PharmD (6–8 years total)",
    growth: 5,
    note: "Six figures, but retail pharmacy is consolidating — hospital roles are the growth.",
  },
  {
    id: "pharmacy-tech",
    title: "Pharmacy Technician",
    field: "health",
    medianPay: 40300,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Many chains train and certify on the job",
    growth: 7,
    note: "A paid on-ramp into healthcare straight from high school.",
  },
  {
    id: "dental-hygienist",
    title: "Dental Hygienist",
    field: "health",
    medianPay: 87530,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 9,
    note: "One of the best associate-degree paychecks in the economy.",
  },
  {
    id: "dental-assistant",
    title: "Dental Assistant",
    field: "health",
    medianPay: 46540,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert program — or trained on the job in many states",
    growth: 8,
    note: "Chairside from month one; hygienist is the classic step up.",
  },
  {
    id: "medical-assistant",
    title: "Medical Assistant",
    field: "health",
    medianPay: 42000,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "~1-year certificate",
    growth: 15,
    note: "Every clinic needs them — a common first rung to nursing.",
  },
  {
    id: "emt",
    title: "EMT",
    field: "health",
    medianPay: 38930,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "A weeks-long course + state certification",
    growth: 6,
    note: "The cheapest fast entry into emergency medicine.",
  },
  {
    id: "paramedic",
    title: "Paramedic",
    field: "health",
    medianPay: 53180,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "1–2 year program after EMT",
    growth: 6,
    note: "The ambulance's clinician — fire departments pay more for the patch.",
  },
  {
    id: "radiologic-tech",
    title: "X-Ray / Radiologic Tech",
    field: "health",
    medianPay: 73410,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + certification",
    growth: 6,
    note: "Add CT or MRI credentials and the pay steps up each time.",
  },
  {
    id: "sonographer",
    title: "Ultrasound Technologist",
    field: "health",
    medianPay: 84470,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + certification",
    growth: 11,
    note: "Bachelor-level wages on a 2-year degree.",
  },
  {
    id: "respiratory-therapist",
    title: "Respiratory Therapist",
    field: "health",
    medianPay: 77960,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 13,
    note: "Hospitals can't run without them — a 2-year degree at nearly $80k.",
  },
  {
    id: "physical-therapist",
    title: "Physical Therapist",
    field: "health",
    medianPay: 99710,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "DPT (~7 years total)",
    growth: 14,
    note: "A doctorate — but one of the happiest-ranked jobs in healthcare.",
  },
  {
    id: "pta",
    title: "Physical Therapist Assistant",
    field: "health",
    medianPay: 64080,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 25,
    note: "A quarter more jobs this decade — on a 2-year degree.",
  },
  {
    id: "occupational-therapist",
    title: "Occupational Therapist",
    field: "health",
    medianPay: 96370,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's + license",
    growth: 11,
    note: "Helping people relearn daily life — schools, hospitals, home care.",
  },
  {
    id: "ota",
    title: "Occupational Therapy Assistant",
    field: "health",
    medianPay: 67010,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 22,
    note: "OT's 2-year sibling — same growth story as PTA.",
  },
  {
    id: "home-health-aide",
    title: "Home Health Aide",
    field: "health",
    medianPay: 33530,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Short paid training",
    growth: 21,
    note: "Millions of openings as America ages — the on-ramp to healthcare careers.",
  },
  {
    id: "phlebotomist",
    title: "Phlebotomist",
    field: "health",
    medianPay: 41810,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "A weeks-long certificate course",
    growth: 8,
    note: "One skill, every hospital — often the first healthcare paycheck.",
  },
  {
    id: "surgical-tech",
    title: "Surgical Technologist",
    field: "health",
    medianPay: 60610,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Certificate or associate program",
    growth: 6,
    note: "In the operating room without medical school.",
  },
  {
    id: "veterinarian",
    title: "Veterinarian",
    field: "health",
    medianPay: 119100,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "DVM (~8 years total)",
    growth: 19,
    note: "Vet school debt is real — but demand has never been higher.",
  },
  {
    id: "vet-tech",
    title: "Veterinary Technician",
    field: "health",
    medianPay: 43740,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + credential",
    growth: 19,
    note: "The animal-medicine job that needs 2 years, not 8.",
  },
  {
    id: "physician",
    title: "Physician (Family Medicine)",
    field: "health",
    medianPay: 240000,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "MD/DO + residency (11+ years)",
    growth: 4,
    note: "The long game — but residency itself is a paid job, and loan forgiveness is real in primary care.",
  },
  {
    id: "dentist",
    title: "Dentist",
    field: "health",
    medianPay: 170910,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "DDS/DMD (~8 years total)",
    growth: 5,
    note: "Own the practice and the ceiling disappears.",
  },
  {
    id: "optometrist",
    title: "Optometrist",
    field: "health",
    medianPay: 125590,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "OD (~8 years total)",
    growth: 9,
    note: "Healthcare's calmest doctorate — regular hours, six figures.",
  },
  {
    id: "software-developer",
    title: "Software Developer",
    field: "tech",
    medianPay: 132270,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "CS degree — or a proven portfolio",
    growth: 18,
    note: "Still the biggest paycheck per year of school in the economy; the junior market is tighter than the headlines say.",
  },
  {
    id: "web-developer",
    title: "Web Developer",
    field: "tech",
    medianPay: 84960,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree optional with a strong portfolio",
    growth: 8,
    note: "The most portfolio-forgiving door into tech.",
  },
  {
    id: "infosec-analyst",
    title: "Cybersecurity Analyst",
    field: "tech",
    medianPay: 120360,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus certs — Security+ opens doors",
    growth: 33,
    note: "A third more jobs this decade — certifications genuinely matter here.",
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    field: "tech",
    medianPay: 108020,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "A quantitative degree",
    growth: 36,
    note: "Statistics plus code — every industry is hiring for it.",
  },
  {
    id: "sysadmin",
    title: "Systems Administrator",
    field: "tech",
    medianPay: 95360,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree or equivalent certifications",
    growth: -3,
    note: "Cloud ate the server room — the one shrinking tech job on this list; cloud skills are the exit ramp.",
  },
  {
    id: "it-support",
    title: "IT Support Specialist",
    field: "tech",
    medianPay: 60810,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Certs (A+) — many start at the helpdesk and learn up",
    growth: 6,
    note: "Tech's classic no-degree entrance: helpdesk today, admin or security later.",
  },
  {
    id: "database-admin",
    title: "Database Administrator",
    field: "tech",
    medianPay: 101510,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus real SQL depth",
    growth: 8,
    note: "Data never stops growing — and someone has to keep it alive.",
  },
  {
    id: "accountant",
    title: "Accountant",
    field: "business",
    medianPay: 79880,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Accounting degree; the CPA multiplies pay",
    growth: 6,
    note: "The steadiest white-collar career there is — every organization needs one.",
  },
  {
    id: "bookkeeper",
    title: "Bookkeeper",
    field: "business",
    medianPay: 47440,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Certificate or trained on the job",
    growth: -5,
    note: "Software keeps shrinking this one — the accountant path is safer.",
  },
  {
    id: "financial-analyst",
    title: "Financial Analyst",
    field: "business",
    medianPay: 99890,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Finance or economics degree",
    growth: 9,
    note: "Corporate finance's front door — Excel fluency is the real credential.",
  },
  {
    id: "financial-advisor",
    title: "Personal Financial Advisor",
    field: "business",
    medianPay: 99580,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus licenses (Series 65)",
    growth: 17,
    note: "Helping people manage money pays well — and the field needs advisors who look like their clients.",
  },
  {
    id: "actuary",
    title: "Actuary",
    field: "business",
    medianPay: 120000,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Math degree + an exam ladder — employers pay per exam passed",
    growth: 22,
    note: "Exams instead of grad school: six figures with no debt beyond a bachelor's.",
  },
  {
    id: "hr-specialist",
    title: "HR Specialist",
    field: "business",
    medianPay: 67650,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "A degree — many majors accepted",
    growth: 6,
    note: "Every company above 50 people hires one.",
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    field: "business",
    medianPay: 156580,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus years of campaign experience",
    growth: 8,
    note: "The highest-paid job on this list that starts from any major.",
  },
  {
    id: "management-analyst",
    title: "Management Consultant",
    field: "business",
    medianPay: 99410,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree; an MBA is common later",
    growth: 11,
    note: "The generalist's six-figure path — firms recruit straight from campus.",
  },
  {
    id: "insurance-agent",
    title: "Insurance Agent",
    field: "business",
    medianPay: 59080,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "State license — companies train new agents",
    growth: 6,
    note: "Commission work with a real earn-while-you-learn setup.",
  },
  {
    id: "real-estate-agent",
    title: "Real Estate Agent",
    field: "business",
    medianPay: 54300,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "State license course (weeks)",
    growth: 2,
    note: "Commission-only at the start — build a cash buffer before you leap.",
  },
  {
    id: "paralegal",
    title: "Paralegal",
    field: "business",
    medianPay: 60970,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree or certificate",
    growth: 1,
    note: "Law-firm work without law school — and a proving ground before committing to a JD.",
  },
  {
    id: "admin-assistant",
    title: "Administrative Assistant",
    field: "business",
    medianPay: 44280,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Learned on the job",
    growth: -8,
    note: "Shrinking fast as software absorbs the work — treat it as a stepping stone.",
  },
  {
    id: "customer-service",
    title: "Customer Service Representative",
    field: "business",
    medianPay: 39680,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Trained on the job",
    growth: -5,
    note: "Everywhere, but automating — the skills transfer to better-paid ops roles.",
  },
  {
    id: "logistician",
    title: "Logistician",
    field: "business",
    medianPay: 79400,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree; military experience counts double",
    growth: 19,
    note: "Supply chains never sleep — 19% growth this decade.",
  },
  {
    id: "lawyer",
    title: "Lawyer",
    field: "education",
    medianPay: 145760,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "JD + bar exam (7 years total)",
    growth: 5,
    note: "The median hides a split: BigLaw pays triple what most public-interest law does.",
  },
  {
    id: "teacher-elementary",
    title: "Elementary School Teacher",
    field: "education",
    medianPay: 63680,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree + state credential",
    growth: -1,
    note: "Flat nationally but shortage-driven locally — loan forgiveness programs apply.",
  },
  {
    id: "teacher-hs",
    title: "High School Teacher",
    field: "education",
    medianPay: 65220,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree + state credential",
    growth: -1,
    note: "Math and science credentials jump the hiring line.",
  },
  {
    id: "teacher-assistant",
    title: "Teacher Assistant",
    field: "education",
    medianPay: 35240,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Hired and trained by districts",
    growth: 0,
    note: "Many districts now pay assistants' way through teaching credentials.",
  },
  {
    id: "school-counselor",
    title: "School Counselor",
    field: "education",
    medianPay: 61710,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's in counseling",
    growth: 4,
    note: "The job this website wishes every school had more of.",
  },
  {
    id: "social-worker",
    title: "Social Worker",
    field: "education",
    medianPay: 58380,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "BSW; clinical roles need the MSW",
    growth: 7,
    note: "Heavy, meaningful work — public-service loan forgiveness fits it perfectly.",
  },
  {
    id: "childcare-worker",
    title: "Childcare Worker",
    field: "education",
    medianPay: 30370,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Trained on the job",
    growth: -2,
    note: "Underpaid for what it is — often a step toward early-childhood education credentials.",
  },
  {
    id: "librarian",
    title: "Librarian",
    field: "education",
    medianPay: 64370,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's (MLIS)",
    growth: 3,
    note: "Quietly competitive — school and public systems hire on the MLIS.",
  },
  {
    id: "interpreter",
    title: "Interpreter / Translator",
    field: "education",
    medianPay: 57090,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Fluency + certification; a degree helps",
    growth: 2,
    note: "Bilingual first-gen students start with the core skill already earned.",
  },
  {
    id: "police-officer",
    title: "Police Officer",
    field: "public",
    medianPay: 74910,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid police academy",
    growth: 4,
    note: "Pension math matters here: 20-25 years to retirement with benefits.",
  },
  {
    id: "firefighter",
    title: "Firefighter",
    field: "public",
    medianPay: 57120,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Paid fire academy + EMT certification",
    growth: 4,
    note: "Fiercely competitive to enter — EMT and paramedic certs are the edge.",
  },
  {
    id: "correctional-officer",
    title: "Correctional Officer",
    field: "public",
    medianPay: 53300,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid academy",
    growth: -7,
    note: "Declining as incarceration falls — but hiring still runs constant on turnover.",
  },
  {
    id: "air-traffic-controller",
    title: "Air Traffic Controller",
    field: "public",
    medianPay: 137380,
    education: "associate",
    earnWhileTraining: true,
    trainingNote: "The FAA pays you to train at its academy — no degree required",
    growth: 3,
    note: "Six figures in your twenties with no bachelor's. Hard rule: apply before you turn 31.",
  },
  {
    id: "postal-worker",
    title: "Postal Service Worker",
    field: "public",
    medianPay: 56510,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Hired and trained by USPS",
    growth: -6,
    note: "Federal benefits and union protection — but a shrinking headcount.",
  },
  {
    id: "civil-engineer",
    title: "Civil Engineer",
    field: "engineering",
    medianPay: 95890,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree; PE license later",
    growth: 6,
    note: "Infrastructure money flows for a decade — bridges don't build themselves.",
  },
  {
    id: "mechanical-engineer",
    title: "Mechanical Engineer",
    field: "engineering",
    medianPay: 99510,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree",
    growth: 11,
    note: "The most versatile engineering degree — every industry buys it.",
  },
  {
    id: "electrical-engineer",
    title: "Electrical Engineer",
    field: "engineering",
    medianPay: 106950,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree",
    growth: 9,
    note: "Grid modernization and chips — both hiring hard.",
  },
  {
    id: "industrial-engineer",
    title: "Industrial Engineer",
    field: "engineering",
    medianPay: 99380,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree",
    growth: 12,
    note: "The efficiency engineers — manufacturing's comeback is their moment.",
  },
  {
    id: "architect",
    title: "Architect",
    field: "engineering",
    medianPay: 93310,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "5-year B.Arch or M.Arch + license",
    growth: 8,
    note: "Long licensure road; the pay arrives after it.",
  },
  {
    id: "construction-manager",
    title: "Construction Manager",
    field: "engineering",
    medianPay: 104900,
    education: "bachelor",
    earnWhileTraining: true,
    trainingNote: "Degree — or rise from the trades",
    growth: 9,
    note: "Plenty climb from the tools to the trailer — field experience counts as much as the degree.",
  },
  {
    id: "environmental-scientist",
    title: "Environmental Scientist",
    field: "engineering",
    medianPay: 78980,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "A science degree",
    growth: 7,
    note: "Climate compliance work is growing in every state.",
  },
  {
    id: "chemist",
    title: "Chemist",
    field: "engineering",
    medianPay: 84680,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Chemistry degree",
    growth: 8,
    note: "Pharma and materials pay best; a master's moves you up fast.",
  },
  {
    id: "clinical-lab-tech",
    title: "Clinical Lab Technologist",
    field: "engineering",
    medianPay: 60780,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree + certification",
    growth: 5,
    note: "Every diagnosis runs through a lab — steady, hospital-based science.",
  },
  {
    id: "statistician",
    title: "Statistician",
    field: "engineering",
    medianPay: 104110,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's in statistics",
    growth: 12,
    note: "The quieter, steadier sibling of data science.",
  },
  {
    id: "urban-planner",
    title: "Urban Planner",
    field: "engineering",
    medianPay: 81800,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's in planning",
    growth: 4,
    note: "Housing policy is the story of the decade — planners sit in the middle of it.",
  },
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    field: "service",
    medianPay: 58910,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree or portfolio",
    growth: 2,
    note: "AI pressure is real — motion, brand systems, and UX adjacency are the durable end.",
  },
  {
    id: "technical-writer",
    title: "Technical Writer",
    field: "service",
    medianPay: 80050,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Writing skill + a technical domain",
    growth: 4,
    note: "The best-paid pure-writing job in the economy.",
  },
  {
    id: "chef",
    title: "Chef / Head Cook",
    field: "service",
    medianPay: 58920,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Kitchens promote from within — culinary school optional",
    growth: 8,
    note: "The kitchen ladder is real: line to sous to head, paid the whole way.",
  },
  {
    id: "cook",
    title: "Cook",
    field: "service",
    medianPay: 35780,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Learned on the line",
    growth: 6,
    note: "Always hiring, everywhere — the first rung of the kitchen ladder.",
  },
  {
    id: "barber-cosmetologist",
    title: "Barber / Cosmetologist",
    field: "service",
    medianPay: 34970,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "State license program",
    growth: 7,
    note: "Chair rental is small-business ownership with tiny startup costs.",
  },
  {
    id: "massage-therapist",
    title: "Massage Therapist",
    field: "service",
    medianPay: 55310,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "License program (~600 hours)",
    growth: 18,
    note: "Healthcare-adjacent growth without healthcare-length training.",
  },
  {
    id: "truck-driver",
    title: "Truck Driver (Long-Haul)",
    field: "service",
    medianPay: 54320,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Company-paid CDL training is common",
    growth: 4,
    note: "Real money fast with no degree — the lifestyle is the true cost.",
  },
  {
    id: "delivery-driver",
    title: "Delivery Driver",
    field: "service",
    medianPay: 42470,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Hired and trained",
    growth: 9,
    note: "E-commerce keeps this one growing.",
  },
  {
    id: "airline-pilot",
    title: "Airline Pilot",
    field: "service",
    medianPay: 219140,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Ratings ladder — airlines now fund cadet programs",
    growth: 5,
    note: "The shortage rewrote the path: cadet programs pay for your ratings.",
  },
  {
    id: "commercial-pilot",
    title: "Commercial Pilot",
    field: "service",
    medianPay: 113080,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Flight ratings — no degree required",
    growth: 5,
    note: "Charter, cargo, medevac — six figures without the airline seniority ladder.",
  },
  {
    id: "flight-attendant",
    title: "Flight Attendant",
    field: "service",
    medianPay: 68370,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Airline-paid training academy",
    growth: 10,
    note: "Free training, flight benefits, and union pay scales — no degree.",
  },
  {
    id: "dispatcher",
    title: "911 Dispatcher",
    field: "service",
    medianPay: 46900,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Hired and trained",
    growth: 3,
    note: "The first first-responder — steady public-sector work in every county.",
  },
];
