// Career Explorer data (July 16, 2026 — the last parked preview ships; owner
// ask continues the Compare Colleges pattern). Careers from PUBLIC BLS data:
// median annual pay, 2024–34 employment-projection growth, and the typical
// entry education from the Occupational Outlook Handbook. The original 100
// carry May 2025 OEWS pay (refreshed July 17 2026 from bls.gov oesm25nat, all
// SOC-matched, median change +2.5%). WAVE 1 (July 18, 2026): +50 high-
// employment / career-ladder occupations toward comprehensive coverage, their
// pay + growth + openings + entry education taken from the BLS Employment
// Projections table (2024 wage · 2024–34 projections); their May 2025 pay
// range (10th–90th) backfills from the OEWS API as the daily quota allows.
// Honesty rules:
//   - Figures are vintage-tagged (CAREER_DATA_VINTAGE) — re-check each year
//     when BLS refreshes OES (spring) and projections (fall).
//   - earnWhileTraining is strict: TRUE only when a genuinely PAID pathway
//     exists (registered apprenticeship, paid academy, employer-funded
//     training) — not merely "no degree required."
//   - No rankings; sort by published facts only (house rule).

export type CareerField =
  | "trades"
  | "health"
  | "tech"
  | "business"
  | "education"
  | "public"
  | "engineering"
  | "service";

export const FIELD_LABELS: Record<CareerField, string> = {
  trades: "Skilled trades",
  health: "Healthcare",
  tech: "Tech",
  business: "Business & finance",
  education: "Education, law & social work",
  public: "Public service",
  engineering: "Engineering & science",
  service: "Everyday & transport",
};

export type EducationLevel =
  | "none"
  | "some-college"
  | "hs"
  | "certificate"
  | "associate"
  | "bachelor"
  | "master"
  | "doctoral";

export const EDUCATION_LABELS: Record<EducationLevel, string> = {
  none: "No formal credential",
  "some-college": "Some college, no degree",
  hs: "High school / no degree",
  certificate: "Certificate program",
  associate: "Associate degree",
  bachelor: "Bachelor's degree",
  master: "Master's degree",
  doctoral: "Doctoral / professional degree",
};

export interface Career {
  id: string;
  title: string;
  field: CareerField;
  /** Median annual pay, dollars (BLS OEWS, May 2025). */
  medianPay: number;
  /** Typical entry-level education (BLS OOH). */
  education: EducationLevel;
  /** True only when a PAID training pathway exists. */
  earnWhileTraining: boolean;
  trainingNote: string;
  /** Projected employment change 2024–34, percent (BLS). */
  growth: number;
  note: string;
}

/** Shown publicly; re-verify when BLS refreshes. */
export const CAREER_DATA_VINTAGE =
  "May 2024–25 BLS wage data · 2024–34 BLS employment projections";

/** Growth band in plain words (BLS-style framing, ~4% = all-job average). */
export function growthLabel(g: number): string {
  if (g >= 9) return "Much faster than average";
  if (g >= 5) return "Faster than average";
  if (g >= 2) return "About average";
  if (g >= -1) return "Little change";
  return "Declining";
}

export const careers: Career[] = [
  {
    id: "electrician",
    title: "Electrician",
    field: "trades",
    medianPay: 63190,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4–5 year paid apprenticeship",
    growth: 9,
    note: "Union apprentices earn from day one — journeyman pay beats many bachelor's careers.",
  },
  {
    id: "plumber",
    title: "Plumber / Pipefitter",
    field: "trades",
    medianPay: 63800,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4–5 year paid apprenticeship",
    growth: 4,
    note: "Licensed trades can't be outsourced or automated — steady work everywhere.",
  },
  {
    id: "hvac-tech",
    title: "HVAC Technician",
    field: "trades",
    medianPay: 61010,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship or a short cert program",
    growth: 8,
    note: "Every building has climate control — heat waves keep demand climbing.",
  },
  {
    id: "carpenter",
    title: "Carpenter",
    field: "trades",
    medianPay: 60580,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "3–4 year paid apprenticeship",
    growth: 4,
    note: "The broadest trade — framing to finish work, and a path to contractor.",
  },
  {
    id: "welder",
    title: "Welder",
    field: "trades",
    medianPay: 53750,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Cert programs or paid on-the-job training",
    growth: 2,
    note: "Specialty welds — pipeline, underwater — multiply the base pay.",
  },
  {
    id: "machinist",
    title: "Machinist / CNC Operator",
    field: "trades",
    medianPay: 58750,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Apprenticeships and paid on-the-job training",
    growth: 0,
    note: "CNC skills modernized the shop floor — precision still pays.",
  },
  {
    id: "ironworker",
    title: "Ironworker",
    field: "trades",
    medianPay: 62780,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "3–4 year paid apprenticeship",
    growth: 4,
    note: "High steel, real pay, no degree — and union benefits.",
  },
  {
    id: "sheet-metal",
    title: "Sheet Metal Worker",
    field: "trades",
    medianPay: 61800,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4–5 year paid apprenticeship",
    growth: 2,
    note: "Fabrication plus install — HVAC ductwork keeps it steady.",
  },
  {
    id: "equipment-operator",
    title: "Construction Equipment Operator",
    field: "trades",
    medianPay: 59850,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship or on-the-job",
    growth: 4,
    note: "Cranes and excavators — certifications stack the pay up.",
  },
  {
    id: "elevator-tech",
    title: "Elevator Installer & Repairer",
    field: "trades",
    medianPay: 109910,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "4-year paid apprenticeship",
    growth: 5,
    note: "The best-paid trade in America — six figures, no degree, union apprenticeship.",
  },
  {
    id: "lineworker",
    title: "Power Line Installer",
    field: "trades",
    medianPay: 95320,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship",
    growth: 7,
    note: "Storm work pays overtime on top of six-figure potential.",
  },
  {
    id: "auto-tech",
    title: "Auto Service Technician",
    field: "trades",
    medianPay: 50620,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert programs plus dealer on-the-job training",
    growth: 4,
    note: "EVs are rewriting the job — early movers on electric certs win.",
  },
  {
    id: "diesel-tech",
    title: "Diesel Mechanic",
    field: "trades",
    medianPay: 61770,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Cert programs plus paid on-the-job training",
    growth: 2,
    note: "Everything that moves freight needs one.",
  },
  {
    id: "aircraft-mechanic",
    title: "Aircraft Mechanic",
    field: "trades",
    medianPay: 79870,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "FAA-approved program (~18–24 months)",
    growth: 4,
    note: "Airlines are short thousands of mechanics — hiring bonuses are common.",
  },
  {
    id: "wind-turbine-tech",
    title: "Wind Turbine Technician",
    field: "trades",
    medianPay: 64120,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert program plus paid on-the-job training",
    growth: 50,
    note: "The fastest-growing job in America.",
  },
  {
    id: "solar-installer",
    title: "Solar Panel Installer",
    field: "trades",
    medianPay: 53140,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid on-the-job training",
    growth: 42,
    note: "Second-fastest-growing job — learn on the roof.",
  },
  {
    id: "rn",
    title: "Registered Nurse",
    field: "health",
    medianPay: 97550,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "BSN — or the cheaper ADN route to the same license",
    growth: 5,
    note: "The associate-degree route earns the same RN license for a fraction of the cost.",
  },
  {
    id: "lpn",
    title: "Licensed Practical Nurse",
    field: "health",
    medianPay: 64400,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "~1-year practical nursing program",
    growth: 3,
    note: "The fastest route into nursing — many bridge to RN later, employer-paid.",
  },
  {
    id: "nurse-practitioner",
    title: "Nurse Practitioner",
    field: "health",
    medianPay: 132300,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "RN first, then an MSN",
    growth: 40,
    note: "Among the fastest-growing jobs anywhere — near-physician scope in many states.",
  },
  {
    id: "physician-assistant",
    title: "Physician Assistant",
    field: "health",
    medianPay: 135880,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "~27-month PA program after prerequisites",
    growth: 20,
    note: "Physician-level work on a master's timeline.",
  },
  {
    id: "pharmacist",
    title: "Pharmacist",
    field: "health",
    medianPay: 140910,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "PharmD (6–8 years total)",
    growth: 5,
    note: "Six figures, but retail pharmacy is consolidating — hospital roles are the growth.",
  },
  {
    id: "pharmacy-tech",
    title: "Pharmacy Technician",
    field: "health",
    medianPay: 45750,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Many chains train and certify on the job",
    growth: 6,
    note: "A paid on-ramp into healthcare straight from high school.",
  },
  {
    id: "dental-hygienist",
    title: "Dental Hygienist",
    field: "health",
    medianPay: 98100,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 7,
    note: "One of the best associate-degree paychecks in the economy.",
  },
  {
    id: "dental-assistant",
    title: "Dental Assistant",
    field: "health",
    medianPay: 48070,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Cert program — or trained on the job in many states",
    growth: 6,
    note: "Chairside from month one; hygienist is the classic step up.",
  },
  {
    id: "medical-assistant",
    title: "Medical Assistant",
    field: "health",
    medianPay: 45690,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "~1-year certificate",
    growth: 12,
    note: "Every clinic needs them — a common first rung to nursing.",
  },
  {
    id: "emt",
    title: "EMT",
    field: "health",
    medianPay: 44470,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "A weeks-long course + state certification",
    growth: 5,
    note: "The cheapest fast entry into emergency medicine.",
  },
  {
    id: "paramedic",
    title: "Paramedic",
    field: "health",
    medianPay: 60600,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "1–2 year program after EMT",
    growth: 5,
    note: "The ambulance's clinician — fire departments pay more for the patch.",
  },
  {
    id: "radiologic-tech",
    title: "X-Ray / Radiologic Tech",
    field: "health",
    medianPay: 80110,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + certification",
    growth: 4,
    note: "Add CT or MRI credentials and the pay steps up each time.",
  },
  {
    id: "sonographer",
    title: "Ultrasound Technologist",
    field: "health",
    medianPay: 96590,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + certification",
    growth: 13,
    note: "Bachelor-level wages on a 2-year degree.",
  },
  {
    id: "respiratory-therapist",
    title: "Respiratory Therapist",
    field: "health",
    medianPay: 82280,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 12,
    note: "Hospitals can't run without them — a 2-year degree at nearly $80k.",
  },
  {
    id: "physical-therapist",
    title: "Physical Therapist",
    field: "health",
    medianPay: 102760,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "DPT (~7 years total)",
    growth: 11,
    note: "A doctorate — but one of the happiest-ranked jobs in healthcare.",
  },
  {
    id: "pta",
    title: "Physical Therapist Assistant",
    field: "health",
    medianPay: 68380,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 22,
    note: "Over a fifth more jobs this decade — on a 2-year degree.",
  },
  {
    id: "occupational-therapist",
    title: "Occupational Therapist",
    field: "health",
    medianPay: 100330,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's + license",
    growth: 14,
    note: "Helping people relearn daily life — schools, hospitals, home care.",
  },
  {
    id: "ota",
    title: "Occupational Therapy Assistant",
    field: "health",
    medianPay: 72300,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + license",
    growth: 19,
    note: "OT's 2-year sibling — same growth story as PTA.",
  },
  {
    id: "home-health-aide",
    title: "Home Health Aide",
    field: "health",
    medianPay: 35800,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Short paid training",
    growth: 17,
    note: "Millions of openings as America ages — the on-ramp to healthcare careers.",
  },
  {
    id: "phlebotomist",
    title: "Phlebotomist",
    field: "health",
    medianPay: 45230,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "A weeks-long certificate course",
    growth: 6,
    note: "One skill, every hospital — often the first healthcare paycheck.",
  },
  {
    id: "surgical-tech",
    title: "Surgical Technologist",
    field: "health",
    medianPay: 64650,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Certificate or associate program",
    growth: 5,
    note: "In the operating room without medical school.",
  },
  {
    id: "veterinarian",
    title: "Veterinarian",
    field: "health",
    medianPay: 130100,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "DVM (~8 years total)",
    growth: 10,
    note: "Vet school debt is real — but demand has never been higher.",
  },
  {
    id: "vet-tech",
    title: "Veterinary Technician",
    field: "health",
    medianPay: 47380,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + credential",
    growth: 9,
    note: "The animal-medicine job that needs 2 years, not 8.",
  },
  {
    id: "physician",
    title: "Physician (Family Medicine)",
    field: "health",
    medianPay: 244180,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "MD/DO + residency (11+ years)",
    growth: 3,
    note: "The long game — but residency itself is a paid job, and loan forgiveness is real in primary care.",
  },
  {
    id: "dentist",
    title: "Dentist",
    field: "health",
    medianPay: 170950,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "DDS/DMD (~8 years total)",
    growth: 4,
    note: "Own the practice and the ceiling disappears.",
  },
  {
    id: "optometrist",
    title: "Optometrist",
    field: "health",
    medianPay: 136570,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "OD (~8 years total)",
    growth: 8,
    note: "Healthcare's calmest doctorate — regular hours, six figures.",
  },
  {
    id: "software-developer",
    title: "Software Developer",
    field: "tech",
    medianPay: 135980,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "CS degree — or a proven portfolio",
    growth: 16,
    note: "Still the biggest paycheck per year of school in the economy; the junior market is tighter than the headlines say.",
  },
  {
    id: "web-developer",
    title: "Web Developer",
    field: "tech",
    medianPay: 92650,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree optional with a strong portfolio",
    growth: 8,
    note: "The most portfolio-forgiving door into tech.",
  },
  {
    id: "infosec-analyst",
    title: "Cybersecurity Analyst",
    field: "tech",
    medianPay: 129180,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus certs — Security+ opens doors",
    growth: 29,
    note: "Nearly a third more jobs this decade — certifications genuinely matter here.",
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    field: "tech",
    medianPay: 120230,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "A quantitative degree",
    growth: 34,
    note: "Statistics plus code — every industry is hiring for it.",
  },
  {
    id: "sysadmin",
    title: "Systems Administrator",
    field: "tech",
    medianPay: 99130,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree or equivalent certifications",
    growth: -4,
    note: "Cloud ate the server room — the one shrinking tech job on this list; cloud skills are the exit ramp.",
  },
  {
    id: "it-support",
    title: "IT Support Specialist",
    field: "tech",
    medianPay: 61860,
    education: "some-college",
    earnWhileTraining: true,
    trainingNote: "Certs (A+) — many start at the helpdesk and learn up",
    growth: -3,
    note: "Tech's classic no-degree entrance: helpdesk today, admin or security later.",
  },
  {
    id: "database-admin",
    title: "Database Administrator",
    field: "tech",
    medianPay: 104620,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus real SQL depth",
    growth: -1,
    note: "Data never stops growing — and someone has to keep it alive.",
  },
  {
    id: "accountant",
    title: "Accountant",
    field: "business",
    medianPay: 83680,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Accounting degree; the CPA multiplies pay",
    growth: 5,
    note: "The steadiest white-collar career there is — every organization needs one.",
  },
  {
    id: "bookkeeper",
    title: "Bookkeeper",
    field: "business",
    medianPay: 50670,
    education: "some-college",
    earnWhileTraining: true,
    trainingNote: "Certificate or trained on the job",
    growth: -6,
    note: "Software keeps shrinking this one — the accountant path is safer.",
  },
  {
    id: "financial-analyst",
    title: "Financial Analyst",
    field: "business",
    medianPay: 102740,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Finance or economics degree",
    growth: 6,
    note: "Corporate finance's front door — Excel fluency is the real credential.",
  },
  {
    id: "financial-advisor",
    title: "Personal Financial Advisor",
    field: "business",
    medianPay: 105070,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus licenses (Series 65)",
    growth: 10,
    note: "Helping people manage money pays well — and the field needs advisors who look like their clients.",
  },
  {
    id: "actuary",
    title: "Actuary",
    field: "business",
    medianPay: 130000,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Math degree + an exam ladder — employers pay per exam passed",
    growth: 22,
    note: "Exams instead of grad school: six figures with no debt beyond a bachelor's.",
  },
  {
    id: "hr-specialist",
    title: "HR Specialist",
    field: "business",
    medianPay: 75940,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "A degree — many majors accepted",
    growth: 6,
    note: "Every company above 50 people hires one.",
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    field: "business",
    medianPay: 166790,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree plus years of campaign experience",
    growth: 6,
    note: "The highest-paid job on this list that starts from any major.",
  },
  {
    id: "management-analyst",
    title: "Management Consultant",
    field: "business",
    medianPay: 101860,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree; an MBA is common later",
    growth: 9,
    note: "The generalist's six-figure path — firms recruit straight from campus.",
  },
  {
    id: "insurance-agent",
    title: "Insurance Agent",
    field: "business",
    medianPay: 62280,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "State license — companies train new agents",
    growth: 4,
    note: "Commission work with a real earn-while-you-learn setup.",
  },
  {
    id: "real-estate-agent",
    title: "Real Estate Agent",
    field: "business",
    medianPay: 52830,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "State license course (weeks)",
    growth: 3,
    note: "Commission-only at the start — build a cash buffer before you leap.",
  },
  {
    id: "paralegal",
    title: "Paralegal",
    field: "business",
    medianPay: 62890,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree or certificate",
    growth: 0,
    note: "Law-firm work without law school — and a proving ground before committing to a JD.",
  },
  {
    id: "admin-assistant",
    title: "Administrative Assistant",
    field: "business",
    medianPay: 47540,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Learned on the job",
    growth: -2,
    note: "Slowly shrinking as software absorbs the work — treat it as a stepping stone.",
  },
  {
    id: "customer-service",
    title: "Customer Service Representative",
    field: "business",
    medianPay: 44770,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Trained on the job",
    growth: -5,
    note: "Everywhere, but automating — the skills transfer to better-paid ops roles.",
  },
  {
    id: "logistician",
    title: "Logistician",
    field: "business",
    medianPay: 82320,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree; military experience counts double",
    growth: 17,
    note: "Supply chains never sleep — 17% growth this decade.",
  },
  {
    id: "lawyer",
    title: "Lawyer",
    field: "education",
    medianPay: 159670,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "JD + bar exam (7 years total)",
    growth: 4,
    note: "The median hides a split: BigLaw pays triple what most public-interest law does.",
  },
  {
    id: "teacher-elementary",
    title: "Elementary School Teacher",
    field: "education",
    medianPay: 63970,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree + state credential",
    growth: -2,
    note: "Flat nationally but shortage-driven locally — loan forgiveness programs apply.",
  },
  {
    id: "teacher-hs",
    title: "High School Teacher",
    field: "education",
    medianPay: 72040,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree + state credential",
    growth: -2,
    note: "Math and science credentials jump the hiring line.",
  },
  {
    id: "teacher-assistant",
    title: "Teacher Assistant",
    field: "education",
    medianPay: 36780,
    education: "some-college",
    earnWhileTraining: true,
    trainingNote: "Hired and trained by districts",
    growth: -1,
    note: "Many districts now pay assistants' way through teaching credentials.",
  },
  {
    id: "school-counselor",
    title: "School Counselor",
    field: "education",
    medianPay: 64330,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's in counseling",
    growth: 4,
    note: "The job this website wishes every school had more of.",
  },
  {
    id: "social-worker",
    title: "Social Worker",
    field: "education",
    medianPay: 59550,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "BSW; clinical roles need the MSW",
    growth: 6,
    note: "Heavy, meaningful work — public-service loan forgiveness fits it perfectly.",
  },
  {
    id: "childcare-worker",
    title: "Childcare Worker",
    field: "education",
    medianPay: 34980,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Trained on the job",
    growth: -3,
    note: "Underpaid for what it is — often a step toward early-childhood education credentials.",
  },
  {
    id: "librarian",
    title: "Librarian",
    field: "education",
    medianPay: 68270,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's (MLIS)",
    growth: 2,
    note: "Quietly competitive — school and public systems hire on the MLIS.",
  },
  {
    id: "interpreter",
    title: "Interpreter / Translator",
    field: "education",
    medianPay: 60170,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Fluency + certification; a degree helps",
    growth: 2,
    note: "Bilingual first-gen students start with the core skill already earned.",
  },
  {
    id: "police-officer",
    title: "Police Officer",
    field: "public",
    medianPay: 76210,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid police academy",
    growth: 3,
    note: "Pension math matters here: 20-25 years to retirement with benefits.",
  },
  {
    id: "firefighter",
    title: "Firefighter",
    field: "public",
    medianPay: 59280,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Paid fire academy + EMT certification",
    growth: 3,
    note: "Fiercely competitive to enter — EMT and paramedic certs are the edge.",
  },
  {
    id: "correctional-officer",
    title: "Correctional Officer",
    field: "public",
    medianPay: 58940,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid academy",
    growth: -7,
    note: "Declining as incarceration falls — but hiring still runs constant on turnover.",
  },
  {
    id: "air-traffic-controller",
    title: "Air Traffic Controller",
    field: "public",
    medianPay: 148080,
    education: "associate",
    earnWhileTraining: true,
    trainingNote: "The FAA pays you to train at its academy — no degree required",
    growth: 1,
    note: "Six figures in your twenties with no bachelor's. Hard rule: apply before you turn 31.",
  },
  {
    id: "postal-worker",
    title: "Postal Service Worker",
    field: "public",
    medianPay: 58470,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "Hired and trained by USPS",
    growth: -5,
    note: "Federal benefits and union protection — but a shrinking headcount.",
  },
  {
    id: "civil-engineer",
    title: "Civil Engineer",
    field: "engineering",
    medianPay: 100840,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree; PE license later",
    growth: 5,
    note: "Infrastructure money flows for a decade — bridges don't build themselves.",
  },
  {
    id: "mechanical-engineer",
    title: "Mechanical Engineer",
    field: "engineering",
    medianPay: 104110,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree",
    growth: 9,
    note: "The most versatile engineering degree — every industry buys it.",
  },
  {
    id: "electrical-engineer",
    title: "Electrical Engineer",
    field: "engineering",
    medianPay: 120630,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree",
    growth: 7,
    note: "Grid modernization and chips — both hiring hard.",
  },
  {
    id: "industrial-engineer",
    title: "Industrial Engineer",
    field: "engineering",
    medianPay: 102440,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "ABET degree",
    growth: 11,
    note: "The efficiency engineers — manufacturing's comeback is their moment.",
  },
  {
    id: "architect",
    title: "Architect",
    field: "engineering",
    medianPay: 99280,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "5-year B.Arch or M.Arch + license",
    growth: 4,
    note: "Long licensure road; the pay arrives after it.",
  },
  {
    id: "construction-manager",
    title: "Construction Manager",
    field: "engineering",
    medianPay: 114990,
    education: "bachelor",
    earnWhileTraining: true,
    trainingNote: "Degree — or rise from the trades",
    growth: 9,
    note: "Plenty climb from the tools to the trailer — field experience counts as much as the degree.",
  },
  {
    id: "environmental-scientist",
    title: "Environmental Scientist",
    field: "engineering",
    medianPay: 82220,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "A science degree",
    growth: 4,
    note: "Climate compliance work is growing in every state.",
  },
  {
    id: "chemist",
    title: "Chemist",
    field: "engineering",
    medianPay: 91240,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Chemistry degree",
    growth: 5,
    note: "Pharma and materials pay best; a master's moves you up fast.",
  },
  {
    id: "clinical-lab-tech",
    title: "Clinical Lab Technologist",
    field: "engineering",
    medianPay: 62930,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree + certification",
    growth: 2,
    note: "Every diagnosis runs through a lab — steady, hospital-based science.",
  },
  {
    id: "statistician",
    title: "Statistician",
    field: "engineering",
    medianPay: 105650,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's in statistics",
    growth: 9,
    note: "The quieter, steadier sibling of data science.",
  },
  {
    id: "urban-planner",
    title: "Urban Planner",
    field: "engineering",
    medianPay: 89320,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's in planning",
    growth: 3,
    note: "Housing policy is the story of the decade — planners sit in the middle of it.",
  },
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    field: "service",
    medianPay: 62960,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Degree or portfolio",
    growth: 2,
    note: "AI pressure is real — motion, brand systems, and UX adjacency are the durable end.",
  },
  {
    id: "technical-writer",
    title: "Technical Writer",
    field: "service",
    medianPay: 90390,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Writing skill + a technical domain",
    growth: 1,
    note: "The best-paid pure-writing job in the economy.",
  },
  {
    id: "chef",
    title: "Chef / Head Cook",
    field: "service",
    medianPay: 62470,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Kitchens promote from within — culinary school optional",
    growth: 7,
    note: "The kitchen ladder is real: line to sous to head, paid the whole way.",
  },
  {
    id: "cook",
    title: "Cook",
    field: "service",
    medianPay: 37390,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "Learned on the line",
    growth: 15,
    note: "Always hiring, everywhere — the first rung of the kitchen ladder.",
  },
  {
    id: "barber-cosmetologist",
    title: "Barber / Cosmetologist",
    field: "service",
    medianPay: 35790,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "State license program",
    growth: 5,
    note: "Chair rental is small-business ownership with tiny startup costs.",
  },
  {
    id: "massage-therapist",
    title: "Massage Therapist",
    field: "service",
    medianPay: 58450,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "License program (~600 hours)",
    growth: 15,
    note: "Healthcare-adjacent growth without healthcare-length training.",
  },
  {
    id: "truck-driver",
    title: "Truck Driver (Long-Haul)",
    field: "service",
    medianPay: 58640,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Company-paid CDL training is common",
    growth: 4,
    note: "Real money fast with no degree — the lifestyle is the true cost.",
  },
  {
    id: "delivery-driver",
    title: "Delivery Driver",
    field: "service",
    medianPay: 44860,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Hired and trained",
    growth: 8,
    note: "E-commerce keeps this one growing.",
  },
  {
    id: "airline-pilot",
    title: "Airline Pilot",
    field: "service",
    medianPay: 232140,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Ratings ladder — airlines now fund cadet programs",
    growth: 4,
    note: "The shortage rewrote the path: cadet programs pay for your ratings.",
  },
  {
    id: "commercial-pilot",
    title: "Commercial Pilot",
    field: "service",
    medianPay: 123220,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Flight ratings — no degree required",
    growth: 5,
    note: "Charter, cargo, medevac — six figures without the airline seniority ladder.",
  },
  {
    id: "flight-attendant",
    title: "Flight Attendant",
    field: "service",
    medianPay: 63580,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Airline-paid training academy",
    growth: 9,
    note: "Free training, flight benefits, and union pay scales — no degree.",
  },
  {
    id: "dispatcher",
    title: "911 Dispatcher",
    field: "service",
    medianPay: 53040,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Hired and trained",
    growth: 3,
    note: "The first first-responder — steady public-sector work in every county.",
  },

  // --- Wave 1 expansion (July 18, 2026): 50 high-employment and career-
  // ladder occupations toward comprehensive BLS coverage. Pay + growth +
  // openings + entry education from the BLS Employment Projections table
  // (2024 wage, 2024–34 projections); pay RANGE (10th–90th) backfills from
  // the OEWS May 2025 API as quota allows (see lib/careerDetails.ts).
  {
    id: "nursing-assistant",
    title: "Nursing Assistant (CNA)",
    field: "health",
    medianPay: 39530,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Short state course, then competency exam",
    growth: 2,
    note: "The fastest paid entry into hospital and nursing-home work, and a proven first rung toward LPN and RN.",
  },
  {
    id: "speech-language-pathologist",
    title: "Speech-Language Pathologist",
    field: "health",
    medianPay: 95410,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree + supervised clinical hours",
    growth: 15,
    note: "Steady demand across schools and clinics, but the master's degree and clinical hours are a real commitment.",
  },
  {
    id: "dietitian",
    title: "Dietitian / Nutritionist",
    field: "health",
    medianPay: 73850,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + supervised internship",
    growth: 6,
    note: "A science-backed path into health care that does not require medical school, though the credential process is involved.",
  },
  {
    id: "medical-records-specialist",
    title: "Medical Records Specialist",
    field: "health",
    medianPay: 50250,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Certificate program, sometimes on the job",
    growth: 7,
    note: "A behind-the-scenes way into health care for people who prefer computers and coding to bedside work.",
  },
  {
    id: "mri-tech",
    title: "MRI Technologist",
    field: "health",
    medianPay: 88180,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + certification",
    growth: 7,
    note: "Strong pay for a two-year degree, and a natural step up for radiologic techs who want to specialize.",
  },
  {
    id: "athletic-trainer",
    title: "Athletic Trainer",
    field: "health",
    medianPay: 60250,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree + certification",
    growth: 11,
    note: "Rewarding work in sports medicine, but the master's requirement now sets a higher bar than many expect.",
  },
  {
    id: "substance-abuse-counselor",
    title: "Substance Abuse & Mental Health Counselor",
    field: "education",
    medianPay: 59190,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree + supervised hours",
    growth: 17,
    note: "Meaningful, growing work in mental health, though the emotional weight and licensing hours are real.",
  },
  {
    id: "human-service-assistant",
    title: "Social & Human Service Assistant",
    field: "education",
    medianPay: 45120,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 6,
    note: "A foot in the door to social work, with paid on-the-job training and no degree required to start.",
  },
  {
    id: "systems-analyst",
    title: "Computer Systems Analyst",
    field: "tech",
    medianPay: 103790,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 9,
    note: "A practical tech role that bridges business and IT, often reachable without a hardcore programming background.",
  },
  {
    id: "network-architect",
    title: "Computer Network Architect",
    field: "tech",
    medianPay: 130390,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + experience",
    growth: 12,
    note: "High pay for people who master networking, but it usually takes years of hands-on IT work to get here.",
  },
  {
    id: "qa-analyst",
    title: "Software QA Analyst / Tester",
    field: "tech",
    medianPay: 102610,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree or bootcamp",
    growth: 10,
    note: "A common entry point into software teams for detail-oriented people who like breaking things to find bugs.",
  },
  {
    id: "operations-research-analyst",
    title: "Operations Research Analyst",
    field: "tech",
    medianPay: 91290,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree, often a master's",
    growth: 22,
    note: "One of the faster-growing analytical careers, using math to solve real business problems behind the scenes.",
  },
  {
    id: "operations-manager",
    title: "General & Operations Manager",
    field: "business",
    medianPay: 102950,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + experience",
    growth: 4,
    note: "A broad management role found in nearly every industry, usually reached after years of proving yourself first.",
  },
  {
    id: "financial-manager",
    title: "Financial Manager",
    field: "business",
    medianPay: 161700,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + experience",
    growth: 15,
    note: "Among the best-paid business roles, but it sits at the top of a ladder you climb over many years.",
  },
  {
    id: "health-services-manager",
    title: "Medical & Health Services Manager",
    field: "business",
    medianPay: 117960,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree, often a master's",
    growth: 23,
    note: "One of the fastest-growing management fields, opening health-care leadership without a clinical degree.",
  },
  {
    id: "project-manager",
    title: "Project Management Specialist",
    field: "business",
    medianPay: 100750,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree, certification helps",
    growth: 6,
    note: "A flexible, well-paid role across industries, where a certification can matter as much as a degree.",
  },
  {
    id: "market-research-analyst",
    title: "Market Research Analyst",
    field: "business",
    medianPay: 76950,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 7,
    note: "A common entry into the business world for people who like data and consumer behavior, with wide demand.",
  },
  {
    id: "loan-officer",
    title: "Loan Officer",
    field: "business",
    medianPay: 74180,
    education: "bachelor",
    earnWhileTraining: true,
    trainingNote: "Moderate on-the-job training, paid",
    growth: 2,
    note: "You can start with a high school diploma and learn on the job, though pay often leans on commission.",
  },
  {
    id: "tax-preparer",
    title: "Tax Preparer",
    field: "business",
    medianPay: 50560,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Short paid training, then hired",
    growth: 4,
    note: "A seasonal way to earn using a short training course, and a starting point toward accounting work.",
  },
  {
    id: "sales-rep",
    title: "Sales Representative (Wholesale)",
    field: "business",
    medianPay: 66780,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 0,
    note: "No degree needed to start and strong earning potential, though much of your pay can ride on commission.",
  },
  {
    id: "cashier",
    title: "Cashier",
    field: "service",
    medianPay: 31190,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: -10,
    note: "Shrinking as self-checkout spreads, but constant turnover means openings are almost always around.",
  },
  {
    id: "retail-salesperson",
    title: "Retail Salesperson",
    field: "service",
    medianPay: 34580,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 0,
    note: "One of the easiest jobs to land anywhere, and a place to build customer skills that transfer widely.",
  },
  {
    id: "bank-teller",
    title: "Bank Teller",
    field: "business",
    medianPay: 39340,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Short paid training, then hired",
    growth: -13,
    note: "Declining as banking goes digital, but turnover keeps hiring steady and it opens doors inside banks.",
  },
  {
    id: "receptionist",
    title: "Receptionist",
    field: "business",
    medianPay: 37230,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 0,
    note: "A steady office entry point that builds professional habits, though the work itself is often routine.",
  },
  {
    id: "office-clerk",
    title: "Office Clerk",
    field: "business",
    medianPay: 43630,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: -7,
    note: "Slowly shrinking as software absorbs the paperwork, but still a common way into office work.",
  },
  {
    id: "medical-secretary",
    title: "Medical Secretary",
    field: "business",
    medianPay: 44640,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Moderate on-the-job training, paid",
    growth: 4,
    note: "A stable office role inside health care, with paid training and room to grow into billing or admin work.",
  },
  {
    id: "server",
    title: "Waiter / Waitress",
    field: "service",
    medianPay: 33760,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: -1,
    note: "Fast to start and tip income can add up, but pay swings with the shift, the season, and the crowd.",
  },
  {
    id: "bartender",
    title: "Bartender",
    field: "service",
    medianPay: 33530,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 6,
    note: "Tips can make it pay well in busy venues, though hours are late and income depends on foot traffic.",
  },
  {
    id: "fast-food-worker",
    title: "Fast Food & Counter Worker",
    field: "service",
    medianPay: 30480,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 6,
    note: "Almost always hiring and quick to start, making it a common first job to build a work record.",
  },
  {
    id: "food-prep-worker",
    title: "Food Prep Worker",
    field: "service",
    medianPay: 34220,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: -3,
    note: "An easy kitchen entry point and a place to learn skills that lead toward cook and chef roles.",
  },
  {
    id: "baker",
    title: "Baker",
    field: "service",
    medianPay: 36650,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 6,
    note: "A hands-on craft you can learn on the job, with the trade-off of very early morning starts.",
  },
  {
    id: "fitness-trainer",
    title: "Fitness Trainer / Instructor",
    field: "service",
    medianPay: 46180,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Certification, often employer-paid",
    growth: 12,
    note: "Growing demand and flexible hours, though building a steady client base takes time and hustle.",
  },
  {
    id: "esthetician",
    title: "Esthetician / Skincare Specialist",
    field: "service",
    medianPay: 41560,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "State-approved program + license",
    growth: 7,
    note: "A licensed beauty career with a shorter path than many, and room to build a loyal client following.",
  },
  {
    id: "funeral-director",
    title: "Funeral Director",
    field: "service",
    medianPay: 49800,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + state license",
    growth: 3,
    note: "Steady, recession-resistant work that asks for real emotional steadiness alongside the training.",
  },
  {
    id: "janitor",
    title: "Janitor / Custodian",
    field: "service",
    medianPay: 35930,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 2,
    note: "Always hiring and easy to start, with the trade-off of physical work and often off-hours shifts.",
  },
  {
    id: "landscaper",
    title: "Landscaper / Groundskeeper",
    field: "service",
    medianPay: 38090,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 4,
    note: "Outdoor work that is easy to enter, though hours and pay often rise and fall with the seasons.",
  },
  {
    id: "bus-driver",
    title: "Transit Bus Driver",
    field: "service",
    medianPay: 57440,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid training, then earn a CDL",
    growth: 4,
    note: "Solid pay and benefits for a job you can train into quickly, with public-transit shifts to expect.",
  },
  {
    id: "warehouse-worker",
    title: "Warehouse Worker / Material Mover",
    field: "service",
    medianPay: 38940,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 2,
    note: "Widely available and quick to start, though the work is physical and the pace can be demanding.",
  },
  {
    id: "forklift-operator",
    title: "Forklift Operator",
    field: "service",
    medianPay: 46390,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training and certification",
    growth: 1,
    note: "A short certification bumps you above general warehouse pay, and the skill travels to many employers.",
  },
  {
    id: "security-guard",
    title: "Security Guard",
    field: "public",
    medianPay: 38370,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Short paid training + state license",
    growth: 0,
    note: "Easy to enter with quick training, and a common stepping stone toward law enforcement careers.",
  },
  {
    id: "detective",
    title: "Detective / Criminal Investigator",
    field: "public",
    medianPay: 93580,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Police experience, then promotion",
    growth: -1,
    note: "Well-paid investigative work, but it is rarely entry-level and usually comes after years on patrol.",
  },
  {
    id: "construction-laborer",
    title: "Construction Laborer",
    field: "trades",
    medianPay: 46730,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 7,
    note: "A paid entry into the building trades, and a place to test which skilled craft you want to pursue.",
  },
  {
    id: "painter",
    title: "Painter",
    field: "trades",
    medianPay: 48660,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 4,
    note: "A trade you can learn on the job, with steady demand from both new building and repainting work.",
  },
  {
    id: "roofer",
    title: "Roofer",
    field: "trades",
    medianPay: 50970,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid from day one",
    growth: 6,
    note: "Reliable demand and a fast paid start, balanced against tough conditions and real work-at-height risk.",
  },
  {
    id: "maintenance-worker",
    title: "Maintenance & Repair Worker",
    field: "trades",
    medianPay: 48620,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Moderate on-the-job training, paid",
    growth: 4,
    note: "A versatile trade found in every kind of building, and a broad base for moving into specialized repair.",
  },
  {
    id: "industrial-mechanic",
    title: "Industrial Machinery Mechanic",
    field: "trades",
    medianPay: 63760,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Long on-the-job training, paid",
    growth: 16,
    note: "Strong, growing demand as factories automate, with good pay for those who master complex machinery.",
  },
  {
    id: "water-treatment-operator",
    title: "Water Treatment Operator",
    field: "trades",
    medianPay: 58260,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training + state certification",
    growth: -6,
    note: "Essential public-utility work that stays steady even as automation slowly trims the total jobs.",
  },
  {
    id: "aerospace-engineer",
    title: "Aerospace Engineer",
    field: "engineering",
    medianPay: 134830,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 6,
    note: "High pay and cutting-edge work, though it demands strong math and a competitive engineering degree.",
  },
  {
    id: "surveyor",
    title: "Surveyor",
    field: "engineering",
    medianPay: 72740,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + state license",
    growth: 4,
    note: "A field-and-office engineering path with a lighter degree load, but the state license takes years to earn.",
  },
  {
    id: "biological-technician",
    title: "Biological Technician",
    field: "engineering",
    medianPay: 52000,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 4,
    note: "A lab entry point into science with a bachelor's, and useful footing toward research or health careers.",
  },

  // --- Wave 2 expansion (July 18, 2026): +60 more occupations toward
  // comprehensive coverage — health techs, the professional/management rungs,
  // arts & media, more skilled trades, and agriculture. Same BLS Employment
  // Projections source as wave 1 (2024 wage · 2024–34 projections); pay range
  // backfills from the OEWS May 2025 API (see lib/careerDetails.ts).
  {
    id: "nuclear-med-tech",
    title: "Nuclear Medicine Technologist",
    field: "health",
    medianPay: 97020,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + certification",
    growth: 3,
    note: "One of the strongest associate-degree paychecks in health care, though openings stay thin.",
  },
  {
    id: "cardiovascular-tech",
    title: "Cardiovascular Technologist",
    field: "health",
    medianPay: 67260,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree + certification",
    growth: 3,
    note: "A steady hospital role that puts you close to heart procedures without a four-year degree.",
  },
  {
    id: "optician",
    title: "Optician",
    field: "health",
    medianPay: 46560,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 3,
    note: "A retail-based health role you can enter from high school and learn largely on the job.",
  },
  {
    id: "audiologist",
    title: "Audiologist",
    field: "health",
    medianPay: 92120,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "Doctoral degree + license",
    growth: 10,
    note: "A doctoral path with a steadier outlook as an aging population needs more hearing care.",
  },
  {
    id: "chiropractor",
    title: "Chiropractor",
    field: "health",
    medianPay: 79000,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "Doctoral degree + license",
    growth: 10,
    note: "Many run their own practice, so pay swings with how well the business is built.",
  },
  {
    id: "podiatrist",
    title: "Podiatrist",
    field: "health",
    medianPay: 152800,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "Doctoral degree + residency",
    growth: 2,
    note: "A specialized doctoral track with strong pay, though the field is small and openings are few.",
  },
  {
    id: "psychiatric-aide",
    title: "Psychiatric Aide",
    field: "health",
    medianPay: 41590,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 0,
    note: "Demanding front-line work that opens the door to mental health care without a degree.",
  },
  {
    id: "recreational-therapist",
    title: "Recreational Therapist",
    field: "health",
    medianPay: 60280,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 3,
    note: "A hands-on way to use activities and recreation as real clinical treatment.",
  },
  {
    id: "genetic-counselor",
    title: "Genetic Counselor",
    field: "health",
    medianPay: 98910,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree + certification",
    growth: 9,
    note: "A growing niche where science meets counseling, with pay that rewards the master's investment.",
  },
  {
    id: "psychologist",
    title: "Clinical / Counseling Psychologist",
    field: "education",
    medianPay: 95830,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "Doctoral degree + license",
    growth: 11,
    note: "A long doctoral road, but demand for mental health services keeps the outlook solid.",
  },
  {
    id: "school-psychologist",
    title: "School Psychologist",
    field: "education",
    medianPay: 86930,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree + credential",
    growth: 1,
    note: "A stable schools-based path with a master's, though hiring tracks district budgets.",
  },
  {
    id: "rehabilitation-counselor",
    title: "Rehabilitation Counselor",
    field: "education",
    medianPay: 46110,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree + license",
    growth: 1,
    note: "Meaningful work with high turnover — pay runs modest for a role that requires a master's.",
  },
  {
    id: "healthcare-social-worker",
    title: "Healthcare Social Worker",
    field: "education",
    medianPay: 68090,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree + license",
    growth: 8,
    note: "Steady demand across hospitals and hospice, with a heavy caseload behind the paycheck.",
  },
  {
    id: "probation-officer",
    title: "Probation Officer",
    field: "public",
    medianPay: 64520,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + academy training",
    growth: 3,
    note: "A public-service role with a pension track, and real emotional weight in the caseload.",
  },
  {
    id: "budget-analyst",
    title: "Budget Analyst",
    field: "business",
    medianPay: 87930,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 1,
    note: "A quieter finance role with a strong paycheck, common across government and large organizations.",
  },
  {
    id: "cost-estimator",
    title: "Cost Estimator",
    field: "business",
    medianPay: 77070,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: -4,
    note: "Declining overall as software takes over routine estimating, but construction still hires steadily.",
  },
  {
    id: "compliance-officer",
    title: "Compliance Officer",
    field: "business",
    medianPay: 78420,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 3,
    note: "A broad, stable role in almost every industry as rules and oversight keep expanding.",
  },
  {
    id: "purchasing-agent",
    title: "Purchasing Agent / Buyer",
    field: "business",
    medianPay: 75650,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 6,
    note: "A dependable business path that scales into supply-chain and management roles over time.",
  },
  {
    id: "claims-adjuster",
    title: "Claims Adjuster",
    field: "business",
    medianPay: 76790,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: -5,
    note: "Solid pay you can reach from high school, though automation is thinning the field.",
  },
  {
    id: "insurance-underwriter",
    title: "Insurance Underwriter",
    field: "business",
    medianPay: 79880,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: -3,
    note: "Declining as software handles routine decisions, but complex risks still need human judgment.",
  },
  {
    id: "sales-manager",
    title: "Sales Manager",
    field: "business",
    medianPay: 138060,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 5,
    note: "High pay tied to results, so income and pressure both rise with the team's numbers.",
  },
  {
    id: "hr-manager",
    title: "Human Resources Manager",
    field: "business",
    medianPay: 140030,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 5,
    note: "A well-paid path into leadership that rewards people skills as much as policy know-how.",
  },
  {
    id: "property-manager",
    title: "Property Manager",
    field: "business",
    medianPay: 66700,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 4,
    note: "An entry point to real estate you can reach from high school and grow through on the job.",
  },
  {
    id: "food-service-manager",
    title: "Food Service Manager",
    field: "business",
    medianPay: 65310,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 6,
    note: "A path from the kitchen floor to running the place, learned largely by doing.",
  },
  {
    id: "training-development-specialist",
    title: "Training & Development Specialist",
    field: "business",
    medianPay: 65850,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 11,
    note: "A growing role as employers keep reskilling staff, and a bridge into HR leadership.",
  },
  {
    id: "photographer",
    title: "Photographer",
    field: "service",
    medianPay: 42520,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 2,
    note: "Many work freelance, so income depends on steadily finding and keeping clients.",
  },
  {
    id: "journalist",
    title: "Reporter / Journalist",
    field: "service",
    medianPay: 60280,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: -4,
    note: "Shrinking newsrooms make this competitive — early pay is low and the hours are unpredictable.",
  },
  {
    id: "editor",
    title: "Editor",
    field: "service",
    medianPay: 75260,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 1,
    note: "Steadier than reporting, but the same industry shrinkage keeps openings competitive.",
  },
  {
    id: "writer",
    title: "Writer / Author",
    field: "service",
    medianPay: 72270,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 4,
    note: "Many piece together freelance and salaried work, so income can be uneven early on.",
  },
  {
    id: "interior-designer",
    title: "Interior Designer",
    field: "service",
    medianPay: 63490,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 3,
    note: "Creative and client-driven work where reputation and referrals shape how much you earn.",
  },
  {
    id: "industrial-designer",
    title: "Industrial Designer",
    field: "service",
    medianPay: 79450,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 3,
    note: "Blends art and engineering to shape everyday products, with pay above most design roles.",
  },
  {
    id: "pr-specialist",
    title: "Public Relations Specialist",
    field: "service",
    medianPay: 69780,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 5,
    note: "A steady communications path that builds skills useful across marketing and media.",
  },
  {
    id: "coach",
    title: "Coach / Scout",
    field: "service",
    medianPay: 45920,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 6,
    note: "Rewarding but often part-time or seasonal, with pay that thins outside the top levels.",
  },
  {
    id: "art-director",
    title: "Art Director",
    field: "service",
    medianPay: 111040,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 4,
    note: "A senior creative role with strong pay, usually reached after years in design.",
  },
  {
    id: "chemical-engineer",
    title: "Chemical Engineer",
    field: "engineering",
    medianPay: 121860,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 3,
    note: "One of the higher-paying engineering starts, with work tied to manufacturing and energy.",
  },
  {
    id: "biomedical-engineer",
    title: "Biomedical Engineer",
    field: "engineering",
    medianPay: 106950,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 5,
    note: "Sits where engineering meets medicine, designing the devices that health care depends on.",
  },
  {
    id: "environmental-engineer",
    title: "Environmental Engineer",
    field: "engineering",
    medianPay: 104170,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 4,
    note: "Applies engineering to pollution, water, and climate work, with demand tied to regulation.",
  },
  {
    id: "civil-engineering-tech",
    title: "Civil Engineering Technician",
    field: "engineering",
    medianPay: 64200,
    education: "associate",
    earnWhileTraining: false,
    trainingNote: "Associate degree",
    growth: 2,
    note: "An associate-degree way into infrastructure work without the full engineering degree.",
  },
  {
    id: "microbiologist",
    title: "Microbiologist",
    field: "engineering",
    medianPay: 87330,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree",
    growth: 4,
    note: "Lab-based science work, with the strongest options usually needing graduate study later.",
  },
  {
    id: "forensic-science-tech",
    title: "Forensic Science Technician",
    field: "engineering",
    medianPay: 67440,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + training",
    growth: 13,
    note: "Growing faster than most science roles, though popular shows make entry competitive.",
  },
  {
    id: "economist",
    title: "Economist",
    field: "engineering",
    medianPay: 115440,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree",
    growth: 1,
    note: "Strong pay for those who make it in, but a small field that leans on graduate credentials.",
  },
  {
    id: "kindergarten-teacher",
    title: "Kindergarten Teacher",
    field: "education",
    medianPay: 61430,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + license",
    growth: -2,
    note: "Shrinking slightly with enrollment, but a stable public path with a summer break built in.",
  },
  {
    id: "special-ed-teacher",
    title: "Special Education Teacher",
    field: "education",
    medianPay: 63000,
    education: "bachelor",
    earnWhileTraining: false,
    trainingNote: "Bachelor's degree + license",
    growth: -2,
    note: "Persistent shortages mean steady hiring, even as overall numbers dip — and the work is demanding.",
  },
  {
    id: "instructional-coordinator",
    title: "Instructional Coordinator",
    field: "education",
    medianPay: 74720,
    education: "master",
    earnWhileTraining: false,
    trainingNote: "Master's degree",
    growth: 1,
    note: "A step off the classroom track into curriculum and training, usually after teaching first.",
  },
  {
    id: "nursing-instructor",
    title: "Nursing Instructor (Postsecondary)",
    field: "education",
    medianPay: 79940,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "Graduate degree + nursing license",
    growth: 17,
    note: "Fast-growing as nursing schools scramble for faculty to meet a national nurse shortage.",
  },
  {
    id: "court-reporter",
    title: "Court Reporter",
    field: "business",
    medianPay: 67310,
    education: "certificate",
    earnWhileTraining: false,
    trainingNote: "Certificate + certification",
    growth: 0,
    note: "A certificate-level path to solid pay, with steady demand from courts and captioning.",
  },
  {
    id: "judge",
    title: "Judge",
    field: "education",
    medianPay: 156210,
    education: "doctoral",
    earnWhileTraining: false,
    trainingNote: "Law degree + license",
    growth: 2,
    note: "A capstone legal career reached after years as a lawyer, often through election or appointment.",
  },
  {
    id: "fish-game-warden",
    title: "Fish & Game Warden",
    field: "public",
    medianPay: 68180,
    education: "bachelor",
    earnWhileTraining: true,
    trainingNote: "Bachelor's degree + academy training",
    growth: -6,
    note: "Outdoor law enforcement with a small, competitive field and few yearly openings.",
  },
  {
    id: "private-detective",
    title: "Private Detective / Investigator",
    field: "public",
    medianPay: 52370,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 6,
    note: "Flexible investigative work you can enter from high school, often after a law enforcement career.",
  },
  {
    id: "fire-inspector",
    title: "Fire Inspector",
    field: "public",
    medianPay: 78060,
    education: "certificate",
    earnWhileTraining: true,
    trainingNote: "Certificate + certification",
    growth: 4,
    note: "A certificate-level move up from firefighting, with strong pay and regular hours.",
  },
  {
    id: "butcher",
    title: "Butcher / Meat Cutter",
    field: "service",
    medianPay: 38960,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 1,
    note: "Skilled hands-on work you can learn on the job, common in grocery and processing.",
  },
  {
    id: "power-plant-operator",
    title: "Power Plant Operator",
    field: "trades",
    medianPay: 99670,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: -11,
    note: "Top-tier pay for a high school start, but the field is shrinking as older plants close.",
  },
  {
    id: "school-bus-driver",
    title: "School Bus Driver",
    field: "service",
    medianPay: 47040,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 0,
    note: "Often part-time with split shifts, but a reliable entry point with a summer break.",
  },
  {
    id: "crane-operator",
    title: "Crane Operator",
    field: "trades",
    medianPay: 66370,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 3,
    note: "Skilled, well-paid construction work you can enter from high school with certification.",
  },
  {
    id: "farmer",
    title: "Farmer / Rancher",
    field: "service",
    medianPay: 87980,
    education: "hs",
    earnWhileTraining: false,
    trainingNote: "On-the-job experience",
    growth: -1,
    note: "Median pay looks strong, but income swings hard with weather, prices, and land costs.",
  },
  {
    id: "farmworker",
    title: "Farmworker / Ag Laborer",
    field: "service",
    medianPay: 35690,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: -3,
    note: "Hard, low-paying seasonal labor, though steady openings make it easy to enter.",
  },
  {
    id: "brickmason",
    title: "Brickmason / Blockmason",
    field: "trades",
    medianPay: 60800,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship",
    growth: 3,
    note: "A skilled trade learned through apprenticeship, with good pay and physically demanding days.",
  },
  {
    id: "drywall-installer",
    title: "Drywall Installer",
    field: "trades",
    medianPay: 58140,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 4,
    note: "A hands-on trade with no formal schooling needed and steady construction demand.",
  },
  {
    id: "boilermaker",
    title: "Boilermaker",
    field: "trades",
    medianPay: 73340,
    education: "hs",
    earnWhileTraining: true,
    trainingNote: "Paid apprenticeship",
    growth: -2,
    note: "High-paying trade learned by apprenticeship, though demand is slipping with heavy industry.",
  },
  {
    id: "taxi-driver",
    title: "Taxi / Rideshare Driver",
    field: "service",
    medianPay: 36220,
    education: "none",
    earnWhileTraining: true,
    trainingNote: "On-the-job training, paid",
    growth: 11,
    note: "Easy to start and growing with rideshare, but pay is low and you cover your own costs.",
  },
];
