// Career profiles — the richer per-job data behind the Career Explorer
// (July 18, 2026 owner ask: "more info about each job"). Additive to
// lib/careers.ts, keyed by career id. Numbers (payLow/payHigh = 10th/90th
// percentile annual wage, numJobs = total U.S. employment) are BLS OEWS
// May 2025 — the SAME vintage as CAREER_DATA_VINTAGE — pulled by SOC code
// and verified by matching each occupation's API median to the stored
// medianPay. A career whose numbers are still pending simply omits them
// (the UI shows an em dash); nothing is ever estimated or invented.
// The prose fields (whatTheyDo/workSetting/hours/skills/license) describe
// the occupation from the BLS Occupational Outlook Handbook. `related`
// cross-links career ids. Re-verify with the OEWS refresh (see freshness).

export interface CareerDetail {
  /** Standard Occupational Classification code, e.g. "47-2111". */
  soc: string;
  /** 10th-percentile annual wage (BLS OEWS May 2025). */
  payLow?: number;
  /** 90th-percentile annual wage (BLS OEWS May 2025). */
  payHigh?: number;
  /** Total U.S. employment (BLS OEWS May 2025). */
  numJobs?: number;
  /** Plain-language summary of the work. */
  whatTheyDo: string;
  /** Where and in what conditions they work. */
  workSetting: string;
  /** The real schedule. */
  hours: string;
  /** Key skills and qualities the work demands. */
  skills: string[];
  /** Licensing or certification reality, when relevant. */
  license?: string;
  /** Related career ids for cross-linking. */
  related: string[];
}

export const CAREER_DETAILS: Record<string, CareerDetail> = {
  "electrician": {
    soc: "47-2111",
    payLow: 42640,
    payHigh: 108510,
    numJobs: 757220,
    whatTheyDo: "Install, maintain, and repair the wiring, controls, and electrical systems that power homes, businesses, and factories.",
    workSetting: "Job sites, homes, and businesses; indoors and out, often in tight spaces.",
    hours: "Usually full-time; overtime and emergency calls are common.",
    skills: ["Manual dexterity", "Troubleshooting", "Physical stamina", "Color vision"],
    license: "Most states require a license, earned by exam after an apprenticeship.",
    related: ["lineworker", "hvac-tech", "solar-installer"],
  },
  "plumber": {
    soc: "47-2152",
    payLow: 44150,
    payHigh: 108420,
    numJobs: 465840,
    whatTheyDo: "Install and repair the pipes, fixtures, and appliances that carry water, gas, and waste through buildings.",
    workSetting: "Homes, businesses, and construction sites; cramped spaces and outdoors.",
    hours: "Full-time; on-call nights and weekends for emergencies are common.",
    skills: ["Mechanical skills", "Problem solving", "Physical strength", "Customer service"],
    license: "Most states require a license, earned by exam after an apprenticeship.",
    related: ["hvac-tech", "electrician", "sheet-metal"],
  },
  "hvac-tech": {
    soc: "49-9021",
    payLow: 40050,
    payHigh: 95210,
    numJobs: 409670,
    whatTheyDo: "Install, maintain, and repair the heating, ventilation, air conditioning, and refrigeration systems that keep buildings comfortable.",
    workSetting: "Homes, businesses, rooftops, and basements; indoors and out, all weather.",
    hours: "Full-time; long hours and on-call work peak in summer and winter.",
    skills: ["Mechanical skills", "Troubleshooting", "Physical stamina", "Customer service"],
    license: "Some states and localities require a license; EPA certification is required to handle refrigerants.",
    related: ["electrician", "plumber", "sheet-metal"],
  },
  "carpenter": {
    soc: "47-2031",
    payLow: 40410,
    payHigh: 99910,
    numJobs: 670090,
    whatTheyDo: "Cut, shape, and assemble wood and other materials to build and repair structures, frames, and fixtures.",
    workSetting: "Construction sites and workshops; indoors and out, often standing and lifting.",
    hours: "Full-time; work can be seasonal and weather-dependent.",
    skills: ["Manual dexterity", "Math skills", "Physical stamina", "Attention to detail"],
    license: "No license required in most places; apprenticeship builds the skills employers want.",
    related: ["construction-manager", "electrician", "ironworker"],
  },
  "welder": {
    soc: "51-4121",
    payLow: 39240,
    payHigh: 77530,
    numJobs: 416210,
    whatTheyDo: "Join and cut metal parts using heat, following blueprints and specifications to build and repair structures and equipment.",
    workSetting: "Factories, shops, and job sites; hot, loud conditions, often with protective gear.",
    hours: "Full-time; shift work and overtime are common.",
    skills: ["Manual dexterity", "Attention to detail", "Physical stamina", "Steady hands"],
    license: "No license required; employers often want certification proving specific welding skills.",
    related: ["ironworker", "sheet-metal", "machinist"],
  },
  "machinist": {
    soc: "51-4041",
    payLow: 39200,
    payHigh: 80010,
    numJobs: 287050,
    whatTheyDo: "Set up and operate machine tools, including computer-controlled ones, to produce precise metal parts.",
    workSetting: "Machine shops and factories; loud floors with moving equipment and metal chips.",
    hours: "Full-time; shift work is common in production shops.",
    skills: ["Mechanical skills", "Math skills", "Attention to detail", "Technical aptitude"],
    license: "No license required; certification can prove skills to employers.",
    related: ["welder", "sheet-metal", "diesel-tech"],
  },
  "ironworker": {
    soc: "47-2221",
    payLow: 44580,
    payHigh: 108260,
    numJobs: 68380,
    whatTheyDo: "Install and reinforce the structural and ornamental steel and iron that frames bridges, buildings, and other large structures.",
    workSetting: "Construction sites, often at great heights; outdoors in all weather.",
    hours: "Full-time; work can be seasonal and weather-dependent, with travel.",
    skills: ["Physical strength", "Balance", "Hand-eye coordination", "Unafraid of heights"],
    license: "No license required; skills are learned through a paid apprenticeship.",
    related: ["welder", "equipment-operator", "carpenter"],
  },
  "sheet-metal": {
    soc: "47-2211",
    payLow: 38630,
    payHigh: 105650,
    numJobs: 119770,
    whatTheyDo: "Fabricate and install products made from thin metal sheets, such as ducts, gutters, and roofing.",
    workSetting: "Shops and construction sites; indoors and out, standing and lifting.",
    hours: "Full-time; overtime is common, and outdoor work can be seasonal.",
    skills: ["Manual dexterity", "Math skills", "Physical stamina", "Attention to detail"],
    license: "No license required in most places; apprenticeship is the standard path.",
    related: ["hvac-tech", "welder", "ironworker"],
  },
  "equipment-operator": {
    soc: "47-2073",
    payLow: 42190,
    payHigh: 101090,
    numJobs: 478090,
    whatTheyDo: "Drive and control heavy machines such as cranes, bulldozers, and excavators to move earth, materials, and structures.",
    workSetting: "Construction sites, roads, and mines; outdoors in all weather and dust.",
    hours: "Full-time; early starts, long days, and seasonal work are common.",
    skills: ["Hand-eye coordination", "Mechanical skills", "Attention to detail", "Depth perception"],
    license: "A commercial driver's license is often needed; crane operators usually require certification.",
    related: ["truck-driver", "ironworker", "diesel-tech"],
  },
  "elevator-tech": {
    soc: "47-4021",
    payLow: 59270,
    payHigh: 158890,
    numJobs: 23790,
    whatTheyDo: "Install, maintain, and repair elevators, escalators, and moving walkways, testing safety systems as you go.",
    workSetting: "Buildings under construction and in use; shafts, machine rooms, and heights.",
    hours: "Full-time; on-call nights and weekends for emergency repairs.",
    skills: ["Mechanical skills", "Troubleshooting", "Physical stamina", "Safety awareness"],
    license: "Many states require a license; skills come through a long paid apprenticeship.",
    related: ["electrician", "hvac-tech", "ironworker"],
  },
  "lineworker": {
    soc: "49-9051",
    payLow: 51470,
    payHigh: 128690,
    numJobs: 131070,
    whatTheyDo: "Install and repair the power lines and cables that carry electricity from plants to homes and businesses.",
    workSetting: "Outdoors at heights and in the field; all weather, including storms.",
    hours: "Full-time; on-call and long storm-recovery shifts are common.",
    skills: ["Physical strength", "Balance", "Safety awareness", "Unafraid of heights"],
    license: "No license required; a commercial driver's license and paid apprenticeship are typical.",
    related: ["electrician", "wind-turbine-tech", "solar-installer"],
  },
  "auto-tech": {
    soc: "49-3023",
    payLow: 34660,
    payHigh: 81790,
    numJobs: 704640,
    whatTheyDo: "Inspect, diagnose, and repair cars and light trucks, from brakes and engines to electronic systems.",
    workSetting: "Repair shops and dealerships; indoors, often standing, lifting, and bending.",
    hours: "Usually full-time; some evenings and weekends.",
    skills: ["Troubleshooting", "Mechanical skills", "Customer service", "Technical aptitude"],
    license: "No license required; ASE certification is the widely recognized credential.",
    related: ["diesel-tech", "aircraft-mechanic", "machinist"],
  },
  "diesel-tech": {
    soc: "49-3031",
    payLow: 44530,
    payHigh: 88740,
    numJobs: 289960,
    whatTheyDo: "Inspect, repair, and overhaul the diesel engines in trucks, buses, and heavy equipment.",
    workSetting: "Repair shops and fleet garages; loud, greasy, standing and lifting.",
    hours: "Full-time; evening, night, and weekend shifts are common.",
    skills: ["Mechanical skills", "Troubleshooting", "Physical strength", "Attention to detail"],
    license: "No license required; a commercial driver's license and ASE certification help.",
    related: ["auto-tech", "aircraft-mechanic", "equipment-operator"],
  },
  "aircraft-mechanic": {
    soc: "49-3011",
    payLow: 48780,
    payHigh: 128890,
    numJobs: 138090,
    whatTheyDo: "Inspect, maintain, and repair aircraft engines, systems, and structures to keep planes safe to fly.",
    workSetting: "Hangars, airfields, and repair stations; loud, sometimes at heights.",
    hours: "Full-time; shift work, nights, and weekends are common.",
    skills: ["Mechanical skills", "Attention to detail", "Troubleshooting", "Physical stamina"],
    license: "Most jobs require FAA certification as an Airframe and Powerplant mechanic.",
    related: ["diesel-tech", "auto-tech", "machinist"],
  },
  "wind-turbine-tech": {
    soc: "49-9081",
    payLow: 49230,
    payHigh: 92460,
    numJobs: 9980,
    whatTheyDo: "Install, inspect, and repair the mechanical and electrical systems inside wind turbines.",
    workSetting: "Wind farms, often high inside turbines; outdoors and at great heights.",
    hours: "Full-time; on-call and travel to remote sites are common.",
    skills: ["Mechanical skills", "Physical stamina", "Troubleshooting", "Unafraid of heights"],
    license: "No license required; employers provide safety and technical certifications.",
    related: ["solar-installer", "lineworker", "electrician"],
  },
  "solar-installer": {
    soc: "47-2231",
    payLow: 41600,
    payHigh: 79970,
    numJobs: 31350,
    whatTheyDo: "Assemble, install, and connect solar panels on roofs and in fields, then test the systems.",
    workSetting: "Rooftops and open sites; outdoors in all weather, often at heights.",
    hours: "Usually full-time; outdoor work can be seasonal.",
    skills: ["Physical stamina", "Mechanical skills", "Attention to detail", "Unafraid of heights"],
    license: "No license required to assist; certification and an electrician's help with wiring.",
    related: ["electrician", "wind-turbine-tech", "lineworker"],
  },
  "rn": {
    soc: "29-1141",
    payLow: 68940,
    payHigh: 137470,
    numJobs: 3379720,
    whatTheyDo: "Assess patients, give treatments and medications, and coordinate care as part of the medical team.",
    workSetting: "Hospitals, clinics, and homes; fast-paced, on your feet most of the shift.",
    hours: "Often long shifts including nights, weekends, and holidays.",
    skills: ["Compassion", "Critical thinking", "Attention to detail", "Communication"],
    license: "Requires passing the NCLEX-RN and holding a state license.",
    related: ["lpn", "nurse-practitioner", "respiratory-therapist"],
  },
  "lpn": {
    soc: "29-2061",
    payLow: 49740,
    payHigh: 83440,
    numJobs: 648410,
    whatTheyDo: "Provide basic nursing care, monitor patients, and report to registered nurses and doctors.",
    workSetting: "Nursing homes, hospitals, and clinics; on your feet, hands-on with patients.",
    hours: "Full-time and part-time; nights, weekends, and holidays are common.",
    skills: ["Compassion", "Patience", "Attention to detail", "Stamina"],
    license: "Requires passing the NCLEX-PN and holding a state license.",
    related: ["rn", "medical-assistant", "home-health-aide"],
  },
  "nurse-practitioner": {
    soc: "29-1171",
    payLow: 101340,
    payHigh: 174420,
    numJobs: 323040,
    whatTheyDo: "Diagnose and treat illnesses, order tests, and prescribe medication, often as a patient's main provider.",
    workSetting: "Clinics, hospitals, and private practices; steady patient contact.",
    hours: "Usually full-time; some evenings, weekends, and on-call.",
    skills: ["Clinical judgment", "Compassion", "Communication", "Leadership"],
    license: "Requires a state license and national certification in a specialty; nurses train as RNs first.",
    related: ["physician-assistant", "rn", "physician"],
  },
  "physician-assistant": {
    soc: "29-1071",
    payLow: 99380,
    payHigh: 190280,
    numJobs: 162150,
    whatTheyDo: "Examine, diagnose, and treat patients and prescribe medicine, working alongside physicians.",
    workSetting: "Clinics, hospitals, and surgical suites; steady, hands-on patient care.",
    hours: "Usually full-time; evenings, weekends, and on-call are common.",
    skills: ["Clinical judgment", "Compassion", "Communication", "Attention to detail"],
    license: "Requires passing a national exam and holding a state license.",
    related: ["nurse-practitioner", "physician", "rn"],
  },
  "pharmacist": {
    soc: "29-1051",
    payLow: 99290,
    payHigh: 174230,
    numJobs: 321970,
    whatTheyDo: "Dispense prescription medications, check for interactions, and counsel patients on safe use.",
    workSetting: "Pharmacies and hospitals; mostly standing, behind a counter or in a lab.",
    hours: "Full-time and part-time; evenings, weekends, and holidays in retail.",
    skills: ["Attention to detail", "Communication", "Analytical skills", "Patience"],
    license: "Requires a Doctor of Pharmacy degree, national exams, and a state license.",
    related: ["pharmacy-tech", "physician", "clinical-lab-tech"],
  },
  "pharmacy-tech": {
    soc: "29-2052",
    payLow: 36020,
    payHigh: 61040,
    numJobs: 471680,
    whatTheyDo: "Fill prescriptions, measure medications, and manage inventory under a pharmacist's supervision.",
    workSetting: "Retail and hospital pharmacies; standing behind a counter, steady pace.",
    hours: "Full-time and part-time; evenings and weekends are common.",
    skills: ["Attention to detail", "Math skills", "Customer service", "Organization"],
    license: "Many states require registration or certification; requirements vary.",
    related: ["pharmacist", "medical-assistant", "phlebotomist"],
  },
  "dental-hygienist": {
    soc: "29-1292",
    payLow: 74880,
    payHigh: 126050,
    numJobs: 222740,
    whatTheyDo: "Clean teeth, take X-rays, screen for oral disease, and teach patients how to care for their mouths.",
    workSetting: "Dental offices; seated chairside, close, detailed work with protective gear.",
    hours: "Full-time or part-time; flexible schedules are common.",
    skills: ["Manual dexterity", "Attention to detail", "Compassion", "Communication"],
    license: "Requires graduating from an accredited program and holding a state license.",
    related: ["dental-assistant", "dentist", "radiologic-tech"],
  },
  "dental-assistant": {
    soc: "31-9091",
    payLow: 37130,
    payHigh: 62250,
    numJobs: 387790,
    whatTheyDo: "Prepare patients and instruments, assist the dentist chairside, and handle records and scheduling.",
    workSetting: "Dental offices; chairside, on your feet, close hands-on work.",
    hours: "Full-time and part-time; some evenings and weekends.",
    skills: ["Manual dexterity", "Attention to detail", "Organization", "Customer service"],
    license: "Requirements vary by state; some duties require certification or registration.",
    related: ["dental-hygienist", "medical-assistant", "surgical-tech"],
  },
  "medical-assistant": {
    soc: "31-9092",
    payLow: 36050,
    payHigh: 59310,
    numJobs: 817870,
    whatTheyDo: "Take vital signs, record histories, prepare patients, and handle clerical tasks in clinics and offices.",
    workSetting: "Doctors' offices and clinics; on your feet, steady patient contact.",
    hours: "Usually full-time; some evenings and weekends.",
    skills: ["Compassion", "Attention to detail", "Communication", "Organization"],
    license: "No license required in most states; certification such as CMA or RMA helps.",
    related: ["phlebotomist", "lpn", "pharmacy-tech"],
  },
  "emt": {
    soc: "29-2042",
    payLow: 34130,
    payHigh: 62500,
    numJobs: 180510,
    whatTheyDo: "Respond to emergencies, give basic life-saving care, and transport patients to hospitals.",
    workSetting: "Ambulances and emergency scenes; outdoors, indoors, high-stress, physical.",
    hours: "Long shifts including nights, weekends, and holidays; on-call.",
    skills: ["Composure", "Physical stamina", "Compassion", "Quick decisions"],
    license: "Requires state certification or licensure after an approved training course.",
    related: ["paramedic", "firefighter", "dispatcher"],
  },
  "paramedic": {
    soc: "29-2043",
    payLow: 44230,
    payHigh: 84850,
    numJobs: 100610,
    whatTheyDo: "Deliver advanced emergency medical care, including medications and airway support, before and during transport.",
    workSetting: "Ambulances and emergency scenes; high-stress, physical, all conditions.",
    hours: "Long shifts including nights, weekends, and holidays; on-call.",
    skills: ["Clinical judgment", "Composure", "Physical stamina", "Communication"],
    license: "Requires completing an accredited program and holding state licensure.",
    related: ["emt", "firefighter", "rn"],
  },
  "radiologic-tech": {
    soc: "29-2034",
    payLow: 55980,
    payHigh: 118660,
    numJobs: 230490,
    whatTheyDo: "Position patients and operate imaging equipment to produce X-rays and other scans for diagnosis.",
    workSetting: "Hospitals and imaging centers; on your feet, moving equipment and patients.",
    hours: "Full-time; evenings, weekends, and on-call in hospitals.",
    skills: ["Attention to detail", "Technical skills", "Compassion", "Physical stamina"],
    license: "Most states require a license or certification to practice.",
    related: ["sonographer", "surgical-tech", "clinical-lab-tech"],
  },
  "sonographer": {
    soc: "29-2032",
    payLow: 67820,
    payHigh: 129370,
    numJobs: 90160,
    whatTheyDo: "Operate ultrasound equipment to create images of organs and tissues that help doctors diagnose conditions.",
    workSetting: "Hospitals and clinics; dim rooms, standing and moving patients.",
    hours: "Full-time; some evenings, weekends, and on-call.",
    skills: ["Attention to detail", "Hand-eye coordination", "Compassion", "Technical skills"],
    license: "No universal license; most employers require professional certification.",
    related: ["radiologic-tech", "clinical-lab-tech", "respiratory-therapist"],
  },
  "respiratory-therapist": {
    soc: "29-1126",
    payLow: 63660,
    payHigh: 118050,
    numJobs: 139790,
    whatTheyDo: "Treat patients who have trouble breathing, managing ventilators, oxygen, and lung therapies.",
    workSetting: "Hospitals, especially intensive and emergency care; on your feet, hands-on.",
    hours: "Often long shifts including nights, weekends, and holidays.",
    skills: ["Clinical judgment", "Compassion", "Attention to detail", "Composure"],
    license: "Requires certification and a state license in nearly every state.",
    related: ["rn", "radiologic-tech", "surgical-tech"],
  },
  "physical-therapist": {
    soc: "29-1123",
    payLow: 77140,
    payHigh: 135140,
    numJobs: 267330,
    whatTheyDo: "Guide patients through exercises and treatments to recover movement and manage pain after injury or illness.",
    workSetting: "Clinics, hospitals, and homes; active, hands-on, on your feet.",
    hours: "Usually full-time; some evenings and weekends.",
    skills: ["Compassion", "Physical stamina", "Communication", "Attention to detail"],
    license: "Requires a doctoral degree, a national exam, and a state license.",
    related: ["pta", "occupational-therapist", "massage-therapist"],
  },
  "pta": {
    soc: "31-2021",
    whatTheyDo: "Carry out physical therapy plans, guiding patients through exercises and treatments under a therapist's direction.",
    workSetting: "Clinics, hospitals, and homes; active, hands-on, on your feet.",
    hours: "Full-time and part-time; some evenings and weekends.",
    skills: ["Compassion", "Physical stamina", "Communication", "Attention to detail"],
    license: "Most states require a license after an accredited associate program and exam.",
    related: ["physical-therapist", "ota", "massage-therapist"],
  },
  "occupational-therapist": {
    soc: "29-1122",
    whatTheyDo: "Help people regain the skills for daily living and working after injury, illness, or disability.",
    workSetting: "Hospitals, schools, clinics, and homes; hands-on, active work.",
    hours: "Usually full-time; some evenings and weekends.",
    skills: ["Compassion", "Patience", "Communication", "Problem solving"],
    license: "Requires a master's degree, a national exam, and a state license.",
    related: ["ota", "physical-therapist", "social-worker"],
  },
  "ota": {
    soc: "31-2011",
    whatTheyDo: "Carry out occupational therapy plans, helping patients practice daily-living and work skills.",
    workSetting: "Clinics, schools, and nursing homes; hands-on, active, on your feet.",
    hours: "Full-time and part-time; some evenings and weekends.",
    skills: ["Compassion", "Patience", "Communication", "Physical stamina"],
    license: "Most states require a license after an accredited associate program and exam.",
    related: ["occupational-therapist", "pta", "home-health-aide"],
  },
  "home-health-aide": {
    soc: "31-1121",
    whatTheyDo: "Help clients with daily tasks such as bathing, dressing, meals, and light medical support in their homes.",
    workSetting: "Clients' homes; hands-on, physical, often traveling between visits.",
    hours: "Full-time and part-time; nights, weekends, and irregular hours.",
    skills: ["Compassion", "Patience", "Physical stamina", "Dependability"],
    license: "No license required; some settings require brief training or certification.",
    related: ["medical-assistant", "lpn", "childcare-worker"],
  },
  "phlebotomist": {
    soc: "31-9097",
    whatTheyDo: "Draw blood from patients for tests, donations, and transfusions, then label and prepare samples.",
    workSetting: "Hospitals, labs, and clinics; standing, close patient contact.",
    hours: "Full-time and part-time; some early mornings, evenings, and weekends.",
    skills: ["Manual dexterity", "Compassion", "Attention to detail", "Steady hands"],
    license: "No license in most states; certification is often preferred by employers.",
    related: ["medical-assistant", "clinical-lab-tech", "pharmacy-tech"],
  },
  "surgical-tech": {
    soc: "29-2055",
    whatTheyDo: "Prepare operating rooms, sterilize instruments, and hand tools to surgeons during operations.",
    workSetting: "Operating rooms; sterile, fast-paced, standing for long stretches.",
    hours: "Full-time; on-call, nights, and weekends are common.",
    skills: ["Attention to detail", "Composure", "Manual dexterity", "Stamina"],
    license: "No universal license; most employers require certification.",
    related: ["radiologic-tech", "respiratory-therapist", "dental-assistant"],
  },
  "veterinarian": {
    soc: "29-1131",
    whatTheyDo: "Diagnose and treat illness and injury in animals, perform surgery, and advise owners on care.",
    workSetting: "Clinics, farms, and hospitals; hands-on with animals, sometimes outdoors.",
    hours: "Often long hours; nights, weekends, and emergency calls.",
    skills: ["Compassion", "Manual dexterity", "Problem solving", "Communication"],
    license: "Requires a veterinary doctoral degree and a state license.",
    related: ["vet-tech", "physician", "clinical-lab-tech"],
  },
  "vet-tech": {
    soc: "29-2056",
    whatTheyDo: "Assist veterinarians by running lab tests, taking X-rays, and providing nursing care to animals.",
    workSetting: "Veterinary clinics and hospitals; hands-on with animals, standing.",
    hours: "Full-time and part-time; nights, weekends, and holidays.",
    skills: ["Compassion", "Manual dexterity", "Attention to detail", "Patience"],
    license: "Most states require credentialing by exam after an accredited program.",
    related: ["veterinarian", "medical-assistant", "clinical-lab-tech"],
  },
  "physician": {
    soc: "29-1215",
    whatTheyDo: "Examine patients, diagnose illness, prescribe treatment, and manage long-term health as a primary doctor.",
    workSetting: "Clinics and hospitals; steady patient contact, some on your feet.",
    hours: "Long hours; on-call, nights, and weekends are common.",
    skills: ["Clinical judgment", "Compassion", "Communication", "Stamina"],
    license: "Requires medical school, residency, national exams, and a state license.",
    related: ["physician-assistant", "nurse-practitioner", "pharmacist"],
  },
  "dentist": {
    soc: "29-1021",
    whatTheyDo: "Diagnose and treat problems with teeth and gums, from fillings and extractions to running the practice.",
    workSetting: "Dental offices; seated chairside, close, detailed hands-on work.",
    hours: "Usually full-time; some evenings and weekends, often regular.",
    skills: ["Manual dexterity", "Attention to detail", "Communication", "Business sense"],
    license: "Requires a dental doctoral degree, national exams, and a state license.",
    related: ["dental-hygienist", "optometrist", "physician"],
  },
  "optometrist": {
    soc: "29-1041",
    whatTheyDo: "Examine eyes, diagnose vision problems and disease, and prescribe glasses, contacts, and treatments.",
    workSetting: "Offices and clinics; seated, close patient work, regular pace.",
    hours: "Usually full-time; often regular hours, some weekends.",
    skills: ["Attention to detail", "Communication", "Analytical skills", "Compassion"],
    license: "Requires a doctor of optometry degree, national exams, and a state license.",
    related: ["dentist", "physician", "pharmacist"],
  },
  "software-developer": {
    soc: "15-1252",
    whatTheyDo: "Design, build, and test the programs and applications that run on computers and phones.",
    workSetting: "Offices or remote; at a desk, much of the day at a screen.",
    hours: "Usually full-time; crunch periods near deadlines.",
    skills: ["Problem solving", "Analytical thinking", "Attention to detail", "Communication"],
    license: "No license required; a portfolio and demonstrated skill matter most.",
    related: ["web-developer", "data-scientist", "infosec-analyst"],
  },
  "web-developer": {
    soc: "15-1254",
    whatTheyDo: "Build and maintain websites, writing the code and layouts that make pages work and look right.",
    workSetting: "Offices or remote; at a desk, most of the day at a screen.",
    hours: "Usually full-time; some freelance and deadline crunch.",
    skills: ["Creativity", "Attention to detail", "Problem solving", "Communication"],
    license: "No license required; a portfolio is the main credential.",
    related: ["software-developer", "graphic-designer", "it-support"],
  },
  "infosec-analyst": {
    soc: "15-1212",
    whatTheyDo: "Protect an organization's networks and data by monitoring for threats and responding to breaches.",
    workSetting: "Offices or remote; at a desk, watching systems and logs.",
    hours: "Usually full-time; on-call for security incidents.",
    skills: ["Analytical thinking", "Attention to detail", "Problem solving", "Ingenuity"],
    license: "No license required; certifications carry real weight with employers.",
    related: ["it-support", "software-developer", "sysadmin"],
  },
  "data-scientist": {
    soc: "15-2051",
    whatTheyDo: "Collect, clean, and analyze large sets of data, then build models to find patterns and guide decisions.",
    workSetting: "Offices or remote; at a desk, most of the day at a screen.",
    hours: "Usually full-time.",
    skills: ["Analytical thinking", "Math skills", "Problem solving", "Communication"],
    license: "No license required; skills and a project portfolio matter most.",
    related: ["statistician", "software-developer", "financial-analyst"],
  },
  "sysadmin": {
    soc: "15-1244",
    whatTheyDo: "Set up, maintain, and secure the servers, networks, and systems an organization runs on.",
    workSetting: "Offices and data centers; at a desk, sometimes in server rooms.",
    hours: "Full-time; on-call for outages, some nights and weekends.",
    skills: ["Problem solving", "Attention to detail", "Communication", "Technical skills"],
    license: "No license required; certifications help, especially in cloud platforms.",
    related: ["it-support", "database-admin", "infosec-analyst"],
  },
  "it-support": {
    soc: "15-1232",
    whatTheyDo: "Help users solve computer and network problems, set up equipment, and answer technical questions.",
    workSetting: "Offices, help desks, or remote; at a desk or moving to workstations.",
    hours: "Full-time; shift work and on-call for round-the-clock support.",
    skills: ["Problem solving", "Patience", "Communication", "Technical skills"],
    license: "No license required; entry-level certifications help you get hired.",
    related: ["sysadmin", "infosec-analyst", "web-developer"],
  },
  "database-admin": {
    soc: "15-1242",
    whatTheyDo: "Organize, secure, and maintain the databases that store an organization's information, keeping them running fast.",
    workSetting: "Offices or remote; at a desk, most of the day at a screen.",
    hours: "Full-time; on-call for outages, some nights and weekends.",
    skills: ["Analytical thinking", "Attention to detail", "Problem solving", "Communication"],
    license: "No license required; vendor certifications are valued.",
    related: ["sysadmin", "data-scientist", "software-developer"],
  },
  "accountant": {
    soc: "13-2011",
    whatTheyDo: "Prepare and examine financial records, ensure accuracy, and handle taxes and reporting for people and organizations.",
    workSetting: "Offices or remote; at a desk, busier during tax and closing periods.",
    hours: "Full-time; long hours during tax season and year-end.",
    skills: ["Attention to detail", "Math skills", "Analytical thinking", "Integrity"],
    license: "No license to start; the CPA credential opens higher-level roles.",
    related: ["bookkeeper", "financial-analyst", "actuary"],
  },
  "bookkeeper": {
    soc: "43-3031",
    whatTheyDo: "Record daily financial transactions, reconcile accounts, and keep an organization's books accurate and current.",
    workSetting: "Offices or remote; at a desk, steady detail work.",
    hours: "Full-time and part-time; fairly regular hours.",
    skills: ["Attention to detail", "Math skills", "Organization", "Integrity"],
    license: "No license required; certification can help you stand out.",
    related: ["accountant", "admin-assistant", "financial-analyst"],
  },
  "financial-analyst": {
    soc: "13-2051",
    whatTheyDo: "Study financial data and market trends to guide companies and investors on money decisions.",
    workSetting: "Offices or remote; at a desk, much of the day in spreadsheets.",
    hours: "Full-time; long hours are common in some firms.",
    skills: ["Analytical thinking", "Math skills", "Attention to detail", "Communication"],
    license: "No license to start; some roles require securities licenses or the CFA.",
    related: ["accountant", "financial-advisor", "actuary"],
  },
  "financial-advisor": {
    soc: "13-2052",
    whatTheyDo: "Help people plan their finances, from budgeting and saving to investing and retirement.",
    workSetting: "Offices, client meetings, or remote; steady contact with clients.",
    hours: "Full-time; evenings and weekends to meet clients.",
    skills: ["Communication", "Analytical thinking", "Sales ability", "Integrity"],
    license: "Selling investments or insurance requires passing licensing exams.",
    related: ["financial-analyst", "insurance-agent", "accountant"],
  },
  "actuary": {
    soc: "15-2011",
    whatTheyDo: "Use math and statistics to measure financial risk, pricing insurance and pensions so they stay sound.",
    workSetting: "Offices or remote; at a desk, deep in data and models.",
    hours: "Usually full-time; regular hours with study time for exams.",
    skills: ["Math skills", "Analytical thinking", "Problem solving", "Attention to detail"],
    license: "Advancement comes through a series of professional certification exams.",
    related: ["statistician", "financial-analyst", "accountant"],
  },
  "hr-specialist": {
    soc: "13-1071",
    whatTheyDo: "Recruit, screen, and hire workers, and handle pay, benefits, and employee questions.",
    workSetting: "Offices or remote; at a desk, plenty of meetings and interviews.",
    hours: "Usually full-time; regular hours.",
    skills: ["Communication", "Organization", "Decision making", "Discretion"],
    license: "No license required; professional certifications can help advancement.",
    related: ["admin-assistant", "management-analyst", "customer-service"],
  },
  "marketing-manager": {
    soc: "11-2021",
    whatTheyDo: "Plan and direct campaigns that promote products and services, and lead the teams that create them.",
    workSetting: "Offices or remote; at a desk with frequent meetings.",
    hours: "Full-time; long hours around launches and deadlines.",
    skills: ["Creativity", "Communication", "Analytical thinking", "Leadership"],
    license: "No license required; a track record of results matters most.",
    related: ["graphic-designer", "management-analyst", "financial-analyst"],
  },
  "management-analyst": {
    soc: "13-1111",
    whatTheyDo: "Study how organizations work and recommend changes to cut costs and improve efficiency.",
    workSetting: "Offices, client sites, or remote; travel to clients is common.",
    hours: "Full-time; long hours and travel around projects.",
    skills: ["Analytical thinking", "Communication", "Problem solving", "Time management"],
    license: "No license required; certification can help, but results matter most.",
    related: ["financial-analyst", "logistician", "marketing-manager"],
  },
  "insurance-agent": {
    soc: "41-3021",
    whatTheyDo: "Sell insurance policies, explain coverage options, and help clients file and manage claims.",
    workSetting: "Offices, client visits, or remote; steady contact with people.",
    hours: "Full-time; evenings and weekends to meet clients.",
    skills: ["Sales ability", "Communication", "Self-motivation", "Customer service"],
    license: "Requires a state license, earned by exam, for each line of insurance sold.",
    related: ["financial-advisor", "real-estate-agent", "customer-service"],
  },
  "real-estate-agent": {
    soc: "41-9022",
    whatTheyDo: "Help clients buy, sell, and rent property, showing homes and guiding them through the paperwork.",
    workSetting: "On the road and at properties; showings, open houses, and offices.",
    hours: "Irregular; evenings and weekends are the busiest.",
    skills: ["Sales ability", "Communication", "Self-motivation", "Local knowledge"],
    license: "Requires a state license, earned by coursework and exam.",
    related: ["insurance-agent", "financial-advisor", "construction-manager"],
  },
  "paralegal": {
    soc: "23-2011",
    whatTheyDo: "Support lawyers by researching cases, drafting documents, and organizing evidence and files.",
    workSetting: "Law offices or remote; at a desk, detailed research and writing.",
    hours: "Full-time; overtime around trials and deadlines.",
    skills: ["Research skills", "Attention to detail", "Organization", "Writing"],
    license: "No license required; a certificate or degree is the usual path.",
    related: ["lawyer", "admin-assistant", "hr-specialist"],
  },
  "admin-assistant": {
    soc: "43-6014",
    whatTheyDo: "Keep an office running by scheduling, managing records, handling communication, and supporting staff.",
    workSetting: "Offices or remote; at a desk, juggling many small tasks.",
    hours: "Usually full-time; regular business hours.",
    skills: ["Organization", "Communication", "Time management", "Attention to detail"],
    license: "No license required; software skills matter most.",
    related: ["customer-service", "bookkeeper", "hr-specialist"],
  },
  "customer-service": {
    soc: "43-4051",
    whatTheyDo: "Answer questions, resolve complaints, and help customers with orders, accounts, and products.",
    workSetting: "Call centers, offices, or remote; at a desk with headset or chat.",
    hours: "Full-time and part-time; shifts including evenings and weekends.",
    skills: ["Communication", "Patience", "Problem solving", "Empathy"],
    license: "No license required; on-the-job training is standard.",
    related: ["admin-assistant", "insurance-agent", "hr-specialist"],
  },
  "logistician": {
    soc: "13-1081",
    whatTheyDo: "Manage the supply chain, coordinating how products are bought, stored, and moved from source to customer.",
    workSetting: "Offices, warehouses, and plants; at a desk and on the floor.",
    hours: "Full-time; some long hours to keep shipments moving.",
    skills: ["Organization", "Problem solving", "Communication", "Attention to detail"],
    license: "No license required; certification can help advancement.",
    related: ["management-analyst", "truck-driver", "industrial-engineer"],
  },
  "lawyer": {
    soc: "23-1011",
    whatTheyDo: "Advise and represent clients in legal matters, research the law, draft documents, and argue cases.",
    workSetting: "Offices and courtrooms; at a desk researching, some travel to court.",
    hours: "Full-time; long hours are common.",
    skills: ["Analytical thinking", "Research skills", "Persuasion", "Writing"],
    license: "Requires a law degree and passing the state bar exam.",
    related: ["paralegal", "management-analyst", "social-worker"],
  },
  "teacher-elementary": {
    soc: "25-2021",
    whatTheyDo: "Teach young students core subjects, manage the classroom, and track each child's progress.",
    workSetting: "Elementary classrooms; on your feet, active with children all day.",
    hours: "School hours plus grading and prep; summers often off.",
    skills: ["Patience", "Communication", "Creativity", "Organization"],
    license: "Public school teaching requires a state license or certification.",
    related: ["teacher-assistant", "teacher-hs", "childcare-worker"],
  },
  "teacher-hs": {
    soc: "25-2031",
    whatTheyDo: "Teach a subject to teenagers, plan lessons, grade work, and prepare students for what comes next.",
    workSetting: "High school classrooms; on your feet, active, with older students.",
    hours: "School hours plus grading, prep, and activities; summers often off.",
    skills: ["Subject expertise", "Communication", "Patience", "Organization"],
    license: "Public school teaching requires a state license or certification.",
    related: ["teacher-elementary", "school-counselor", "teacher-assistant"],
  },
  "teacher-assistant": {
    soc: "25-9045",
    whatTheyDo: "Support the lead teacher by helping students, preparing materials, and supervising the classroom.",
    workSetting: "Classrooms; on your feet, hands-on with students.",
    hours: "School hours; often part-time, summers off.",
    skills: ["Patience", "Communication", "Reliability", "Adaptability"],
    license: "No license required; some roles need an assessment or associate degree.",
    related: ["teacher-elementary", "childcare-worker", "teacher-hs"],
  },
  "school-counselor": {
    soc: "21-1012",
    whatTheyDo: "Help students with academic plans, college and career choices, and personal or social challenges.",
    workSetting: "Schools; offices and classrooms, steady contact with students.",
    hours: "School hours; some summer and evening work.",
    skills: ["Empathy", "Communication", "Listening", "Problem solving"],
    license: "Public schools require a state credential, usually with a master's degree.",
    related: ["social-worker", "teacher-hs", "teacher-elementary"],
  },
  "social-worker": {
    soc: "21-1021",
    whatTheyDo: "Help people cope with challenges, connecting them to resources and services and advocating for their needs.",
    workSetting: "Offices, schools, homes, and hospitals; travel to clients is common.",
    hours: "Full-time; some evenings, weekends, and on-call.",
    skills: ["Empathy", "Communication", "Organization", "Emotional resilience"],
    license: "Clinical roles require a state license; many positions need a social work degree.",
    related: ["school-counselor", "occupational-therapist", "home-health-aide"],
  },
  "childcare-worker": {
    soc: "39-9011",
    whatTheyDo: "Care for and supervise young children, leading play and learning while keeping them safe.",
    workSetting: "Daycares, homes, and preschools; on your feet, active with children.",
    hours: "Full-time and part-time; early mornings and long days are common.",
    skills: ["Patience", "Communication", "Physical stamina", "Nurturing nature"],
    license: "No license for workers, though programs and some states require training.",
    related: ["teacher-assistant", "teacher-elementary", "home-health-aide"],
  },
  "librarian": {
    soc: "25-4022",
    whatTheyDo: "Help people find information, manage collections, and run programs and services in a library.",
    workSetting: "Libraries; at desks and among shelves, steady public contact.",
    hours: "Full-time and part-time; some evenings and weekends.",
    skills: ["Research skills", "Communication", "Organization", "Patience"],
    license: "Most roles require a master's in library science; some states certify school librarians.",
    related: ["teacher-hs", "interpreter", "admin-assistant"],
  },
  "interpreter": {
    soc: "27-3091",
    whatTheyDo: "Convert speech or writing from one language to another so people can understand each other.",
    workSetting: "Courts, hospitals, schools, and remote; varies widely by assignment.",
    hours: "Often freelance and irregular; some full-time staff roles.",
    skills: ["Bilingual fluency", "Listening", "Cultural knowledge", "Concentration"],
    license: "No universal license; court and medical work often require certification.",
    related: ["teacher-hs", "librarian", "social-worker"],
  },
  "police-officer": {
    soc: "33-3051",
    whatTheyDo: "Patrol communities, respond to calls, enforce laws, and investigate crimes to keep people safe.",
    workSetting: "Streets, vehicles, and stations; outdoors and in, physical and unpredictable.",
    hours: "Shift work including nights, weekends, holidays, and on-call.",
    skills: ["Composure", "Physical stamina", "Communication", "Sound judgment"],
    license: "Requires completing a police academy and meeting state certification standards.",
    related: ["correctional-officer", "firefighter", "dispatcher"],
  },
  "firefighter": {
    soc: "33-2011",
    whatTheyDo: "Respond to fires and emergencies, rescue people, and provide first aid while protecting property.",
    workSetting: "Fire stations and emergency scenes; physical, dangerous, all conditions.",
    hours: "Long shifts, often twenty-four hours on, then off; nights and holidays.",
    skills: ["Physical strength", "Composure", "Teamwork", "Quick decisions"],
    license: "Requires training and certification; EMT or paramedic credentials give an edge.",
    related: ["emt", "paramedic", "police-officer"],
  },
  "correctional-officer": {
    soc: "33-3012",
    whatTheyDo: "Supervise and maintain order among people who are in jail or prison, enforcing rules and keeping them safe.",
    workSetting: "Jails and prisons; indoors, secure, sometimes tense environments.",
    hours: "Shift work including nights, weekends, holidays, and overtime.",
    skills: ["Composure", "Physical stamina", "Communication", "Sound judgment"],
    license: "Requires training and state certification; no college degree needed.",
    related: ["police-officer", "dispatcher", "firefighter"],
  },
  "air-traffic-controller": {
    soc: "53-2021",
    whatTheyDo: "Direct aircraft safely on the ground and in the air, coordinating takeoffs, landings, and routes.",
    workSetting: "Control towers and radar centers; intense focus at screens and windows.",
    hours: "Shift work including nights, weekends, and holidays; rotating schedules.",
    skills: ["Concentration", "Quick decisions", "Communication", "Composure"],
    license: "Requires FAA training and certification; there is an age limit to enter.",
    related: ["airline-pilot", "commercial-pilot", "dispatcher"],
  },
  "postal-worker": {
    soc: "43-5052",
    whatTheyDo: "Sort and deliver mail and packages along routes, and serve customers at the counter.",
    workSetting: "Post offices, trucks, and streets; on your feet, outdoors in all weather.",
    hours: "Full-time and part-time; early mornings, weekends, and holidays.",
    skills: ["Physical stamina", "Reliability", "Organization", "Customer service"],
    license: "No license required beyond a driver's license for routes.",
    related: ["delivery-driver", "truck-driver", "admin-assistant"],
  },
  "civil-engineer": {
    soc: "17-2051",
    whatTheyDo: "Design and oversee the roads, bridges, water systems, and buildings that communities rely on.",
    workSetting: "Offices and construction sites; a mix of desk work and field visits.",
    hours: "Usually full-time; some long hours near project deadlines.",
    skills: ["Math skills", "Problem solving", "Communication", "Attention to detail"],
    license: "A Professional Engineer license is required to approve public projects.",
    related: ["construction-manager", "architect", "urban-planner"],
  },
  "mechanical-engineer": {
    soc: "17-2141",
    whatTheyDo: "Design, build, and test machines and mechanical systems, from engines to tools to devices.",
    workSetting: "Offices and labs; desk design work plus testing and site visits.",
    hours: "Usually full-time; some long hours near deadlines.",
    skills: ["Math skills", "Problem solving", "Creativity", "Attention to detail"],
    license: "A Professional Engineer license helps for senior and public-facing roles.",
    related: ["electrical-engineer", "industrial-engineer", "civil-engineer"],
  },
  "electrical-engineer": {
    soc: "17-2071",
    whatTheyDo: "Design and test electrical equipment and systems, from power grids to electronics and chips.",
    workSetting: "Offices and labs; desk design work plus testing and field visits.",
    hours: "Usually full-time; some long hours near deadlines.",
    skills: ["Math skills", "Problem solving", "Analytical thinking", "Attention to detail"],
    license: "A Professional Engineer license helps for senior and public-facing roles.",
    related: ["mechanical-engineer", "electrician", "industrial-engineer"],
  },
  "industrial-engineer": {
    soc: "17-2112",
    whatTheyDo: "Find better ways to make things by improving how people, machines, and materials work together.",
    workSetting: "Factories, offices, and warehouses; floor observation plus desk analysis.",
    hours: "Usually full-time; some long hours near deadlines.",
    skills: ["Analytical thinking", "Problem solving", "Communication", "Attention to detail"],
    license: "A Professional Engineer license helps for senior roles.",
    related: ["mechanical-engineer", "logistician", "construction-manager"],
  },
  "architect": {
    soc: "17-1011",
    whatTheyDo: "Design buildings, plan how spaces work and look, and guide projects from drawings to construction.",
    workSetting: "Offices and construction sites; desk design plus field visits.",
    hours: "Usually full-time; long hours near deadlines.",
    skills: ["Creativity", "Visualization", "Communication", "Attention to detail"],
    license: "Requires a degree, an internship period, and passing licensing exams.",
    related: ["civil-engineer", "urban-planner", "construction-manager"],
  },
  "construction-manager": {
    soc: "11-9021",
    whatTheyDo: "Plan, budget, and oversee construction projects, coordinating crews, schedules, and safety on site.",
    workSetting: "Construction sites and field offices; outdoors and in, on your feet.",
    hours: "Full-time; long hours and on-call to keep projects on track.",
    skills: ["Leadership", "Organization", "Problem solving", "Communication"],
    license: "No license required; certification and field experience carry weight.",
    related: ["civil-engineer", "carpenter", "architect"],
  },
  "environmental-scientist": {
    soc: "19-2041",
    whatTheyDo: "Study the environment to protect human health, testing samples and advising on pollution and cleanup.",
    workSetting: "Labs, offices, and outdoor field sites; travel to sites is common.",
    hours: "Usually full-time; fieldwork can mean travel and irregular hours.",
    skills: ["Analytical thinking", "Problem solving", "Communication", "Attention to detail"],
    license: "No license required in general; some specialties value certification.",
    related: ["chemist", "urban-planner", "civil-engineer"],
  },
  "chemist": {
    soc: "19-2031",
    whatTheyDo: "Study substances at the molecular level to develop products, run tests, and solve problems.",
    workSetting: "Labs and offices; bench work with instruments and safety gear.",
    hours: "Usually full-time; regular hours, some longer around experiments.",
    skills: ["Analytical thinking", "Attention to detail", "Problem solving", "Math skills"],
    license: "No license required; advanced degrees open research roles.",
    related: ["clinical-lab-tech", "environmental-scientist", "pharmacist"],
  },
  "clinical-lab-tech": {
    soc: "29-2011",
    whatTheyDo: "Run tests on blood, tissue, and other samples to help doctors diagnose and treat disease.",
    workSetting: "Hospital and clinical labs; at a bench with instruments and samples.",
    hours: "Full-time; shifts including nights, weekends, and holidays.",
    skills: ["Attention to detail", "Technical skills", "Analytical thinking", "Dexterity"],
    license: "Some states require a license; certification is widely expected.",
    related: ["phlebotomist", "radiologic-tech", "chemist"],
  },
  "statistician": {
    soc: "15-2041",
    whatTheyDo: "Design studies and analyze data using math to help organizations understand results and make decisions.",
    workSetting: "Offices or remote; at a desk, most of the day in data.",
    hours: "Usually full-time; regular hours.",
    skills: ["Math skills", "Analytical thinking", "Problem solving", "Communication"],
    license: "No license required; advanced degrees are standard.",
    related: ["data-scientist", "actuary", "financial-analyst"],
  },
  "urban-planner": {
    soc: "19-3051",
    whatTheyDo: "Plan how land is used in communities, guiding housing, transportation, and development for growth.",
    workSetting: "Offices, public meetings, and site visits; a mix of desk and field.",
    hours: "Usually full-time; evening public meetings are common.",
    skills: ["Analytical thinking", "Communication", "Problem solving", "Negotiation"],
    license: "No license required in most states; professional certification is valued.",
    related: ["architect", "civil-engineer", "environmental-scientist"],
  },
  "graphic-designer": {
    soc: "27-1024",
    whatTheyDo: "Create visual designs, from logos to layouts, that communicate ideas for print and screen.",
    workSetting: "Offices, studios, or remote; at a desk, most of the day at a screen.",
    hours: "Full-time and freelance; deadline crunch is common.",
    skills: ["Creativity", "Attention to detail", "Communication", "Software skills"],
    license: "No license required; a strong portfolio is the credential.",
    related: ["web-developer", "marketing-manager", "technical-writer"],
  },
  "technical-writer": {
    soc: "27-3042",
    whatTheyDo: "Turn complex information into clear guides, manuals, and instructions people can actually use.",
    workSetting: "Offices or remote; at a desk, writing and researching.",
    hours: "Usually full-time; some deadline pressure.",
    skills: ["Writing", "Attention to detail", "Communication", "Technical aptitude"],
    license: "No license required; writing samples matter most.",
    related: ["graphic-designer", "web-developer", "software-developer"],
  },
  "chef": {
    soc: "35-1011",
    whatTheyDo: "Plan menus, direct the kitchen, and prepare food while managing cooks, costs, and quality.",
    workSetting: "Restaurant and hotel kitchens; hot, fast-paced, on your feet.",
    hours: "Long hours including early mornings, nights, weekends, and holidays.",
    skills: ["Creativity", "Leadership", "Time management", "Physical stamina"],
    license: "No license required; food safety certification is often expected.",
    related: ["cook", "barber-cosmetologist", "customer-service"],
  },
  "cook": {
    soc: "35-2014",
    whatTheyDo: "Prepare and cook food to order, following recipes and keeping the kitchen clean and stocked.",
    workSetting: "Restaurant and cafeteria kitchens; hot, fast-paced, on your feet.",
    hours: "Full-time and part-time; nights, weekends, and holidays.",
    skills: ["Speed", "Attention to detail", "Physical stamina", "Teamwork"],
    license: "No license required; food safety training is often provided.",
    related: ["chef", "delivery-driver", "customer-service"],
  },
  "barber-cosmetologist": {
    soc: "39-5012",
    whatTheyDo: "Cut, color, and style hair, and provide grooming and beauty services for clients.",
    workSetting: "Salons and barbershops; on your feet, close hands-on work.",
    hours: "Full-time and part-time; evenings and weekends are busiest.",
    skills: ["Manual dexterity", "Creativity", "Customer service", "Stamina"],
    license: "Requires a state license, earned by training hours and an exam.",
    related: ["massage-therapist", "chef", "customer-service"],
  },
  "massage-therapist": {
    soc: "31-9011",
    whatTheyDo: "Treat clients by manipulating muscles and soft tissue to ease pain, stress, and injury.",
    workSetting: "Spas, clinics, and studios; quiet rooms, hands-on, on your feet.",
    hours: "Full-time and part-time; evenings and weekends are common.",
    skills: ["Physical stamina", "Empathy", "Communication", "Manual dexterity"],
    license: "Most states require a license after training and an exam.",
    related: ["pta", "barber-cosmetologist", "physical-therapist"],
  },
  "truck-driver": {
    soc: "53-3032",
    whatTheyDo: "Drive tractor-trailers over long distances to deliver goods, keeping logs and inspecting the rig.",
    workSetting: "On the road for days at a time; long stretches alone in the cab.",
    hours: "Long, irregular hours; nights, weekends, and days away from home.",
    skills: ["Focus", "Stamina", "Independence", "Safe driving"],
    license: "Requires a commercial driver's license, earned by training and exams.",
    related: ["delivery-driver", "diesel-tech", "equipment-operator"],
  },
  "delivery-driver": {
    soc: "53-3033",
    whatTheyDo: "Drive routes to deliver packages and goods to homes and businesses, loading and tracking each stop.",
    workSetting: "On the road and at doorsteps; in and out of the vehicle, all weather.",
    hours: "Full-time and part-time; early starts, long days, some weekends.",
    skills: ["Safe driving", "Physical stamina", "Time management", "Customer service"],
    license: "A regular driver's license is enough for most routes; larger trucks need more.",
    related: ["truck-driver", "postal-worker", "cook"],
  },
  "airline-pilot": {
    soc: "53-2011",
    whatTheyDo: "Fly passengers and cargo on scheduled airline routes, planning flights and operating the aircraft safely.",
    workSetting: "Airliner cockpits; long stretches at the controls, nights away from home.",
    hours: "Irregular; nights, weekends, holidays, and multi-day trips.",
    skills: ["Focus", "Quick decisions", "Communication", "Composure"],
    license: "Requires FAA licensing, including an airline transport pilot certificate and medical clearance.",
    related: ["commercial-pilot", "air-traffic-controller", "flight-attendant"],
  },
  "commercial-pilot": {
    soc: "53-2012",
    whatTheyDo: "Fly aircraft for charter, cargo, medical, and other on-demand work outside scheduled airlines.",
    workSetting: "Cockpits of smaller aircraft and helicopters; varied, sometimes remote.",
    hours: "Irregular; on-call, nights, and weekends depending on the job.",
    skills: ["Focus", "Quick decisions", "Communication", "Composure"],
    license: "Requires an FAA commercial pilot certificate and medical clearance.",
    related: ["airline-pilot", "air-traffic-controller", "aircraft-mechanic"],
  },
  "flight-attendant": {
    soc: "53-2031",
    whatTheyDo: "Keep passengers safe and comfortable on flights, handling service, emergencies, and safety checks.",
    workSetting: "Aircraft cabins; on your feet, close quarters, frequent travel.",
    hours: "Irregular; nights, weekends, holidays, and days away from home.",
    skills: ["Customer service", "Composure", "Communication", "Stamina"],
    license: "Requires FAA certification earned through airline training.",
    related: ["airline-pilot", "customer-service", "dispatcher"],
  },
  "dispatcher": {
    soc: "43-5031",
    whatTheyDo: "Answer emergency calls, gather information, and send police, fire, or medical help to the scene.",
    workSetting: "Communication centers; at a desk with screens and headsets, high-stress.",
    hours: "Shift work including nights, weekends, and holidays.",
    skills: ["Composure", "Communication", "Multitasking", "Quick decisions"],
    license: "Requirements vary; many states require certification and training.",
    related: ["emt", "police-officer", "firefighter"],
  },
};

export function getCareerDetail(id: string): CareerDetail | undefined {
  return CAREER_DETAILS[id];
}
