// Compare Colleges data (July 2026 — the parked preview goes live; owner ask:
// "some are need blind, some aren't — some consider religious affiliation,
// some are more holistic than others").
//
// Every profile is drawn from the college's OWN published Common Data Set
// (section C7 "relative importance of factors"), admissions releases, and aid
// pages — the 2024–25 cycle unless a note says otherwise. Honesty rules, same
// bar as the scholarships list:
//   - Figures are year-tagged; admit rates move yearly, so a point or two of
//     difference is noise, not signal.
//   - A missing value (null) means the college doesn't publish it — render
//     "—", never invent a number. GPA is a free-text NOTE (weighting systems
//     differ too much for a sortable cross-school number to be honest).
//   - No rankings, ever (house rule): sort by published facts only.
// Re-verify each cycle like article figures. To add a college: fill what its
// CDS actually says and leave the rest null.

export type C7Rating = "very" | "important" | "considered" | "no";

export type FactorId =
  | "rigor"
  | "gpa"
  | "rank"
  | "essay"
  | "recs"
  | "interview"
  | "ecs"
  | "talent"
  | "character"
  | "firstGen"
  | "legacy"
  | "interest"
  | "religion"
  | "work";

export const FACTOR_LABELS: Record<FactorId, string> = {
  rigor: "Course rigor",
  gpa: "GPA",
  rank: "Class rank",
  essay: "Essays",
  recs: "Recommendations",
  interview: "Interview",
  ecs: "Extracurriculars",
  talent: "Talent / ability",
  character: "Character",
  firstGen: "First-gen status",
  legacy: "Legacy (family ties)",
  interest: "Demonstrated interest",
  religion: "Religious affiliation",
  work: "Work experience",
};

export const RATING_LABELS: Record<C7Rating, string> = {
  very: "Very important",
  important: "Important",
  considered: "Considered",
  no: "Not considered",
};

export interface CollegeProfile {
  id: string;
  name: string;
  /** "Cambridge, MA" */
  place: string;
  control: "public" | "private";
  /** Religious affiliation, when the college has one. */
  religious?: string;
  /** Undergraduate enrollment, rounded (render with ≈); null = not encoded. */
  undergrads: number | null;
  /** SAT middle 50% of enrolled first-years (CDS C9); null = not published
   *  or test-blind. */
  satRange: string | null;
  /** ACT middle 50% (CDS C9); null = not published or test-blind. */
  actRange: string | null;
  /** Six-year graduation rate, percent (CDS section B); null = not encoded. */
  gradRate: number | null;
  /** Percent admitted, with the cycle it comes from. */
  admitRate: number;
  admitYear: string;
  /** null = policy in flux / not encoded — render "—". */
  testPolicy: "required" | "optional" | "blind" | null;
  testNote?: string;
  /** Published GPA info as free text (weighted vs unweighted differs). */
  gpaNote: string | null;
  /** all = need-blind incl. international · domestic = need-blind for US
   *  applicants · aware = ability to pay can be a factor · null = the
   *  college's policy isn't clearly published / not yet encoded. */
  needBlind: "all" | "domestic" | "aware" | null;
  meetsFullNeed: boolean | null;
  aidNote?: string;
  /** CDS C7 extract — ONLY the cells we're confident of; missing = unknown. */
  factors: Partial<Record<FactorId, C7Rating>>;
  /** One honest line of personality/context. */
  note: string;
  /** Transfer admission (CDS section D) — absent = not encoded yet.
   *  The door that matters most for community-college students. */
  transfer?: {
    /** Percent of transfer applicants admitted; null = not published. */
    admitRate: number | null;
    admitYear?: string;
    /** GPA to apply / typical admitted GPA, free text (null = not published). */
    gpaNote: string | null;
    /** One-line transfer reality: guarantees, CC priority, tiny intake. */
    note?: string;
  };
}

/** The cycle most figures come from — shown publicly, re-verify yearly. */
export const COLLEGE_DATA_VINTAGE = "2024–25 admissions cycle";

export const colleges: CollegeProfile[] = [
  {
    id: "harvard",
    undergrads: 7100,
    satRange: "1500–1580",
    actRange: "34–36",
    gradRate: 98,
    name: "Harvard University",
    place: "Cambridge, MA",
    control: "private",
    admitRate: 3.6,
    admitYear: "fall 2024",
    testPolicy: "required",
    testNote: "Reinstated for fall 2025 applicants",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    aidNote: "No-loan aid; EVERYTHING free under $100k family income, tuition free under $200k (2025–26)",
    factors: {
      rigor: "considered",
      essay: "considered",
      ecs: "considered",
      character: "considered",
      legacy: "considered",
      interest: "no",
      religion: "no",
    },
    note: "Its CDS rates nearly every factor just “considered” — the fully holistic read, no formula to game.",
    transfer: {
      admitRate: 1,
      admitYear: "fall 2023",
      gpaNote: null,
      note: "Roughly a dozen transfer spots a year — effectively a lottery.",
    },
  },
  {
    id: "mit",
    undergrads: 4600,
    satRange: "1520–1580",
    actRange: "35–36",
    gradRate: 96,
    name: "MIT",
    place: "Cambridge, MA",
    control: "private",
    admitRate: 4.5,
    admitYear: "fall 2024",
    testPolicy: "required",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    aidNote: "Tuition free under $200k family income (2025–26)",
    factors: {
      character: "very",
      rigor: "important",
      essay: "important",
      interview: "important",
      ecs: "important",
      talent: "important",
      firstGen: "considered",
      legacy: "no",
      interest: "no",
      religion: "no",
    },
    note: "One of the few that says outright: legacy counts for nothing.",
    transfer: {
      admitRate: 2,
      admitYear: "fall 2023",
      gpaNote: null,
      note: "A few dozen admits a year — transfer is HARDER than freshman admission here.",
    },
  },
  {
    id: "yale",
    undergrads: 6700,
    satRange: "1500–1580",
    actRange: "33–35",
    gradRate: 97,
    name: "Yale University",
    place: "New Haven, CT",
    control: "private",
    admitRate: 3.7,
    admitYear: "fall 2024",
    testPolicy: "required",
    testNote: "SAT/ACT required; the AP/IB substitution option ended with the May 2026 policy update",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    factors: {
      rigor: "very",
      essay: "very",
      recs: "important",
      character: "important",
      legacy: "considered",
      interest: "no",
      religion: "no",
    },
    note: "Reads applications in committee, two readers minimum — context matters more than any single number.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "Tiny transfer class, plus the Eli Whitney program for nontraditional students returning to school.",
    },
  },
  {
    id: "stanford",
    undergrads: 7800,
    satRange: "1500–1580",
    actRange: "34–35",
    gradRate: 94,
    name: "Stanford University",
    place: "Stanford, CA",
    control: "private",
    admitRate: 3.9,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Required starting with fall 2025 applications (first entering class fall 2026)",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: {
      rigor: "very",
      essay: "very",
      ecs: "important",
      character: "important",
      legacy: "no",
      interest: "no",
      religion: "no",
    },
    note: "California banned legacy preference at private colleges from fall 2025 — it no longer counts here.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "Only a few dozen spots a year — but community-college and nontraditional students are genuinely part of that class.",
    },
  },
  {
    id: "amherst",
    undergrads: 1900,
    satRange: "1500–1560",
    actRange: "33–35",
    gradRate: 93,
    name: "Amherst College",
    place: "Amherst, MA",
    control: "private",
    admitRate: 9.8,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    aidNote: "No-loan aid for every aided student",
    factors: {
      rigor: "very",
      essay: "important",
      firstGen: "considered",
      legacy: "no",
      interest: "no",
    },
    note: "Dropped legacy preference in 2021 — one of the first elite colleges to do it.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "Actively recruits community-college transfers — rare among elite liberal-arts colleges.",
    },
  },
  {
    id: "bowdoin",
    undergrads: 1800,
    satRange: "1450–1550",
    actRange: "33–35",
    gradRate: 94,
    name: "Bowdoin College",
    place: "Brunswick, ME",
    control: "private",
    admitRate: 8,
    admitYear: "fall 2023",
    testPolicy: "optional",
    testNote: "Test-optional since 1969 — the original",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    aidNote: "No-loan aid",
    factors: {
      rigor: "very",
      essay: "important",
      character: "important",
      interest: "considered",
    },
    note: "Small, writing-heavy, and genuinely test-optional — scores truly aren’t missed.",
  },
  {
    id: "dartmouth",
    undergrads: 4500,
    satRange: "1480–1570",
    actRange: "33–35",
    gradRate: 95,
    name: "Dartmouth College",
    place: "Hanover, NH",
    control: "private",
    admitRate: 5.3,
    admitYear: "fall 2024",
    testPolicy: "required",
    testNote: "Reinstated for fall 2025 applicants",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    factors: {
      rigor: "very",
      essay: "important",
      recs: "important",
      legacy: "considered",
      interest: "no",
    },
    note: "Went need-blind for international applicants in 2022 — one of a handful.",
  },
  {
    id: "brown",
    undergrads: 7200,
    satRange: "1490–1570",
    actRange: "34–35",
    gradRate: 95,
    name: "Brown University",
    place: "Providence, RI",
    control: "private",
    admitRate: 5.2,
    admitYear: "fall 2024",
    testPolicy: "required",
    testNote: "Reinstated for fall 2025 applicants",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "Need-blind for international applicants starting with fall 2025 admits",
    factors: {
      rigor: "very",
      essay: "very",
      character: "important",
      legacy: "considered",
      interest: "no",
    },
    note: "The open curriculum school — essays about how you’d actually use that freedom carry weight.",
  },
  {
    id: "georgetown",
    undergrads: 7900,
    satRange: "1400–1540",
    actRange: "32–35",
    gradRate: null,
    name: "Georgetown University",
    place: "Washington, DC",
    control: "private",
    religious: "Catholic (Jesuit)",
    admitRate: 13,
    admitYear: "fall 2024",
    testPolicy: "required",
    testNote: "Never dropped testing — one of the only ones",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    factors: {
      rigor: "very",
      essay: "important",
      interview: "important",
      recs: "important",
    },
    note: "Interviews nearly every applicant; used its own application for decades and adds the Common App in August 2026.",
  },
  {
    id: "notre-dame",
    undergrads: 8900,
    satRange: "1440–1550",
    actRange: "33–35",
    gradRate: 96,
    name: "University of Notre Dame",
    place: "Notre Dame, IN",
    control: "private",
    religious: "Catholic",
    admitRate: 11,
    admitYear: "fall 2024",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    aidNote: "No-loan aid packages starting fall 2025",
    factors: {
      rigor: "very",
      essay: "important",
      character: "important",
      religion: "considered",
      legacy: "considered",
    },
    note: "Catholic character is real here — religious affiliation is a considered factor, not a checkbox.",
  },
  {
    id: "boston-college",
    undergrads: 9500,
    satRange: "1430–1530",
    actRange: "32–34",
    gradRate: 92,
    name: "Boston College",
    place: "Chestnut Hill, MA",
    control: "private",
    religious: "Catholic (Jesuit)",
    admitRate: 16,
    admitYear: "fall 2024",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: {
      rigor: "very",
      essay: "important",
      character: "important",
    },
    note: "Jesuit school that admits students of every faith; meets full need without the Ivy sticker shock.",
  },
  {
    id: "baylor",
    undergrads: 15200,
    satRange: null,
    actRange: "25–31",
    gradRate: 80,
    name: "Baylor University",
    place: "Waco, TX",
    control: "private",
    religious: "Baptist",
    admitRate: 51,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "aware",
    meetsFullNeed: false,
    factors: {
      gpa: "very",
      rigor: "important",
      religion: "considered",
    },
    note: "A big religious university where faith is part of campus life but not a bar to admission.",
  },
  {
    id: "byu",
    undergrads: 31000,
    satRange: null,
    actRange: "28–32",
    gradRate: null,
    name: "BYU (Brigham Young)",
    place: "Provo, UT",
    control: "private",
    religious: "Latter-day Saints (LDS)",
    admitRate: 69,
    admitYear: "fall 2023",
    testPolicy: null,
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    aidNote: "LDS members pay $6,688/yr tuition (2024–25)",
    factors: {
      gpa: "very",
      religion: "very",
      character: "important",
    },
    note: "Requires an ecclesiastical endorsement — religious commitment is central to admission here.",
  },
  {
    id: "berea",
    undergrads: 1500,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Berea College",
    place: "Berea, KY",
    control: "private",
    religious: "Christian (nondenominational heritage)",
    admitRate: 33,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "aware",
    meetsFullNeed: true,
    aidNote: "Every admitted student receives a full-tuition scholarship",
    factors: {
      gpa: "very",
      character: "important",
      work: "considered",
    },
    note: "The inverse of need-aware: Berea ONLY admits students with financial need — no tuition, work program instead.",
  },
  {
    id: "vanderbilt",
    undergrads: 7100,
    satRange: "1500–1570",
    actRange: "34–35",
    gradRate: 93,
    name: "Vanderbilt University",
    place: "Nashville, TN",
    control: "private",
    admitRate: 6.3,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "Opportunity Vanderbilt: no-loan aid",
    factors: {
      rigor: "very",
      gpa: "very",
      essay: "important",
      ecs: "important",
    },
    note: "One of the few super-selectives with serious full-tuition MERIT scholarships on top of need aid.",
  },
  {
    id: "rice",
    undergrads: 4500,
    satRange: "1500–1570",
    actRange: "34–35",
    gradRate: 93,
    name: "Rice University",
    place: "Houston, TX",
    control: "private",
    admitRate: 7.8,
    admitYear: "fall 2024",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "The Rice Investment: sliding-scale aid reaching well into middle incomes",
    factors: {
      rigor: "very",
      essay: "important",
      character: "important",
      interest: "considered",
    },
    note: "Small classes, residential colleges, and one of the strongest aid programs in Texas.",
  },
  {
    id: "uc-berkeley",
    undergrads: 33000,
    satRange: null,
    actRange: null,
    gradRate: 93,
    name: "UC Berkeley",
    place: "Berkeley, CA",
    control: "public",
    admitRate: 11,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: "4.31–4.65 weighted (middle 50% of admits, fall 2024)",
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: {
      rigor: "very",
      gpa: "very",
      essay: "important",
      firstGen: "considered",
      recs: "considered",
      legacy: "no",
      interest: "no",
      religion: "no",
    },
    note: "UC “comprehensive review”: no test scores, no legacy, no required letters (Berkeley invites some optionally) — your record and your PIQ essays.",
    transfer: {
      admitRate: 25,
      admitYear: "fall 2024",
      gpaNote: "3.0 minimum for all applicants (3.5 for Engineering); admitted mid-50% 3.61–3.96",
      note: "Junior-level transfers only; California community colleges get priority by UC policy.",
    },
  },
  {
    id: "ucla",
    undergrads: 32000,
    satRange: null,
    actRange: null,
    gradRate: 92,
    name: "UCLA",
    place: "Los Angeles, CA",
    control: "public",
    admitRate: 9,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: "4.42–4.76 weighted (middle 50% of admits, fall 2024)",
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: {
      rigor: "very",
      gpa: "very",
      essay: "important",
      firstGen: "considered",
      recs: "no",
      legacy: "no",
      interest: "no",
      religion: "no",
    },
    note: "The most-applied-to university in America — same UC review as Berkeley, no legacy, no letters.",
    transfer: {
      admitRate: 23,
      admitYear: "fall 2024",
      gpaNote: "2.4 minimum to apply (competitive admits 3.2+); admitted median 3.90",
      note: "CA community-college applicants fare even better (26% admitted) — 93% of admitted transfers come from a CCC.",
    },
  },
  {
    id: "ut-austin",
    undergrads: 42000,
    satRange: "1230–1480",
    actRange: null,
    gradRate: 88,
    name: "UT Austin",
    place: "Austin, TX",
    control: "public",
    admitRate: 26.6,
    admitYear: "fall 2024",
    testPolicy: "required",
    testNote: "Reinstated for fall 2025 applicants",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: {
      rank: "considered",
      rigor: "important",
      essay: "important",
      legacy: "no",
    },
    note: "Texans in the top 5% of their class (fall 2026 cycle) are auto-admitted by law — rank is the formula even though the CDS calls it merely “considered.”",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "Transfer admission is major-dependent — business and CS run far tougher than the average.",
    },
  },
  {
    id: "michigan",
    undergrads: 33000,
    satRange: "1350–1530",
    actRange: "31–34",
    gradRate: 93,
    name: "University of Michigan",
    place: "Ann Arbor, MI",
    control: "public",
    admitRate: 18,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    aidNote: "Go Blue Guarantee: free in-state tuition under $125k family income",
    factors: {
      rigor: "very",
      gpa: "very",
      essay: "important",
      firstGen: "considered",
    },
    note: "A public that reads like a private — essays and context genuinely move decisions.",
    transfer: {
      admitRate: 35,
      admitYear: "fall 2024",
      gpaNote: "No university-wide minimum published; Engineering requires 3.0 in prerequisites",
      note: "Roughly double the freshman admit rate — a genuinely wider second door.",
    },
  },
  {
    id: "alabama",
    undergrads: 32000,
    satRange: null,
    actRange: "21–31",
    gradRate: 72,
    name: "University of Alabama",
    place: "Tuscaloosa, AL",
    control: "public",
    admitRate: 76,
    admitYear: "fall 2023",
    testPolicy: "optional",
    testNote: "Optional now, but UA requires tests for everyone starting with 2028 entry",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Published merit tables: strong GPA + test = automatic large scholarships, even for out-of-state",
    factors: {
      gpa: "very",
      rigor: "considered",
    },
    note: "The formula-friendly path: hit the published numbers and both admission and merit money are near-automatic.",
  },
  {
    id: "csulb",
    undergrads: 33000,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Cal State Long Beach",
    place: "Long Beach, CA",
    control: "public",
    admitRate: 47,
    admitYear: "fall 2023",
    testPolicy: "blind",
    testNote: "CSUs dropped the SAT/ACT permanently in 2022",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: {
      gpa: "very",
      rigor: "considered",
      essay: "no",
      recs: "no",
      interview: "no",
      ecs: "no",
      legacy: "no",
      interest: "no",
    },
    note: "CSUs admit on a GPA-based eligibility index — no essays, no recommendations, no interviews at all.",
    transfer: {
      admitRate: null,
      gpaNote: "2.0+ with an Associate Degree for Transfer",
      note: "An ADT from a California community college guarantees CSU admission — the surest four-year path in the state.",
    },
  },
  {
    id: "howard",
    undergrads: 10000,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Howard University",
    place: "Washington, DC",
    control: "private",
    admitRate: 35,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: {
      gpa: "very",
      rigor: "important",
      essay: "considered",
      ecs: "considered",
    },
    note: "The flagship HBCU — real merit scholarships and an alumni network that opens doors for decades.",
  },
  {
    id: "asu",
    undergrads: 65000,
    satRange: null,
    actRange: null,
    gradRate: 67,
    name: "Arizona State University",
    place: "Tempe, AZ",
    control: "public",
    admitRate: 90,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: {
      gpa: "very",
      rank: "important",
    },
    note: "Assured admission by published GPA/class-rank standards — if you qualify, you’re in. Access is the mission.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "Guaranteed transfer pathways (MyPath2ASU) from hundreds of community colleges.",
    },
  },
  {
    id: "princeton",
    undergrads: 5400,
    satRange: "1500–1580",
    actRange: "34–35",
    gradRate: 98,
    name: "Princeton University",
    place: "Princeton, NJ",
    control: "private",
    admitRate: 4.5,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "all",
    meetsFullNeed: true,
    aidNote: "Invented no-loan aid in 2001; free for most families under $100k",
    factors: { rigor: "very", essay: "very", character: "important", legacy: "considered", interest: "no" },
    note: "The no-loan pioneer — every aid dollar is a grant, and it stayed test-optional when peers went back.",
  },
  {
    id: "columbia",
    undergrads: 8800,
    satRange: "1500–1570",
    actRange: "34–35",
    gradRate: 95,
    name: "Columbia University",
    place: "New York, NY",
    control: "private",
    admitRate: 3.9,
    admitYear: "fall 2023",
    testPolicy: "optional",
    testNote: "Permanently test-optional — the first Ivy to commit",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "very", legacy: "considered", interest: "no" },
    note: "Core Curriculum school in Manhattan; went permanently test-optional in 2023.",
  },
  {
    id: "penn",
    undergrads: 10000,
    satRange: "1500–1570",
    actRange: "34–35",
    gradRate: 96,
    name: "University of Pennsylvania",
    place: "Philadelphia, PA",
    control: "private",
    admitRate: 6,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Reinstated for fall 2026 applicants",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "All-grant, no-loan aid packages",
    factors: { rigor: "very", essay: "very", ecs: "important", legacy: "considered", interest: "no" },
    note: "Ben Franklin's practical university — Wharton sits inside it, and aid packages carry no loans.",
  },
  {
    id: "cornell",
    undergrads: 15700,
    satRange: "1470–1560",
    actRange: "33–35",
    gradRate: 95,
    name: "Cornell University",
    place: "Ithaca, NY",
    control: "private",
    admitRate: 7.5,
    admitYear: "fall 2023",
    testPolicy: "optional",
    testNote: "Policy varies by college within Cornell",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important", interest: "no" },
    note: "The biggest Ivy — you apply to one of its colleges, and each reads differently.",
  },
  {
    id: "uchicago",
    undergrads: 7300,
    satRange: "1510–1580",
    actRange: "34–35",
    gradRate: 96,
    name: "University of Chicago",
    place: "Chicago, IL",
    control: "private",
    admitRate: 4.8,
    admitYear: "fall 2023",
    testPolicy: "optional",
    testNote: "The elite test-optional pioneer (2018)",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "No Barriers: no-loan aid; free tuition under $125k family income",
    factors: { rigor: "very", essay: "very", interest: "considered" },
    note: "Home of the famously weird essay prompts — the writing genuinely decides here.",
  },
  {
    id: "duke",
    undergrads: 6600,
    satRange: "1510–1570",
    actRange: "34–35",
    gradRate: 96,
    name: "Duke University",
    place: "Durham, NC",
    control: "private",
    admitRate: 6.3,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "Free tuition for Carolinas families under $150k income",
    factors: { rigor: "very", essay: "very", ecs: "important", legacy: "considered" },
    note: "Reads regionally with two readers; strong aid deal for North and South Carolina families.",
  },
  {
    id: "jhu",
    undergrads: 6000,
    satRange: "1530–1580",
    actRange: "35–36",
    gradRate: 94,
    name: "Johns Hopkins University",
    place: "Baltimore, MD",
    control: "private",
    admitRate: 7.5,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "Bloomberg's $1.8B gift made aid permanent: no loans, ever",
    factors: { rigor: "very", essay: "very", legacy: "no", interest: "no" },
    note: "Ended legacy preference in 2020 and told everyone — a Bloomberg-funded no-loan machine.",
  },
  {
    id: "northwestern",
    undergrads: 8700,
    satRange: "1500–1570",
    actRange: "33–35",
    gradRate: 95,
    name: "Northwestern University",
    place: "Evanston, IL",
    control: "private",
    admitRate: 7.2,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "No-loan aid packages",
    factors: { rigor: "very", essay: "important", ecs: "important" },
    note: "Quarter system, ten schools, one application — the 'and' school: engineering AND theater.",
  },
  {
    id: "caltech",
    undergrads: 1000,
    satRange: "1530–1580",
    actRange: "35–36",
    gradRate: 93,
    name: "Caltech",
    place: "Pasadena, CA",
    control: "private",
    admitRate: 3,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Reinstated for fall 2025 applicants",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", gpa: "very", legacy: "no", interest: "no", religion: "no" },
    note: "1,000 students, ended legacy in 2022, and the math bar is real — the purest academics-first read.",
  },
  {
    id: "cmu",
    undergrads: 7700,
    satRange: "1500–1570",
    actRange: "34–35",
    gradRate: 92,
    name: "Carnegie Mellon University",
    place: "Pittsburgh, PA",
    control: "private",
    admitRate: 11,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: null,
    factors: { rigor: "very", essay: "important", talent: "important" },
    note: "Admits by college — CS is among the hardest doors in the country; drama auditions its own class.",
  },
  {
    id: "nyu",
    undergrads: 29000,
    satRange: "1450–1560",
    actRange: "33–35",
    gradRate: 87,
    name: "New York University",
    place: "New York, NY",
    control: "private",
    admitRate: 12.5,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "aware",
    meetsFullNeed: false,
    factors: { rigor: "very", essay: "important" },
    note: "Huge, global, and famous for aid gaps — get the award letter before you fall in love.",
  },
  {
    id: "usc",
    undergrads: 21000,
    satRange: "1450–1550",
    actRange: "32–35",
    gradRate: 92,
    name: "University of Southern California",
    place: "Los Angeles, CA",
    control: "private",
    admitRate: 12,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: true,
    aidNote: "Free tuition under $80k family income (with typical assets)",
    factors: { rigor: "very", essay: "important", ecs: "important", legacy: "no" },
    note: "California's legacy ban applies here too (2025) — and the under-$80k free-tuition deal is real.",
  },
  {
    id: "tufts",
    undergrads: 6800,
    satRange: "1460–1550",
    actRange: "33–35",
    gradRate: 94,
    name: "Tufts University",
    place: "Medford, MA",
    control: "private",
    admitRate: 10,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important", character: "important" },
    note: "Went need-blind for US applicants in 2023 and meets full need — quietly one of the fairest doors in Boston.",
  },
  {
    id: "bu",
    undergrads: 18000,
    satRange: "1370–1490",
    actRange: "31–34",
    gradRate: 89,
    name: "Boston University",
    place: "Boston, MA",
    control: "private",
    admitRate: 11,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important" },
    note: "Meets full need for US students since 2020 — a big-city school that got serious about aid.",
  },
  {
    id: "northeastern",
    undergrads: 16000,
    satRange: "1450–1540",
    actRange: "33–35",
    gradRate: 90,
    name: "Northeastern University",
    place: "Boston, MA",
    control: "private",
    admitRate: 6,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: null,
    factors: { rigor: "very", essay: "considered" },
    note: "The co-op school: alternating semesters of real paid work — and an admit rate that collapsed as applications exploded.",
  },
  {
    id: "tulane",
    undergrads: 7300,
    satRange: "1370–1500",
    actRange: "30–33",
    gradRate: 86,
    name: "Tulane University",
    place: "New Orleans, LA",
    control: "private",
    admitRate: 13,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", essay: "important", interest: "important" },
    note: "One of the schools where demonstrated interest genuinely counts — visit, write, engage.",
  },
  {
    id: "rochester",
    undergrads: 6700,
    satRange: "1370–1520",
    actRange: "31–34",
    gradRate: 86,
    name: "University of Rochester",
    place: "Rochester, NY",
    control: "private",
    admitRate: 36,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", essay: "important" },
    note: "Open curriculum energy with strong merit money — a research university that discounts generously.",
  },
  {
    id: "case-western",
    undergrads: 6000,
    satRange: "1420–1530",
    actRange: "32–35",
    gradRate: 86,
    name: "Case Western Reserve",
    place: "Cleveland, OH",
    control: "private",
    admitRate: 28,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", essay: "considered" },
    note: "Engineering/pre-med heavy with real merit scholarships — runs its own aid math, so compare letters.",
  },
  {
    id: "brandeis",
    undergrads: 3600,
    satRange: "1380–1520",
    actRange: "31–34",
    gradRate: 88,
    name: "Brandeis University",
    place: "Waltham, MA",
    control: "private",
    admitRate: 35,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", essay: "considered" },
    note: "Founded by the Jewish community, open to all — small research university with merit aid.",
  },
  {
    id: "wake-forest",
    undergrads: 5400,
    satRange: "1370–1490",
    actRange: "30–33",
    gradRate: 88,
    name: "Wake Forest University",
    place: "Winston-Salem, NC",
    control: "private",
    admitRate: 22,
    admitYear: "fall 2023",
    testPolicy: "optional",
    testNote: "Test-optional since 2008 — long before the pandemic",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important", interview: "important" },
    note: "The original elite test-optional school; interviews matter and classes stay small.",
  },
  {
    id: "williams",
    undergrads: 2100,
    satRange: "1480–1570",
    actRange: "33–35",
    gradRate: 95,
    name: "Williams College",
    place: "Williamstown, MA",
    control: "private",
    admitRate: 10,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "All-grant aid — loans eliminated from every package",
    factors: { rigor: "very", essay: "important", character: "important", interest: "no" },
    note: "Tutorials of two students and a professor — the deepest classroom access in the country.",
  },
  {
    id: "swarthmore",
    undergrads: 1600,
    satRange: "1480–1560",
    actRange: "33–35",
    gradRate: 94,
    name: "Swarthmore College",
    place: "Swarthmore, PA",
    control: "private",
    admitRate: 7,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "No-loan aid packages",
    factors: { rigor: "very", essay: "very", character: "important" },
    note: "Quaker-rooted, intellectually intense, no loans — engineering inside a liberal-arts college.",
  },
  {
    id: "pomona",
    undergrads: 1700,
    satRange: "1480–1560",
    actRange: "33–35",
    gradRate: 94,
    name: "Pomona College",
    place: "Claremont, CA",
    control: "private",
    admitRate: 7,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "No-loan aid packages",
    factors: { rigor: "very", essay: "very", character: "important" },
    note: "Anchor of the five Claremont Colleges — LAC intimacy with a 5-campus course catalog.",
  },
  {
    id: "wellesley",
    undergrads: 2400,
    satRange: "1440–1550",
    actRange: "32–35",
    gradRate: 92,
    name: "Wellesley College",
    place: "Wellesley, MA",
    control: "private",
    admitRate: 14,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important", character: "important" },
    note: "The most powerful women's-college network in America — cross-register at MIT.",
  },
  {
    id: "barnard",
    undergrads: 3200,
    satRange: "1450–1550",
    actRange: "33–35",
    gradRate: 93,
    name: "Barnard College",
    place: "New York, NY",
    control: "private",
    admitRate: 7,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "aware",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "very" },
    note: "A women's college wrapped inside Columbia — openly need-aware, so aid strategy matters here.",
  },
  {
    id: "smith",
    undergrads: 2500,
    satRange: "1400–1520",
    actRange: "31–34",
    gradRate: 88,
    name: "Smith College",
    place: "Northampton, MA",
    control: "private",
    admitRate: 21,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important" },
    note: "Went need-blind in 2021 and replaced loans with grants — a women's college that put money behind access.",
  },
  {
    id: "haverford",
    undergrads: 1400,
    satRange: "1450–1550",
    actRange: "33–35",
    gradRate: 93,
    name: "Haverford College",
    place: "Haverford, PA",
    control: "private",
    admitRate: 14,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "No-loan aid packages",
    factors: { rigor: "very", essay: "important", character: "very" },
    note: "Runs on a student-written honor code — exams are unproctored and character is the read.",
  },
  {
    id: "vassar",
    undergrads: 2400,
    satRange: "1440–1540",
    actRange: "32–34",
    gradRate: 91,
    name: "Vassar College",
    place: "Poughkeepsie, NY",
    control: "private",
    admitRate: 19,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important" },
    note: "Open curriculum, strong arts, need-blind with full need met.",
  },
  {
    id: "davidson",
    undergrads: 1900,
    satRange: "1400–1510",
    actRange: "31–34",
    gradRate: 92,
    name: "Davidson College",
    place: "Davidson, NC",
    control: "private",
    admitRate: 15,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "The Davidson Trust: no-loan aid for everyone",
    factors: { rigor: "very", essay: "important", character: "important" },
    note: "The Davidson Trust pledged loan-free aid before the Ivies did — honor code campus.",
  },
  {
    id: "grinnell",
    undergrads: 1700,
    satRange: "1390–1540",
    actRange: "31–34",
    gradRate: 88,
    name: "Grinnell College",
    place: "Grinnell, IA",
    control: "private",
    admitRate: 11,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "No-loan aid; one of the largest endowments per student anywhere",
    factors: { rigor: "very", essay: "important" },
    note: "A tiny Iowa college with a Wall-Street-sized endowment — open curriculum, serious aid.",
  },
  {
    id: "wesleyan",
    undergrads: 3000,
    satRange: "1440–1550",
    actRange: "32–35",
    gradRate: 91,
    name: "Wesleyan University",
    place: "Middletown, CT",
    control: "private",
    admitRate: 16,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "aware",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "important" },
    note: "Openly need-aware and honest about it — film and music powerhouse.",
  },
  {
    id: "hamilton",
    undergrads: 2000,
    satRange: "1450–1540",
    actRange: "33–35",
    gradRate: 93,
    name: "Hamilton College",
    place: "Clinton, NY",
    control: "private",
    admitRate: 12,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    factors: { rigor: "very", essay: "very" },
    note: "Need-blind since 2010; the open curriculum school that makes everyone learn to write.",
  },
  {
    id: "villanova",
    undergrads: 7000,
    satRange: "1400–1500",
    actRange: "32–34",
    gradRate: 91,
    name: "Villanova University",
    place: "Villanova, PA",
    control: "private",
    religious: "Catholic (Augustinian)",
    admitRate: 21,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: null,
    factors: { rigor: "very", essay: "important" },
    note: "Augustinian Catholic with a national brand — admits students of every faith.",
  },
  {
    id: "fordham",
    undergrads: 10000,
    satRange: "1320–1450",
    actRange: "30–33",
    gradRate: 83,
    name: "Fordham University",
    place: "Bronx, NY",
    control: "private",
    religious: "Catholic (Jesuit)",
    admitRate: 54,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", essay: "considered" },
    note: "Jesuit school with two NYC campuses — real merit aid, but packages can gap; compare letters.",
  },
  {
    id: "pepperdine",
    undergrads: 3700,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Pepperdine University",
    place: "Malibu, CA",
    control: "private",
    religious: "Churches of Christ",
    admitRate: 49,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", character: "important", religion: "considered" },
    note: "Faith is part of campus life (convocation requirement) — and yes, that is the Malibu campus.",
  },
  {
    id: "smu",
    undergrads: 7100,
    satRange: "1310–1460",
    actRange: "29–33",
    gradRate: 81,
    name: "Southern Methodist University",
    place: "Dallas, TX",
    control: "private",
    religious: "United Methodist",
    admitRate: 61,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", gpa: "important" },
    note: "Dallas connections and big merit scholarships — Methodist-affiliated, all faiths admitted.",
  },
  {
    id: "tcu",
    undergrads: 10500,
    satRange: "1210–1390",
    actRange: "26–31",
    gradRate: 82,
    name: "Texas Christian University",
    place: "Fort Worth, TX",
    control: "private",
    religious: "Disciples of Christ",
    admitRate: 43,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", gpa: "important" },
    note: "Church-affiliated in name, big-time college sports in practice — merit aid is the draw.",
  },
  {
    id: "gonzaga",
    undergrads: 5000,
    satRange: "1220–1390",
    actRange: "26–31",
    gradRate: 86,
    name: "Gonzaga University",
    place: "Spokane, WA",
    control: "private",
    religious: "Catholic (Jesuit)",
    admitRate: 76,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { rigor: "very", gpa: "important" },
    note: "Jesuit access mission with a famous basketball front door — solid merit for solid grades.",
  },
  {
    id: "yeshiva",
    undergrads: 2100,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Yeshiva University",
    place: "New York, NY",
    control: "private",
    religious: "Jewish (Modern Orthodox)",
    admitRate: 63,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { gpa: "very", religion: "very" },
    note: "Torah study is half the curriculum — the flagship of Modern Orthodox higher education.",
  },
  {
    id: "uva",
    undergrads: 17500,
    satRange: "1400–1520",
    actRange: "32–34",
    gradRate: 94,
    name: "University of Virginia",
    place: "Charlottesville, VA",
    control: "public",
    admitRate: 17,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "AccessUVA: one of the only publics that meets full need",
    factors: { rigor: "very", essay: "important", recs: "considered" },
    note: "Jefferson's university — and one of two big publics that promise to meet full financial need.",
  },
  {
    id: "unc",
    undergrads: 20500,
    satRange: "1350–1500",
    actRange: "29–33",
    gradRate: 91,
    name: "UNC Chapel Hill",
    place: "Chapel Hill, NC",
    control: "public",
    admitRate: 19,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: true,
    aidNote: "Carolina Covenant: debt-free graduation for low-income students",
    factors: { rigor: "very", essay: "important" },
    note: "The Carolina Covenant promised debt-free degrees back in 2004 — the other full-need public.",
  },
  {
    id: "gatech",
    undergrads: 19500,
    satRange: "1370–1530",
    actRange: "31–35",
    gradRate: 92,
    name: "Georgia Tech",
    place: "Atlanta, GA",
    control: "public",
    admitRate: 16,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Georgia's public universities kept the test requirement",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { rigor: "very", gpa: "very", essay: "important" },
    note: "The best engineering value in the country for Georgians — co-ops built into the culture.",
  },
  {
    id: "wm",
    undergrads: 6800,
    satRange: "1350–1490",
    actRange: "31–34",
    gradRate: 91,
    name: "William & Mary",
    place: "Williamsburg, VA",
    control: "public",
    admitRate: 33,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { rigor: "very", essay: "important" },
    note: "A public that feels like a small private — colonial campus, liberal-arts core.",
  },
  {
    id: "washington",
    undergrads: 36000,
    satRange: "1220–1450",
    actRange: null,
    gradRate: 84,
    name: "University of Washington",
    place: "Seattle, WA",
    control: "public",
    admitRate: 46,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Husky Promise: free tuition for Washington Pell/state-grant students",
    factors: { rigor: "very", gpa: "very", essay: "important" },
    note: "Seattle's front door to tech — direct-to-major admission makes CS the hard part.",
  },
  {
    id: "wisconsin",
    undergrads: 37000,
    satRange: "1300–1460",
    actRange: "27–32",
    gradRate: 89,
    name: "UW–Madison",
    place: "Madison, WI",
    control: "public",
    admitRate: 43,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Bucky's Tuition Promise: free tuition under $65k Wisconsin family income",
    factors: { rigor: "very", gpa: "very" },
    note: "Big Ten flagship with a real in-state tuition promise for working families.",
  },
  {
    id: "uiuc",
    undergrads: 35000,
    satRange: "1300–1500",
    actRange: "29–34",
    gradRate: 85,
    name: "University of Illinois Urbana-Champaign",
    place: "Champaign, IL",
    control: "public",
    admitRate: 44,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Illinois Commitment: free tuition under $75k Illinois family income",
    factors: { rigor: "very", gpa: "very" },
    note: "Admission is by major — the overall rate hides single-digit CS. Engineering pedigree for public tuition.",
  },
  {
    id: "ohio-state",
    undergrads: 46000,
    satRange: "1260–1420",
    actRange: "26–32",
    gradRate: 88,
    name: "Ohio State University",
    place: "Columbus, OH",
    control: "public",
    admitRate: 51,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { rigor: "very", gpa: "very", rank: "important" },
    note: "One of America's biggest campuses — every major, every club, college sports at maximum volume.",
  },
  {
    id: "penn-state",
    undergrads: 41000,
    satRange: "1160–1360",
    actRange: "25–30",
    gradRate: 83,
    name: "Penn State (University Park)",
    place: "University Park, PA",
    control: "public",
    admitRate: 54,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { gpa: "very", rigor: "important" },
    note: "GPA carries two-thirds of the decision by the university's own formula — the alumni network is everywhere.",
  },
  {
    id: "purdue",
    undergrads: 39000,
    satRange: "1190–1420",
    actRange: "25–32",
    gradRate: 83,
    name: "Purdue University",
    place: "West Lafayette, IN",
    control: "public",
    admitRate: 50,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Reinstated for 2024 applicants",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Tuition frozen since 2013 — a decade-plus without an increase",
    factors: { rigor: "very", gpa: "very", essay: "considered" },
    note: "Froze tuition in 2013 and never unfroze it — engineering value that compounds.",
  },
  {
    id: "maryland",
    undergrads: 30000,
    satRange: "1330–1490",
    actRange: "30–34",
    gradRate: 89,
    name: "University of Maryland",
    place: "College Park, MD",
    control: "public",
    admitRate: 45,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { rigor: "very", gpa: "very", essay: "important" },
    note: "DC-adjacent flagship with 26 review factors — strong in CS and business.",
  },
  {
    id: "rutgers",
    undergrads: 36000,
    satRange: "1260–1430",
    actRange: null,
    gradRate: 84,
    name: "Rutgers–New Brunswick",
    place: "New Brunswick, NJ",
    control: "public",
    admitRate: 66,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { gpa: "very", rigor: "important" },
    note: "New Jersey's flagship — Big Ten research on NJ Transit's schedule.",
  },
  {
    id: "georgia",
    undergrads: 31000,
    satRange: "1220–1400",
    actRange: "27–32",
    gradRate: 88,
    name: "University of Georgia",
    place: "Athens, GA",
    control: "public",
    admitRate: 40,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Georgia's public universities kept the test requirement",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { rigor: "very", gpa: "very" },
    note: "Athens is the college-town archetype; HOPE Scholarship makes it near-free for strong Georgia students.",
  },
  {
    id: "florida",
    undergrads: 35000,
    satRange: "1300–1450",
    actRange: "28–33",
    gradRate: 90,
    name: "University of Florida",
    place: "Gainesville, FL",
    control: "public",
    admitRate: 24,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Florida's publics never dropped the test requirement",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Bright Futures covers up to 100% of tuition for Florida students",
    factors: { gpa: "very", rigor: "very", rank: "important" },
    note: "Florida's flagship — Bright Futures plus low tuition makes it one of the cheapest strong degrees anywhere.",
  },
  {
    id: "florida-state",
    undergrads: 33000,
    satRange: "1220–1350",
    actRange: "26–30",
    gradRate: 85,
    name: "Florida State University",
    place: "Tallahassee, FL",
    control: "public",
    admitRate: 25,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Florida's publics never dropped the test requirement",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Bright Futures covers up to 100% of tuition for Florida students",
    factors: { gpa: "very", rigor: "important" },
    note: "Same Bright Futures math as UF with a friendlier admit rate.",
  },
  {
    id: "texas-am",
    undergrads: 57000,
    satRange: "1160–1380",
    actRange: "24–30",
    gradRate: 83,
    name: "Texas A&M University",
    place: "College Station, TX",
    control: "public",
    admitRate: 63,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { rank: "very", gpa: "very" },
    note: "Top 10% of a Texas class = automatic admission by law; the Aggie network is legendarily loyal.",
  },
  {
    id: "virginia-tech",
    undergrads: 30000,
    satRange: "1180–1390",
    actRange: null,
    gradRate: 86,
    name: "Virginia Tech",
    place: "Blacksburg, VA",
    control: "public",
    admitRate: 57,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { gpa: "very", rigor: "important" },
    note: "Engineering-first land-grant with a service ethos — Ut Prosim, that I may serve.",
  },
  {
    id: "stony-brook",
    undergrads: 18000,
    satRange: "1280–1450",
    actRange: null,
    gradRate: 78,
    name: "Stony Brook University",
    place: "Stony Brook, NY",
    control: "public",
    admitRate: 49,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { gpa: "very", rigor: "important" },
    note: "SUNY's research flagship — a top social-mobility engine at state-school prices.",
  },
  {
    id: "umass",
    undergrads: 24000,
    satRange: "1260–1420",
    actRange: null,
    gradRate: 83,
    name: "UMass Amherst",
    place: "Amherst, MA",
    control: "public",
    admitRate: 58,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { gpa: "very", rigor: "important" },
    note: "Massachusetts' flagship, five-college consortium access, and famously the best dining in America.",
  },
  {
    id: "ucsd",
    undergrads: 33000,
    satRange: null,
    actRange: null,
    gradRate: 88,
    name: "UC San Diego",
    place: "La Jolla, CA",
    control: "public",
    admitRate: 26,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: { rigor: "very", gpa: "very", essay: "important", firstGen: "considered", legacy: "no", interest: "no", religion: "no" },
    note: "STEM-heavy UC on the Pacific — no TAG here, but transfers still fare far better than freshmen.",
    transfer: {
      admitRate: 55,
      admitYear: "fall 2023",
      gpaNote: null,
      note: "Transfer admit rate roughly double the freshman rate; CA community colleges get priority.",
    },
  },
  {
    id: "uc-irvine",
    undergrads: 29000,
    satRange: null,
    actRange: null,
    gradRate: 87,
    name: "UC Irvine",
    place: "Irvine, CA",
    control: "public",
    admitRate: 26,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: { rigor: "very", gpa: "very", essay: "important", firstGen: "considered", legacy: "no", interest: "no", religion: "no" },
    note: "First-gen students are the majority here — an Anteater degree with a UC research engine.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "TAG: hit the GPA bar at a California community college and admission is GUARANTEED by agreement.",
    },
  },
  {
    id: "uc-davis",
    undergrads: 31000,
    satRange: null,
    actRange: null,
    gradRate: 86,
    name: "UC Davis",
    place: "Davis, CA",
    control: "public",
    admitRate: 42,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: { rigor: "very", gpa: "very", essay: "important", firstGen: "considered", legacy: "no", interest: "no", religion: "no" },
    note: "Ag-science roots, vet-med fame, and a bike-everywhere college town.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "TAG: hit the GPA bar at a California community college and admission is GUARANTEED by agreement.",
    },
  },
  {
    id: "ucsb",
    undergrads: 23000,
    satRange: null,
    actRange: null,
    gradRate: 85,
    name: "UC Santa Barbara",
    place: "Santa Barbara, CA",
    control: "public",
    admitRate: 33,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: { rigor: "very", gpa: "very", essay: "important", firstGen: "considered", legacy: "no", interest: "no", religion: "no" },
    note: "Nobel-heavy physics and engineering — on a literal beach.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "TAG: hit the GPA bar at a California community college and admission is GUARANTEED by agreement.",
    },
  },
  {
    id: "uc-santa-cruz",
    undergrads: 17000,
    satRange: null,
    actRange: null,
    gradRate: 78,
    name: "UC Santa Cruz",
    place: "Santa Cruz, CA",
    control: "public",
    admitRate: 61,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: { rigor: "very", gpa: "very", essay: "important", firstGen: "considered", legacy: "no", interest: "no", religion: "no" },
    note: "Redwoods, ocean, and genomics — the UC that feels like a liberal-arts college.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "TAG: hit the GPA bar at a California community college and admission is GUARANTEED by agreement.",
    },
  },
  {
    id: "uc-riverside",
    undergrads: 22000,
    satRange: null,
    actRange: null,
    gradRate: 76,
    name: "UC Riverside",
    place: "Riverside, CA",
    control: "public",
    admitRate: 70,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: { rigor: "very", gpa: "very", essay: "important", firstGen: "considered", legacy: "no", interest: "no", religion: "no" },
    note: "Tops social-mobility measures year after year — the UC built for first-gen success.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "TAG: hit the GPA bar at a California community college and admission is GUARANTEED by agreement.",
    },
  },
  {
    id: "uc-merced",
    undergrads: 8000,
    satRange: null,
    actRange: null,
    gradRate: 64,
    name: "UC Merced",
    place: "Merced, CA",
    control: "public",
    admitRate: 89,
    admitYear: "fall 2024",
    testPolicy: "blind",
    testNote: "All UCs are test-blind — scores are never seen",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Blue & Gold plan covers in-state tuition under $100k family income",
    factors: { rigor: "very", gpa: "very", essay: "important", firstGen: "considered", legacy: "no", interest: "no", religion: "no" },
    note: "The newest UC admits nearly 9 in 10 — a real UC research degree with an open front door.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "TAG: hit the GPA bar at a California community college and admission is GUARANTEED by agreement.",
    },
  },
  {
    id: "spelman",
    undergrads: 2400,
    satRange: null,
    actRange: null,
    gradRate: 75,
    name: "Spelman College",
    place: "Atlanta, GA",
    control: "private",
    admitRate: 25,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { gpa: "very", essay: "important", character: "important" },
    note: "The #1-ranked HBCU — a women's college producing Black women leaders at an unmatched rate.",
  },
  {
    id: "morehouse",
    undergrads: 2200,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Morehouse College",
    place: "Atlanta, GA",
    control: "private",
    admitRate: 52,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { gpa: "very", character: "important" },
    note: "The only historically Black men's college — MLK's alma mater, across the street from Spelman.",
  },
  {
    id: "hampton",
    undergrads: 3200,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Hampton University",
    place: "Hampton, VA",
    control: "private",
    admitRate: 34,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { gpa: "very", character: "important" },
    note: "'The Standard of Excellence' — a waterfront HBCU with strong nursing, business, and journalism.",
  },
  {
    id: "nc-at",
    undergrads: 12000,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "North Carolina A&T",
    place: "Greensboro, NC",
    control: "public",
    admitRate: 57,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { gpa: "very" },
    note: "The largest HBCU in America — and the #1 producer of Black engineers.",
  },
  {
    id: "xavier-la",
    undergrads: 2700,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Xavier University of Louisiana",
    place: "New Orleans, LA",
    control: "private",
    religious: "Catholic",
    admitRate: 65,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { gpa: "very", character: "important" },
    note: "Sends more Black graduates to medical school than any university in America — at any size.",
  },
  {
    id: "georgia-state",
    undergrads: 28000,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "Georgia State University",
    place: "Atlanta, GA",
    control: "public",
    admitRate: 63,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    factors: { gpa: "very" },
    note: "Graduates more Black students than any US university — its data-driven advising erased the graduation gap.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "Transfer-friendly by design — most credits move, and advising is the famous part.",
    },
  },
  {
    id: "cuny-baruch",
    undergrads: 15000,
    satRange: "1250–1410",
    actRange: null,
    gradRate: 74,
    name: "CUNY Baruch College",
    place: "New York, NY",
    control: "public",
    admitRate: 46,
    admitYear: "fall 2023",
    testPolicy: "optional",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: false,
    aidNote: "CUNY tuition ≈ $7k/yr — routinely tops social-mobility indexes",
    factors: { gpa: "very", rigor: "important" },
    note: "The mobility machine: Wall Street internships at community-college-adjacent prices.",
  },
  {
    id: "ucf",
    undergrads: 58000,
    satRange: "1170–1340",
    actRange: "25–30",
    gradRate: 74,
    name: "University of Central Florida",
    place: "Orlando, FL",
    control: "public",
    admitRate: 43,
    admitYear: "fall 2023",
    testPolicy: "required",
    testNote: "Florida's publics never dropped the test requirement",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    aidNote: "Bright Futures covers up to 100% of tuition for Florida students",
    factors: { gpa: "very", rigor: "important" },
    note: "One of the biggest campuses in America — DirectConnect guarantees admission from partner state colleges.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "DirectConnect: an associate degree at a partner Florida college guarantees UCF admission.",
    },
  },
  {
    id: "cal-poly-slo",
    undergrads: 21000,
    satRange: null,
    actRange: null,
    gradRate: 85,
    name: "Cal Poly San Luis Obispo",
    place: "San Luis Obispo, CA",
    control: "public",
    admitRate: 28,
    admitYear: "fall 2023",
    testPolicy: "blind",
    testNote: "CSUs dropped the SAT/ACT permanently in 2022",
    gpaNote: null,
    needBlind: "domestic",
    meetsFullNeed: false,
    factors: { gpa: "very", rigor: "very", essay: "no", recs: "no", interview: "no" },
    note: "Learn By Doing: the CSU that outperforms its price tag — admission by MCA formula, no essays read.",
  },
  {
    id: "west-point",
    undergrads: 4400,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "West Point (US Military Academy)",
    place: "West Point, NY",
    control: "public",
    admitRate: 12,
    admitYear: "fall 2023",
    testPolicy: "required",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: null,
    aidNote: "Free: tuition, room, board, and a salary — repaid with five years of service as an Army officer",
    factors: { rigor: "very", character: "very", ecs: "important", interview: "important" },
    note: "Requires a congressional nomination and a fitness test — you graduate debt-free as an officer.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "No transfer credit — everyone starts as a plebe, whatever they've studied before.",
    },
  },
  {
    id: "naval-academy",
    undergrads: 4500,
    satRange: null,
    actRange: null,
    gradRate: null,
    name: "US Naval Academy",
    place: "Annapolis, MD",
    control: "public",
    admitRate: 9,
    admitYear: "fall 2023",
    testPolicy: "required",
    gpaNote: null,
    needBlind: null,
    meetsFullNeed: null,
    aidNote: "Free: tuition, room, board, and a salary — repaid with five years of service as a Navy or Marine officer",
    factors: { rigor: "very", character: "very", ecs: "important", interview: "important" },
    note: "Congressional nomination, fitness assessment, medical exam — then a free degree and a commission.",
    transfer: {
      admitRate: null,
      gpaNote: null,
      note: "No transfer credit — all midshipmen start from year one.",
    },
  },
];
