// Internships & opportunities (July 2026, owner ask): the experience side
// of the student money story — paid internships, fellowships, research
// programs, and college-access programs. Same rules as lib/scholarships:
// every entry verified against its OFFICIAL page (VERIFIED_AS_OF shown
// publicly, re-verify yearly via scripts/check-opportunities.mjs), free to
// apply, free or PAID to attend — never tuition-charging camps, never
// resume-harvesting portals. Deadlines stay "Typically <month>" since
// cycles shift; ordering is the academic year (August first), no Date().

export const OPPS_VERIFIED_AS_OF = "July 2026";

export type OpportunityType =
  | "internship"
  | "fellowship"
  | "research"
  | "program";

export type OppStage = "high-school" | "college" | "transfer";

export interface Opportunity {
  id: string;
  name: string;
  type: OpportunityType;
  /** What you actually get: "Paid — $5,000 stipend", "Free + housing". */
  compensation: string;
  /** "Typically March" — cycles shift yearly. */
  deadline: string;
  /** 1-12 for academic-year ordering; null = rolling/varies. */
  deadlineMonth: number | null;
  /** One plain sentence: who it's for. */
  who: string;
  stages: OppStage[];
  /** True ONLY when the official page explicitly says citizenship or a
   *  green card is not required (or DACA-eligible). */
  openToUndocumented?: boolean;
  /** Search keywords — folded into the fuzzy haystack, never displayed. */
  tags?: string[];
  officialUrl: string;
}

export const TYPE_LABELS: Record<OpportunityType, string> = {
  internship: "Internship",
  fellowship: "Fellowship",
  research: "Research",
  program: "Program",
};

export const opportunities: Opportunity[] = [
  // --- Batch 1 (July 13, 2026): three parallel verification passes
  // (fellowships/research, college career pipelines, high-school
  // programs); official pages fetched with evidence. Dropped in
  // verification: Code2040 (defunct), Jopwell (now a recruiter data
  // product), BofA Student Leaders (became college-only), COSMOS
  // (charges tuition), Clark Scholars ($25 application fee), Girls Who
  // Code Summer Immersion (ended; Pathways listed instead), plus
  // fetch-blocked holdouts (LoC Junior Fellows, USAJOBS Pathways, RSI). ---
  {
    id: "nsf-reu",
    name: "NSF Research Experiences for Undergraduates (REU)",
    type: "research",
    compensation: "Paid — stipend, often housing, meals, and travel",
    deadline: "Varies by site; many close January–February",
    deadlineMonth: 2,
    who: "Undergraduates at any U.S. institution, including community college students, doing hands-on summer research in any NSF-funded field.",
    stages: ["college", "transfer"],
    tags: ["STEM", "science", "summer", "paid"],
    officialUrl: "https://www.nsf.gov/crssprgm/reu/",
  },
  {
    id: "amgen-scholars",
    name: "Amgen Scholars Program",
    type: "research",
    compensation: "Fully funded biotech summer research at premier universities",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Undergraduates aiming at science and biotech research careers, hosted at top universities in the U.S. and abroad.",
    stages: ["college"],
    tags: ["biology", "biotech", "STEM", "summer"],
    officialUrl: "https://amgenscholars.com/",
  },
  {
    id: "leadership-alliance-sreip",
    name: "Leadership Alliance Summer Research (SR-EIP)",
    type: "research",
    compensation: "Fully paid 8–10 weeks: stipend, travel, and housing",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Undergraduates with a 3.0+ GPA committed to a PhD or MD-PhD; citizens, nationals, or permanent residents only.",
    stages: ["college"],
    tags: ["PhD", "research", "summer", "graduate school"],
    officialUrl: "https://theleadershipalliance.org/summer-research-early-identification-program",
  },
  {
    id: "mcnair-scholars",
    name: "McNair Scholars Program (federal TRIO)",
    type: "program",
    compensation: "Free — paid research internships, stipends, GRE prep, grad-app support",
    deadline: "Varies by campus program",
    deadlineMonth: null,
    who: "Low-income, first-generation students and those underrepresented in graduate education who aim for a PhD; find your campus's McNair program.",
    stages: ["college", "transfer"],
    tags: ["first-generation", "PhD", "TRIO", "research"],
    officialUrl: "https://www.ed.gov/grants-and-programs/grants-higher-education/federal-trio-programs/ronald-e-mcnair-postbaccalaureate-achievement-program-84217a",
  },
  {
    id: "goldwater",
    name: "Barry Goldwater Scholarship",
    type: "fellowship",
    compensation: "Up to $7,500 a year for STEM research careers",
    deadline: "Typically late January (campus nomination in fall)",
    deadlineMonth: 1,
    who: "Sophomores and juniors with a 3.0+ GPA pursuing research careers in science, math, or engineering; citizens and permanent residents.",
    stages: ["college"],
    tags: ["STEM", "research", "prestigious"],
    officialUrl: "https://goldwaterscholarship.gov/",
  },
  {
    id: "truman",
    name: "Harry S. Truman Scholarship",
    type: "fellowship",
    compensation: "Up to $30,000 for graduate school + leadership network",
    deadline: "Typically early February (campus nomination)",
    deadlineMonth: 2,
    who: "Juniors committed to public-service careers, nominated by their school; U.S. citizens and nationals.",
    stages: ["college"],
    tags: ["public service", "policy", "prestigious", "graduate school"],
    officialUrl: "https://www.truman.gov/apply/applying/eligibility",
  },
  {
    id: "udall",
    name: "Udall Undergraduate Scholarship",
    type: "fellowship",
    compensation: "Up to $7,500 (about 65 a year) + scholar network",
    deadline: "Typically early March (campus nomination)",
    deadlineMonth: 3,
    who: "Sophomores and juniors in environmental fields, or Native American students in tribal policy or Native health care.",
    stages: ["college"],
    tags: ["environment", "Native American", "tribal", "prestigious"],
    officialUrl: "https://www.udall.gov/OurPrograms/Scholarship/Scholarship.aspx",
  },
  {
    id: "ppia-jsi",
    name: "PPIA Junior Summer Institute",
    type: "fellowship",
    compensation: "Fully funded 7 weeks at Harvard, Princeton, or Michigan: stipend, housing, coursework",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Juniors preparing for public-policy careers and grad school; citizens, permanent residents, and DACA recipients may apply to all sites.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["policy", "public service", "summer", "DACA"],
    officialUrl: "https://www.ppiaprogram.org/JSI",
  },
  {
    id: "fulbright-uk-summer",
    name: "Fulbright UK Summer Institutes",
    type: "fellowship",
    compensation: "Fully funded 3–4 weeks in the UK: airfare, tuition, housing",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Freshmen and sophomores (3.6+ GPA, citizens) with little or no travel experience; prioritizes low-income and first-generation students.",
    stages: ["college"],
    tags: ["study abroad", "travel", "first-generation", "summer"],
    officialUrl: "https://fulbright.org.uk/our-programmes/undergraduate-and-pre-university-programmes/uk-summer-institutes/",
  },
  {
    id: "nasa-internships",
    name: "NASA Internships",
    type: "internship",
    compensation: "Paid — stipend by academic level, three sessions a year",
    deadline: "Typically February for summer (Sept/May for other sessions)",
    deadlineMonth: 2,
    who: "U.S. citizens 16+ with a 3.0+ GPA, in college or high school; STEM and non-STEM roles exist.",
    stages: ["college", "transfer", "high-school"],
    tags: ["space", "STEM", "government", "paid"],
    officialUrl: "https://www.nasa.gov/learning-resources/internship-programs/",
  },
  {
    id: "doe-suli",
    name: "DOE National Lab Internships (SULI)",
    type: "internship",
    compensation: "Paid research at one of 17 national laboratories",
    deadline: "Summer deadline typically January",
    deadlineMonth: 1,
    who: "Undergraduates and recent grads in STEM; citizens and permanent residents.",
    stages: ["college", "transfer"],
    tags: ["energy", "STEM", "government", "research", "paid"],
    officialUrl: "https://science.osti.gov/wdts/suli",
  },
  {
    id: "nih-sip",
    name: "NIH Summer Internship Program",
    type: "internship",
    compensation: "Paid biomedical research at NIH; stipend by education level",
    deadline: "Typically mid-February",
    deadlineMonth: 2,
    who: "College students 18+ interested in biomedical research; citizens and permanent residents.",
    stages: ["college"],
    tags: ["health", "medicine", "biology", "research", "paid"],
    officialUrl: "https://www.training.nih.gov/research-training/pb/sip/",
  },
  {
    id: "smithsonian-internships",
    name: "Smithsonian Internships",
    type: "internship",
    compensation: "Varies by unit; many paid (some with weekly stipends)",
    deadline: "Varies by museum; many close January–March",
    deadlineMonth: 2,
    who: "High school through graduate students across 21 museums, research centers, and the zoo; requirements vary by unit.",
    stages: ["college", "high-school"],
    tags: ["museums", "arts", "history", "research"],
    officialUrl: "https://internships.si.edu/",
  },
  {
    id: "seo-career",
    name: "SEO Career",
    type: "internship",
    compensation: "Free training + placement into paid internships (~$10,000 summers)",
    deadline: "Rolling, roughly October–April for summer",
    deadlineMonth: null,
    who: "Black, Hispanic/Latino, and Native American first-years through juniors at four-year colleges (about 3.0+ GPA, U.S. work authorization).",
    stages: ["college"],
    tags: ["finance", "consulting", "corporate", "paid"],
    officialUrl: "https://career.seo-usa.org/",
  },
  {
    id: "inroads",
    name: "INROADS College Internship Program",
    type: "internship",
    compensation: "Paid corporate internships + leadership training and mentorship",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "Undergraduates from underrepresented backgrounds seeking corporate careers.",
    stages: ["college", "transfer"],
    tags: ["corporate", "business", "paid"],
    officialUrl: "https://www.inroads.org/interns/",
  },
  {
    id: "mlt-career-prep",
    name: "MLT Career Prep",
    type: "fellowship",
    compensation: "Free 18-month fellowship: personal coach, seminars, employer access",
    deadline: "Track deadlines August–January",
    deadlineMonth: 1,
    who: "Sophomores from underrepresented backgrounds aiming at business and tech; citizens, permanent residents, and DACA recipients.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["business", "tech", "consulting", "coaching", "DACA"],
    officialUrl: "https://mlt.org/career-prep/",
  },
  {
    id: "year-up",
    name: "Year Up United",
    type: "program",
    compensation: "Tuition-free training + stipend + corporate internship; grads average ~$55,000 starting",
    deadline: "Rolling — multiple cohorts a year",
    deadlineMonth: null,
    who: "Young adults roughly 18–29 without a four-year degree, headed into banking, IT, and corporate roles at 20+ campuses.",
    stages: ["college", "transfer"],
    tags: ["job training", "no degree required", "paid", "career change"],
    officialUrl: "https://www.yearup.org/",
  },
  {
    id: "colorstack",
    name: "ColorStack",
    type: "program",
    compensation: "Free lifetime membership: community, workshops, partner-company pipeline",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "Black and Latinx computer science students at U.S. colleges; 13,000+ members across 1,000+ schools.",
    stages: ["college", "transfer"],
    tags: ["computer science", "tech", "community"],
    officialUrl: "https://www.colorstack.org/",
  },
  {
    id: "t-howard",
    name: "T. Howard Foundation Internships",
    type: "internship",
    compensation: "Paid summer internships in media, entertainment, and tech",
    deadline: "Rolling — opens each August for the next summer",
    deadlineMonth: null,
    who: "College students seeking media, entertainment, and tech careers; open to all students.",
    stages: ["college"],
    tags: ["media", "entertainment", "tech", "paid"],
    officialUrl: "https://www.t-howard.org/",
  },
  {
    id: "emma-bowen",
    name: "Emma Bowen Foundation Fellowship",
    type: "fellowship",
    compensation: "Paid summer internships renewed through graduation + mentorship",
    deadline: "Rolling, roughly September–May",
    deadlineMonth: null,
    who: "Undergraduates (and graduating seniors) with a 3.0+ GPA headed into media and technology; U.S. work authorization required.",
    stages: ["college"],
    tags: ["media", "tech", "paid"],
    officialUrl: "https://www.emmabowenfoundation.org/apply",
  },
  {
    id: "hacu-hnip",
    name: "HACU National Internship Program",
    type: "internship",
    compensation: "Paid federal-agency internships (corporate track too)",
    deadline: "Spring, summer, and fall cohorts",
    deadlineMonth: null,
    who: "Students at HACU member schools, including Hispanic-Serving Institutions and community colleges; 14,000 alumni since 1992.",
    stages: ["college", "transfer"],
    tags: ["government", "federal", "Latino", "Hispanic", "paid"],
    officialUrl: "https://www.hacu.net/hacu/HNIP.asp",
  },
  {
    id: "chci-internship",
    name: "CHCI Congressional Internship",
    type: "internship",
    compensation: "Paid ($4,776 summer) + housing, travel, insurance, Metro stipend",
    deadline: "Typically December (summer) and March (fall)",
    deadlineMonth: 12,
    who: "Full-time Latino/a undergraduates with leadership and public-service commitment; DACA recipients with work authorization eligible.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["government", "policy", "Latino", "Hispanic", "DC", "paid", "DACA"],
    officialUrl: "https://chci.org/programs/congressional-internship-program/",
  },
  {
    id: "cbcf-internships",
    name: "CBCF Congressional Internships",
    type: "internship",
    compensation: "Paid stipend + housing in Washington, D.C.",
    deadline: "Summer, fall, and spring cycles",
    deadlineMonth: null,
    who: "College students and recent grads interested in public policy, especially those serving Black communities.",
    stages: ["college"],
    tags: ["government", "policy", "Black", "DC", "paid"],
    officialUrl: "https://www.cbcfinc.org/internships/",
  },
  {
    id: "girls-who-code-college",
    name: "Girls Who Code College & Career Programs",
    type: "program",
    compensation: "Free — career prep, College Loops chapters, hiring pipeline",
    deadline: "Rolling by program",
    deadlineMonth: null,
    who: "Women and nonbinary students in computer science, ages 18–25.",
    stages: ["college", "transfer"],
    tags: ["women", "computer science", "tech"],
    officialUrl: "https://girlswhocode.com/programs",
  },
  {
    id: "rewriting-the-code",
    name: "Rewriting the Code",
    type: "program",
    compensation: "Free membership: mentors, career programs, members-only job portal",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "University students and early-career women in tech across the U.S., Canada, UK, and Ireland.",
    stages: ["college", "transfer"],
    tags: ["women", "tech", "community"],
    officialUrl: "https://rewritingthecode.org/",
  },
  {
    id: "seo-scholars",
    name: "SEO Scholars",
    type: "program",
    compensation: "Free 8-year academic + mentoring program, high school through college",
    deadline: "Typically December of 9th grade (varies by city)",
    deadlineMonth: 12,
    who: "Low-income public school 9th graders in NYC, San Francisco, Miami, or North Carolina; 85% college graduation rate.",
    stages: ["high-school"],
    tags: ["college access", "mentoring", "first-generation", "regional"],
    officialUrl: "https://www.seo-usa.org/scholars/",
  },
  {
    id: "leda-scholars",
    name: "LEDA Scholars Program",
    type: "program",
    compensation: "Free — 7-week summer institute at Princeton + years of college guidance",
    deadline: "Typically December of junior year",
    deadlineMonth: 12,
    who: "High-achieving public school juniors from under-resourced backgrounds; about 100 selected a year.",
    stages: ["high-school"],
    tags: ["college access", "leadership", "first-generation"],
    officialUrl: "https://ledascholars.org/our-program/leda-scholars-program/",
  },
  {
    id: "questbridge-prep",
    name: "QuestBridge College Prep Scholars",
    type: "program",
    compensation: "Free — summer-program scholarships, conferences, essay coaching",
    deadline: "Typically late March of junior year",
    deadlineMonth: 3,
    who: "Juniors from households typically under $65,000 (family of four) earning mostly A's in challenging courses.",
    stages: ["high-school"],
    tags: ["college access", "low income", "juniors"],
    officialUrl: "https://www.questbridge.org/high-school-students/college-prep-scholars",
  },
  {
    id: "mites-summer",
    name: "MITES Summer (MIT)",
    type: "program",
    compensation: "Free — housing and meals included; you cover travel only",
    deadline: "Typically February of junior year",
    deadlineMonth: 2,
    who: "Juniors, especially underrepresented, low-income, and first-generation students; citizens and permanent residents.",
    stages: ["high-school"],
    tags: ["STEM", "engineering", "MIT", "summer"],
    officialUrl: "https://mites.mit.edu/discover-mites/mites-summer/",
  },
  {
    id: "trio-upward-bound",
    name: "TRIO Upward Bound (find your local program)",
    type: "program",
    compensation: "Free — tutoring, summer instruction, and counseling at ~1,000 sites",
    deadline: "Varies by local program",
    deadlineMonth: null,
    who: "Students 13–19 from low-income families or who would be first-generation college students; apply through a local project.",
    stages: ["high-school"],
    tags: ["TRIO", "college access", "first-generation", "tutoring"],
    officialUrl: "https://www.ed.gov/grants-and-programs/grants-higher-education/federal-trio-programs/upward-bound-program-84047a",
  },
  {
    id: "telluride-tass",
    name: "Telluride Association Summer Seminar (TASS)",
    type: "program",
    compensation: "Free — tuition, room, board, books, travel help, even lost-summer-earnings aid",
    deadline: "Typically early December",
    deadlineMonth: 12,
    who: "Sophomores and juniors ages 15–17 for critical-thinking seminars; U.S. and international students welcome.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["humanities", "seminar", "summer"],
    officialUrl: "https://tellurideassociation.org/tass/",
  },
  {
    id: "cmu-sams",
    name: "Carnegie Mellon SAMS",
    type: "program",
    compensation: "Free, fully funded with housing; you cover travel only",
    deadline: "Typically February 1",
    deadlineMonth: 2,
    who: "Juniors at least 16 from groups underrepresented in STEM; citizens and permanent residents.",
    stages: ["high-school"],
    tags: ["STEM", "math", "science", "summer"],
    officialUrl: "https://www.cmu.edu/pre-college/academic-programs/sams.html",
  },
  {
    id: "simons-summer-research",
    name: "Simons Summer Research Program",
    type: "research",
    compensation: "Free + stipend award; faculty-mentored lab research at Stony Brook",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Current juniors at least 16 doing hands-on research; citizens and permanent residents only.",
    stages: ["high-school"],
    tags: ["STEM", "research", "summer", "lab"],
    officialUrl: "https://www.stonybrook.edu/simons/",
  },
  {
    id: "gwc-pathways",
    name: "Girls Who Code Pathways",
    type: "program",
    compensation: "Free, 100% virtual — AI, cybersecurity, game design, web dev tracks",
    deadline: "Typically April (early deadline February)",
    deadlineMonth: 4,
    who: "Girls and nonbinary students in grades 9–12, anywhere in the U.S.; the in-person Summer Immersion ended after 2025.",
    stages: ["high-school"],
    tags: ["women", "coding", "virtual", "computer science"],
    officialUrl: "https://girlswhocode.com/programs/pathways",
  },
  {
    id: "nyu-arise",
    name: "NYU ARISE",
    type: "research",
    compensation: "Free + $2,000 stipend — 10 weeks with NYU lab research",
    deadline: "Typically late February",
    deadlineMonth: 2,
    who: "NYC rising juniors and seniors attending NYC schools full-time.",
    stages: ["high-school"],
    tags: ["STEM", "research", "NYC", "New York", "regional", "paid"],
    officialUrl: "https://k12stem.engineering.nyu.edu/programs/arise",
  },
  {
    id: "jackson-lab-ssp",
    name: "Jackson Laboratory Summer Student Program",
    type: "research",
    compensation: "Paid — $7,500 stipend plus room, board, and travel",
    deadline: "Typically late January",
    deadlineMonth: 1,
    who: "Graduating seniors and undergraduates for 10 weeks of mentored genetics research in Maine or Connecticut.",
    stages: ["high-school", "college"],
    tags: ["genetics", "biology", "research", "paid"],
    officialUrl: "https://www.jax.org/education-and-learning/high-school-students-and-undergraduates/learn-earn-and-explore",
  },
  // --- Batch 2 (July 13, 2026): three parallel verification passes
  // (corporate early-ID, gov/defense/health paid research, media/civics/
  // HS access); official pages fetched with evidence. Dropped in
  // verification — do NOT list: Meta University (discontinued),
  // Google STEP (effectively ended), D.E. Shaw fellowships (site gone,
  // likely discontinued), Palantir Path (superseded), Woods Hole PEP
  // (discontinued 2025), CDC Ferguson Fellowship (now grad-only),
  // White House Internship (unpaid), Prep for Prep (applicants are
  // 5th-7th graders, younger than this list serves), 826 National
  // (enrichment tutoring, skews younger, no compensation), Bloomberg/
  // Citadel (403-walled, unverifiable), Two Sigma (no live early-ID
  // track). BofA Student Leaders returns as early-COLLEGE (2026
  // eligibility change, noted in its entry). ---
  {
    id: "microsoft-explore",
    name: "Microsoft Explore Internship",
    type: "internship",
    compensation: "Paid — 12-week summer software internship",
    deadline: "Rolling — apply in early fall before slots fill",
    deadlineMonth: null,
    who: "First- and second-year college students who have taken an intro CS course and a semester of calculus; you don't have to be a CS major.",
    stages: ["college"],
    tags: ["tech", "coding", "software", "computer science", "freshman", "sophomore"],
    officialUrl: "https://careers.microsoft.com/v2/global/en/exploremicrosoft",
  },
  {
    id: "jane-street-amp",
    name: "Jane Street AMP (Academy of Math and Programming)",
    type: "program",
    compensation: "Free — tuition, housing, meals, and travel covered, plus a $5,000 scholarship",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Graduating high school seniors into math and computer science who've faced barriers to advanced STEM opportunities; five weeks in the summer before college.",
    stages: ["high-school"],
    tags: ["math", "coding", "finance", "summer", "scholarship"],
    officialUrl: "https://www.janestreet.com/join-jane-street/programs-and-events/amp/",
  },
  {
    id: "jane-street-insight",
    name: "Jane Street INSIGHT",
    type: "program",
    compensation: "Free — travel, housing, and a daily stipend provided",
    deadline: "Rolling — cohorts announced on the programs page",
    deadlineMonth: null,
    who: "College students who are women, transgender, or gender-expansive, curious about trading and technology; no finance background needed.",
    stages: ["college"],
    tags: ["finance", "trading", "women", "tech"],
    officialUrl: "https://www.janestreet.com/join-jane-street/programs-and-events/insight/",
  },
  {
    id: "girls-who-invest",
    name: "Girls Who Invest Summer Intensive",
    type: "program",
    compensation: "Free training; top performers move to paid internships at investment firms",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "First-years and sophomores of all gender identities interested in investment management careers.",
    stages: ["college"],
    tags: ["finance", "investing", "women", "internship track"],
    officialUrl: "https://www.girlswhoinvest.org/apply-faq",
  },
  {
    id: "codepath",
    name: "CodePath",
    type: "program",
    compensation: "Free — 10-week virtual tech courses plus career services",
    deadline: "Typically August for the fall cohort; runs several times a year",
    deadlineMonth: 8,
    who: "College students in CS and tech — built for first-generation and low-income students, at any campus.",
    stages: ["college", "transfer"],
    tags: ["coding", "tech", "virtual", "interview prep", "cybersecurity", "AI"],
    officialUrl: "https://www.codepath.org/courses",
  },
  {
    id: "braven",
    name: "Braven Accelerator",
    type: "program",
    compensation: "Free — semester-long career course (stipend on the BravenX track)",
    deadline: "Rolling — sign up through your campus",
    deadlineMonth: null,
    who: "Undergraduates at Braven partner colleges (SJSU, Rutgers–Newark, NIU, CUNY Lehman, UMass Lowell, and more), largely first-gen and Pell-eligible students.",
    stages: ["college", "transfer"],
    tags: ["career", "first-gen", "job readiness"],
    officialUrl: "https://braven.org/",
  },
  {
    id: "america-needs-you",
    name: "America Needs You Fellows Program",
    type: "fellowship",
    compensation: "Free — two-year mentorship plus up to $1,000 in grants each year",
    deadline: "Typically opens November; deadlines vary by state",
    deadlineMonth: 11,
    who: "First-generation college students in New York, New Jersey, and Illinois; a dedicated mentor coach and 15 career workshops a year.",
    stages: ["college", "transfer"],
    tags: ["first-gen", "mentorship", "career", "regional", "New York", "New Jersey", "Illinois"],
    officialUrl: "https://americaneedsyou.org/what-we-do/fellows-program/",
  },
  {
    id: "genesys-works",
    name: "Genesys Works",
    type: "internship",
    compensation: "Paid — year-long corporate internship during senior year",
    deadline: "Rolling — apply as a junior",
    deadlineMonth: null,
    who: "High school juniors in underserved communities in the Bay Area, Chicago, Houston, Jacksonville, Nashville, the D.C. region, NYC, Tulsa, and the Twin Cities; free skills training the summer before.",
    stages: ["high-school"],
    tags: ["paid", "corporate", "regional", "career", "high school"],
    officialUrl: "https://genesysworks.org/",
  },
  {
    id: "uber-career-prep",
    name: "Uber Career Prep",
    type: "program",
    compensation: "Free — workshops, 1:1 engineer mentorship, and mock technical interviews",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "Undergraduate engineering and CS students facing barriers to breaking into tech; mentorship comes from a working Uber software engineer.",
    stages: ["college"],
    tags: ["tech", "coding", "mentorship", "interview prep"],
    officialUrl: "https://jobs.uber.com/en/teams/emerging-talent/careerprep/",
  },
  {
    id: "npower",
    name: "NPower",
    type: "program",
    compensation: "Free — tech training and industry certifications, with job placement help",
    deadline: "Rolling — cohorts start through the year",
    deadlineMonth: null,
    who: "Young adults roughly 18–26 with a high school diploma or equivalent (plus military-connected people); no college degree required, and graduates average three times their prior income.",
    stages: ["high-school", "college"],
    tags: ["tech", "certification", "no degree", "career change", "job placement"],
    officialUrl: "https://www.npower.org/",
  },
  {
    id: "bofa-student-leaders",
    name: "Bank of America Student Leaders",
    type: "internship",
    compensation: "Paid — $17/hour or local minimum wage for six weeks, plus an all-expenses leadership summit",
    deadline: "Typically mid-March",
    deadlineMonth: 3,
    who: "Early college students (18+, high school diploma within the last two years, 12–18 college credits) interning at a national nonprofit. Heads up: eligibility moved from high school to early college in 2026 — many guides haven't caught up.",
    stages: ["college"],
    tags: ["paid", "nonprofit", "leadership", "summer"],
    officialUrl: "https://about.bankofamerica.com/en/making-an-impact/student-leaders",
  },
  {
    id: "noaa-hollings",
    name: "NOAA Ernest F. Hollings Scholarship",
    type: "fellowship",
    compensation: "Up to $9,500/year for two years, plus a paid NOAA summer internship ($700/week)",
    deadline: "Typically January; opens each September",
    deadlineMonth: 1,
    who: "Second-year students at four-year colleges (or community college students transferring to one) with a 3.0+ GPA in science, math, engineering, or education.",
    stages: ["college", "transfer"],
    tags: ["STEM", "ocean", "weather", "scholarship", "paid", "federal"],
    officialUrl: "https://www.noaa.gov/office-education/hollings-scholarship",
  },
  {
    id: "noaa-epp-msi",
    name: "NOAA EPP/MSI Undergraduate Scholarship",
    type: "fellowship",
    compensation: "Up to $45,000 over two years, including two paid NOAA summer internships",
    deadline: "Typically January; shared application with Hollings",
    deadlineMonth: 1,
    who: "Second-year students at minority-serving institutions (or transferring from a two-year to a four-year MSI) with a 3.2+ GPA in NOAA mission fields.",
    stages: ["college", "transfer"],
    tags: ["STEM", "MSI", "HBCU", "scholarship", "paid", "federal"],
    officialUrl: "https://www.noaa.gov/office-education/epp-msi/undergraduate-scholarship",
  },
  {
    id: "nreip",
    name: "Naval Research Enterprise Internship (NREIP)",
    type: "internship",
    compensation: "Paid — $7,500–$9,000 stipend for 10 summer weeks at Navy labs",
    deadline: "Typically November; opens August 1",
    deadlineMonth: 11,
    who: "Undergraduates from rising sophomores through seniors at four-year U.S. colleges, placed across 62 Department of Navy laboratories.",
    stages: ["college"],
    tags: ["STEM", "defense", "research", "paid", "federal", "summer"],
    officialUrl: "https://navalsteminterns.us/nreip/",
  },
  {
    id: "aeop-internships",
    name: "AEOP Internships (Army labs — SEAP, CQL, URAP)",
    type: "internship",
    compensation: "Paid — educational stipend at Army and DoD laboratories",
    deadline: "Varies by position; many roll year-round",
    deadlineMonth: null,
    who: "High school students and undergraduates living within commuting distance of a participating Army or DoD lab; no application fee.",
    stages: ["high-school", "college"],
    tags: ["STEM", "defense", "research", "paid", "federal", "high school"],
    officialUrl: "https://aeopinternships-fellowships.org/internships/",
  },
  {
    id: "nist-surf",
    name: "NIST Summer Undergraduate Research Fellowship (SURF)",
    type: "research",
    compensation: "Paid — $7,810 for 11 weeks plus up to $4,500 housing and $500 travel",
    deadline: "Opens mid-October — check the close date on the NIST page",
    deadlineMonth: null,
    who: "Full-time undergraduates at two- or four-year U.S. colleges, from first-years through seniors, age 18+, doing measurement-science research.",
    stages: ["college", "transfer"],
    tags: ["STEM", "physics", "engineering", "research", "paid", "federal"],
    officialUrl: "https://www.nist.gov/surf",
  },
  {
    id: "shpep",
    name: "Summer Health Professions Education Program (SHPEP)",
    type: "program",
    compensation: "Free + housing, meals, and a stipend",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "College freshmen through juniors (2.5+ GPA) from economically or educationally disadvantaged backgrounds headed toward health professions. Heads up: 2026 was the final cohort under current funding — check the site for the next cycle.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["health", "medicine", "dental", "pre-med", "DACA", "summer"],
    officialUrl: "https://www.shpep.org/",
  },
  {
    id: "mayo-surf",
    name: "Mayo Clinic Summer Undergraduate Research Fellowship",
    type: "research",
    compensation: "Paid — $6,000 for 10 weeks of biomedical research",
    deadline: "Typically early February; opens November 1",
    deadlineMonth: 2,
    who: "Undergraduates past sophomore year with a 3.0+ GPA seriously considering a Ph.D. or M.D.–Ph.D. research career; campuses in Minnesota, Arizona, and Florida.",
    stages: ["college"],
    tags: ["health", "biomedical", "research", "paid", "pre-med"],
    officialUrl: "https://college.mayo.edu/academics/biomedical-research-training/summer-undergraduate-research-fellowship-surf/",
  },
  {
    id: "cdc-lewis-scholars",
    name: "CDC John R. Lewis Undergraduate Public Health Scholars",
    type: "program",
    compensation: "Paid summer public-health training at one of seven host universities",
    deadline: "Opens each fall; deadlines vary by host",
    deadlineMonth: null,
    who: "Undergraduates and recent grads interested in minority health and health equity, hosted at Columbia, Morehouse, UCLA, Michigan, Pitt, Kennedy Krieger, and the Southern Plains Tribal Health Board.",
    stages: ["college"],
    tags: ["health", "public health", "equity", "paid", "federal", "summer"],
    officialUrl: "https://www.cdc.gov/minority-health/student-programs/internships-fellowships.html",
  },
  {
    id: "afrl-scholars",
    name: "AFRL Scholars Program (Air Force Research Lab)",
    type: "internship",
    compensation: "Paid — roughly $507/week for high schoolers, $622–$870/week for undergrads",
    deadline: "Typically early January; opens in October",
    deadlineMonth: 1,
    who: "U.S. citizen students 16+ enrolled at least half-time in high school or college, working full-time on-site at an Air Force Research Laboratory for the summer.",
    stages: ["high-school", "college"],
    tags: ["STEM", "defense", "research", "paid", "federal", "high school", "summer"],
    officialUrl: "https://afrlscholars.usra.edu/",
  },
  {
    id: "epa-pathways",
    name: "EPA Pathways Internships",
    type: "internship",
    compensation: "Paid — federal internships at GS-02 to GS-07 pay",
    deadline: "Rolling — posted on USAJOBS through the year",
    deadlineMonth: null,
    who: "Students enrolled at least half-time at a college or university, interested in environmental careers; summer, semester, and year-round options.",
    stages: ["college"],
    tags: ["environment", "climate", "paid", "federal"],
    officialUrl: "https://www.epa.gov/careers/students",
  },
  {
    id: "usgs-pathways",
    name: "USGS Pathways Internships",
    type: "internship",
    compensation: "Paid — part- or full-time, with possible conversion to a permanent federal job",
    deadline: "Rolling — summer roles usually post December–February",
    deadlineMonth: null,
    who: "Students enrolled at least part-time in high school, community college, four-year college, or vocational programs, interested in earth and natural science.",
    stages: ["high-school", "college", "transfer"],
    tags: ["science", "geology", "environment", "paid", "federal", "high school"],
    officialUrl: "https://www.usgs.gov/human-capital/students-and-recent-graduates",
  },
  {
    id: "usda-ars-internships",
    name: "USDA ARS Student Internships (Pathways & HACU)",
    type: "internship",
    compensation: "Paid — up to GS-11 pay; the HACU track pays $15.25/hour",
    deadline: "Rolling — posted on USAJOBS as funding opens",
    deadlineMonth: null,
    who: "High school, college, and trade school students enrolled at least half-time with a 2.0+ GPA (HACU track: 3.0+ at HACU-member schools) in agriculture and food science.",
    stages: ["high-school", "college"],
    tags: ["agriculture", "science", "paid", "federal", "Hispanic", "high school"],
    officialUrl: "https://aglab.ars.usda.gov/the-future-is-now/we-re-looking-for-innovators",
  },
  {
    id: "princeton-summer-journalism",
    name: "Princeton Summer Journalism Program",
    type: "program",
    compensation: "Free — summer journalism intensive plus a personal college adviser through senior year",
    deadline: "Typically January; opens early December",
    deadlineMonth: 1,
    who: "High school juniors nationwide from limited-income families (roughly $65,000 or free/reduced lunch) with about a 3.5 GPA and an interest in journalism.",
    stages: ["high-school"],
    tags: ["journalism", "writing", "media", "college access", "low-income"],
    officialUrl: "https://psjp.princeton.edu/",
  },
  {
    id: "aaja-jcamp",
    name: "AAJA JCamp",
    type: "program",
    compensation: "Free — six-day journalism camp with travel, lodging, and meals covered",
    deadline: "Typically early-to-mid January",
    deadlineMonth: 1,
    who: "High school sophomores and juniors nationwide, all backgrounds welcome — training from working journalists and hands-on news production.",
    stages: ["high-school"],
    tags: ["journalism", "media", "writing", "high school", "free travel"],
    officialUrl: "https://www.aaja.org/programs/for-students/jcamp/",
  },
  {
    id: "state-dept-internship",
    name: "U.S. Department of State Student Internship",
    type: "internship",
    compensation: "Paid — about $18/hour, plus travel covered and housing help",
    deadline: "Typically October for the summer cycle",
    deadlineMonth: 10,
    who: "U.S.-citizen college juniors and seniors with 60+ credit hours and a 3.2 GPA, working in D.C. bureaus, U.S. offices, or the U.S. Mission to the UN.",
    stages: ["college"],
    tags: ["government", "diplomacy", "policy", "paid", "federal", "D.C."],
    officialUrl: "https://careers.state.gov/interns-fellows/student-internship-program/",
  },
  {
    id: "npr-internships",
    name: "NPR Internships",
    type: "internship",
    compensation: "Paid — $20/hour; onsite in D.C., hybrid, or fully remote",
    deadline: "Rolling by session — each posting stays open about two weeks",
    deadlineMonth: null,
    who: "Current college students or grads within 12 months, anywhere in the U.S. — newsroom, podcasts, digital, design, and business teams.",
    stages: ["college"],
    tags: ["journalism", "media", "radio", "podcast", "paid", "remote"],
    officialUrl: "https://www.npr.org/about-npr/181881227/want-to-be-an-npr-intern",
  },
  {
    id: "kode-with-klossy",
    name: "Kode with Klossy Summer Camps",
    type: "program",
    compensation: "Free — two-week virtual coding camps",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Young women and gender-expansive youth ages 13–18 anywhere in the U.S.; tracks in web dev, mobile apps, data science, and AI — no experience needed.",
    stages: ["high-school"],
    tags: ["coding", "women", "virtual", "tech", "high school", "summer"],
    officialUrl: "https://www.kodewithklossy.com/",
  },
  {
    id: "ai4all-ignite",
    name: "AI4ALL Ignite",
    type: "program",
    compensation: "Free — two-semester virtual AI accelerator with industry mentors",
    deadline: "Typically April; opens in winter",
    deadlineMonth: 4,
    who: "U.S. undergraduates (community college students included) majoring or minoring in CS, data science, or a related field, with basic Python.",
    stages: ["college", "transfer"],
    tags: ["AI", "tech", "coding", "mentorship", "virtual", "portfolio"],
    officialUrl: "https://ai-4-all.org/",
  },
  {
    id: "sadie-nash",
    name: "Sadie Nash Leadership Project — Summer Institute",
    type: "program",
    compensation: "Free + a $450 stipend — six-week summer leadership program",
    deadline: "Typically mid-March",
    deadlineMonth: 3,
    who: "Young women and gender-expansive high schoolers in New York City or Newark, NJ; no academic or skill criteria for admission.",
    stages: ["high-school"],
    tags: ["leadership", "women", "NYC", "Newark", "regional", "stipend", "high school"],
    officialUrl: "https://sadienash.org/summer-institute/",
  },
  {
    id: "bottom-line",
    name: "Bottom Line",
    type: "program",
    compensation: "Free — one-on-one college advising from senior year through college graduation",
    deadline: "Varies by region — apply during senior year",
    deadlineMonth: null,
    who: "First-generation high school seniors from low-income households in Massachusetts, Chicago, Detroit, Houston, New York City, and Ohio (roughly 2.5+ GPA).",
    stages: ["high-school", "college"],
    tags: ["college access", "advising", "first-gen", "regional", "FAFSA"],
    officialUrl: "https://www.bottomline.org/",
  },
  {
    id: "minds-matter",
    name: "Minds Matter",
    type: "program",
    compensation: "Free — two mentors, weekly sessions, test prep, and summer program placements",
    deadline: "Varies by chapter — typically fall of sophomore year",
    deadlineMonth: null,
    who: "Driven high schoolers from low-income families in chapter cities including NYC, Boston, Chicago, Denver, Detroit, Houston, LA, Philadelphia, Portland, and Seattle.",
    stages: ["high-school"],
    tags: ["mentorship", "college access", "test prep", "regional", "high school"],
    officialUrl: "https://mindsmatternyc.org/",
  },
];
