// Internships & opportunities (July 2026, owner ask): the experience side
// of the student money story — paid internships, fellowships, research
// programs, and college-access programs. Same rules as lib/scholarships:
// every entry verified against its OFFICIAL page (VERIFIED_AS_OF shown
// publicly, re-verify yearly via scripts/check-opportunities.mjs), free to
// apply, free or PAID to attend — never tuition-charging camps, never
// resume-harvesting portals. Deadlines stay "Typically <month>" since
// cycles shift; ordering is the academic year (August first), no Date().

export const OPPS_VERIFIED_AS_OF = "July 2026";

export type OpportunityType =
  | "internship"
  | "fellowship"
  | "research"
  | "program";

export type OppStage = "high-school" | "college" | "transfer";

export interface Opportunity {
  id: string;
  name: string;
  type: OpportunityType;
  /** What you actually get: "Paid — $5,000 stipend", "Free + housing". */
  compensation: string;
  /** "Typically March" — cycles shift yearly. */
  deadline: string;
  /** 1-12 for academic-year ordering; null = rolling/varies. */
  deadlineMonth: number | null;
  /** One plain sentence: who it's for. */
  who: string;
  stages: OppStage[];
  /** True ONLY when the official page explicitly says citizenship or a
   *  green card is not required (or DACA-eligible). */
  openToUndocumented?: boolean;
  /** Search keywords — folded into the fuzzy haystack, never displayed. */
  tags?: string[];
  officialUrl: string;
}

export const TYPE_LABELS: Record<OpportunityType, string> = {
  internship: "Internship",
  fellowship: "Fellowship",
  research: "Research",
  program: "Program",
};

export const opportunities: Opportunity[] = [
  // --- Batch 1 (July 13, 2026): three parallel verification passes
  // (fellowships/research, college career pipelines, high-school
  // programs); official pages fetched with evidence. Dropped in
  // verification: Code2040 (defunct), Jopwell (now a recruiter data
  // product), BofA Student Leaders (became college-only), COSMOS
  // (charges tuition), Clark Scholars ($25 application fee), Girls Who
  // Code Summer Immersion (ended; Pathways listed instead), plus
  // fetch-blocked holdouts (LoC Junior Fellows, USAJOBS Pathways, RSI). ---
  {
    id: "nsf-reu",
    name: "NSF Research Experiences for Undergraduates (REU)",
    type: "research",
    compensation: "Paid — stipend, often housing, meals, and travel",
    deadline: "Varies by site; many close January–February",
    deadlineMonth: 2,
    who: "Undergraduates at any U.S. institution, including community college students, doing hands-on summer research in any NSF-funded field.",
    stages: ["college", "transfer"],
    tags: ["STEM", "science", "summer", "paid"],
    officialUrl: "https://www.nsf.gov/crssprgm/reu/",
  },
  {
    id: "amgen-scholars",
    name: "Amgen Scholars Program",
    type: "research",
    compensation: "Fully funded biotech summer research at premier universities",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Undergraduates aiming at science and biotech research careers, hosted at top universities in the U.S. and abroad.",
    stages: ["college"],
    tags: ["biology", "biotech", "STEM", "summer"],
    officialUrl: "https://amgenscholars.com/",
  },
  {
    id: "leadership-alliance-sreip",
    name: "Leadership Alliance Summer Research (SR-EIP)",
    type: "research",
    compensation: "Fully paid 8–10 weeks: stipend, travel, and housing",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Undergraduates with a 3.0+ GPA committed to a PhD or MD-PhD; citizens, nationals, or permanent residents only.",
    stages: ["college"],
    tags: ["PhD", "research", "summer", "graduate school"],
    officialUrl: "https://theleadershipalliance.org/summer-research-early-identification-program",
  },
  {
    id: "mcnair-scholars",
    name: "McNair Scholars Program (federal TRIO)",
    type: "program",
    compensation: "Free — paid research internships, stipends, GRE prep, grad-app support",
    deadline: "Varies by campus program",
    deadlineMonth: null,
    who: "Low-income, first-generation students and those underrepresented in graduate education who aim for a PhD; find your campus's McNair program.",
    stages: ["college", "transfer"],
    tags: ["first-generation", "PhD", "TRIO", "research"],
    officialUrl: "https://www.ed.gov/grants-and-programs/grants-higher-education/federal-trio-programs/ronald-e-mcnair-postbaccalaureate-achievement-program-84217a",
  },
  {
    id: "goldwater",
    name: "Barry Goldwater Scholarship",
    type: "fellowship",
    compensation: "Up to $7,500 a year for STEM research careers",
    deadline: "Typically late January (campus nomination in fall)",
    deadlineMonth: 1,
    who: "Sophomores and juniors with a 3.0+ GPA pursuing research careers in science, math, or engineering; citizens and permanent residents.",
    stages: ["college"],
    tags: ["STEM", "research", "prestigious"],
    officialUrl: "https://goldwaterscholarship.gov/",
  },
  {
    id: "truman",
    name: "Harry S. Truman Scholarship",
    type: "fellowship",
    compensation: "Up to $30,000 for graduate school + leadership network",
    deadline: "Typically early February (campus nomination)",
    deadlineMonth: 2,
    who: "Juniors committed to public-service careers, nominated by their school; U.S. citizens and nationals.",
    stages: ["college"],
    tags: ["public service", "policy", "prestigious", "graduate school"],
    officialUrl: "https://www.truman.gov/apply/applying/eligibility",
  },
  {
    id: "udall",
    name: "Udall Undergraduate Scholarship",
    type: "fellowship",
    compensation: "Up to $7,500 (about 65 a year) + scholar network",
    deadline: "Typically early March (campus nomination)",
    deadlineMonth: 3,
    who: "Sophomores and juniors in environmental fields, or Native American students in tribal policy or Native health care.",
    stages: ["college"],
    tags: ["environment", "Native American", "tribal", "prestigious"],
    officialUrl: "https://www.udall.gov/OurPrograms/Scholarship/Scholarship.aspx",
  },
  {
    id: "ppia-jsi",
    name: "PPIA Junior Summer Institute",
    type: "fellowship",
    compensation: "Fully funded 7 weeks at Harvard, Princeton, or Michigan: stipend, housing, coursework",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Juniors preparing for public-policy careers and grad school; citizens, permanent residents, and DACA recipients may apply to all sites.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["policy", "public service", "summer", "DACA"],
    officialUrl: "https://www.ppiaprogram.org/JSI",
  },
  {
    id: "fulbright-uk-summer",
    name: "Fulbright UK Summer Institutes",
    type: "fellowship",
    compensation: "Fully funded 3–4 weeks in the UK: airfare, tuition, housing",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Freshmen and sophomores (3.6+ GPA, citizens) with little or no travel experience; prioritizes low-income and first-generation students.",
    stages: ["college"],
    tags: ["study abroad", "travel", "first-generation", "summer"],
    officialUrl: "https://fulbright.org.uk/our-programmes/undergraduate-and-pre-university-programmes/uk-summer-institutes/",
  },
  {
    id: "nasa-internships",
    name: "NASA Internships",
    type: "internship",
    compensation: "Paid — stipend by academic level, three sessions a year",
    deadline: "Typically February for summer (Sept/May for other sessions)",
    deadlineMonth: 2,
    who: "U.S. citizens 16+ with a 3.0+ GPA, in college or high school; STEM and non-STEM roles exist.",
    stages: ["college", "transfer", "high-school"],
    tags: ["space", "STEM", "government", "paid"],
    officialUrl: "https://www.nasa.gov/learning-resources/internship-programs/",
  },
  {
    id: "doe-suli",
    name: "DOE National Lab Internships (SULI)",
    type: "internship",
    compensation: "Paid research at one of 17 national laboratories",
    deadline: "Summer deadline typically January",
    deadlineMonth: 1,
    who: "Undergraduates and recent grads in STEM; citizens and permanent residents.",
    stages: ["college", "transfer"],
    tags: ["energy", "STEM", "government", "research", "paid"],
    officialUrl: "https://science.osti.gov/wdts/suli",
  },
  {
    id: "nih-sip",
    name: "NIH Summer Internship Program",
    type: "internship",
    compensation: "Paid biomedical research at NIH; stipend by education level",
    deadline: "Typically mid-February",
    deadlineMonth: 2,
    who: "College students 18+ interested in biomedical research; citizens and permanent residents.",
    stages: ["college"],
    tags: ["health", "medicine", "biology", "research", "paid"],
    officialUrl: "https://www.training.nih.gov/research-training/pb/sip/",
  },
  {
    id: "smithsonian-internships",
    name: "Smithsonian Internships",
    type: "internship",
    compensation: "Varies by unit; many paid (some with weekly stipends)",
    deadline: "Varies by museum; many close January–March",
    deadlineMonth: 2,
    who: "High school through graduate students across 21 museums, research centers, and the zoo; requirements vary by unit.",
    stages: ["college", "high-school"],
    tags: ["museums", "arts", "history", "research"],
    officialUrl: "https://internships.si.edu/",
  },
  {
    id: "seo-career",
    name: "SEO Career",
    type: "internship",
    compensation: "Free training + placement into paid internships (~$10,000 summers)",
    deadline: "Rolling, roughly October–April for summer",
    deadlineMonth: null,
    who: "Black, Hispanic/Latino, and Native American first-years through juniors at four-year colleges (about 3.0+ GPA, U.S. work authorization).",
    stages: ["college"],
    tags: ["finance", "consulting", "corporate", "paid"],
    officialUrl: "https://career.seo-usa.org/",
  },
  {
    id: "inroads",
    name: "INROADS College Internship Program",
    type: "internship",
    compensation: "Paid corporate internships + leadership training and mentorship",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "Undergraduates from underrepresented backgrounds seeking corporate careers.",
    stages: ["college", "transfer"],
    tags: ["corporate", "business", "paid"],
    officialUrl: "https://www.inroads.org/interns/",
  },
  {
    id: "mlt-career-prep",
    name: "MLT Career Prep",
    type: "fellowship",
    compensation: "Free 18-month fellowship: personal coach, seminars, employer access",
    deadline: "Track deadlines August–January",
    deadlineMonth: 1,
    who: "Sophomores from underrepresented backgrounds aiming at business and tech; citizens, permanent residents, and DACA recipients.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["business", "tech", "consulting", "coaching", "DACA"],
    officialUrl: "https://mlt.org/career-prep/",
  },
  {
    id: "year-up",
    name: "Year Up United",
    type: "program",
    compensation: "Tuition-free training + stipend + corporate internship; grads average ~$55,000 starting",
    deadline: "Rolling — multiple cohorts a year",
    deadlineMonth: null,
    who: "Young adults roughly 18–29 without a four-year degree, headed into banking, IT, and corporate roles at 20+ campuses.",
    stages: ["college", "transfer"],
    tags: ["job training", "no degree required", "paid", "career change"],
    officialUrl: "https://www.yearup.org/",
  },
  {
    id: "colorstack",
    name: "ColorStack",
    type: "program",
    compensation: "Free lifetime membership: community, workshops, partner-company pipeline",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "Black and Latinx computer science students at U.S. colleges; 13,000+ members across 1,000+ schools.",
    stages: ["college", "transfer"],
    tags: ["computer science", "tech", "community"],
    officialUrl: "https://www.colorstack.org/",
  },
  {
    id: "t-howard",
    name: "T. Howard Foundation Internships",
    type: "internship",
    compensation: "Paid summer internships in media, entertainment, and tech",
    deadline: "Rolling — opens each August for the next summer",
    deadlineMonth: null,
    who: "College students seeking media, entertainment, and tech careers; open to all students.",
    stages: ["college"],
    tags: ["media", "entertainment", "tech", "paid"],
    officialUrl: "https://www.t-howard.org/",
  },
  {
    id: "emma-bowen",
    name: "Emma Bowen Foundation Fellowship",
    type: "fellowship",
    compensation: "Paid summer internships renewed through graduation + mentorship",
    deadline: "Rolling, roughly September–May",
    deadlineMonth: null,
    who: "Undergraduates (and graduating seniors) with a 3.0+ GPA headed into media and technology; U.S. work authorization required.",
    stages: ["college"],
    tags: ["media", "tech", "paid"],
    officialUrl: "https://www.emmabowenfoundation.org/apply",
  },
  {
    id: "hacu-hnip",
    name: "HACU National Internship Program",
    type: "internship",
    compensation: "Paid federal-agency internships (corporate track too)",
    deadline: "Spring, summer, and fall cohorts",
    deadlineMonth: null,
    who: "Students at HACU member schools, including Hispanic-Serving Institutions and community colleges; 14,000 alumni since 1992.",
    stages: ["college", "transfer"],
    tags: ["government", "federal", "Latino", "Hispanic", "paid"],
    officialUrl: "https://www.hacu.net/hacu/HNIP.asp",
  },
  {
    id: "chci-internship",
    name: "CHCI Congressional Internship",
    type: "internship",
    compensation: "Paid ($4,776 summer) + housing, travel, insurance, Metro stipend",
    deadline: "Typically December (summer) and March (fall)",
    deadlineMonth: 12,
    who: "Full-time Latino/a undergraduates with leadership and public-service commitment; DACA recipients with work authorization eligible.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["government", "policy", "Latino", "Hispanic", "DC", "paid", "DACA"],
    officialUrl: "https://chci.org/programs/congressional-internship-program/",
  },
  {
    id: "cbcf-internships",
    name: "CBCF Congressional Internships",
    type: "internship",
    compensation: "Paid stipend + housing in Washington, D.C.",
    deadline: "Summer, fall, and spring cycles",
    deadlineMonth: null,
    who: "College students and recent grads interested in public policy, especially those serving Black communities.",
    stages: ["college"],
    tags: ["government", "policy", "Black", "DC", "paid"],
    officialUrl: "https://www.cbcfinc.org/internships/",
  },
  {
    id: "girls-who-code-college",
    name: "Girls Who Code College & Career Programs",
    type: "program",
    compensation: "Free — career prep, College Loops chapters, hiring pipeline",
    deadline: "Rolling by program",
    deadlineMonth: null,
    who: "Women and nonbinary students in computer science, ages 18–25.",
    stages: ["college", "transfer"],
    tags: ["women", "computer science", "tech"],
    officialUrl: "https://girlswhocode.com/programs",
  },
  {
    id: "rewriting-the-code",
    name: "Rewriting the Code",
    type: "program",
    compensation: "Free membership: mentors, career programs, members-only job portal",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "University students and early-career women in tech across the U.S., Canada, UK, and Ireland.",
    stages: ["college", "transfer"],
    tags: ["women", "tech", "community"],
    officialUrl: "https://rewritingthecode.org/",
  },
  {
    id: "seo-scholars",
    name: "SEO Scholars",
    type: "program",
    compensation: "Free 8-year academic + mentoring program, high school through college",
    deadline: "Typically December of 9th grade (varies by city)",
    deadlineMonth: 12,
    who: "Low-income public school 9th graders in NYC, San Francisco, Miami, or North Carolina; 85% college graduation rate.",
    stages: ["high-school"],
    tags: ["college access", "mentoring", "first-generation", "regional"],
    officialUrl: "https://www.seo-usa.org/scholars/",
  },
  {
    id: "leda-scholars",
    name: "LEDA Scholars Program",
    type: "program",
    compensation: "Free — 7-week summer institute at Princeton + years of college guidance",
    deadline: "Typically December of junior year",
    deadlineMonth: 12,
    who: "High-achieving public school juniors from under-resourced backgrounds; about 100 selected a year.",
    stages: ["high-school"],
    tags: ["college access", "leadership", "first-generation"],
    officialUrl: "https://ledascholars.org/our-program/leda-scholars-program/",
  },
  {
    id: "questbridge-prep",
    name: "QuestBridge College Prep Scholars",
    type: "program",
    compensation: "Free — summer-program scholarships, conferences, essay coaching",
    deadline: "Typically late March of junior year",
    deadlineMonth: 3,
    who: "Juniors from households typically under $65,000 (family of four) earning mostly A's in challenging courses.",
    stages: ["high-school"],
    tags: ["college access", "low income", "juniors"],
    officialUrl: "https://www.questbridge.org/high-school-students/college-prep-scholars",
  },
  {
    id: "mites-summer",
    name: "MITES Summer (MIT)",
    type: "program",
    compensation: "Free — housing and meals included; you cover travel only",
    deadline: "Typically February of junior year",
    deadlineMonth: 2,
    who: "Juniors, especially underrepresented, low-income, and first-generation students; citizens and permanent residents.",
    stages: ["high-school"],
    tags: ["STEM", "engineering", "MIT", "summer"],
    officialUrl: "https://mites.mit.edu/discover-mites/mites-summer/",
  },
  {
    id: "trio-upward-bound",
    name: "TRIO Upward Bound (find your local program)",
    type: "program",
    compensation: "Free — tutoring, summer instruction, and counseling at ~1,000 sites",
    deadline: "Varies by local program",
    deadlineMonth: null,
    who: "Students 13–19 from low-income families or who would be first-generation college students; apply through a local project.",
    stages: ["high-school"],
    tags: ["TRIO", "college access", "first-generation", "tutoring"],
    officialUrl: "https://www.ed.gov/grants-and-programs/grants-higher-education/federal-trio-programs/upward-bound-program-84047a",
  },
  {
    id: "telluride-tass",
    name: "Telluride Association Summer Seminar (TASS)",
    type: "program",
    compensation: "Free — tuition, room, board, books, travel help, even lost-summer-earnings aid",
    deadline: "Typically early December",
    deadlineMonth: 12,
    who: "Sophomores and juniors ages 15–17 for critical-thinking seminars; U.S. and international students welcome.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["humanities", "seminar", "summer"],
    officialUrl: "https://tellurideassociation.org/tass/",
  },
  {
    id: "cmu-sams",
    name: "Carnegie Mellon SAMS",
    type: "program",
    compensation: "Free, fully funded with housing; you cover travel only",
    deadline: "Typically February 1",
    deadlineMonth: 2,
    who: "Juniors at least 16 from groups underrepresented in STEM; citizens and permanent residents.",
    stages: ["high-school"],
    tags: ["STEM", "math", "science", "summer"],
    officialUrl: "https://www.cmu.edu/pre-college/academic-programs/sams.html",
  },
  {
    id: "simons-summer-research",
    name: "Simons Summer Research Program",
    type: "research",
    compensation: "Free + stipend award; faculty-mentored lab research at Stony Brook",
    deadline: "Typically early February",
    deadlineMonth: 2,
    who: "Current juniors at least 16 doing hands-on research; citizens and permanent residents only.",
    stages: ["high-school"],
    tags: ["STEM", "research", "summer", "lab"],
    officialUrl: "https://www.stonybrook.edu/simons/",
  },
  {
    id: "gwc-pathways",
    name: "Girls Who Code Pathways",
    type: "program",
    compensation: "Free, 100% virtual — AI, cybersecurity, game design, web dev tracks",
    deadline: "Typically April (early deadline February)",
    deadlineMonth: 4,
    who: "Girls and nonbinary students in grades 9–12, anywhere in the U.S.; the in-person Summer Immersion ended after 2025.",
    stages: ["high-school"],
    tags: ["women", "coding", "virtual", "computer science"],
    officialUrl: "https://girlswhocode.com/programs/pathways",
  },
  {
    id: "nyu-arise",
    name: "NYU ARISE",
    type: "research",
    compensation: "Free + $2,000 stipend — 10 weeks with NYU lab research",
    deadline: "Typically late February",
    deadlineMonth: 2,
    who: "NYC rising juniors and seniors attending NYC schools full-time.",
    stages: ["high-school"],
    tags: ["STEM", "research", "NYC", "New York", "regional", "paid"],
    officialUrl: "https://k12stem.engineering.nyu.edu/programs/arise",
  },
  {
    id: "jackson-lab-ssp",
    name: "Jackson Laboratory Summer Student Program",
    type: "research",
    compensation: "Paid — $7,500 stipend plus room, board, and travel",
    deadline: "Typically late January",
    deadlineMonth: 1,
    who: "Graduating seniors and undergraduates for 10 weeks of mentored genetics research in Maine or Connecticut.",
    stages: ["high-school", "college"],
    tags: ["genetics", "biology", "research", "paid"],
    officialUrl: "https://www.jax.org/education-and-learning/high-school-students-and-undergraduates/learn-earn-and-explore",
  },
];
