// The curated scholarship list (July 2026): real, established, national
// awards relevant to Empower's audience — first-gen, low-income, immigrant,
// and transfer students. HONESTY RULES: every entry is a real program with
// its OFFICIAL site linked; amounts are the program's published figures;
// deadlines are the month the application usually closes ("Typically …")
// because exact dates shift yearly — the page tells readers to confirm on
// the official site. VERIFIED_AS_OF is shown publicly; re-verify every
// entry (still running? amount changed? link alive?) once a year like the
// state highlights, and prune anything that dies. Curation bar: no essay
// mills, no "sweepstakes" scholarships that sell your data, no programs we
// can't verify.

export const VERIFIED_AS_OF = "July 2026";

export type StudentStage = "high-school" | "college" | "transfer";

export interface Scholarship {
  id: string;
  name: string;
  /** Published award figure, as the program states it. */
  amount: string;
  /** When applications usually close. */
  deadline: string;
  /** 1-12; used only for academic-year ordering. Null = rolling/varies. */
  deadlineMonth: number | null;
  /** One plain sentence: who it's for. */
  who: string;
  stages: StudentStage[];
  /** True when the program is explicitly open to undocumented/DACA/TPS
   *  students (no citizenship or green card required). */
  openToUndocumented?: boolean;
  /** Optional search keywords (majors, identities, states) — folded into
   *  the finder's fuzzy haystack, never displayed. */
  tags?: string[];
  officialUrl: string;
}

export const scholarships: Scholarship[] = [
  {
    id: "jkc-transfer",
    name: "Jack Kent Cooke Undergraduate Transfer Scholarship",
    amount: "Up to $55,000/yr",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "High-achieving community college students transferring to a four-year school, with financial need.",
    stages: ["transfer"],
    officialUrl: "https://www.jkcf.org/our-scholarships/undergraduate-transfer-scholarship/",
  },
  {
    id: "jkc-college",
    name: "Jack Kent Cooke College Scholarship",
    amount: "Up to $55,000/yr",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "High-achieving high school seniors with financial need.",
    stages: ["high-school"],
    officialUrl: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
  },
  {
    id: "gates",
    name: "The Gates Scholarship",
    amount: "Full cost of attendance",
    deadline: "Typically September",
    deadlineMonth: 9,
    who: "Pell-eligible high school seniors from minority backgrounds with strong records.",
    stages: ["high-school"],
    officialUrl: "https://www.thegatesscholarship.org/",
  },
  {
    id: "questbridge",
    name: "QuestBridge National College Match",
    amount: "Full four-year scholarship",
    deadline: "Typically September",
    deadlineMonth: 9,
    who: "Low-income high school seniors; matches you to full rides at partner colleges.",
    stages: ["high-school"],
    officialUrl: "https://www.questbridge.org/",
  },
  {
    id: "coca-cola",
    name: "Coca-Cola Scholars Program",
    amount: "$20,000",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "High school seniors with leadership and service; one of the largest merit programs.",
    stages: ["high-school"],
    officialUrl: "https://www.coca-colascholarsfoundation.org/",
  },
  {
    id: "dell",
    name: "Dell Scholars",
    amount: "$20,000 plus laptop and support",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "Low-income students in an approved college-readiness program, with grit valued over grades.",
    stages: ["high-school"],
    officialUrl: "https://www.dellscholars.org/",
  },
  {
    id: "horatio-alger",
    name: "Horatio Alger National Scholarship",
    amount: "$25,000",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "High school students who have faced and overcome significant adversity, with financial need.",
    stages: ["high-school"],
    officialUrl: "https://scholars.horatioalger.org/",
  },
  {
    id: "dream-us-national",
    name: "TheDream.US National Scholarship",
    amount: "Up to $33,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Undocumented students (DACA or TPS not required) headed to a partner college.",
    stages: ["high-school", "college", "transfer"],
    openToUndocumented: true,
    officialUrl: "https://www.thedream.us/",
  },
  {
    id: "dream-us-opportunity",
    name: "TheDream.US Opportunity Scholarship",
    amount: "Up to $80,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Undocumented students in states that lock them out of in-state tuition.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    officialUrl: "https://www.thedream.us/",
  },
  {
    id: "golden-door",
    name: "Golden Door Scholars",
    amount: "Up to full tuition",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "Undocumented students, with special focus on career-track degrees.",
    stages: ["high-school", "college", "transfer"],
    openToUndocumented: true,
    officialUrl: "https://www.roadtohire.org/golden-door-scholars",
  },
  {
    id: "hsf",
    name: "Hispanic Scholarship Fund",
    amount: "$500–$5,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Students of Hispanic heritage, high school seniors through graduate students.",
    stages: ["high-school", "college", "transfer"],
    officialUrl: "https://www.hsf.net/",
  },
  {
    id: "jackie-robinson",
    name: "Jackie Robinson Foundation Scholarship",
    amount: "Up to $35,000 over four years",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Minority high school seniors with leadership and financial need; includes mentoring.",
    stages: ["high-school"],
    officialUrl: "https://jackierobinson.org/",
  },
  {
    id: "ron-brown",
    name: "Ron Brown Scholar Program",
    amount: "$40,000 ($10,000 × 4 years)",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Black high school seniors with academic excellence, leadership, and need.",
    stages: ["high-school"],
    officialUrl: "https://ronbrown.org/",
  },
  {
    id: "apia",
    name: "APIA Scholars",
    amount: "$2,500–$20,000",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Asian and Pacific Islander American students with financial need; first-gen prioritized.",
    stages: ["high-school", "college"],
    officialUrl: "https://apiascholars.org/",
  },
  {
    id: "american-indian-college-fund",
    name: "American Indian College Fund Scholarships",
    amount: "Varies by program",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Native American students, both at tribal colleges and mainstream campuses.",
    stages: ["high-school", "college", "transfer"],
    officialUrl: "https://collegefund.org/",
  },
  {
    id: "point",
    name: "Point Foundation Flagship Scholarship",
    amount: "Varies; multi-year",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "LGBTQ students with demonstrated leadership, college through graduate school.",
    stages: ["college", "transfer"],
    officialUrl: "https://pointfoundation.org/",
  },
  {
    id: "ptk",
    name: "Phi Theta Kappa Scholarships",
    amount: "Varies by award",
    deadline: "Multiple rounds yearly",
    deadlineMonth: null,
    who: "Community college students; PTK membership unlocks a whole pipeline of transfer awards.",
    stages: ["college", "transfer"],
    officialUrl: "https://www.ptk.org/scholarships/",
  },
  {
    id: "cameron-impact",
    name: "Cameron Impact Scholarship",
    amount: "Full tuition",
    deadline: "Typically May and September rounds",
    deadlineMonth: 5,
    who: "High school seniors with strong academics, leadership, and community service.",
    stages: ["high-school"],
    officialUrl: "https://www.bryancameroneducationfoundation.org/",
  },
  {
    id: "amazon-future-engineer",
    name: "Amazon Future Engineer Scholarship",
    amount: "$40,000 ($10,000 × 4 years)",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "High school seniors from underserved communities planning computer science degrees; includes an internship offer.",
    stages: ["high-school"],
    officialUrl: "https://www.amazonfutureengineer.com/scholarships",
  },
  {
    id: "elks-mvs",
    name: "Elks Most Valuable Student",
    amount: "$1,000–$7,500 per year",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "High school seniors, judged on leadership, need, and scholarship; huge number of awards.",
    stages: ["high-school"],
    officialUrl: "https://www.elks.org/scholars/",
  },
  {
    id: "vfw-voice",
    name: "VFW Voice of Democracy",
    amount: "Up to $35,000",
    deadline: "Typically October 31",
    deadlineMonth: 10,
    who: "9th–12th graders; an audio essay contest, so it rewards effort over GPA.",
    stages: ["high-school"],
    officialUrl: "https://www.vfw.org/community/youth-and-education/youth-scholarships",
  },
  {
    id: "equitable-excellence",
    name: "Equitable Excellence Scholarship",
    amount: "$2,500–$25,000",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "High school seniors demonstrating courage, strength, and wisdom; hundreds awarded yearly.",
    stages: ["high-school"],
    officialUrl: "https://equitable.com/foundation/equitable-excellence-scholarship",
  },
  {
    id: "ge-reagan",
    name: "GE-Reagan Foundation Scholarship",
    amount: "$10,000, renewable",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "High school seniors with leadership, integrity, and financial need.",
    stages: ["high-school"],
    officialUrl: "https://www.reaganfoundation.org/education/scholarship-programs/",
  },
  {
    id: "dream-award",
    name: "Scholarship America Dream Award",
    amount: "$5,000–$15,000, renewable",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "Students entering their SECOND year or later. One of the few big awards for students already in college.",
    stages: ["college", "transfer"],
    officialUrl: "https://scholarshipamerica.org/students/browse-scholarships/",
  },
  {
    id: "regeneron-sts",
    name: "Regeneron Science Talent Search",
    amount: "Up to $250,000",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "High school seniors with an original science research project.",
    stages: ["high-school"],
    officialUrl: "https://www.societyforscience.org/regeneron-sts/",
  },

  // --- Batch 1 expansion (July 13, 2026): 59 awards researched against
  // official pages by six parallel verification passes; dedup'd, curated
  // (marketing-site awards, grad-only fellowships, and prize contests cut),
  // citizenship flags conservative (explicit statements only). ---
  {
    id: "mikerowe-work-ethic",
    name: "mikeroweWORKS Work Ethic Scholarship",
    amount: "Varies by year",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "High school seniors, graduates, or GED holders entering a skilled-trades program at a two-year college or technical school who sign the S.W.E.A.T. Pledge.",
    stages: ["high-school", "college"],
    tags: ["trades", "technical", "vocational"],
    officialUrl: "https://istsprogramsupport.com/mikeroweworks/",
  },
  {
    id: "soroptimist-live-your-dream",
    name: "Soroptimist Live Your Dream Awards",
    amount: "$1,000 to $16,000",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Women who are the primary financial support for their families, enrolled in or accepted to vocational training or an undergraduate program.",
    stages: ["college"],
    tags: ["women", "mothers", "adult students"],
    officialUrl: "https://www.soroptimist.org/our-work/live-your-dream-awards/index.html",
  },
  {
    id: "rankin-scholar-grant",
    name: "Jeannette Rankin Foundation National Scholar Grant",
    amount: "Up to $2,500 a year, renewable up to five years",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Low-income women and nonbinary students age 35 or older pursuing a first associate or bachelor's degree or vocational training.",
    stages: ["college"],
    tags: ["women", "adult students", "returning students"],
    officialUrl: "https://rankinfoundation.org/national-scholar-grant/",
  },
  {
    id: "patsy-mink-education-award",
    name: "Patsy Takemoto Mink Education Support Award",
    amount: "Up to $5,000 (five awards a year)",
    deadline: "Typically August",
    deadlineMonth: 8,
    who: "Low-income mothers with minor children, age 17 or older, enrolled in a degree, certificate, or training program in the U.S.",
    stages: ["college"],
    tags: ["mothers", "women", "adult students"],
    officialUrl: "https://www.patsyminkfoundation.org/education-support-application",
  },
  {
    id: "ewi-asist",
    name: "EWI ASIST Scholarship",
    amount: "Varies by chapter",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Adults 18+ facing economic, social, or physical challenges who are entering, re-entering, or continuing college or a certificate program, in a participating EWI chapter area.",
    stages: ["college"],
    tags: ["adult students", "returning students"],
    officialUrl: "https://apply.mykaleidoscope.com/program/Asist2026",
  },
  {
    id: "davis-putter",
    name: "Davis-Putter Scholarship Fund",
    amount: "Up to $15,000 a year",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Students with financial need who are active organizers in movements for social and economic justice; no social security number or visa needed.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["activism", "organizing"],
    officialUrl: "https://www.davisputter.org/apply",
  },
  {
    id: "nths-poteat",
    name: "NTHS Jon H. Poteat Scholarship",
    amount: "$1,000 (275 awards a year)",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Active National Technical Honor Society members in career and technical education programs, high school or college.",
    stages: ["high-school", "college"],
    tags: ["trades", "technical", "CTE"],
    officialUrl: "https://www.nths.org/scholarships/",
  },
  {
    id: "techforce",
    name: "TechForce Foundation Scholarships",
    amount: "Typically $2,500 to $3,500",
    deadline: "Rolling; new cycles all year",
    deadlineMonth: null,
    who: "Students entering or enrolled in an accredited vehicle-technician program (auto, diesel, collision, aviation) with financial need; open to citizens, permanent residents, and DACA students.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["trades", "automotive", "technician"],
    officialUrl: "https://techforce.org/scholarships/",
  },
  {
    id: "sme-education",
    name: "SME Education Foundation Scholarships",
    amount: "$2,500 to $20,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "High school seniors and college students, including community college students, pursuing manufacturing and related technical degrees; one free application covers 100+ awards.",
    stages: ["high-school", "college"],
    tags: ["manufacturing", "engineering", "STEM", "trades"],
    officialUrl: "https://www.smeef.org/scholarships/",
  },
  {
    id: "tau-sigma",
    name: "Tau Sigma National Honor Society Scholarships",
    amount: "$500 to $5,000",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Tau Sigma members, the transfer students inducted after a strong first semester at their four-year school; apply through your chapter.",
    stages: ["transfer"],
    tags: ["transfer", "honor society"],
    officialUrl: "https://www.tausigmanhs.org/scholarships",
  },
  {
    id: "aws-welding",
    name: "AWS Foundation Welding Scholarships",
    amount: "$1,000 to $10,000+",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Students enrolled or enrolling in welding programs at trade schools, community colleges, or universities; 1,600+ awards a year through one application.",
    stages: ["high-school", "college"],
    tags: ["welding", "trades", "technical"],
    officialUrl: "https://www.aws.org/career-resources/students/scholarships/",
  },
  {
    id: "taco-bell-live-mas",
    name: "Taco Bell Live Más Scholarship",
    amount: "Up to $25,000",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "U.S. residents ages 16 to 26 heading into any accredited post-secondary program, including trade school. Judged on a short passion video, no GPA or essay.",
    stages: ["high-school", "college"],
    tags: ["video", "no essay", "trades"],
    officialUrl: "https://www.tacobellfoundation.org/live-mas-scholarship/",
  },
  {
    id: "uncf-scholarships",
    name: "UNCF Scholarships",
    amount: "Varies by program; $62M+ awarded a year",
    deadline: "Rolling; many programs, many dates",
    deadlineMonth: null,
    who: "African American students from high school senior year through college, applying across the many programs UNCF administers.",
    stages: ["high-school", "college"],
    tags: ["Black", "African American", "HBCU"],
    officialUrl: "https://uncf.org/scholarships",
  },
  {
    id: "tmcf-scholarships",
    name: "Thurgood Marshall College Fund Scholarships",
    amount: "Varies by program",
    deadline: "Rolling; varies by program",
    deadlineMonth: null,
    who: "Students at TMCF member schools (publicly supported HBCUs) and other eligible institutions.",
    stages: ["college"],
    tags: ["Black", "African American", "HBCU"],
    officialUrl: "https://www.tmcf.org/students-alumni/scholarships/",
  },
  {
    id: "hhf-youth-awards",
    name: "Hispanic Heritage Foundation Youth Awards",
    amount: "Varies by category",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Graduating high school seniors of Hispanic or Latino heritage with a 3.0+ GPA heading to college the next year.",
    stages: ["high-school"],
    tags: ["Latino", "Hispanic"],
    officialUrl: "https://hispanicheritage.org/programs/leadership/youth-awards/",
  },
  {
    id: "cafe-bustelo",
    name: "Café Bustelo El Café del Futuro Scholarship",
    amount: "$5,000 (25 awards a year)",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "First-generation Latino students enrolled full-time at a four-year HACU-member school with a 2.5+ GPA.",
    stages: ["college"],
    tags: ["Latino", "Hispanic", "first-generation"],
    officialUrl: "https://hacu.net/hacu-and-cafe-bustelo-el-cafe-del-futuro-scholarships-for-2025-26/",
  },
  {
    id: "kasf",
    name: "Korean American Scholarship Foundation",
    amount: "$500 to $5,000",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Students of Korean heritage studying full-time in the U.S. with a 3.0+ GPA, open regardless of citizenship status.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["Korean", "Asian American"],
    officialUrl: "https://www.kasf.org/apply/",
  },
  {
    id: "oca-gold-mountain",
    name: "OCA-UPS Gold Mountain Scholarship",
    amount: "$2,000 to $2,500",
    deadline: "Varies; check current cycle",
    deadlineMonth: null,
    who: "First-generation Asian American and Pacific Islander students: high school seniors and current undergraduates, including community college students.",
    stages: ["high-school", "college"],
    tags: ["Asian American", "Pacific Islander", "first-generation"],
    officialUrl: "https://www.ocanational.org/scholarships",
  },
  {
    id: "aises",
    name: "AISES Scholarships",
    amount: "$1,000 to $7,000",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Indigenous STEM students (tribal citizens or descendants, Alaska Native, Native Hawaiian, or Pacific Islander) with a 3.0+ GPA; student membership is free.",
    stages: ["college"],
    tags: ["Native American", "Indigenous", "STEM"],
    officialUrl: "https://aises.org/students/scholarships/",
  },
  {
    id: "cobell-undergrad",
    name: "Cobell Scholarship (Undergraduate)",
    amount: "Up to $5,000 new / $8,000 returning",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Enrolled members of federally recognized tribes or Alaska Native Corporations pursuing an associate or bachelor's degree full-time.",
    stages: ["college", "transfer"],
    tags: ["Native American", "Indigenous", "tribal"],
    officialUrl: "https://www.cobellscholar.org/scholarships/undergraduate",
  },
  {
    id: "league-foundation",
    name: "LEAGUE Foundation Academic Scholarships",
    amount: "Typically $2,500 to $4,000",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Self-identifying LGBTQ+ graduating high school seniors with a 3.0+ GPA and community service, heading to an accredited U.S. college.",
    stages: ["high-school"],
    tags: ["LGBTQ"],
    officialUrl: "https://leaguefoundation.org/",
  },
  {
    id: "out-to-innovate",
    name: "Out to Innovate Scholarships",
    amount: "$2,000 to $2,500",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "LGBTQ+ students two or more years past high school with a declared STEM or STEM-teaching major and a 2.75+ GPA.",
    stages: ["college", "transfer"],
    tags: ["LGBTQ", "STEM"],
    officialUrl: "https://www.outtoinnovate.org/scholarships",
  },
  {
    id: "aahd-krause",
    name: "AAHD Frederick J. Krause Scholarship",
    amount: "Generally $1,000",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Students with a disability (sophomore year or beyond) studying a field related to health and disability.",
    stages: ["college"],
    tags: ["disability", "health"],
    officialUrl: "https://www.aahd.us/scholarship/",
  },
  {
    id: "lime-pathways",
    name: "Lime Connect Pathways Scholarship",
    amount: "$1,000 (13 awards a year)",
    deadline: "Varies; opens in winter",
    deadlineMonth: null,
    who: "High school seniors with a visible or invisible disability enrolling full-time at a four-year college.",
    stages: ["high-school"],
    tags: ["disability"],
    officialUrl: "https://limeconnect.com/awards/lime-connect-pathways-scholarship-for-high-school-seniors/",
  },
  {
    id: "foster-love-fellowship",
    name: "Foster Love Family Fellowship",
    amount: "Up to $12,000 a year for up to five years",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Current and former foster youth ages 18 to 24 pursuing a bachelor's degree full-time, with housing help and mentoring included; U.S. citizenship required.",
    stages: ["high-school", "college"],
    tags: ["foster youth", "foster care"],
    officialUrl: "https://fosterlove.com/family-fellowship-scholarship/",
  },
  {
    id: "burger-king-scholars",
    name: "Burger King Scholars Program",
    amount: "$1,000 to $60,000",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "High school seniors in the U.S., Puerto Rico, Guam, or Canada with at least a 2.0 GPA; 4,000+ awards a year, judged on grades, work, service, and need.",
    stages: ["high-school"],
    tags: ["large program"],
    officialUrl: "https://www.burgerkingfoundation.org/programs/burger-king-sm-scholars",
  },
  {
    id: "carson-scholars",
    name: "Carson Scholars Fund Scholarship",
    amount: "$1,000",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Students in grades 4 to 11 with a 3.75+ GPA and strong community service, nominated by an educator.",
    stages: ["high-school"],
    tags: ["middle school", "community service"],
    officialUrl: "https://carsonscholars.org/scholarships/",
  },
  {
    id: "nhs-scholarship",
    name: "National Honor Society Scholarship",
    amount: "$2 million across 600 members a year",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "High school seniors who are NHS members in good standing, heading to an accredited college, university, or trade school.",
    stages: ["high-school"],
    tags: ["honor society"],
    officialUrl: "https://www.nationalhonorsociety.org/students/the-nhs-scholarship/",
  },
  {
    id: "legion-oratorical",
    name: "American Legion Oratorical Contest",
    amount: "Up to $25,000 (plus $2,000 per state winner)",
    deadline: "Varies by state; enter in fall",
    deadlineMonth: null,
    who: "High school students under 20 (citizens or permanent residents) delivering prepared and assigned speeches on the U.S. Constitution, starting at the local post.",
    stages: ["high-school"],
    tags: ["speech", "civics", "essay"],
    officialUrl: "https://www.legion.org/get-involved/youth-programs/oratorical-contest",
  },
  {
    id: "afsa-essay",
    name: "AFSA National High School Essay Contest",
    amount: "$2,500 plus a trip to Washington, D.C.",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Students in grades 9 to 12 at any U.S. school writing an essay on diplomacy and foreign service.",
    stages: ["high-school"],
    tags: ["essay", "writing"],
    officialUrl: "https://afsa.org/essay-contest",
  },
  {
    id: "optimist-essay",
    name: "Optimist International Essay Contest",
    amount: "$2,500 at the district level",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Students under 19 entering through their local Optimist Club in the U.S., Canada, or the Caribbean.",
    stages: ["high-school"],
    tags: ["essay", "writing"],
    officialUrl: "https://www.optimist.org/member/scholarships3.cfm",
  },
  {
    id: "davidson-fellows",
    name: "Davidson Fellows Scholarship",
    amount: "$25,000 to $100,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Students 18 or younger (citizens or permanent residents) who have completed a significant piece of work in STEM, literature, music, or philosophy.",
    stages: ["high-school"],
    tags: ["STEM", "research", "gifted"],
    officialUrl: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
  },
  {
    id: "coolidge-scholarship",
    name: "Coolidge Scholarship",
    amount: "Full ride: tuition, room, board, and fees for four years",
    deadline: "Typically early fall of junior year",
    deadlineMonth: 9,
    who: "High school juniors (citizens or permanent residents) planning full-time enrollment at any accredited U.S. college.",
    stages: ["high-school"],
    tags: ["full ride", "juniors"],
    officialUrl: "https://coolidgescholars.org/",
  },
  {
    id: "hagan-scholarship",
    name: "Hagan Scholarship",
    amount: "Up to $7,500 per semester for eight semesters",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "High school seniors with a 3.5+ GPA and household income under $100,000 who have worked 240+ hours, open regardless of nationality or citizenship.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["rural", "work experience", "large award"],
    officialUrl: "https://haganscholarships.org/application/",
  },
  {
    id: "smart-dod",
    name: "SMART Scholarship-for-Service (DoD)",
    amount: "Full tuition plus a $30,000 to $46,000 annual stipend",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "STEM students (citizens) willing to work at a Department of Defense facility after graduation. Covers tuition, stipend, internships, and a guaranteed job.",
    stages: ["college"],
    tags: ["STEM", "engineering", "full tuition", "service"],
    officialUrl: "https://www.smartscholarship.org/smart",
  },
  {
    id: "swe-scholarships",
    name: "Society of Women Engineers Scholarships",
    amount: "Varies; 330+ awards, ~$1.6M a year",
    deadline: "Varies; one annual application",
    deadlineMonth: null,
    who: "Women in engineering and engineering technology from high school senior year through grad school; one application covers every award, offered globally.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["women", "engineering", "STEM"],
    officialUrl: "https://swe.org/scholarships/",
  },
  {
    id: "nsbe-scholarships",
    name: "NSBE Scholarships",
    amount: "$1,000 to $10,000",
    deadline: "Fall and spring cycles",
    deadlineMonth: null,
    who: "Black engineering and STEM students, high school through grad school; requires NSBE student membership (small annual dues).",
    stages: ["high-school", "college"],
    tags: ["Black", "engineering", "STEM"],
    officialUrl: "https://www.nsbe.org/scholarships/",
  },
  {
    id: "scholarshpe",
    name: "ScholarSHPE",
    amount: "Varies; $1M+ a year",
    deadline: "Opens February each year",
    deadlineMonth: null,
    who: "Hispanic and Latino STEM students from high school seniors through grad school with a 2.5+ GPA; SHPE membership required, and SHPE-funded awards require no citizenship.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["Latino", "Hispanic", "engineering", "STEM"],
    officialUrl: "https://shpe.org/students/scholarshpe/",
  },
  {
    id: "gmis-stem",
    name: "GMiS STEM Scholarships (Great Minds in STEM)",
    amount: "$500 to $5,000",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Underrepresented students in STEM or health degrees with a 3.0+ GPA and demonstrated leadership or service.",
    stages: ["college"],
    tags: ["Latino", "Hispanic", "STEM", "health"],
    officialUrl: "https://greatmindsinstem.org/gmis-scholarship-application/gmis-scholarships/gmis-scholarship-guidelines/",
  },
  {
    id: "acs-catalyst",
    name: "ACS Catalyst Scholarship",
    amount: "$10,000, renewable",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "High school seniors and undergraduates (citizens or permanent residents) majoring in chemistry, biochemistry, or chemical engineering with a 3.0+ GPA.",
    stages: ["high-school", "college"],
    tags: ["chemistry", "STEM", "science"],
    officialUrl: "https://www.acs.org/education/acs-undergraduate-scholarship.html",
  },
  {
    id: "nurse-corps",
    name: "Nurse Corps Scholarship Program (HRSA)",
    amount: "Full tuition, fees, and a monthly stipend",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Nursing students (citizens, nationals, or permanent residents) who commit to working at a critical-shortage facility after graduation; preference for greatest financial need.",
    stages: ["high-school", "college"],
    tags: ["nursing", "health", "full tuition", "service"],
    officialUrl: "https://bhw.hrsa.gov/programs/nurse-corps/scholarship/apply",
  },
  {
    id: "aicpa-legacy",
    name: "AICPA Foundation Legacy Scholarships",
    amount: "$5,000 to $10,000",
    deadline: "Typically spring",
    deadlineMonth: null,
    who: "Accounting students committed to the CPA path, with dedicated awards for minority students and community-college transfers.",
    stages: ["college", "transfer"],
    tags: ["accounting", "business", "transfer"],
    officialUrl: "https://www.thiswaytocpa.com/education/aicpa-legacy-scholarships/",
  },
  {
    id: "acfe-ritchie-jennings",
    name: "Ritchie-Jennings Memorial Scholarship (ACFE)",
    amount: "$2,000 to $10,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Full-time students majoring or minoring in accounting, business, finance, or criminal justice with an interest in anti-fraud careers; open internationally.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["accounting", "business", "criminal justice"],
    officialUrl: "https://www.acfe.com/scholarship.aspx",
  },
  {
    id: "esa-game-arts",
    name: "ESA Foundation Video Game Arts & Sciences Scholarship",
    amount: "Varies (plus industry mentoring)",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Women and underrepresented students (citizens) with financial need in video game-related degree programs, high school senior through college junior year.",
    stages: ["high-school", "college"],
    tags: ["video games", "design", "technology", "women"],
    officialUrl: "https://www.theesa.com/foundation/computer-and-video-game-arts-and-sciences-scholarship/",
  },
  {
    id: "aiga-worldstudio",
    name: "AIGA Worldstudio DxD Scholarships",
    amount: "Typically $2,000 to $5,000",
    deadline: "Typically spring",
    deadlineMonth: null,
    who: "Art and design students (graphic design, illustration, photography) from underrepresented and economically disadvantaged backgrounds with a 3.0+ GPA.",
    stages: ["high-school", "college"],
    tags: ["art", "design", "creative"],
    officialUrl: "https://www.aiga.org/competitions-initiatives/aiga-worldstudio-dd-scholarships",
  },
  {
    id: "tylenol-future-care",
    name: "TYLENOL Future Care Scholarship",
    amount: "$5,000 or $10,000 (35 awards)",
    deadline: "Typically July",
    deadlineMonth: 7,
    who: "Students headed into medicine, nursing, or pharmacy graduate programs (including college seniors applying) who plan to treat patients; residency-based, no citizenship requirement.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["health", "medicine", "nursing", "pharmacy"],
    officialUrl: "https://www.tylenol.com/news/scholarship",
  },
  {
    id: "schoolhouse-connection",
    name: "SchoolHouse Connection Youth Leadership Scholarship",
    amount: "$2,500 plus monthly stipends through college",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Students who experienced homelessness in the last six years, starting college or trade school for the first time, explicitly open to undocumented students.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["homelessness", "housing"],
    officialUrl: "https://schoolhouseconnection.org/program/scholarship",
  },
  {
    id: "frs-rural",
    name: "Foundation for Rural Service Scholarships",
    amount: "$1,000 to $9,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Students in the service area of an NTCA rural broadband member company, including non-traditional and returning students; one application covers all awards.",
    stages: ["high-school", "college"],
    tags: ["rural"],
    officialUrl: "https://apply.mykaleidoscope.com/program/FRSScholarships2026",
  },
  {
    id: "evans-scholars",
    name: "Chick Evans Scholarship",
    amount: "Full tuition and housing, renewable four years",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "Golf caddies with two+ years of regular caddying, strong grades, and demonstrated financial need.",
    stages: ["high-school"],
    tags: ["caddie", "full ride", "work experience"],
    officialUrl: "https://wgaesf.org/a-life-changing-opportunity/applying-evans-scholarship",
  },
  {
    id: "simon-youth",
    name: "Simon Youth Community Scholarship",
    amount: "Around $1,500; some renewable",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "High school seniors living near a Simon mall, with priority for first-generation students and financial need.",
    stages: ["high-school"],
    tags: ["first-generation"],
    officialUrl: "https://syf.org/scholarships/",
  },
  {
    id: "sallie-mae-bridging",
    name: "Bridging the Dream Scholarship (Sallie Mae Fund)",
    amount: "Up to $10,000 (30 awards)",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Pell-eligible high school seniors with financial need heading to a two- or four-year college or an eligible certificate program.",
    stages: ["high-school"],
    tags: ["Pell", "first-generation"],
    officialUrl: "https://www.salliemae.com/landing/bridging-the-dream/",
  },
  {
    id: "ascend-educational",
    name: "Ascend Educational Fund",
    amount: "$2,500 to $20,000",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Graduating seniors in New York City's five boroughs who were born abroad or have two foreign-born parents, regardless of immigration status.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["immigrants", "New York", "NYC", "regional"],
    officialUrl: "https://www.ascendfundny.org/scholarship",
  },
  {
    id: "esperanza-fund",
    name: "Esperanza Education Fund",
    amount: "Up to $10,000",
    deadline: "Typically July",
    deadlineMonth: 7,
    who: "Immigrant students (born abroad or with two foreign-born parents) graduating high school or earning a GED in DC, Maryland, or Virginia. No status requirement.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["immigrants", "DC", "Maryland", "Virginia", "regional"],
    officialUrl: "https://www.esperanzafund.org/scholarship",
  },
  {
    id: "que-llueva-cafe",
    name: "Que Llueva Café Scholarship",
    amount: "Varies",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Undocumented high school or GED graduates anywhere in the U.S. or Puerto Rico enrolling in college for the first time.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["undocumented", "immigrants", "Chicano"],
    officialUrl: "https://ca-core.org/scholarship/",
  },
  {
    id: "fontana-scholars",
    name: "Fontana Transport Inc. Scholars Program",
    amount: "Varies",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "First-generation, underrepresented high school seniors nationwide with a 3.5+ GPA entering select majors; U.S. citizenship not required.",
    stages: ["high-school"],
    openToUndocumented: true,
    tags: ["first-generation", "immigrants", "STEM"],
    officialUrl: "https://www.fontanatransportincscholarsprogram.com/scholarship-requirements",
  },
  {
    id: "ushli-andrade",
    name: "USHLI Dr. Juan Andrade Jr. Scholarship",
    amount: "$1,000",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "Undergraduates (through age 25) with at least one parent of Hispanic ancestry and financial need; non-citizens eligible.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["Latino", "Hispanic", "immigrants"],
    officialUrl: "https://www.ushli.org/dr-juan-andrade-jr-scholarship-for-young-hispanic-leaders/",
  },
  {
    id: "pride-foundation",
    name: "Pride Foundation Scholarships",
    amount: "Average around $6,500",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "LGBTQ+ and questioning students of any age in Alaska, Idaho, Montana, Oregon, or Washington; one application covers 50+ funds, no citizenship check.",
    stages: ["high-school", "college", "transfer"],
    openToUndocumented: true,
    tags: ["LGBTQ", "Northwest", "regional"],
    officialUrl: "https://pridefoundation.org/what-we-do/scholarships/",
  },
  {
    id: "dream-project-va",
    name: "Dream Project Scholarship",
    amount: "$4,500 a year, renewable up to five years",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Virginia high school graduates whose immigration status (undocumented, DACA, TPS, asylum-seeking) creates a barrier to higher education.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["undocumented", "immigrants", "Virginia", "regional"],
    officialUrl: "https://dream-project.org/scholarship/",
  },

  // --- Batch 2 expansion (July 13, 2026): military families, civic and
  // faith organizations, corporate public tracks, agriculture, hospitality,
  // arts. Same pipeline: official pages fetched with evidence, dead and
  // fee-charging programs dropped, conservative citizenship flags. ---
  {
    id: "folds-of-honor",
    name: "Folds of Honor Scholarship",
    amount: "Up to $5,000 a year, based on unmet need",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Dependents and spouses of fallen or catastrophically injured U.S. service members or first responders.",
    stages: ["high-school", "college"],
    tags: ["military", "first responders", "families"],
    officialUrl: "https://foldsofhonor.org/scholarships/",
  },
  {
    id: "marine-corps-scholarship",
    name: "Marine Corps Scholarship Foundation",
    amount: "Varies by need; up to $10,000 a year for children of the wounded",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Children of Marines and of Navy Corpsmen or Chaplains attached to Marine units, with family income under $129,000.",
    stages: ["high-school", "college", "transfer"],
    tags: ["military", "families"],
    officialUrl: "https://www.mcsf.org/apply/",
  },
  {
    id: "fisher-house-military-children",
    name: "Scholarships for Military Children (Fisher House)",
    amount: "$2,000 (about 500 awards a year)",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "Dependent children under 23 of active duty, reserve, retired, or deceased service members, enrolling full-time in an undergraduate program.",
    stages: ["high-school", "college"],
    tags: ["military", "families"],
    officialUrl: "https://fisherhouse.org/programs/scholarship-programs/scholarships-for-military-children/",
  },
  {
    id: "tillman-scholars",
    name: "Tillman Scholars",
    amount: "Average $10,000 a year",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Service members, veterans, and military spouses enrolled full-time at a U.S. college or university.",
    stages: ["college"],
    tags: ["military", "veterans", "spouses"],
    officialUrl: "https://pattillmanfoundation.org/apply/",
  },
  {
    id: "amvets-national",
    name: "AMVETS National Scholarships",
    amount: "$4,000 over four years",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Children and grandchildren of veterans, active duty, Guard, or Reserve members with demonstrated financial need.",
    stages: ["high-school", "college"],
    tags: ["military", "veterans", "families"],
    officialUrl: "https://amvets.org/scholarships/",
  },
  {
    id: "jack-and-jill",
    name: "Jack and Jill of America Foundation Scholarship",
    amount: "$2,500 freshman year, renewable through senior year",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "African American high school seniors with a 3.0+ GPA, 60+ service hours, and financial need, heading to a four-year college or HBCU.",
    stages: ["high-school"],
    tags: ["Black", "African American", "community service"],
    officialUrl: "https://jackandjillfoundation.org/jack-and-jill-foundation-scholarship/",
  },
  {
    id: "lulac-lnsf",
    name: "LULAC National Scholarship Fund",
    amount: "$250 to $2,000",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Students (citizens, permanent residents, or DACA recipients) enrolling at a two- or four-year college or vocational school in an area with a participating LULAC Council.",
    stages: ["high-school", "college", "transfer"],
    openToUndocumented: true,
    tags: ["Latino", "Hispanic", "DACA"],
    officialUrl: "https://lnesc.org/",
  },
  {
    id: "islamic-scholarship-fund",
    name: "Islamic Scholarship Fund",
    amount: "$3,000 to $10,000",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Muslim undergraduate juniors and seniors (citizens, permanent residents, or DACA recipients) in policy, law, media, and related majors with a 3.0+ GPA.",
    stages: ["college"],
    openToUndocumented: true,
    tags: ["Muslim", "faith", "policy", "media", "DACA"],
    officialUrl: "https://islamicscholarshipfund.org/scholarship/",
  },
  {
    id: "peo-pce",
    name: "P.E.O. Program for Continuing Education",
    amount: "Up to $4,000, need-based",
    deadline: "Rolling; through a local chapter",
    deadlineMonth: null,
    who: "Women returning to school after an interruption to finish a degree or certification; requires sponsorship by a local P.E.O. chapter.",
    stages: ["college", "transfer"],
    tags: ["women", "returning students", "adult students"],
    officialUrl: "https://www.peointernational.org/about-peo-program-continuing-education-pce",
  },
  {
    id: "aief-undergrad",
    name: "American Indian Education Fund Undergraduate Scholarship",
    amount: "Up to $2,000 a year (200+ awards)",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "American Indian and Alaska Native students (tribal enrollment for themselves or a parent) enrolled full-time with a 2.0+ GPA.",
    stages: ["high-school", "college", "transfer"],
    tags: ["Native American", "Indigenous", "tribal"],
    officialUrl: "https://secure.nativepartnership.org/site/SPageServer/RAR/PageServer?pagename=aief_services_scholarships_undergrad",
  },
  {
    id: "first-nations-ag",
    name: "Native Agriculture & Food Systems Scholarship",
    amount: "$1,000 to $1,500",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Tribally affiliated Native American, Alaska Native, and Native Hawaiian students majoring in agriculture or food systems with a 2.75+ GPA.",
    stages: ["college", "transfer"],
    tags: ["Native American", "Indigenous", "agriculture"],
    officialUrl: "https://www.firstnations.org/projects/native-agriculture-food-systems-scholarships/",
  },
  {
    id: "chick-fil-a-community",
    name: "Chick-fil-A Community Scholars",
    amount: "$25,000 (13 awards a year)",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "Students 18+ with a 3.0 GPA heading to full-time study, judged on academics, service, and need. Explicitly open to DACA and international students; employees not eligible.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["community service", "large award"],
    officialUrl: "https://www.chick-fil-a.com/community-scholars",
  },
  {
    id: "mcdonalds-hacer",
    name: "McDonald's HACER National Scholarship",
    amount: "$5,000 to $100,000 ($1M total to up to 100 students)",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "High school seniors of Hispanic or Latino heritage, under 21, with a 3.0+ GPA, heading to college or vocational school.",
    stages: ["high-school"],
    tags: ["Latino", "Hispanic", "large award"],
    officialUrl: "https://www.mcdonalds.com/us/en-us/community/hacer.html",
  },
  {
    id: "ffa-scholarships",
    name: "National FFA Scholarships",
    amount: "Nearly $2.5M a year via one application",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Senior FFA members in high school or FFA alumni in college, headed to trade school, a certificate, or a degree; one application covers many sponsored awards.",
    stages: ["high-school", "college"],
    tags: ["agriculture", "FFA", "trades"],
    officialUrl: "https://www.ffa.org/participate/grants-and-scholarships/scholarships/",
  },
  {
    id: "afa-scholarships",
    name: "Agriculture Future of America Scholarships",
    amount: "$1,600 to $3,200 plus the AFA Leaders Conference",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "High school seniors and undergraduates ages 17 to 25 pursuing a four-year agriculture or food-related degree.",
    stages: ["high-school", "college"],
    tags: ["agriculture", "food"],
    officialUrl: "https://www.agfuture.org/scholarships",
  },
  {
    id: "princess-grace-awards",
    name: "Princess Grace Awards",
    amount: "$15,000 unrestricted",
    deadline: "Typically February (nominations)",
    deadlineMonth: 2,
    who: "Emerging artists in theater, dance, choreography, and film, nominated by their university or a nonprofit. Ask your department; self-nomination isn't allowed.",
    stages: ["college"],
    tags: ["arts", "theater", "dance", "film"],
    officialUrl: "https://pgfusa.org/apply/",
  },
  {
    id: "sodexo-stop-hunger",
    name: "Stephen J. Brady Stop Hunger Scholarships",
    amount: "$10,000 plus $5,000 to your hunger charity",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Students ages 5 to 25 who have volunteered against hunger in their communities in the past year.",
    stages: ["high-school", "college"],
    tags: ["community service", "volunteering", "hunger"],
    officialUrl: "https://www.us.stop-hunger.org/grants/youth-scholarships",
  },
  {
    id: "regions-riding-forward",
    name: "Regions Riding Forward Scholarship Contest",
    amount: "$8,000 (16 awards a year, quarterly)",
    deadline: "Quarterly; March, June, September, December",
    deadlineMonth: null,
    who: "Students 16+ in one of 15 eligible states (largely the Southeast and Midwest) with undergraduate study remaining, judged on a written or video essay; no banking relationship needed.",
    stages: ["high-school", "college"],
    tags: ["essay", "video", "regional", "Southeast"],
    officialUrl: "https://www.regions.com/about-regions/inclusion-belonging-impact/supporting-communities/essay-contest-scholarship",
  },
  {
    id: "dennys-hungry-for-education",
    name: "Denny's Hungry for Education Scholarship",
    amount: "$2,000 (HACU track)",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Students at HACU-member colleges with a 2.5+ GPA and a 500-word essay; Denny's runs parallel tracks through several partner organizations.",
    stages: ["college"],
    tags: ["Latino", "Hispanic"],
    officialUrl: "https://hacu.net/hacu-and-dennys-hungry-for-education-scholarships-for-2026-27/",
  },
  {
    id: "nraef-hospitality",
    name: "NRAEF Restaurant & Hospitality Scholarships",
    amount: "Varies; $1M+ awarded a year",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "High school seniors and college students pursuing restaurant, foodservice, or hospitality degrees.",
    stages: ["high-school", "college"],
    tags: ["hospitality", "culinary", "restaurant"],
    officialUrl: "https://chooserestaurants.org/scholarships",
  },
  {
    id: "ahla-academic",
    name: "AHLA Foundation Academic Scholarships",
    amount: "$2,000 to $7,000 (300+ students a year)",
    deadline: "Opens each December",
    deadlineMonth: null,
    who: "College students in hospitality management and related fields at any school.",
    stages: ["college"],
    tags: ["hospitality", "hotel", "tourism"],
    officialUrl: "https://www.ahlafoundation.org/scholarships",
  },
  {
    id: "deca-scholarships",
    name: "DECA Scholarship Program",
    amount: "Typically $1,000 to $2,500 ($200,000+ total)",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "High school and college DECA members, strictly merit-based, funded by corporate sponsors.",
    stages: ["high-school", "college"],
    tags: ["business", "marketing", "DECA"],
    officialUrl: "https://www.deca.org/scholarships",
  },
  // --- Batch 3 expansion (July 2026): state grants & promise programs,
  // corporate/STEM/trade contests, women-in-STEM, LGBTQ+, CTE & agriculture,
  // journalism, disability, and identity awards — 81 added, researched
  // against official pages by six parallel verification passes; dedup'd
  // against the live list, curated (a dead contest link cut), citizenship
  // flags conservative (explicit statements only), every URL link-checked. ---
  {
    id: "ccpg-california",
    name: "California College Promise Grant (CCPG)",
    amount: "Waives the $46-per-unit enrollment fee at California community colleges",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "California residents (or students exempt from nonresident fees under the California Dream Act) with financial need enrolled at a California community college.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["california", "state aid", "fee waiver", "community college"],
    officialUrl: "https://icangotocollege.com/financial-aid/california-college-promise-grant",
  },
  {
    id: "texas-grant",
    name: "TEXAS Grant (Toward EXcellence, Access, and Success)",
    amount: "Up to $5,429 per semester at Texas public universities (FY 2026 maximum)",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Texas residents with financial need enrolled at least three-quarter time at a Texas public university.",
    stages: ["high-school", "college"],
    tags: ["texas", "state aid", "need-based"],
    officialUrl: "https://www.highered.texas.gov/student-financial-aid-programs/grant-loan-programs/",
  },
  {
    id: "terry-foundation",
    name: "Terry Foundation Scholarship",
    amount: "Full-ride, last-dollar scholarship covering up to eight semesters",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Texas residents who graduated from a Texas high school and enroll full-time as entering freshmen at one of 11 Terry-affiliated Texas public universities.",
    stages: ["high-school"],
    tags: ["texas", "full ride", "foundation", "leadership"],
    officialUrl: "https://www.terryfoundation.org/",
  },
  {
    id: "florida-bright-futures",
    name: "Florida Bright Futures Scholarship",
    amount: "100% of tuition and applicable fees (Academic Scholars) or 75% (Medallion Scholars) at Florida public institutions",
    deadline: "Typically August",
    deadlineMonth: 8,
    who: "Florida high school graduates who meet GPA, test-score, and community-service benchmarks and enroll at an eligible Florida postsecondary institution.",
    stages: ["high-school"],
    tags: ["florida", "state aid", "merit"],
    officialUrl: "https://www.floridastudentfinancialaidsg.org/",
  },
  {
    id: "fsag-florida",
    name: "Florida Student Assistance Grant (FSAG)",
    amount: "Varies by institution; $200 minimum annual award, maximum set yearly by the Florida Legislature",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Florida residents who are undergraduates with substantial financial need at participating Florida institutions.",
    stages: ["high-school", "college"],
    tags: ["florida", "state aid", "need-based"],
    officialUrl: "https://www.floridastudentfinancialaidsg.org/PDF/factsheets/FSAG.pdf",
  },
  {
    id: "take-stock-in-children",
    name: "Take Stock in Children",
    amount: "Florida Prepaid STARS college scholarship plus one-on-one mentoring and college readiness coaching",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Low-income Florida students who enter the program in middle or high school and commit to staying on track for college.",
    stages: ["high-school"],
    tags: ["florida", "mentoring", "nonprofit", "first generation"],
    officialUrl: "https://www.takestockinchildren.org/",
  },
  {
    id: "excelsior-ny",
    name: "Excelsior Scholarship",
    amount: "Covers remaining SUNY/CUNY tuition after other grants are applied (last-dollar)",
    deadline: "Typically August",
    deadlineMonth: 8,
    who: "New York State residents from households earning $125,000 or less who attend a SUNY or CUNY college full-time.",
    stages: ["high-school", "college"],
    tags: ["new york", "state aid", "promise", "free college"],
    officialUrl: "https://hesc.ny.gov/find-aid/nys-grants-scholarships/excelsior-scholarship-program",
  },
  {
    id: "nys-tap",
    name: "NYS Tuition Assistance Program (TAP)",
    amount: "Up to $5,665 per year",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "New York State residents who meet income limits and attend an in-state college at least half-time.",
    stages: ["high-school", "college"],
    tags: ["new york", "state aid", "need-based"],
    officialUrl: "https://hesc.ny.gov/find-aid/nys-grants-scholarships/tuition-assistance-program-tap",
  },
  {
    id: "nys-dream-act",
    name: "Senator Jose Peralta NYS DREAM Act",
    amount: "Varies — unlocks NYS-administered aid such as TAP (up to $5,665/year) and state scholarships",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "New York students, including undocumented students, who earned a NY high school diploma or GED or qualify for in-state tuition.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["new york", "state aid", "undocumented", "dream act"],
    officialUrl: "https://hesc.ny.gov/applying-aid/nys-dream-act",
  },
  {
    id: "pa-state-grant",
    name: "Pennsylvania State Grant",
    amount: "Up to $5,750 for 2025-26 (in-state maximum)",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Pennsylvania residents with financial need enrolled at least half-time in an approved program of two or more academic years.",
    stages: ["high-school", "college"],
    tags: ["pennsylvania", "state aid", "need-based"],
    officialUrl: "https://www.pheaa.org/grants/state-grant-program",
  },
  {
    id: "octavius-catto",
    name: "Octavius Catto Scholarship",
    amount: "Full tuition and fees plus course materials and up to a $1,600-per-semester stipend",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "Philadelphia residents of 12+ months who enroll full-time at Community College of Philadelphia with a Student Aid Index of $8,000 or less.",
    stages: ["high-school", "college", "transfer"],
    tags: ["pennsylvania", "promise", "community college", "last dollar"],
    officialUrl: "https://www.ccp.edu/admission-aid/paying-college/scholarships/octavius-catto-scholarship",
  },
  {
    id: "pittsburgh-promise",
    name: "Pittsburgh Promise",
    amount: "Up to $5,000 per year ($20,000 maximum)",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Graduates of Pittsburgh Public Schools (classes through 2028) who have been enrolled since the start of 9th grade and meet eligibility criteria.",
    stages: ["high-school"],
    tags: ["pennsylvania", "promise", "last dollar", "pittsburgh"],
    officialUrl: "https://pittsburghpromise.org/the-scholarship/about/",
  },
  {
    id: "illinois-map",
    name: "Illinois Monetary Award Program (MAP)",
    amount: "Up to $8,400 per year toward tuition and mandatory fees",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Illinois residents with financial need attending approved Illinois colleges, including adult and part-time students.",
    stages: ["high-school", "college", "transfer"],
    openToUndocumented: true,
    tags: ["illinois", "state aid", "need-based"],
    officialUrl: "https://www.isac.org/students/during-college/types-of-financial-aid/grants/monetary-award-program/",
  },
  {
    id: "aim-high-illinois",
    name: "AIM HIGH Grant (Illinois)",
    amount: "Varies by university; renewable merit award toward cost of attendance at Illinois' 12 public universities",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Illinois residents enrolling for the first time at one of the state's 12 public four-year universities, with household income under eight times the poverty guideline.",
    stages: ["high-school", "transfer"],
    openToUndocumented: true,
    tags: ["illinois", "state aid", "merit"],
    officialUrl: "https://www.isac.org/students/during-college/types-of-financial-aid/grants/aim-high.html",
  },
  {
    id: "chicago-star",
    name: "Chicago Star Scholarship",
    amount: "Free tuition plus books and materials at City Colleges of Chicago (last-dollar waiver)",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Chicago Public Schools and partner Big Shoulders Fund high school graduates with a 3.0 GPA attending City Colleges of Chicago.",
    stages: ["high-school"],
    tags: ["illinois", "promise", "community college"],
    officialUrl: "https://colleges.ccc.edu/chicago-star-scholarship/",
  },
  {
    id: "golden-apple-scholars",
    name: "Golden Apple Scholars (Illinois)",
    amount: "Up to $23,000 in total financial assistance, including paid professional development",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Illinois high school seniors and early college students who commit to teach five years in an Illinois school-of-need after graduating.",
    stages: ["high-school", "college"],
    openToUndocumented: true,
    tags: ["illinois", "teaching", "service scholarship"],
    officialUrl: "https://www.goldenapple.org/scholars-illinois",
  },
  {
    id: "ocog-ohio",
    name: "Ohio College Opportunity Grant (OCOG)",
    amount: "Up to $4,000 per year at Ohio public universities; up to $5,000 at private nonprofit colleges",
    deadline: "Typically October",
    deadlineMonth: 10,
    who: "Ohio residents with high financial need (SAI of $3,750 or less and household income of $96,000 or less) pursuing a first degree.",
    stages: ["high-school", "college", "transfer"],
    tags: ["ohio", "state aid", "need-based"],
    officialUrl: "https://highered.ohio.gov/wps/portal/gov/odhe/students/pay-for-college/ohio-grants-scholarships/ocog/ocog",
  },
  {
    id: "ohio-governors-merit",
    name: "Governor's Merit Scholarship (Ohio)",
    amount: "$5,000 per year, renewable for up to four years",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Ohio high school seniors in the top 5% of their graduating class who attend an eligible Ohio college or university.",
    stages: ["high-school"],
    tags: ["ohio", "state aid", "merit"],
    officialUrl: "https://meritscholarship.ohio.gov/",
  },
  {
    id: "choose-ohio-first",
    name: "Choose Ohio First (STEM)",
    amount: "Varies by college; recent averages about $4,300 per year at four-year schools and $2,200 at two-year schools",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Ohio residents pursuing a certificate through graduate degree in an eligible STEM field, or STEM teaching, at participating Ohio colleges.",
    stages: ["high-school", "college", "transfer"],
    tags: ["ohio", "state aid", "stem"],
    officialUrl: "https://highered.ohio.gov/initiatives/affordability/choose-ohio-first/cof-faq",
  },
  {
    id: "hope-scholarship-ga",
    name: "HOPE Scholarship (Georgia)",
    amount: "Covers a large share of tuition at eligible Georgia colleges (per-credit-hour award rates set annually)",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Georgia residents who graduate with a 3.0 HOPE GPA (or earn it in college) and attend an eligible Georgia college.",
    stages: ["high-school", "college", "transfer"],
    tags: ["georgia", "state aid", "merit"],
    officialUrl: "https://www.gafutures.org/hope-state-aid-programs/hope-zell-miller-scholarships/hope-scholarship/",
  },
  {
    id: "zell-miller-ga",
    name: "Zell Miller Scholarship (Georgia)",
    amount: "Award applied toward full standard undergraduate tuition (a higher rate than HOPE; tables set annually)",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Georgia's highest-achieving residents, generally a 3.7 high school GPA plus test-score or valedictorian/salutatorian criteria.",
    stages: ["high-school", "college", "transfer"],
    tags: ["georgia", "state aid", "merit"],
    officialUrl: "https://www.gafutures.org/hope-state-aid-programs/hope-zell-miller-scholarships/zell-miller-scholarship/",
  },
  {
    id: "hope-grant-ga",
    name: "HOPE Grant (Georgia)",
    amount: "Pays toward tuition for certificate and diploma programs (per-credit-hour rates set annually); no minimum high school GPA",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Georgia residents working toward a certificate or diploma at an eligible Georgia college, most often a technical college.",
    stages: ["high-school", "college"],
    tags: ["georgia", "state aid", "career training"],
    officialUrl: "https://www.gafutures.org/hope-state-aid-programs/hope-zell-miller-grants/hope-grant/",
  },
  {
    id: "next-nc",
    name: "Next NC Scholarship",
    amount: "At least $3,000 per year at NC community colleges; at least $5,000 per year at UNC System universities",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "North Carolina residents from households with adjusted gross income of $80,000 or less attending an NC community college or UNC System university.",
    stages: ["high-school", "college", "transfer"],
    tags: ["north carolina", "state aid", "promise"],
    officialUrl: "https://www.cfnc.org/pay-for-college/next-nc-scholarship/",
  },
  {
    id: "golden-leaf-nc",
    name: "Golden LEAF Scholarship (North Carolina)",
    amount: "$3,500 per year for up to four years (up to $14,000); community college awards up to $2,250 per year",
    deadline: "Varies",
    deadlineMonth: null,
    who: "High school seniors and community college transfer students from rural North Carolina counties who intend to return to rural NC after graduating.",
    stages: ["high-school", "transfer"],
    tags: ["north carolina", "rural", "scholarship"],
    officialUrl: "https://scholars.goldenleaf.org/",
  },
  {
    id: "michigan-achievement",
    name: "Michigan Achievement Scholarship",
    amount: "Tuition-free community college (Community College Guarantee) or up to $5,500 per year for five years (up to $27,500) at universities",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Recent Michigan high school graduates attending a Michigan community college, public university, or private college.",
    stages: ["high-school"],
    tags: ["michigan", "state aid", "promise"],
    officialUrl: "https://www.michigan.gov/mistudentaid/programs/michigan-achievement-scholarship",
  },
  {
    id: "michigan-reconnect",
    name: "Michigan Reconnect",
    amount: "Free in-district tuition, mandatory fees, and contact hours at Michigan public community colleges",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "Michigan adults 25 or older with a high school diploma or equivalent and no college degree, resident for at least a year.",
    stages: ["college"],
    tags: ["michigan", "state aid", "adult learners", "promise"],
    officialUrl: "https://www.michigan.gov/reconnect",
  },
  {
    id: "detroit-promise",
    name: "Detroit Promise",
    amount: "Tuition-free path to a certificate, associate, or bachelor's degree at 32 Michigan colleges (last-dollar scholarship)",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Detroit residents who graduate from an eligible Detroit high school.",
    stages: ["high-school"],
    tags: ["michigan", "detroit", "promise"],
    officialUrl: "https://www.detroitpromise.com/",
  },
  {
    id: "fostering-futures-mi",
    name: "Fostering Futures Scholarship (Michigan)",
    amount: "Up to $5,000 for the 2025-26 academic year, toward tuition, fees, books, and supplies",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "Michigan undergraduates who experienced foster care in Michigan on or after age 13 and demonstrate financial need.",
    stages: ["high-school", "college", "transfer"],
    tags: ["michigan", "foster youth", "state aid"],
    officialUrl: "https://www.michigan.gov/mistudentaid/programs/fostering-futures-scholarship",
  },
  {
    id: "stuck-at-prom",
    name: "Duck Brand Stuck at Prom Scholarship Contest",
    amount: "$10,000 grand prize (one dress, one tux); $1,000 for each of eight runners-up",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "High school students in the U.S. and Canada who design and wear prom attire made from Duck Tape; prom attendance not required.",
    stages: ["high-school"],
    tags: ["creative", "contest", "corporate"],
    officialUrl: "https://www.duckbrand.com/stuck-at-prom",
  },
  {
    id: "samsung-legion",
    name: "Samsung American Legion Scholarship",
    amount: "$10,000 (10 National Scholars); $5,000 (10 runners-up); $1,250 (department finalists)",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "High school juniors attending American Legion Boys State or Auxiliary Girls State who are direct descendants of wartime U.S. veterans.",
    stages: ["high-school"],
    tags: ["military-family", "leadership", "corporate"],
    officialUrl: "https://www.legion.org/scholarships/samsung",
  },
  {
    id: "path-to-pro",
    name: "Home Depot Foundation Path to Pro Scholarship",
    amount: "$2,500",
    deadline: "Rolling",
    deadlineMonth: null,
    who: "High school seniors, graduates, or GED holders entering an accredited skilled-trades program (HVAC, electrical, plumbing, carpentry, construction management), administered by the SkillPointe Foundation.",
    stages: ["high-school", "college"],
    tags: ["trades", "vocational", "corporate"],
    officialUrl: "https://corporate.homedepot.com/page/path-pro-scholarship-programs",
  },
  {
    id: "wells-fargo-veterans",
    name: "Wells Fargo Veterans Scholarship Program",
    amount: "Up to $5,000 per year, renewable up to three additional years",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Honorably discharged U.S. veterans (including Guard/Reserve), spouses of service-disabled veterans, and widows of veterans pursuing undergraduate or first-master's study.",
    stages: ["college", "transfer"],
    tags: ["veterans", "military", "corporate"],
    officialUrl: "https://scholarshipamerica.org/scholarship/wellsfargoveterans/",
  },
  {
    id: "stacey-milbern",
    name: "Wells Fargo Stacey Milbern Scholarship",
    amount: "$2,500 (full-time study) or $1,250 (half-time)",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "High school seniors and current undergraduates with an identified disability and a 3.0+ GPA, nationwide.",
    stages: ["high-school", "college"],
    tags: ["disability", "corporate"],
    officialUrl: "https://scholarshipamerica.org/scholarship/pwdscholarship/",
  },
  {
    id: "uhf-health-care-scholars",
    name: "United Health Foundation Health Care Scholars United Scholarship",
    amount: "$3,200 (up to 325 awards)",
    deadline: "Typically September",
    deadlineMonth: 9,
    who: "Students nationwide in the final year of a clinical health degree, certificate, or credential program (pharmacy, nursing, behavioral, maternal, rural, primary care) with financial need.",
    stages: ["college"],
    tags: ["healthcare", "career-specific", "corporate"],
    officialUrl: "https://scholarshipamerica.org/scholarship/unitedhealthfoundation/",
  },
  {
    id: "haz-la-u",
    name: "Colgate-Palmolive Haz la U / Make the U Educational Grant",
    amount: "$10,000 national grant; additional $2,000–$4,000 grants (31 total)",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "High school seniors in U.S. states and territories with a 3.0+ unweighted GPA; run with the Hispanic Heritage Foundation with a focus on Latino students.",
    stages: ["high-school"],
    tags: ["hispanic-latino", "community", "corporate"],
    officialUrl: "https://www.colgate.com/en-us/mission/make-the-u",
  },
  {
    id: "nm-cancer-survivor",
    name: "Northwestern Mutual Childhood Cancer Survivor Scholarship",
    amount: "Up to $10,000 (25 awards)",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Childhood cancer survivors age 25 or under, nationwide, who are high school seniors or current undergraduates enrolling full-time.",
    stages: ["high-school", "college"],
    tags: ["cancer-community", "medical-hardship", "corporate"],
    officialUrl: "https://scholarshipamerica.org/scholarship/nmsurvivors/",
  },
  {
    id: "nm-cancer-sibling",
    name: "Northwestern Mutual Childhood Cancer Sibling Scholarship",
    amount: "Up to $10,000 (25 awards)",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Siblings (age 25 or under, nationwide) of children who are in treatment for, survived, or died from childhood cancer.",
    stages: ["high-school", "college"],
    tags: ["cancer-community", "medical-hardship", "corporate"],
    officialUrl: "https://scholarshipamerica.org/scholarship/nmsibling/",
  },
  {
    id: "exploravision",
    name: "Toshiba/NSTA ExploraVision Science Competition",
    amount: "$10,000 U.S. savings bond (at maturity) per student on first-place teams; $5,000 for second place",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "K-12 student teams in the U.S. and Canada (with a teacher coach) who design a technology of the future; no entry fee.",
    stages: ["high-school"],
    tags: ["STEM", "competition", "team", "corporate"],
    officialUrl: "https://www.exploravision.org/",
  },
  {
    id: "ncwit-collegiate",
    name: "NCWIT Aspirations in Computing Collegiate Award",
    amount: "$7,500 (winners); $2,500 (honorable mentions)",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Women and nonbinary college students in computing or engineering who join NCWIT's free Aspirations in Computing community.",
    stages: ["college"],
    tags: ["women", "STEM"],
    officialUrl: "https://www.aspirations.org/award-programs/aic-collegiate-award",
  },
  {
    id: "awg-geoscience",
    name: "AWG Geoscience IDEA Scholarship (Association for Women Geoscientists)",
    amount: "$2,500 (three awards) plus one $500 Rising Potential award",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Undergraduate women from under-served communities studying geoscience at a U.S. college or university.",
    stages: ["college"],
    tags: ["women", "STEM"],
    officialUrl: "https://www.awg.org/page/ScholarshipsandAwards",
  },
  {
    id: "hyundai-women-stem",
    name: "Hyundai Women in STEM Scholarship",
    amount: "$10,000 (five awards)",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Female high school seniors and college undergraduates in the U.S. pursuing a STEM field, selected through an annual essay contest.",
    stages: ["high-school", "college"],
    tags: ["women", "STEM"],
    officialUrl: "https://www.hyundainews.com/en-us/releases/4409",
  },
  {
    id: "women-in-aviation",
    name: "Women in Aviation International Scholarships",
    amount: "Varies by scholarship (dozens awarded annually)",
    deadline: "Typically September",
    deadlineMonth: 9,
    who: "Women in Aviation International members at any career stage pursuing aviation degrees, flight training, and aerospace careers.",
    stages: ["high-school", "college"],
    tags: ["women", "STEM"],
    officialUrl: "https://www.wai.org/education/scholarships",
  },
  {
    id: "amelia-earhart-99s",
    name: "Amelia Earhart Memorial Academic Scholarship (The Ninety-Nines)",
    amount: "Up to $10,000 per year",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Women pilot members of The Ninety-Nines pursuing college degrees in aviation or aerospace fields.",
    stages: ["college"],
    tags: ["women", "STEM"],
    officialUrl: "https://ninety-nines.org/ae-memorial-scholarships/",
  },
  {
    id: "ieee-wie",
    name: "IEEE Women in Engineering International Scholarship",
    amount: "$2,500",
    deadline: "Typically November",
    deadlineMonth: 11,
    who: "Female IEEE Women in Engineering student members who have completed two years of an undergraduate engineering program.",
    stages: ["college"],
    tags: ["women", "STEM"],
    officialUrl: "https://wie.ieee.org/grants-scholarships/international-scholarship/",
  },
  {
    id: "aysen-tunca-sps",
    name: "Aysen Tunca Memorial Scholarship (Society of Physics Students)",
    amount: "$2,500",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Female sophomore or junior STEM majors who are Society of Physics Students members at U.S. colleges, with preference for first-generation students.",
    stages: ["college"],
    tags: ["women", "STEM"],
    officialUrl: "https://students.aip.org/aysen-tunca-memorial-scholarship",
  },
  {
    id: "point-community-college",
    name: "Point Foundation Community College Scholarship",
    amount: "$4,800",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "LGBTQ+ and ally students earning an associate degree or planning to transfer to a four-year college.",
    stages: ["high-school", "college", "transfer"],
    tags: ["LGBTQ"],
    officialUrl: "https://pointfoundation.org/scholarships/community-college",
  },
  {
    id: "gamma-mu",
    name: "Gamma Mu Foundation Scholarships",
    amount: "$2,500–$5,000",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Gay men under 35 nationwide (some named awards open to all LGBTQ+ students), with preference for students from rural and underserved parts of America.",
    stages: ["high-school", "college"],
    tags: ["LGBTQ"],
    officialUrl: "https://www.gammamufoundation.org/scholarship-guidelines---application-info",
  },
  {
    id: "pfund",
    name: "PFund Foundation Scholarships",
    amount: "$1,000–$12,000 (average $1,500)",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "LGBTQ+ students in Iowa, Minnesota, North Dakota, South Dakota, Wisconsin, or the Native Nations therein, at any stage of education including trade school.",
    stages: ["high-school", "college", "transfer"],
    tags: ["LGBTQ"],
    officialUrl: "https://www.pfundfoundation.org/scholarships",
  },
  {
    id: "traub-dicker-rainbow",
    name: "Traub-Dicker Rainbow Scholarship (Stonewall Community Foundation)",
    amount: "$4,000",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Lesbian students pursuing undergraduate or graduate study anywhere in the United States.",
    stages: ["high-school", "college"],
    tags: ["LGBTQ", "women"],
    officialUrl: "https://www.stonewallfoundation.org/scholarships/",
  },
  {
    id: "markowski-leach",
    name: "Markowski-Leach Scholarship",
    amount: "Varies ($508,500 awarded across 363 scholarships since 1991)",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "LGBTQ students enrolling full-time at one of eight San Francisco Bay Area-affiliated California universities, including Stanford, UC Berkeley, and San Francisco State.",
    stages: ["college"],
    tags: ["LGBTQ"],
    officialUrl: "https://mlscholarships.org/",
  },
  {
    id: "live-out-loud",
    name: "Live Out Loud Young Trailblazers Scholarship",
    amount: "$5,000",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "LGBTQ+ high school seniors in New York State with financial need heading to college, university, or vocational programs.",
    stages: ["high-school"],
    tags: ["LGBTQ"],
    officialUrl: "https://liveoutloud.org/programs/young-trailblazers-scholarship/",
  },
  {
    id: "apiqwtc",
    name: "APIQWTC Scholarship",
    amount: "$3,500 (two awards)",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "Asian and Pacific Islander lesbian, bisexual, or queer women and transgender or nonbinary students entering or enrolled in U.S. degree or certificate programs.",
    stages: ["high-school", "college"],
    tags: ["LGBTQ", "women"],
    officialUrl: "https://apiqwtc.org/call-for-applications-apiqwtc-scholarship-2026/",
  },
  {
    id: "nfpa-youth-foster",
    name: "NFPA Youth Scholarship (National Foster Parent Association)",
    amount: "$500",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "High school seniors or GED students ages 17-21 from foster, kinship, or adoptive families whose parent or another supportive adult is an NFPA member.",
    stages: ["high-school"],
    tags: ["foster youth"],
    officialUrl: "https://nfpaonline.org/resources/scholarships/",
  },
  {
    id: "skillsusa",
    name: "SkillsUSA Scholarships",
    amount: "$1,000-$2,500",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Registered, active SkillsUSA members in high school or college/postsecondary career and technical education programs.",
    stages: ["high-school", "college"],
    tags: ["trades"],
    officialUrl: "https://www.skillsusa.org/membership-resources/scholarships-financial-aid/",
  },
  {
    id: "phcc-foundation",
    name: "PHCC Educational Foundation Scholarships",
    amount: "Up to $5,000",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Apprentices and college or trade-school students preparing for careers in plumbing, heating, and cooling.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://www.phccfoundation.org/scholarship-program/",
  },
  {
    id: "nawic-founders",
    name: "NAWIC Founders' Scholarship Foundation",
    amount: "$2,000 and up",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Students enrolled in construction-related degree or trades training programs at U.S. schools, awarded by the National Association of Women in Construction's foundation.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://nfsf.nawic.org/",
  },
  {
    id: "agc-foundation",
    name: "AGC Education & Research Foundation Undergraduate Scholarship",
    amount: "$2,500 per year (renewable up to 3 years)",
    deadline: "Varies",
    deadlineMonth: null,
    who: "U.S. citizens or permanent residents enrolled in ABET- or ACCE-accredited construction management or construction-related engineering programs.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://www.agc.org/learn/education-and-research-foundation/scholarship-program",
  },
  {
    id: "women-in-hvacr",
    name: "Women in HVACR Scholarships",
    amount: "$5,000 (six awarded)",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Women enrolled in HVACR programs at trade schools, technical colleges, or four-year universities with a 3.0 GPA.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://www.womeninhvacr.org/scholarships",
  },
  {
    id: "national-housing-endowment",
    name: "National Housing Endowment Student Scholarships",
    amount: "Varies by fund",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Students in residential construction-related programs such as construction management, construction trades, building technology, or design.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://nationalhousingendowment.org/learn-and-apply/student-scholarships",
  },
  {
    id: "sema-memorial",
    name: "SEMA Memorial Scholarship",
    amount: "Up to $5,000",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "U.S. or Canadian citizens pursuing automotive degrees or certifications for careers in the automotive aftermarket industry.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://sites.sema.org/scholarships",
  },
  {
    id: "sparkforce-fma",
    name: "SparkForce Scholarships (FMA Foundation, formerly Nuts, Bolts & Thingamajigs)",
    amount: "Up to $2,000 per semester",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Students in certification, skills-training, or degree programs at community colleges, trade schools, or universities that lead to manufacturing careers.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://fmamfg.org/scholarships",
  },
  {
    id: "horatio-alger-cte",
    name: "Horatio Alger Career & Technical Scholarship",
    amount: "$2,500 (300 awarded)",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "U.S. citizens under 30 with household income of $65,000 or less who have overcome adversity and are entering a certificate or associate program at a nonprofit community college or trade school.",
    stages: ["college"],
    tags: ["trades"],
    officialUrl: "https://horatioalger.org/career-technical-education-scholarships/",
  },
  {
    id: "ernestine-keiser-grange",
    name: "Ernestine Keiser Memorial Scholarship (Grange Foundation)",
    amount: "$1,000",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Members of the Grange, the national rural community organization, with at least one year of membership, from high school seniors through college, vocational, and certificate students.",
    stages: ["high-school", "college"],
    tags: ["rural"],
    officialUrl: "https://grangefoundation.org/ernestine-memorial-scholarship/",
  },
  {
    id: "farm-credit-ag",
    name: "Farm Credit Foundation for Agricultural Advancement Scholarship",
    amount: "Up to $10,000",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "High school seniors and current college students planning agriculture careers who live in Horizon Farm Credit territory: Delaware, Maryland, Pennsylvania, and parts of Virginia and West Virginia, plus Washington, D.C.",
    stages: ["high-school", "college"],
    tags: ["rural"],
    officialUrl: "https://fcfoundationforag.org/",
  },
  {
    id: "grow-ag-leaders",
    name: "Grow Ag Leaders Scholarship (Bayer Fund)",
    amount: "$1,500",
    deadline: "Typically January",
    deadlineMonth: 1,
    who: "Rural high school seniors and college students pursuing degrees or certifications in agriculture-related fields (administered through National FFA; FFA membership not required).",
    stages: ["high-school", "college"],
    tags: ["rural"],
    officialUrl: "https://www.bayer.com/en/us/agriculture/cultivating-ag-leaders",
  },
  {
    id: "durastak-syngenta",
    name: "Durastak Traits of Tomorrow Scholarship (Syngenta)",
    amount: "$2,000 (five awarded)",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "High school seniors and college or graduate students in STEM or agriculture fields at schools in 12 Midwest states (IL, IN, IA, KS, MI, MN, MO, NE, ND, OH, SD, WI).",
    stages: ["high-school", "college"],
    tags: ["rural"],
    officialUrl: "https://www.syngenta-us.com/seed/corn-traits/durastak-scholarship",
  },
  {
    id: "naacp-agnes-jones",
    name: "NAACP Agnes Jones Jackson Scholarship",
    amount: "$2,000",
    deadline: "Typically May",
    deadlineMonth: 5,
    who: "Black/African American high school seniors, undergrads, or grad students under 25 with financial need; NAACP membership (dues) required.",
    stages: ["high-school", "college"],
    tags: ["Black", "identity", "need-based", "membership-org"],
    officialUrl: "https://naacp.org/find-resources/scholarships-awards-internships/scholarships/agnes-jones-jackson-scholarship",
  },
  {
    id: "naba-national",
    name: "NABA National Scholarship Program",
    amount: "$2,500-$10,000",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Black students in accounting, finance, technology, or business enrolled full-time at a U.S. 2- or 4-year college; free NABA student membership required.",
    stages: ["college"],
    tags: ["Black", "accounting", "business", "membership-org"],
    officialUrl: "https://www.nabainc.org/scholarships",
  },
  {
    id: "nabj",
    name: "NABJ Scholarships",
    amount: "Up to $10,000",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Black high school and college students pursuing journalism careers; NABJ student membership (dues) required to apply.",
    stages: ["high-school", "college"],
    tags: ["Black", "journalism", "membership-org"],
    officialUrl: "https://nabjonline.org/student-services/scholarships/",
  },
  {
    id: "nahj",
    name: "NAHJ Scholarships",
    amount: "$2,000-$6,000",
    deadline: "Typically December",
    deadlineMonth: 12,
    who: "High school seniors, undergrads, and grad students pursuing journalism at colleges in the U.S. and Puerto Rico, with a focus on Hispanic/Latino journalists.",
    stages: ["high-school", "college"],
    tags: ["Latino", "journalism"],
    officialUrl: "https://nahj.org/scholarships/",
  },
  {
    id: "aaja",
    name: "AAJA Scholarships and Grants",
    amount: "$1,000-$2,000",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "College students pursuing journalism, with a focus on Asian American and Pacific Islander journalists; some awards require AAJA student membership (dues).",
    stages: ["college"],
    tags: ["Asian American", "journalism", "membership-org"],
    officialUrl: "https://www.aaja.org/programs/scholarships/",
  },
  {
    id: "ija-aaja-pacific-islander",
    name: "IJA-AAJA Pacific Islander Journalism Scholarship",
    amount: "$5,000",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "Pacific Islander students and early-career journalists committed to coverage of Indigenous Pacific peoples; winners receive IJA and AAJA student memberships.",
    stages: ["college"],
    tags: ["Pacific Islander", "Indigenous", "journalism"],
    officialUrl: "https://www.ijastudents.org/aaja-pacific-islander-scholarship",
  },
  {
    id: "nbna",
    name: "NBNA Scholarship Program",
    amount: "$1,000+",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Black students enrolled in a nursing program (LPN/LVN through BSN and beyond) with at least one year of school remaining; NBNA and local chapter membership (dues) required.",
    stages: ["college"],
    tags: ["Black", "nursing", "health", "membership-org"],
    officialUrl: "https://nbna.org/programs-committees/programs/scholarships/",
  },
  {
    id: "cbc-spouses",
    name: "CBC Spouses Education Scholarship (Congressional Black Caucus Foundation)",
    amount: "Varies",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "African American or Black students pursuing undergraduate, graduate, or doctoral degrees; CBCF also runs visual arts, performing arts, and other named awards.",
    stages: ["college"],
    tags: ["Black", "identity"],
    officialUrl: "https://www.cbcfinc.org/scholarships/",
  },
  {
    id: "nfb-scholarship",
    name: "National Federation of the Blind Scholarship Program",
    amount: "$10,000",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Legally blind students residing in the U.S., D.C., or Puerto Rico pursuing full-time post-secondary study; finalists attend the NFB National Convention in July.",
    stages: ["high-school", "college"],
    tags: ["disability", "blind"],
    officialUrl: "https://nfb.org/programs-services/scholarships-and-awards/scholarship-program",
  },
  {
    id: "sertoma-hearing",
    name: "Sertoma Hard of Hearing or Deaf Scholarship",
    amount: "Varies",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "U.S. citizens with a minimum 40dB bilateral hearing loss pursuing a bachelor's degree full-time, with a 3.2+ GPA.",
    stages: ["high-school", "college"],
    tags: ["disability", "deaf-hard-of-hearing"],
    officialUrl: "https://www.sertoma.org/what-we-do/scholarships/",
  },
  {
    id: "anne-ford-ncld",
    name: "Anne Ford Scholarship (NCLD)",
    amount: "$10,000 ($2,500/year over four years)",
    deadline: "Varies",
    deadlineMonth: null,
    who: "Graduating high school seniors with a documented learning disability who will enroll in a full-time bachelor's degree program.",
    stages: ["high-school"],
    tags: ["disability", "learning-disability"],
    officialUrl: "https://www.ncld.org/scholarships/",
  },
  {
    id: "rubys-rainbow",
    name: "Ruby's Rainbow Scholarship",
    amount: "$1,000-$10,000",
    deadline: "Typically April",
    deadlineMonth: 4,
    who: "Adults (18+) with Down syndrome enrolling in any post-secondary program - college, vocational, trade, certificate, or life-skills programs.",
    stages: ["high-school", "college"],
    tags: ["disability", "Down-syndrome"],
    officialUrl: "https://rubysrainbow.org/scholarship-application/",
  },
  {
    id: "dfbsst",
    name: "Development Fund for Black Students in Science and Technology (DFBSST)",
    amount: "Up to $3,000/year, renewable four years",
    deadline: "Typically June",
    deadlineMonth: 6,
    who: "African American undergraduates majoring in engineering, math, or science at participating HBCUs; U.S. citizen or permanent resident required.",
    stages: ["college"],
    tags: ["Black", "STEM", "HBCU"],
    officialUrl: "https://www.dfbsstscholarship.org/dfb_sch.html",
  },
  {
    id: "blacks-at-microsoft",
    name: "Blacks at Microsoft (BAM) Scholarship",
    amount: "$2,500-$5,000",
    deadline: "Typically March",
    deadlineMonth: 3,
    who: "Black/African American high school seniors headed to a four-year U.S. college in engineering, computer science, computer information systems, or select business programs; 3.0+ GPA and financial need.",
    stages: ["high-school"],
    tags: ["Black", "STEM", "business", "corporate"],
    officialUrl: "https://scholarshipamerica.org/scholarship/blacks-at-microsoft",
  },
  {
    id: "telacu",
    name: "TELACU Education Foundation College Success Program",
    amount: "Varies",
    deadline: "Typically February",
    deadlineMonth: 2,
    who: "College-bound and current college students from eligible communities in California, Illinois, New York, and Texas; priority to first-generation, low-income Latino students in STEAM or business majors.",
    stages: ["high-school", "college"],
    tags: ["Latino", "first-gen", "regional-multi-state", "STEM", "business"],
    officialUrl: "https://telacu.com/telacu-education-foundation/college-success-program/",
  },
];
