// Generated from the completed 2026-08-05 Scholarship Finder QC audit.
//
// These records are legitimate programs whose only audit-blocking category,
// after duplicate and current-existence checks, was the absence of a published
// guarantee that every individual award is at least $500. The site owner
// approved publishing this group on 2026-08-06. The remaining manual-review
// records stay withheld.

export const SCHOLARSHIP_AMOUNT_FLOOR_EXCEPTION_COUNT = 495;

export const scholarshipAmountFloorExceptionIds = new Set(
  [
  "point",
  "mikerowe-work-ethic",
  "techforce",
  "swe-scholarships",
  "esa-game-arts",
  "simon-youth",
  "que-llueva-cafe",
  "fontana-scholars",
  "peo-pce",
  "nraef-hospitality",
  "national-housing-endowment",
  "sema-memorial",
  "sparkforce-fma",
  "farm-credit-ag",
  "cbc-spouses",
  "dfbsst",
  "blacks-at-microsoft",
  "telacu",
  "nv-promise-scholarship",
  "ut-promise-grant",
  "id-launch-grant",
  "va-g3",
  "tn-promise",
  "sc-need-based-grant",
  "wv-invests",
  "md-community-college-promise",
  "de-seed-scholarship",
  "tx-teog",
  "ma-massgrant-plus",
  "ma-masseducate",
  "ct-willis",
  "ct-pact",
  "nj-ccog",
  "ri-promise",
  "vt-vermont-grant",
  "me-state-grant",
  "pa-rtss",
  "wi-grant",
  "mo-a-plus",
  "mo-access-missouri",
  "ia-last-dollar-scholarship",
  "ne-nebraska-promise",
  "nd-state-grant",
  "aliento-adelante-scholarship",
  "tennessee-reconnect",
  "osher-reentry-scholarship",
  "nacme-scholars-program",
  "arc-foundation-student-scholarships",
  "jflf-welding-awards-program",
  "acf-education-foundation-scholarships",
  "cref-student-scholarship-program",
  "aka-eaf-scholarships",
  "delta-research-educational-foundation",
  "zeta-phi-beta-znef-scholarships",
  "native-forward-scholars-fund",
  "teach-grant",
  "california-national-guard-tuition-assistance",
  "new-york-national-guard-tuition-assistance",
  "florida-national-guard-tuition-assistance",
  "illinois-national-guard-grant",
  "georgia-national-guard-service-cancelable-loan",
  "nc-teaching-fellows",
  "ca-golden-state-teacher-grant",
  "ar-minority-teacher-scholars-program",
  "wa-teacher-shortage-conditional-scholarship",
  "il-special-education-teacher-tuition-waiver",
  "in-transition-to-teaching-scholarship",
  "bmi-student-composer-awards",
  "ascap-morton-gould-young-composer-awards",
  "vsa-playwright-discovery-program",
  "vsa-international-young-musicians-program",
  "agbu-scholarship-program",
  "women-of-elca-scholarship",
  "cogic-charities-scholarship",
  "shdf-sikh-scholarship",
  "ucb-family-epilepsy-scholarship",
  "salix-gi-health-scholars",
  "national-garden-clubs-college-scholarship",
  "gca-keller-conservation-horticulture-scholarship",
  "florida-first-generation-matching-grant",
  "afas-hap-arnold-grant",
  "cgma-supplemental-education-grant",
  "aer-ursano-scholarship",
  "nfff-sarbanes-scholarship",
  "cops-scholarship",
  "frcf-scholarship",
  "american-legion-legacy-scholarship",
  "hope-for-the-warriors-spouse-caregiver-scholarship",
  "architects-foundation-diversity-advancement",
  "noble-national-scholarship",
  "sma-foundation-scholarship",
  "wawa-dick-wood-scholarship",
  "pop-warner-all-american-scholar",
  "first-tee-college-scholarship",
  "usta-foundation-college-scholarship",
  "guam-aheg-sfap",
  "american-samoa-asg-scholarship",
  "federal-etv-program",
  "california-chafee-grant",
  "california-nextup-fee-waiver",
  "washington-passport-to-careers",
  "ucc-undergraduate-scholarship",
  "shdf-usa-scholarship",
  "astronaut-scholarship-foundation",
  "team-up-together-scholarship",
  "ford-opportunity-scholarship",
  "aauw-career-development-grant",
  "league-foundation-scholarship",
  "lighthouse-guild-scholarship",
  "helen-jean-simpson-scholarship",
  "americas-allies-scholarship-program",
  "prosper-scholarship-maine",
  "srm-masonic-range-science-scholarship",
  "aka-eaf-merit-scholarship",
  "znef-general-scholarships",
  "freedom-alliance-scholarship-fund",
  "navy-seal-foundation-scholarship",
  "special-forces-scholarship-fund",
  "tjx-companies-scholarship-program",
  "wegmans-employee-scholarship-program",
  "gilman-scholarship",
  "naemt-foundation-scholarship",
  "amt-amtie-student-scholarship",
  "fnsna-undergraduate-scholarship",
  "chasa-college-scholarships",
  "mda-scholarship-program",
  "cfp-board-corient-scholarship",
  "cmaa-joe-perdue-scholarship",
  "lex-honor-society-scholarship-competition",
  "dollar-general-turner-family-scholarship",
  "wingstop-morrison-family-scholarship",
  "cracker-barrel-employee-scholarship",
  "army-womens-foundation-legacy-scholarship",
  "utah-opportunity-scholarship",
  "vt-802opportunity",
  "ne-opportunity-grant",
  "ks-promise-scholarship",
  "ky-work-ready-scholarship",
  "id-opportunity-scholarship",
  "wy-tomorrow-scholarship",
  "foster-love-brandsource-scholars",
  "foster-love-american-industries-scholarship",
  "chafee-etv-program",
  "nsoro-fostering-futures-scholarship",
  "turn2u-scholarship",
  "prison-education-foundation-scholarship",
  "life-lessons-scholarship-life-happens",
  "families-of-freedom-scholarship-fund",
  "artba-lanford-family-memorial-scholarship",
  "construction-angels-scholarship",
  "john-edgar-thomson-foundation-grant",
  "national-migrant-farmworker-baccalaureate-scholarship",
  "nueva-generacion-scholarship",
  "quell-foundation-fighter-scholarship",
  "quell-foundation-survivor-scholarship",
  "afa-teen-alzheimers-awareness-scholarship",
  "paul-drury-memorial-cf-sibling-scholarship",
  "route-79-duchenne-sibling-scholarship",
  "1000-dreams-fund-scholarship",
  "gfwc-success-for-survivors-scholarship",
  "ptk-new-century-transfer-pathway-scholarship",
  "nj-stars",
  "nj-garden-state-guarantee",
  "virginia-commonwealth-award",
  "virginia-guaranteed-assistance-program",
  "arkansas-arfuture-grant",
  "kentucky-cap-grant",
  "mississippi-tuition-assistance-grant",
  "iowa-tuition-grant",
  "anne-lowe-scholarship-christian-record",
  "ear-community-college-scholarship",
  "sealaska-heritage-scholarship",
  "vfw-sport-clips-help-a-hero-scholarship",
  "veterans-united-foundation-scholarship",
  "lithuanian-foundation-scholarship",
  "california-middle-class-scholarship",
  "nevada-silver-state-opportunity-grant",
  "colorado-opportunity-scholarship-initiative",
  "metlife-foundation-legacy-endowed-scholarship",
  "nad-womens-ministries-scholarship",
  "garage-gurus-automotive-technician-scholarship",
  "hri-scholarship-program",
  "dorothy-i-height-education-foundation-scholarship",
  "bmi-foundation-john-lennon-scholarship",
  "jack-kent-cooke-young-artist-award",
  "cfda-scholarship-fund",
  "nsal-winston-art-scholarship",
  "phi-beta-sigma-education-foundation-scholarship",
  "aabe-national-scholarship",
  "ohio-national-guard-scholarship-program",
  "massachusetts-national-guard-tuition-waiver",
  "indiana-national-guard-supplemental-grant",
  "minnesota-gi-bill-national-guard",
  "michigan-national-guard-state-tuition-assistance",
  "wisconsin-national-guard-tuition-grant",
  "north-carolina-tuition-assistance-program",
  "virginia-foster-youth-tuition-grant",
  "kentucky-foster-adopted-tuition-waiver",
  "massachusetts-foster-child-tuition-waiver",
  "maryland-foster-care-tuition-waiver",
  "illinois-dcfs-tuition-fee-waiver",
  "missouri-reach-tuition-waiver",
  "georgia-foster-care-scholarship",
  "autozone-technicians-assistance-award",
  "yum-brands-andy-pearson-scholarship",
  "caseys-general-stores-scholarship",
  "quiktrip-dependents-scholarship",
  "eaa-flight-training-scholarships",
  "pilot-international-scholarship",
  "estonian-students-fund-scholarship",
  "buffett-scholarship-nebraska",
  "ny-stem-incentive-program",
  "dc-mayors-scholars-undergraduate-program",
  "vsac-advancement-grant",
  "maine-free-community-college",
  "utah-adult-learner-grant",
  "missouri-fast-track-workforce-incentive-grant",
  "wyoming-investment-in-nursing",
  "virginia-tuition-assistance-grant",
  "texas-tuition-equalization-grant",
  "kentucky-tuition-grant",
  "arizona-leap",
  "west-virginia-higher-education-grant",
  "illinois-veteran-grant",
  "ohio-war-orphans-scholarship",
  "tennessee-strong-act",
  "virginia-guard-state-tuition-assistance",
  "wv-educational-encouragement-program",
  "kansas-guard-educational-assistance",
  "nebraska-guard-tuition-credit",
  "iowa-guard-service-scholarship",
  "idaho-guard-seap",
  "montana-guard-tuition-waiver",
  "nevada-guard-fee-waiver",
  "oklahoma-guard-educational-assistance",
  "washington-guard-postsecondary-grant",
  "colorado-guard-tuition-waiver",
  "connecticut-guard-tuition-waiver",
  "rhode-island-guard-stap",
  "maine-guard-education-assistance",
  "vermont-guard-tuition-benefit",
  "new-hampshire-guard-educational-assistance",
  "delaware-guard-state-tuition-assistance",
  "arkansas-guard-tuition-waiver",
  "louisiana-guard-step",
  "mississippi-guard-seap",
  "kentucky-guard-tuition-award",
  "utah-guard-state-tuition-assistance",
  "arizona-guard-tuition-reimbursement",
  "north-dakota-guard-tuition-assistance",
  "south-dakota-guard-tuition-assistance",
  "hawaii-guard-stap",
  "alaska-guard-tuition-reimbursement",
  "sc-teaching-fellows",
  "arkansas-teacher-academy-scholarship",
  "missouri-teacher-recruitment-retention-scholarship",
  "teachers-of-illinois-scholarship",
  "next-generation-hoosier-educators",
  "kheaa-teacher-scholarship",
  "mi-future-educator-fellowship",
  "minnesota-student-teacher-grants",
  "nys-math-science-teaching-incentive",
  "virginia-teaching-scholarship-loan",
  "underwood-smith-teaching-scholars",
  "arizona-teachers-academy",
  "sigma-nursing-rn-to-bsn-scholarship",
  "minnesota-fostering-independence-grant",
  "new-jersey-njfc-scholars",
  "pennsylvania-fostering-independence-tuition-waiver",
  "north-carolina-nc-reach",
  "tennessee-hope-foster-child-tuition-grant",
  "connecticut-dcf-postsecondary-education-assistance",
  "oregon-foster-youth-tuition-fee-waiver",
  "colorado-fostered-higher-education-support",
  "kansas-foster-child-education-assistance",
  "west-virginia-foster-care-tuition-waiver",
  "utah-foster-care-tuition-waiver",
  "arizona-foster-care-tuition-waiver",
  "alabama-fostering-hope-scholarship",
  "michigan-indian-tuition-waiver",
  "minnesota-indian-scholarship-program",
  "montana-american-indian-tuition-waiver",
  "north-dakota-indian-scholarship-program",
  "washington-american-indian-endowed-scholarship",
  "maine-native-american-waiver-program",
  "new-york-state-indian-aid",
  "massachusetts-native-american-tuition-credit",
  "new-mexico-native-american-instate-tuition",
  "nevada-native-american-fee-waiver",
  "arizona-native-american-tuition-classification",
  "noah-mcgowan-leadership-scholarship",
  "noah-heckman-empowerment-scholarship",
  "california-calvet-college-fee-waiver",
  "alabama-gi-dependent-scholarship",
  "texas-hazlewood-legacy",
  "washington-tuition-waiver-dependents-veterans",
  "wisconsin-gi-bill-dependents",
  "maine-veterans-dependents-educational-benefits",
  "new-york-merit-scholarship",
  "maryland-conroy-memorial-scholarship",
  "arkansas-heroes-scholarship",
  "tennessee-dependents-tuition-waiver",
  "south-carolina-veterans-children-tuition",
  "north-dakota-dependent-tuition-waiver",
  "florida-children-spouses-veterans-scholarships",
  "iowa-children-of-fallen-service-members",
  "loves-learning-with-loves-scholarship",
  "thompson-tansky-scholarship-fund",
  "georgia-power-foundation-scholarship",
  "exelon-bright-futures-scholarship",
  "pge-better-together-stem-scholarship",
  "ohio-electric-cooperatives-scholarship",
  "georgia-tuition-equalization-grant",
  "south-carolina-tuition-grant",
  "nc-need-based-scholarship-private-college",
  "alabama-student-grant-program",
  "hy-vee-tuition-assistance",
  "construction-graybar-trades",
  "alliance-kruger-melvin-roofing",
  "ahri-rees",
  "automotive-piston-piston",
  "calcpa-institute",
  "accounting-cpa-cpa-endowment-illinois",
  "accounting-acctofi-txcpa",
  "accounting-excellence-moynihan-nysscpa",
  "accountancy-michigan",
  "actuaries-cresta-latino-ola-organization",
  "diversity-fpa",
  "ama-collegiate",
  "bdpa-corporate-technology",
  "sisters-skies",
  "david-meteorology-minority-nwa-sankey",
  "aotf",
  "academic-ena",
  "association-dental-hygienists",
  "marshall-mary-nursing-programs-virginia",
  "arkansas-challenge-workforce",
  "b-hawai-i-state",
  "ayn-rand-anthem-essay-contest",
  "ayn-rand-fountainhead-essay-contest",
  "charles-epilepsy-l-opportunity-shor",
  "bright-future-ndss",
  "buckley-endowed-moss-p",
  "scholars-ufirst",
  "b-church-cme-cobb-four",
  "america-armenian-church-diocese-undergraduate",
  "amaa",
  "america-community-service-zakat",
  "hispanic-iphc",
  "bhavreet-gill-singh",
  "fezana",
  "francis-ouimet",
  "caddie-njsga",
  "fallen-firefighters",
  "afpandcc-family-police-survivors",
  "family-pepsico-scholars",
  "children-dependent-employees-fargo-wells",
  "children-employees-ubs",
  "children-nucor-nucor-teammates",
  "buchan-carl-lowe-s",
  "exxonmobil-teagle",
  "avery-children-dennison-employees-s",
  "career-exploration-rid",
  "bright-families-future-household-parent",
  "la-geaux-louisiana-teach",
  "la-empower-louisiana-people-strategies",
  "la-guard-louisiana-patriot",
  "la-foster-j-louisiana-m",
  "ca-act-california-dream-incentive",
  "oh-heroes-hidden-ohio",
  "oh-assistance-loan-nurse-ohio",
  "in-fields-high-indiana-need",
  "il-access-childhood-consortium-early",
  "il-gear-illinois-up",
  "il-correctional-dependents-fire-illinois",
  "il-higher-illinois-license-plate",
  "mi-fighter-fire-michigan-officer",
  "wi-nonprofit-private-s-schools",
  "mn-developmental-disabilities-grants-intellectual",
  "mn-minnesota-officer-public-s",
  "ia-kibbie",
  "ia-incentive-iowa-workforce",
  "ia-assistance-gap",
  "ia-court-equipment-reporter",
  "mo-act-public-recruitment-retention",
  "mo-chance-kids",
  "mo-environmental-literacy-minority-underrepresented",
  "ne-assistance-community-gap",
  "ne-door-to",
  "ne-at-career-colleges-community",
  "ne-at-career-colleges-ne",
  "builders-career-loan-nd",
  "mt-discharged-honorably-veteran",
  "mt-dependents-firefighters-montana-officers",
  "co-colorado-expanded-free-promise",
  "co-empowered",
  "ut-gap-utah-veterans",
  "ut-karen-mayne-officer-public",
  "ut-advancement-career-officer-public",
  "nv-nevada-teach",
  "nv-incentivizing-pathways-teaching-to",
  "nv-c-guinn-kenny",
  "military-spouses-veterans",
  "correctional-dependents-enforcement-law",
  "nm-incentive-mexico-new",
  "veterans-vietnam-wartime",
  "nm-loan-mexico-new-nursing",
  "nm-allied-health-loan-mexico",
  "or-oregon-tribal",
  "or-care-child-oregon",
  "or-deceased-disabled-officer-or",
  "or-oregon-scholars-teacher",
  "tx-aide-educational-texas",
  "tx-nursing-texas",
  "ok-care-child-excellence-oklahoma",
  "ok-heroes-oklahoma-promise",
  "ok-access-achievement-oklahoma",
  "hi-century-hawai-i-second",
  "tx-blind-deaf-or",
  "children-deceased-disabled-enforcement",
  "tx-benefits-certain-individuals-positions",
  "tx-disabled-duty-firefighters-line",
  "tx-courses-enrolled-fire-firefighters",
  "tx-courses-emergency-enrolled-medical",
  "tx-courses-criminal-enforcement-enrolled",
  "wi-minority-undergraduate-wisconsin",
  "ny-enhanced",
  "ny-veterans",
  "ny-3407-flight",
  "ny-center-trade-world",
  "ny-deceased-ems-families-firefighters",
  "governor-industry-nj-s",
  "pa-grow-pa",
  "industry-pa-targeted",
  "ma-based-massachusetts-need",
  "ma-child-dcf-foster-massachusetts",
  "ma-community-nursing",
  "ma-christian-herter",
  "ccsnh-cup-governor-robotics",
  "va-early-educator-virginia",
  "va-stem-virginia-west",
  "va-nursing-virginia-west",
  "va-stand-virginia-west",
  "md-maryland-part-time",
  "md-delegate-maryland",
  "md-cybersecurity-maryland-public-service",
  "md-f-jack-maryland-tolbert",
  "md-afghanistan-conflicts-douglas-iraq",
  "md-fallen-maryland-transportation-workers",
  "sc-carolina-industry-needs-south",
  "ga-dreams-georgia",
  "ga-georgia-hero",
  "ga-georgia-inclusive-postsecondary",
  "fl-family-florida-rosewood",
  "fl-bracy-florida-ocoee-randolph",
  "al-alabama-credential-short-term",
  "ms-faith-mississippi",
  "tn-children-dependent-tennessee",
  "mn-minnesota-north-promise-star",
  "ia-blue-d-iowa-robert",
  "ia-assistance-gap-iowa",
  "ia-court-equipment-iowa-reporter",
  "ia-iowa-kibbie",
  "mo-chance-kids-missouri",
  "mo-act-missouri-public-recruitment",
  "mo-environmental-literacy-minority-missouri",
  "ks-kansas-military-service",
  "ks-kansas-rotc-service",
  "ne-assistance-community-gap-nebraska",
  "ne-door-nebraska-to",
  "ne-at-career-colleges-community-2",
  "ne-at-career-colleges-nebraska",
  "oh-buckeyes-forever-ohio",
  "oh-ohio-ready-work",
  "oh-chance-ohio-second",
  "in-adult-indiana",
  "in-indiana-ready-workforce",
  "ia-future-iowa-ready",
  "ut-bell-h-t-utah",
  "ut-technical-utah",
  "ut-development-talent-utah",
  "id-adult-idaho-learners-opportunity",
  "ok-finish-higher-line-oklahoma",
  "ut-credential-first-utah",
  "ga-accelerated-career-georgia",
  "grahame-somerville-thelma",
  "family-steiner",
  "emergency-fargo-veterans-wells",
  "american-iranian",
  "iranian",
  "day-dominican-parade",
  "mike-swim-with",
  "scleroderma-warriors",
  "packaging-packaging-professionals",
  "aifd"
],
);

// Prefer the audit's more direct official program page when it found one.
export const scholarshipAmountFloorSourceOverrides: Readonly<Record<string, string>> =
  {
  "point": "https://pointfoundation.org/scholarships/flagship",
  "techforce": "https://techforce.org/students/",
  "peo-pce": "https://www.peointernational.org/educational-support/program-for-continuing-education/eligibility-and-application-process/",
  "nraef-hospitality": "https://chooserestaurants.org/scholarships/",
  "national-housing-endowment": "https://apply.nationalhousingendowment.org/Default.asp",
  "sema-memorial": "https://www.sema.org/news-media/press-release/2026-sema-scholarship-and-loan-forgiveness-applications-now-open",
  "sparkforce-fma": "https://www.fmamfg.org/foundation/scholarships",
  "cbc-spouses": "https://www.cbcfinc.org/programs/scholarships/",
  "blacks-at-microsoft": "https://www.microsoft.com/en-us/diversity/bam-scholarship",
  "tx-teog": "https://www.highered.texas.gov/student-financial-aid-programs/grant-loan-programs/",
  "ct-willis": "https://portal.ct.gov/-/media/sde/performance/fafsa/frequently-asked-questions--roberta-b-willis-need-merit-scholarship.pdf",
  "ct-pact": "https://ctstate.edu/free-tuition",
  "tennessee-reconnect": "https://tnreconnect.gov/TN-Reconnect-Grant-Application",
  "osher-reentry-scholarship": "https://www.osherfoundation.org/scholars.html",
  "nacme-scholars-program": "https://www.nacme.org/scholarships",
  "jflf-welding-awards-program": "https://www.jflf.org/v/vspfiles/assets/pdf/D1_D2_RULES_CONDITIONS.pdf",
  "native-forward-scholars-fund": "https://www.nativeforward.org/scholarship-finder/",
  "florida-national-guard-tuition-assistance": "https://edd.dma.myflorida.com/flng/",
  "ca-golden-state-teacher-grant": "https://www.csac.ca.gov/gstg",
  "ar-minority-teacher-scholars-program": "https://uapb.edu/academics/soe/scholarships/",
  "il-special-education-teacher-tuition-waiver": "https://www.isac.org/students/during-college/types-of-financial-aid/scholarships/illinois-special-education-teacher-tuition-waiver-settw-program.html",
  "florida-first-generation-matching-grant": "https://www.floridastudentfinancialaidsg.org/PDF/factsheets/FGMG.pdf",
  "afas-hap-arnold-grant": "https://afas.org/haparnoldgrant/",
  "architects-foundation-diversity-advancement": "https://architectsfoundation.org/opportunities/",
  "sma-foundation-scholarship": "https://www.stadiummanagers.org/index.php/component/eventbooking/sma-foundation/sma-foundation-scholarship-application-2026-2027",
  "usta-foundation-college-scholarship": "https://www.ustafoundation.com/en/home/what-we-do/college-scholarship-opportunities.html",
  "guam-aheg-sfap": "https://www.uog.edu/financial-aid/local-financial-aid-sfap",
  "federal-etv-program": "https://acf.gov/cb/grant-funding/john-h-chafee-foster-care-independence-program",
  "california-chafee-grant": "https://csac.ca.gov/foster-youth",
  "washington-passport-to-careers": "https://wsac.wa.gov/passport/about",
  "team-up-together-scholarship": "https://www.teamuptogether.org/scholarship",
  "helen-jean-simpson-scholarship": "https://www.azfoundation.org/scholarship-seekers/scholarships/page/6/",
  "prosper-scholarship-maine": "https://prosperityme.org/higher-education/",
  "srm-masonic-range-science-scholarship": "https://rangelands.org/scholarships",
  "aka-eaf-merit-scholarship": "https://donate.akaeaf.org/akaeaf-primary-applications",
  "znef-general-scholarships": "https://www.znef.org/znef-general-scholarships",
  "freedom-alliance-scholarship-fund": "https://fascholarship.com/qualifications/",
  "special-forces-scholarship-fund": "https://www.sfscholarshipfund.org/",
  "tjx-companies-scholarship-program": "https://www.tjx.com/corporate-responsibility/workplace/health-well-being",
  "gilman-scholarship": "https://www.gilmanscholarship.org/program/program-overview/",
  "fnsna-undergraduate-scholarship": "https://www.fnsna.org/2027-undergraduate-scholarship-application",
  "chasa-college-scholarships": "https://chasa.org/we-can-help/college-scholarships/",
  "cmaa-joe-perdue-scholarship": "https://www.clubfoundation.org/apply.html",
  "dollar-general-turner-family-scholarship": "https://www.dollargeneral.com/hereforwhatmatters/empowering-employees-through-education",
  "wingstop-morrison-family-scholarship": "https://wingstopcharities.org/our-programs/",
  "army-womens-foundation-legacy-scholarship": "https://www.awfdn.org/scholarships/general-information/",
  "ks-promise-scholarship": "https://kansasregents.gov/students/student_financial_aid/promise-act-scholarship",
  "ky-work-ready-scholarship": "https://www.kheaa.com/web/scholarships-grants.faces?lv=true",
  "wy-tomorrow-scholarship": "https://communitycolleges.wy.edu/wyomings-tomorrow-scholarship",
  "chafee-etv-program": "https://acf.gov/cb/resource/chafee-foster-care-program",
  "nsoro-fostering-futures-scholarship": "https://nsoro.submittable.com/submit",
  "families-of-freedom-scholarship-fund": "https://www.familiesoffreedom.org/students-families/families-of-freedom-fund/",
  "john-edgar-thomson-foundation-grant": "https://utuia.org/john-edgar-thompson-scholarship/",
  "gfwc-success-for-survivors-scholarship": "https://memberportal.gfwc.org/resources/scholarship/337/gfwc-success-for-survivors-scholarship-application",
  "nj-stars": "https://www.hesaa.org/Documents/FactSheets/NJSTARS/FactSheetfor2026HSGrad.pdf",
  "kentucky-cap-grant": "https://www.kheaa.com/web/scholarships-grants.faces",
  "vfw-sport-clips-help-a-hero-scholarship": "https://www.vfw.org/Scholarship/",
  "colorado-opportunity-scholarship-initiative": "https://cdhe.colorado.gov/provider-resources/matching-student-scholarship-grants",
  "metlife-foundation-legacy-endowed-scholarship": "https://opportunities.uncf.org/s/program-landing-page?id=a2iVJ00000hj2zNYAQ",
  "garage-gurus-automotive-technician-scholarship": "https://automotivescholarships.com/garage-gurus-technician-scholarship",
  "hri-scholarship-program": "https://www.hriresearch.org/scholarship-application-and-resources",
  "cfda-scholarship-fund": "https://cfda.com/programs/students/cfda-scholarship-fund/",
  "massachusetts-national-guard-tuition-waiver": "https://www.mass.edu/forstufam/veterans/financialaid.asp",
  "minnesota-gi-bill-national-guard": "https://mn.gov/mdva/resources/education/educationbenefits/mngibill.jsp",
  "michigan-national-guard-state-tuition-assistance": "https://www.michigan.gov/dmva/quality-of-life/member-benefits-program/mingstap",
  "kentucky-foster-adopted-tuition-waiver": "https://prd.webapps.chfs.ky.gov/kyrise/Home/Education",
  "maryland-foster-care-tuition-waiver": "https://mhec.maryland.gov/preparing/pages/financialaid/programdescriptions/prog_fostercare.aspx",
  "missouri-reach-tuition-waiver": "https://dss.mo.gov/cd/older-youth-program/tuition-assistance.htm",
  "yum-brands-andy-pearson-scholarship": "https://learnmore.scholarsapply.org/pearson/",
  "buffett-scholarship-nebraska": "https://buffettscholarships.org/applicants",
  "texas-tuition-equalization-grant": "https://reportcenter.highered.texas.gov/correspondence/departmental-correspondence/tuition-equalization-grant-fy-2026-and-fy-2027-maximum-award-amounts-memo/",
  "kentucky-tuition-grant": "https://www.kheaa.com/web/scholarships-grants.faces?lv=true",
  "west-virginia-higher-education-grant": "https://www.cfwv.com/financial-aid/wv-higher-education-grant/how-it-works/",
  "illinois-veteran-grant": "https://www.isac.org/students/during-college/types-of-financial-aid/grants/IVG-program.html",
  "ohio-war-orphans-scholarship": "https://dam.assets.ohio.gov/image/upload/highered.ohio.gov/sgs/wos/WOS-Application.pdf",
  "tennessee-strong-act": "https://www.tn.gov/military/programs-benefits/education-incentives/state-ta.html",
  "kansas-guard-educational-assistance": "https://kansasregents.gov/students/student_financial_aid/scholarships_and_grants",
  "iowa-guard-service-scholarship": "https://educate.iowa.gov/higher-ed/financial-aid/scholarships-grants/iowa-national-guard-benefits",
  "idaho-guard-seap": "https://www.imd.idaho.gov/education-services/",
  "nevada-guard-fee-waiver": "https://nshe.nevada.edu/wp-content/uploads/Academic-Affairs/Nevada%20National%20Guard%20Fee%20Waiver%20Fact%20Sheet.pdf",
  "connecticut-guard-tuition-waiver": "https://portal.ct.gov/MIL/Recruiting-and-Retention/RR-Home-Page",
  "arkansas-guard-tuition-waiver": "https://codeofarrules.arkansas.gov/Rules/Rule?chapterID=106&levelType=part&partID=495&sectionID=&subChapterID=138&subPartID=&titleID=6",
  "arizona-guard-tuition-reimbursement": "https://dema.az.gov/education",
  "north-dakota-guard-tuition-assistance": "https://ndlegis.gov/cencode/t37c07-2.pdf",
  "alaska-guard-tuition-reimbursement": "https://ak.ng.mil/Media/News/Article/4132995/new-state-tuition-reimbursement-program-trp-expands-education-opportunities-for/",
  "sc-teaching-fellows": "https://ed.sc.gov/newsroom/scholarships/sc-teaching-fellows-program/",
  "kheaa-teacher-scholarship": "https://www.kheaa.com/web/scholarships-grants.faces?lv=true",
  "new-jersey-njfc-scholars": "https://www.nj.gov/dcf/home/foster_scholars_program.html",
  "connecticut-dcf-postsecondary-education-assistance": "https://portal.ct.gov/dcf/knowledge-base/articles/foster-care-and-adoption/adoption/post-adoption-services",
  "colorado-fostered-higher-education-support": "https://data.highered.colorado.gov/fostered",
  "utah-foster-care-tuition-waiver": "https://le.utah.gov/xcode/Title53H/Chapter11/53H-11-S302.html",
  "new-york-state-indian-aid": "https://www.nysed.gov/indigenous-education/new-york-state-indian-aid",
  "noah-mcgowan-leadership-scholarship": "https://albinism.org/leadership/",
  "noah-heckman-empowerment-scholarship": "https://albinism.org/empowerment/",
  "alabama-gi-dependent-scholarship": "https://va.alabama.gov/education-training/alabama-g-i-dependent-scholarship-program/",
  "texas-hazlewood-legacy": "https://tvc.texas.gov/wp-content/uploads/2025/03/Hazlewood-Act-Policy-Procedure-Manual-25-Mar-2025.pdf",
  "washington-tuition-waiver-dependents-veterans": "https://dva.wa.gov/veterans-their-families/veterans-benefits/education-and-training/washington-tuition-waiver",
  "wisconsin-gi-bill-dependents": "https://dva.wi.gov/benefits/education/wi-gi-bill/",
  "maine-veterans-dependents-educational-benefits": "https://www11.maine.gov/veterans/benefits/education/mesaa/gi-bill",
  "new-york-merit-scholarship": "https://hesc.ny.gov/merit",
  "arkansas-heroes-scholarship": "https://sams.adhe.edu/Scholarship/Details/HEROES",
  "florida-children-spouses-veterans-scholarships": "https://www.floridastudentfinancialaidsg.org/PDF/factsheets/CSDDV.pdf",
  "loves-learning-with-loves-scholarship": "https://occf.org/scholarships/directory/",
  "thompson-tansky-scholarship-fund": "https://thompsontansky.com/scholarships",
  "georgia-power-foundation-scholarship": "https://uncf.org/the-latest/scholarships-for-june-at-uncf",
  "ohio-electric-cooperatives-scholarship": "https://ohioec.org/COEScholarship",
  "south-carolina-tuition-grant": "https://sctuitiongrants.org/eligibility/",
  "construction-graybar-trades": "https://stlouisgraduates.academicworks.com/opportunities/9947",
  "calcpa-institute": "https://www.calcpa.org/membership/chapters/chapter-scholarship-information",
  "accounting-cpa-cpa-endowment-illinois": "https://www.icpas.org/resources/press/press-releases/2026/03/03/illinois-cpa-society-accepting-accounting-scholarship-applications",
  "actuaries-cresta-latino-ola-organization": "https://latinoactuaries.org/scholarships/",
  "aotf": "https://www.aotf.org/educational-scholarships/",
  "ayn-rand-anthem-essay-contest": "https://aynrand.org/students/essay-contests",
  "ayn-rand-fountainhead-essay-contest": "https://aynrand.org/students/essay-contests",
  "scholars-ufirst": "https://firstskinfoundation.org/resources/financial-help/financial-aid/ufirst-scholars-program/",
  "amaa": "https://amaa.org/scholarshipprograms/",
  "fallen-firefighters": "https://www.firehero.org/resources/family-resources/programs/scholarships/how-to-apply-for-nfff-scholarships/",
  "afpandcc-family-police-survivors": "https://www.afp-cc.org/college",
  "children-nucor-nucor-teammates": "https://foundation.nucor.com/",
  "buchan-carl-lowe-s": "https://corporate.lowes.com/sites/lowes-corp/files/2025-09/Lowes_2024_ICR_6.30.25_1.pdf",
  "ca-act-california-dream-incentive": "https://csac.ca.gov/dsig",
  "oh-heroes-hidden-ohio": "https://dam.assets.ohio.gov/image/upload/highered.ohio.gov/sgs/guidance-memos/FA25-012.pdf",
  "oh-assistance-loan-nurse-ohio": "https://codes.ohio.gov/ohio-administrative-code/rule-3333-1-22",
  "il-gear-illinois-up": "https://isac.org/students/during-college/types-of-financial-aid/scholarships/gear-up-scholarship.html",
  "il-correctional-dependents-fire-illinois": "https://www.isac.org/isac-gift-assistance-programs/grant-programs-for-dependents-of-police-fire-correctional-officers/",
  "mo-environmental-literacy-minority-underrepresented": "https://dhewd.mo.gov/ppc/grants-scholarships/muelp",
  "mt-discharged-honorably-veteran": "https://mus.edu/Prepare/Pay/Waivers/index.html",
  "mt-dependents-firefighters-montana-officers": "https://mus.edu/Prepare/Pay/Waivers/index.html",
  "nv-c-guinn-kenny": "https://nvigate.gov/programs/kenny-c-guinn-memorial-scholarship/",
  "tx-nursing-texas": "https://reportcenter.highered.texas.gov/correspondence/departmental-correspondence/nursing-students-scholarship-program-fiscal-year-2027-maximum-semester-amounts/",
  "hi-century-hawai-i-second": "https://manoa.hawaii.edu/fas/types-of-aid/scholarships/financial-aid-scholarships/",
  "tx-benefits-certain-individuals-positions": "https://www.highered.texas.gov/student-financial-aid-programs/exemptions-waivers/",
  "tx-disabled-duty-firefighters-line": "https://www.highered.texas.gov/student-financial-aid-programs/exemptions-waivers/",
  "tx-courses-criminal-enforcement-enrolled": "https://www.highered.texas.gov/student-financial-aid-programs/exemptions-waivers/",
  "wi-minority-undergraduate-wisconsin": "https://heab.state.wi.us/features.html",
  "va-nursing-virginia-west": "https://www.cfwv.com/financial-aid/wv-nursing-scholarship-program/how-it-works/",
  "va-stand-virginia-west": "https://www.cfwv.com/financial-aid/stand/how-it-works/",
  "md-delegate-maryland": "https://mhec.maryland.gov/Preparing/Pages/FinancialAid/ProgramDescriptions/prog_delegate.aspx",
  "md-afghanistan-conflicts-douglas-iraq": "https://mhec.maryland.gov/preparing/Pages/prog_vaic.aspx",
  "ga-dreams-georgia": "https://www.gafutures.org/hope-state-aid-programs/scholarships-grants/dreams/award-amounts/",
  "ga-georgia-hero": "https://www.gafutures.org/hope-state-aid-programs/scholarships-grants/hero/award-amounts/",
  "ga-georgia-inclusive-postsecondary": "https://www.gafutures.org/hope-state-aid-programs/scholarships-grants/ipse/award-amounts/",
  "al-alabama-credential-short-term": "https://www.accs.edu/community-college/pathways-to-prosperity-scholarship/",
  "ms-faith-mississippi": "https://www.msfinancialaid.org/programs/faith-scholarship/",
  "mn-minnesota-north-promise-star": "https://ohe.mn.gov/northstarpromise",
  "ks-kansas-military-service": "https://kansasregents.gov/resources/PDF/Students/Student_Financial_Aid/State_Aid_Brochure_2627.pdf",
  "ks-kansas-rotc-service": "https://kansasregents.gov/resources/PDF/Students/Student_Financial_Aid/State_Aid_Brochure_2627.pdf",
  "oh-buckeyes-forever-ohio": "https://codes.ohio.gov/ohio-revised-code/section-3333.31",
  "oh-ohio-ready-work": "https://dam.assets.ohio.gov/image/upload/highered.ohio.gov/sgs/guidance-memos/FA26-018.pdf",
  "oh-chance-ohio-second": "https://codes.ohio.gov/ohio-revised-code/section-3333.127",
  "in-indiana-ready-workforce": "https://www.in.gov/che/state-financial-aid/state-financial-aid-by-program/workforce-ready-grant/",
  "ga-accelerated-career-georgia": "https://www.gafutures.org/hope-state-aid-programs/scholarships-grants/ace/funding-and-award-amounts/",
  "american-iranian": "https://iasfund.org/apply-for-scholarships/",
  "packaging-packaging-professionals": "https://community.iopp.org/events/event-description?CalendarEventKey=9da44e6b-842d-49e6-a5da-0199e2f76078&CommunityKey=7380e9d4-8ab8-4e3e-9439-b6cdc037ed92&Home=%2Fevents%2Fcalendar"
};
