import { Wallet, TrendDown as TrendingDown, PiggyBank, FileText, IdentificationCard as FileUser, Envelope as Mail } from "@phosphor-icons/react/dist/ssr";
import type { Icon as LucideIcon } from "@phosphor-icons/react";

// Downloadable templates. Spreadsheets (.xlsx) are generated by
// scripts/build-templates.mjs; career documents (.docx) by
// scripts/build-resume-templates.mjs (run `npm run build:templates` /
// `npm run build:resumes`). Add one here AND in the matching script.

export interface Template {
  title: string;
  /** Public path to the generated file (.xlsx or .docx). */
  file: string;
  /** "sheet" (spreadsheet) or "doc" (career document); sheet default. */
  kind?: "sheet" | "doc";
  blurb: string;
  /** What's inside, shown as a short checklist. */
  includes: string[];
  icon: LucideIcon;
  /** Optional related calculator to try the live version. */
  tool?: { label: string; href: string };
}

export const templates: Template[] = [
  {
    title: "Monthly Budget",
    file: "/templates/empower-budget-template.xlsx",
    blurb:
      "Map your income against your spending and see what's left. The totals add themselves up as you type.",
    includes: [
      "Income and 11 expense categories, ready to edit",
      "Auto-totaling planned vs. actual columns",
      "A live “left over” number so you always know where you stand",
    ],
    icon: Wallet,
    tool: { label: "Try the Budget Planner", href: "/tools/budget" },
  },
  {
    title: "Debt Payoff Tracker",
    file: "/templates/empower-debt-payoff-tracker.xlsx",
    blurb:
      "List every debt in one place, watch the totals, and pick a payoff order: snowball or avalanche.",
    includes: [
      "Balance, APR, and minimum payment for each debt",
      "Auto-totaling balance and monthly payment",
      "Built-in snowball vs. avalanche guidance",
    ],
    icon: TrendingDown,
    tool: { label: "Try the Debt Payoff Calculator", href: "/tools/debt" },
  },
  {
    title: "Savings Goal Worksheet",
    file: "/templates/empower-savings-goal-worksheet.xlsx",
    blurb:
      "Set a goal, enter what you can save each month, and the sheet tells you how long it'll take.",
    includes: [
      "A single-goal calculator that finds your timeline",
      "A multi-goal table for tracking several at once",
      "Auto-calculated “still to save” and “months to reach it”",
    ],
    icon: PiggyBank,
    tool: { label: "Try the Savings Goal Calculator", href: "/tools/savings" },
  },
  {
    title: "First Resume (No Experience)",
    file: "/templates/empower-first-resume-template.docx",
    kind: "doc",
    blurb:
      "A one-page resume built for people with no work history yet — every section explains what to put in it as you fill it in.",
    includes: [
      "Sections that replace job history: projects, activities, caregiving, side money",
      "The bullet formula baked into every placeholder",
      "One page, plain formatting — the layout hiring managers actually want",
    ],
    icon: FileUser,
    tool: {
      label: "Read: A Resume With No Work Experience",
      href: "/learn/college/resume-with-no-experience",
    },
  },
  {
    title: "Student Resume (Some Experience)",
    file: "/templates/empower-student-resume-template.docx",
    kind: "doc",
    blurb:
      "For when you've had a job or two: experience up top, education and activities behind it, all in one clean page.",
    includes: [
      "Experience-first layout with result-focused bullet prompts",
      "Education, activities, and skills sections ready to trim",
      "Same one-page, no-graphics format employers scan fastest",
    ],
    icon: FileText,
    tool: {
      label: "Read: Reading Your First Job Offer",
      href: "/learn/college/first-job-offer-money",
    },
  },
  {
    title: "Simple Cover Letter",
    file: "/templates/empower-cover-letter-template.docx",
    kind: "doc",
    blurb:
      "Three short paragraphs: the role, your proof, your ask. Each placeholder shows a worked example to steal the shape of.",
    includes: [
      "The three-paragraph scaffold with example sentences",
      "A header that matches the resume templates",
      "Short enough that you'll actually send it",
    ],
    icon: Mail,
    tool: {
      label: "Read: Your First Interview, Without the Panic",
      href: "/learn/college/ace-your-first-interview",
    },
  },
];
