import { Wallet, TrendingDown, PiggyBank, type LucideIcon } from "lucide-react";

// Downloadable spreadsheet templates. The .xlsx files are generated by
// scripts/build-templates.mjs into public/templates/ (run `npm run build:templates`).
// Add one here AND in that script to publish a new template.

export interface Template {
  title: string;
  /** Public path to the .xlsx file. */
  file: string;
  blurb: string;
  /** What's inside, shown as a short checklist. */
  includes: string[];
  icon: LucideIcon;
  /** Optional related calculator to try the live version. */
  tool?: { label: string; href: string };
}

export const templates: Template[] = [
  {
    title: "Monthly Budget",
    file: "/templates/empower-budget-template.xlsx",
    blurb:
      "Map your income against your spending and see what's left — the totals add themselves up as you type.",
    includes: [
      "Income and 11 expense categories, ready to edit",
      "Auto-totaling planned vs. actual columns",
      "A live “left over” number so you always know where you stand",
    ],
    icon: Wallet,
    tool: { label: "Try the Budget Planner", href: "/tools/budget" },
  },
  {
    title: "Debt Payoff Tracker",
    file: "/templates/empower-debt-payoff-tracker.xlsx",
    blurb:
      "List every debt in one place, watch the totals, and pick your payoff order — snowball or avalanche.",
    includes: [
      "Balance, APR, and minimum payment for each debt",
      "Auto-totaling balance and monthly payment",
      "Built-in snowball vs. avalanche guidance",
    ],
    icon: TrendingDown,
    tool: { label: "Try the Debt Payoff Calculator", href: "/tools/debt" },
  },
  {
    title: "Savings Goal Worksheet",
    file: "/templates/empower-savings-goal-worksheet.xlsx",
    blurb:
      "Set a goal, enter what you can save each month, and the sheet tells you how long it'll take.",
    includes: [
      "A single-goal calculator that finds your timeline",
      "A multi-goal table for tracking several at once",
      "Auto-calculated “still to save” and “months to reach it”",
    ],
    icon: PiggyBank,
    tool: { label: "Try the Savings Goal Calculator", href: "/tools/savings" },
  },
];
